# frozen_string_literal: true

BanList.for_format('msem') do
  format_start(
    'https://snapdragonfirework.wixsite.com/msem2/bans',
    'Angeltouched Cavern' => 'banned',
    'Angeltouched Crag' => 'banned',
    'Angeltouched Garden' => 'banned',
    'Angeltouched Marsh' => 'banned',
    'Angeltouched Saltflat' => 'banned',
    'Deadly Manipulation' => 'banned',
    'District of Artisans' => 'banned',
    'Ebb and Flow' => 'banned',
    'Embrace Madness' => 'banned',
    'Halskrow Street Gallows' => 'banned',
    'Ontarachie Dryad' => 'banned',
    "Parliament's Courtyard" => 'banned',
    'Planar Conflagration' => 'banned',
    'Planar Traversal' => 'banned',
    'Public Gardens' => 'banned',
    'Revert to Moonlight' => 'banned',
    "River's End Falls" => 'banned',
    'Scrapyard Sovereign' => 'banned',
    "Unmasker of Fate's Design" => 'banned',
    'Vidal, Rune Thief' => 'banned',
    'Eleventh Hour Breakthrough' => 'banned',
    'Life-Giving Waters' => 'banned',
    'Leyline Alignment Field' => 'banned',
    'Ammbradu Goliath' => 'banned',
    'Entelan Erasure' => 'banned',
    'Imperial Mox' => 'banned',
    "Kevthra's Will" => 'banned',
    'Last Passage' => 'banned',
    'Hellbent Speed' => 'banned',
    'Lotus Studies' => 'banned',
    'Scintillate' => 'banned',
    'Beckon the Pack' => 'banned',
    'Reefcrown Egg' => 'banned',
    'Reinvent' => 'banned',
    'Instant of Brilliance' => 'banned',
    'Vivid March' => 'banned',
    'Fogspewer' => 'banned',
    'Pensive Songwritter' => 'banned'
  )
end
