BanList.for_format("msem2") do
  format_start(
    "https://snapdragonfirework.wixsite.com/msem2/bans",
    "Aether Leak" => "banned", 
    "Angeltouched Cavern" => "banned",
    "Angeltouched Crag" => "banned",
    "Angeltouched Garden" => "banned",
    "Angeltouched Marsh" => "banned",
    "Angeltouched Saltflat" => "banned",
    "Chigau, the Red Market" => "banned", 
    "Deadly Manipulation" => "banned", 
    "District of Artisans" => "banned", 
    "Ebb and Flow" => "banned", 
    "Embrace Madness" => "banned", 
    "Halskrow Street Gallows" => "banned", 
    "Mercantile Accords" => "banned", 
    "Mystic Meddling" => "banned", 
    "Ontarachie Dryad" => "banned", 
    "Parliament's Courtyard" => "banned", 
    "Planar Conflagration" => "banned", 
    "Planar Traversal" => "banned", 
    "Poisoned Well" => "banned", 
    "Public Gardens" => "banned", 
    "Revert to Moonlight" => "banned", 
    "River's End Falls" => "banned", 
    "Scrapyard Sovereign" => "banned", 
    "Sentinel of Latter Days" => "banned", 
    "Unmasker of Fate's Design" => "banned", 
    "Vidal, Rune Thief" => "banned", 
    "Zetla, the Dragon's Voice" => "banned"  )
end
