class ConditionIsLilia < Condition
	def search(db)
		names = [
			"crystal garden",
			"leyline alignment field",
			"mirrorgate",
			"overloaded aethergate",
			"titan's palace",
			"collapsing ground",
			"forest",
			"island",
			"mountain",
			"plains",
			"ripping wilds",
			"swamp",
			"the high prairies",
			"unstable footing",
			"abandoned sanctuary",
			"inundated sanctuary",
			"sacred sanctuary",
			"savage sanctuary",
			"spire sanctuary",
			"wretched sanctuary",
			"aghavaan's wound",
			"ancient ossuary",
			"clutch of the coil",
			"heavenly temple",
			"imperial ricefields",
			"shugenja sanctuary",
			"sunrise orchard",
			"wayfarer's shrine",
			"adaptive terrains",
			"flooded morass",
			"flourishing crevasse",
			"heart of the glade",
			"lavatorn fields",
			"planar alignment",
			"pool of light",
			"springjack pasture",
			"war golem forge",
			"amber hills",
			"boiling ridge",
			"duskwood thicket",
			"flooded depths",
			"grim bastion",
			"hazy moorland",
			"magmatic torrent",
			"rugged fields",
			"shifting frontiers",
			"sungrace meadows",
			"sunlit highland",
			"unknown shores",
			"altar of adversity",
			"altar of chaos",
			"altar of creation",
			"altar of destruction",
			"altar of order",
			"angeltouched cavern",
			"angeltouched crag",
			"angeltouched garden",
			"angeltouched marsh",
			"angeltouched saltflat",
			"descended delta",
			"descended marsh",
			"descended meadow",
			"descended mortuary",
			"descended towers",
			"ahl's study",
			"crafted coast",
			"dire dive",
			"edge of the world",
			"halls of renown",
			"haunted estate",
			"lush outcrop",
			"spired canopy",
			"ghastly castle",
			"gleaming veldt",
			"grisly marsh",
			"sunken cavern",
			"sunny dunes",
			"desert temple",
			"deathwind expanse",
			"gryla canyon",
			"moonshadow abyss",
			"priest's altar",
			"stormcaster's tower",
			"aquatic refuge",
			"citadel of denial",
			"no-man's land",
			"prairie monastery",
			"scorched copse",
			"sunless ridge",
			"temple of brilliance",
			"toxic spring",
			"enduring vestige",
			"frostfire geysers",
			"fungal mire",
			"gloomcover steppe",
			"kellythross' workshop",
			"lush oasis",
			"shrine of the six pillars",
			"spiraling canyon",
			"bustling docks",
			"choked estuary",
			"derelict amphitheatre",
			"foreboding ruins",
			"fortified village",
			"game trail",
			"interlocked waterways",
			"isolated cloister",
			"port town",
			"shadowed slums",
			"whiterun gates",
			"whiterun harbor",
			"abandoned battlefield",
			"abandoned cairn",
			"abandoned meadow",
			"abandoned skyroad",
			"abandoned wilderness",
			"academy wastes",
			"alpine meadow",
			"barren desolation",
			"calmed battleground",
			"charbroiled core",
			"chiseled cliffside",
			"cleared vault",
			"cliffside entrance",
			"command tower",
			"dawnlit battlefield",
			"deadwood grove",
			"deeplife cavern",
			"deserted steppe",
			"deserted trail",
			"desolate barrens",
			"exotic xenoreef",
			"fiery chasm",
			"flourishing waterways",
			"forgotten cryovault",
			"forgotten shrine",
			"frigid highlands",
			"frontier base",
			"gleaming hot springs",
			"gnarled henge",
			"grim slums",
			"grove of reversal",
			"haughty chateau",
			"haunted woodlock",
			"highland vale",
			"horizon of origins",
			"imperial barracks",
			"jagged crag",
			"legacy foundations",
			"lush outskirts",
			"mossy shrine",
			"mysterious cataract",
			"ocean monastery",
			"ominous lair",
			"ornamented evergreen",
			"overgrown refuge",
			"quintok station",
			"rainforest spring",
			"roaring cascade",
			"secluded cascade",
			"shardstone rift",
			"shrouded rooftops",
			"sky-high spires",
			"sodden cavern",
			"somber marsh",
			"spires of telenia",
			"stormcharged pyre",
			"strange harbor",
			"sunlit ruins",
			"timber range",
			"tirenan market",
			"torrid geysers",
			"toxic jungle",
			"tranquil stream",
			"unlit alley",
			"wastes",
			"weathered fortress",
			"wildrune thicket",
			"abandoned forge",
			"abandoned hideout",
			"abandoned laboratory",
			"abandoned preserve",
			"abandoned shores",
			"anzen, beyond the sea",
			"chikami castle",
			"dragonwall gates",
			"house of forgotten whispers",
			"imperial port",
			"kurayami shrine",
			"memorial of the fallen",
			"midnight keep",
			"perilous passage",
			"saishuteki castle",
			"seishin dojo",
			"shikai's redoubt",
			"sunset monastery",
			"temple of falling leaves",
			"the last sacred gate",
			"tower of long shadows",
			"unzari ruins",
			"bloodstone halls",
			"crumbling vestige",
			"hill of souls",
			"moonlit shore",
			"valley falls",
			"verdant sanctum",
			"wild ravine",
			"bloodriver",
			"cloudbank",
			"corpsebed",
			"cradle of corruption",
			"elrayin, the manaroot",
			"mosecf, the sunseeker's path",
			"ralora, unforgiving depths",
			"sea of skies beyond",
			"seedshrine",
			"sunstage",
			"arctic mine",
			"crumbling precipice",
			"crystal cavern",
			"daunting skyline",
			"decrepit crags",
			"failing port",
			"forgotten steppe",
			"grim courtyard",
			"hazy lagoon",
			"merchant's district",
			"murmuring falls",
			"nomad's township",
			"phosphorescent ravine",
			"rampant summit",
			"resplendent substratum",
			"rickety guildhall",
			"ruined citadel",
			"sedate tundra",
			"serene trail",
			"shifting glade",
			"vibrant rainforest",
			"derelict town",
			"forgotten haunt",
			"sunrise bluffs",
			"sunrise prairie",
			"sunrise river",
			"sunrise ruins",
			"sunrise woods",
			"the aetherite saloon",
			"chamber of splendor",
			"dragonfly shrine",
			"jade temple",
			"palace of reflections",
			"shengin heartland",
			"aerie's pillar",
			"bygone guardian",
			"channeling stone",
			"forgotten pit",
			"lumbering hillock",
			"rousing rubble",
			"abandoned den",
			"dragon queen's den",
			"greenheart den",
			"hibernation den",
			"raider's den",
			"the issbarrens",
			"war-torn tundra",
			"autumn moon",
			"blundering clocktower",
			"canyon creek",
			"cloud rock",
			"crystal grotto",
			"cumulus horizon",
			"evolving wilds",
			"fey grove",
			"frigid thicket",
			"haunted boughs",
			"moon of the encroaching night",
			"moon of the final dawn",
			"moon of the frozen dusk",
			"moon of the lingering day",
			"moon of the promised day",
			"ruined precipice",
			"soaring canyon",
			"verdant bluff",
			"ancient cairns",
			"chroma, the faerie circle",
			"field of obelisks",
			"gate to the nav",
			"noxious garden",
			"overgrown ruins",
			"wanderer's sky",
			"ascendant's gate",
			"backstage rooms",
			"heist headquarters",
			"hidden hollow",
			"legitimate establishment",
			"ruined theater",
			"ruptured citadel",
			"ruptured expanse",
			"ruptured falls",
			"ruptured flats",
			"ruptured grotto",
			"ruptured grove",
			"ruptured meadow",
			"ruptured morass",
			"ruptured square",
			"ruptured trail",
			"seedy bar",
			"talent pool",
			"catalina's turf",
			"dominik's shack",
			"forgotten doorway",
			"ganzorig's domain",
			"hiroto's refuge",
			"neblus' legacy",
			"riga's workshop",
			"riko's academy",
			"riv's safehouse",
			"takumi's headquarters",
			"tsubasa's redoubt",
			"barren boneyard",
			"calcified dunes",
			"el-mazar, wayward palace",
			"flourishing dunes",
			"highland dunes",
			"immolated grave",
			"painted bluffs",
			"ravaged monument",
			"sandswept bazaar",
			"saturated dunes",
			"skeletal oasis",
			"stygian dunes",
			"sunrazed ruins",
			"tomb of great drakes",
			"dust barrens",
			"golden glade",
			"ligos, shadow's source",
			"rius, temple of the grandfather",
			"singers' grove",
			"the aurora's heart",
			"the court of angels",
			"arcane saxophone",
			"art studio",
			"automated maestromancer",
			"aven acoustimancer",
			"beautiful crescendo",
			"blessed mausoleum",
			"bouquet singer",
			"captivating jester",
			"chilling musician",
			"creeping pianist",
			"dangerous territory",
			"dramatic artist",
			"eerie bayou",
			"enthralling actor",
			"exciting band",
			"festival songstress",
			"forlorn ruin",
			"glamorous aerialist",
			"herald of festivities",
			"improvising automaton",
			"inspiring band",
			"lakeside park",
			"mushroom lagoon",
			"new alores fiddler",
			"plume de val singer",
			"prayer hall",
			"pretentious performer",
			"pyrodancer",
			"radiant outburst",
			"rejoicing aristocrats",
			"ritzy parlor",
			"riverguide harpist",
			"royal domain",
			"soul of new alores",
			"streetside entertainer",
			"sunlit plaza",
			"twirling duet",
			"vacated bar",
			"woopip chef",
			"artist's vista",
			"over the horizon",
			"stark copse",
			"stark hinterlands",
			"stark horizon",
			"stark stream",
			"stark wildfire",
			"abandoned monument",
			"aether gateway",
			"autumn canopy",
			"blossoming expanse",
			"brine fleet bay",
			"cloudsteel summit",
			"cursed wastes",
			"dreamscape",
			"dustchoked outpost",
			"endless trove",
			"eternal reactor",
			"explorer's ascent",
			"fractured reach",
			"gathering beacon",
			"ghostspore mire",
			"gilded gulch",
			"glacial shelf",
			"grove of embers",
			"heart of zhedina",
			"idravir, the last city",
			"krismite vault",
			"lotus lake",
			"molten falls",
			"monument of queens",
			"morphic verge",
			"nereba, sandchoked archives",
			"otherworldly forest",
			"otherworldly island",
			"otherworldly mountain",
			"otherworldly plains",
			"otherworldly swamp",
			"paracosm",
			"polyp pools",
			"precursor sanctum",
			"promethean grotto",
			"rainsculpted gorge",
			"razione racecourse",
			"shadowcleft hideout",
			"shifting canyon",
			"shifting cascade",
			"shifting crag",
			"shifting grove",
			"shifting morass",
			"shuddering node",
			"skylight fortress",
			"smuggler's den",
			"soaring rainforest",
			"starlight beacon",
			"steamlit peaks",
			"tears of tizuma",
			"timeless shrine",
			"tomb of shifting sands",
			"untethered spire",
			"voliv edgelands",
			"woven network",
			"zhedina exchange",
			"zhedina outskirts",
			"zhelid, planar academy",
			"brilliant academy",
			"brilliant archives",
			"brilliant capital",
			"brilliant castle",
			"brilliant citadel",
			"brilliant cityscape",
			"brilliant hub",
			"brilliant mansion",
			"brilliant port",
			"brilliant workshop",
			"city gate",
			"renewal grove",
			"riftway to the other side",
			"runecrested valley",
			"timeworn crags",
			"transplanted citadel",
			"drained shore",
			"drought-plagued slum",
			"fluctuating locale",
			"forsaken getaway",
			"grave of an old lord",
			"haunted fairground",
			"hellwaste settlement",
			"memorial ground",
			"pulsating mass",
			"risti citadel",
			"scavenger holdout",
			"secluded farmstead",
			"sepulchral seas",
			"warped landscape",
			"windmill project",
			"aureate panorama",
			"frozen hinterlands",
			"hazy coppice",
			"lowland vista",
			"spires of caulte",
			"sunlit fissure",
			"testament to heroism",
			"the whisperwoods",
			"towering boughs",
			"ancient dominion",
			"bleak dominion",
			"bloodfell caves",
			"blossoming sands",
			"coastal dominion",
			"desolate dominion",
			"dismal backwater",
			"gleaming river",
			"jungle hollow",
			"majestic dominion",
			"murky peat",
			"primal dominion",
			"pristine dominion",
			"rugged dominion",
			"rugged highlands",
			"scoured barrens",
			"stalwart dominion",
			"sunwashed spires",
			"swiftwater cliffs",
			"thornwood falls",
			"tranquil cove",
			"tropical grove",
			"vast savannah",
			"verdant dominion",
			"wind-scarred crag",
			"barren vista",
			"blooming vista",
			"glacial vista",
			"hall of random access memories",
			"living vista",
			"marshy vista",
			"nebula of empty gold",
			"new divide",
			"prismatic cavern",
			"slyten crystal motherlode",
			"the tomb of precursors",
			"arcane sanctum",
			"bigroot valley",
			"bleak shoreline",
			"caustic mangrove",
			"charred marsh",
			"cloudcover heights",
			"crumbling necropolis",
			"erupting territory",
			"forbidding isle",
			"gloomtide gulf",
			"hazy summits",
			"idyllic oasis",
			"jungle shrine",
			"kaleidoscape",
			"lush coast",
			"peaceful passage",
			"savage lands",
			"sculpted observatory",
			"seaside citadel",
			"somber meadow",
			"terramorphic expanse",
			"twisting fissure",
			"center of culture",
			"crescent of possibilities",
			"many-voiced tower",
			"mustering grounds",
			"rupture spire",
			"wondrous bazaar",
			"chikyu league arena",
			"forgotten temple",
			"gene pool",
			"healing center",
			"ice path",
			"lake of rage",
			"muggy mire",
			"power plant",
			"practice range",
			"ruined lab",
			"ruined shrine",
			"still waters",
			"treasure beach",
			"victory road",
			"wandering hamlet",
			"pirate's hideout",
			"anemone cluster",
			"coralight castle",
			"enchanting palace",
			"grisly ruins",
			"molten basin",
			"paradise reef",
			"shanty town",
			"tectonic chateau",
			"typhoon caverns",
			"vibrant sandbar",
			"volcanic hollow",
			"coastal metropolis",
			"crowded tavern",
			"fertile steppe",
			"rogue's passage",
			"spawning barrens",
			"thalassic borough",
			"wild peak",
			"alratha, pearl of the sand sea",
			"collapsing ridges",
			"conto sika, ruined glory",
			"desert's hearth",
			"ecological refuge",
			"path of fire",
			"swaying sands",
			"verdant oasis",
			"fields of worship",
			"inscrutable realms",
			"inviolable realms",
			"mortal realms",
			"tempting realms",
			"wild realms",
			"avaz citadel",
			"avaz sanctuary",
			"avaz temple",
			"danaj citadel",
			"danaj sanctuary",
			"danaj temple",
			"hidden garden entrance",
			"kaneh citadel",
			"kaneh sanctuary",
			"kaneh temple",
			"marketplace crossroads",
			"mercantile satrapy",
			"neutral citystate",
			"nizev citadel",
			"nizev sanctuary",
			"nizev temple",
			"shifting city",
			"shrine to those gone",
			"soli citadel",
			"soli sanctuary",
			"soli temple",
			"bustling harbor",
			"dreary township",
			"glittering grove",
			"monsoon lagoon",
			"urban wastelands",
			"starved oasis",
			"dustridden sepulcher",
			"risti workshop",
			"dragonglass harp",
			"flourishing lowlands",
			"forgotten monument",
			"pathway of lost sultans",
			"raintouched basin",
			"scoured mesa",
			"silent ridge",
			"windworn spires",
			"arcane oasis",
			"arid causeway",
			"bloodsand gulch",
			"blooming needles",
			"crumbling aqueduct",
			"desiccated trail",
			"dunesea expanse",
			"humble hamlet",
			"resurgent oasis",
			"rot-sand ruins",
			"sundappled scrub",
			"chigau market outskirts",
			"dha-bukan, jewel of the dunes",
			"eroded sanctuary",
			"the song of the universe",
			"nestled delta",
			"fellor war-skald",
			"avalanche drummer",
			"enter the mosh pit",
			"aleud warcaller",
			"siamang tale-singer",
			"trumpeting pathmaker",
			"wildheart chorister",
			"lilia of the soul",
			"horn run huntcaller",
			"blistering boneyard",
			"shrine of the world-shepherd",
			"farmyard",
			"tinyvale treetops",
			"bleakrealm moor",
			"dawn hill outskirts",
			"fabled passage",
			"flamingo rock",
			"frondpond grotto",
			"gloomhollow woodlock",
			"highpoint shrine",
			"humble abode",
			"fang den jaws",
			"slipsand oasis",
			"exotic isle",
			"hoof cliff horngrove",
			"crossroads town",
			"northrime aurora",
			"rugged expanse",
			"eon campfire",
			"breathtaking valley",
			"ancestral glade",
			"archmage's tower",
			"bustling marketplace",
			"chamber of ceremonies",
			"cloudpeak spires",
			"commander's stronghold",
			"conjured acropolis",
			"magnificent palace",
			"midnight gate",
			"mystical tomb",
			"sacred summits",
			"seaside grotto",
			"sunlit meadow",
			"tranquil shrine",
			"vale ruins",
			"vraniveer's edge",
			"wildkin grove",
			"tomb of the roseblade",
			"cresting bay",
			"firehearth halls",
			"serene chapel",
			"wise old oak",
			"swarming midden",
			"secluded courtyard",
			"sparring ground",
			"indomitable armory",
			"descended glacier",
			"descended hollow",
			"descended fissure",
			"descended gorge",
			"descended countryside",
			"alchemist's abode",
			"opera house",
			"imperial capital",
			"thriving bluff",
			"thriving moor",
			"thriving isle",
			"thriving grove",
			"thriving heath",
			"barbed reef",
			"calciform wastes",
			"crumbling shrine",
			"implant greenhouse",
			"snow drift",
			"spiny ridge",
			"taifeng shrine",
			"hozen shrine",
			"shoupan shrine",
			"paomar shrine",
			"guang shrine",
			"lieshi shrine",
			"kinsang shrine",
			"laiyru shrine",
			"qi-long shrine",
			"huolin shrine",
			"lotus barrens",
			"eminent palace",
			"ominous palace",
			"forbidden palace",
			"montane palace",
			"concordant palace",
			"eidolic palace",
			"forsaken palace",
			"serene palace",
			"opalescent palace",
			"radiant palace",
			"lonely aerie",
			"treacherous oasis",
			"ravenous hollow",
			"grizzled den",
			"pride ridge",
			"scrounging dunes",
			"reclusive copse",
			"overgrown enclave",
			"spined spire",
			"vulpine bluffs",
			"spirit blossom shrine",
			"the orange orchard",
			"shrine of elder lords",
			"festival centrum",
			"misty churchyard",
			"lost station",
			"hellfire caverns",
			"enshrouded village",
			"sunken homestead",
			"whirling repository",
			"alchemical reserve",
			"soaring observatory",
			"strict instructor",
			"illumination savant",
			"arpechian bellowers",
			"demanding pupil",
			"almgrove bladesinger",
			"almgrove spellblade",
			"wind savant",
			"sensory stimulation",
			"entrancing melody",
			"gilded duo",
			"sending stones",
			"autumnal resonants",
			"lightning and thunder",
			"sing through steel",
			"updraft dancer",
			"harpstring ranger",
			"starfall instructor",
			"gilded conductor",
			"twilight dancer",
			"almgrove ensemble",
			"speed reader",
			"supernal icon",
			"gentle lullaby",
			"yita, almgrove prodigy",
			"almgrove performer",
			"chaotic pupil",
			"focused apprentice",
			"learn through error",
			"flourishing forest",
			"flourishing island",
			"flourishing plains",
			"flourishing swamp",
			"flourishing mountain",
]

		names
			.map{|n| db.cards[n]}
			.flat_map{|card| card ? card.printings : []}
			.to_set
	end

	def to_s
		'is:lilia'
	end
end