class ConditionIsPerfect < Condition
    def search(db)
        names = [
            "serene prayer",
            "elixir of immortality",
            "reclaim relics",
            "lonely devil",
            "cloudshaper",
            "yngou the snowbeast",
            "coppergild mercenary",
            "lost among the lilies",
            "thought blossom",
            "esper command",
            "frostbreath dragon",
            "curse of encroaching waters",
            "monument of queens",
            "archivist's torment",
            "azun, sheriff of daisite",
            "cursory glance",
            "hembwe, the all-mother's hand",
            "arcane genesis",
            "deem unworthy",
            "lotus studies",
            "eradicating flames",
            "miscast",
            "jade temple",
            "calamity rose",
            "ardy's invocation",
            "wild festivities",
            "shining crusader",
            "zoetic tomb",
            "submergence",
            "gruff smith",
            "sharuum, archmagocrat",
            "whatever it takes",
            "blundering clocktower",
            "jarl's brutalizer",
            "citywide automation",
            "sadistic indulgence",
            "abandoned memorial",
            "gilded lotus",
            "cosmic sinkhole",
            "great sable stag",
            "tenacious guide",
            "event horizon",
            "rakkiri initiate",
            "fox of the orange orchard",
            "third legion general",
            "azun, sheriff of daisite",
            "avatar of basat",
            "blow away",
            "bogsworn club",
            "dancing flames",
            "pierce the storm",
            "gao’wu, master soothsayer",
            "tal, locus sentry",
            "blessing of morning",
            "dispel",
            "mastery of the veil",
            "touch of the uncanny",
            "bloomcrawler",
            "bashful drake",
            "reversal of fates",
            "lose track",
            "teeth without number",
            "darken the sky",
            "zhedina envoys",
            "archaeomancer",
            "ghostly flicker",
            "harrier's falcon",
            "fiery embrace",
            "silent wanderer",
            "ostracizer orb",
            "antimagic",
            "dwemer-made dovah",
            "aerie’s pillar",
            "ambushing alligator",
            "frontier hunter",
            "lord of the bubbledome",
            "dawson's marauder",
            "conchhorn shinygrabber",
            "adoroth, the baneful",
            "suitor of the sea",
            "hugo of the shadowstaff",
            "sanitarium skeleton",
            "fair trial",
            "crush the hull",
            "orodu, the onyx wave",
            "myrmidon, coralight exile",
            "coralight lifebloom",
            "autointerment",
            "cannoncoil hermit",
            "law enforcement",
            "master negotiator",
            "ahl’s study",
            "imperial titan",
            "the stranger’s play",
            "meren, bane of the cairns",
            "oceanographer",
            "swarm of the dispossessed",
            "breach the mind",
            "creeping terror",
            "swarm of the dispossessed",
            "siraj, interplanar thief",
            "crain's crony",
            "departed evangel",
            "impden mother",
            "miner's barracks",
            "grand expeditions",
            "perfect distraction",
            "ace trainer",
            "lucien, the grifter",
            "blood frenzy",
            "killdrone assembly works",
            "mindlock field",
            "moment of tranquility",
            "aguri, shadow of doubt",
            "aerida, envious chronomancer",
            "mirai, spring's promise",
            "avatar of plume de val",
            "pakka, the shadowcloak",
            "just business",
            "mpumo, who stands alone",
            "end of days",
            "senator christian winters",
            "legends remembered",
            "thunder road",
            "erika, mourning soul",
            "chi lee of the underworld",
            "descend on the helpless",
            "sukhar, consort to the dark",
            "terror of the ontarachie",
            "dragon queen's disciple",
            "mana ascetic",
            "meren, bane of cairns",
            "ria-demian charm",
            "shroud of hinasa",
            "adam of the ironside",
            "helena, the awakener",
            "holy war",
            "razing throng",
            "aguri, shadow of doubt",
            "pith wilt",
            "rain zai, spiritscale",
            "timestream sentinel",
            "waxing angel",
            "tabia of the lionheart ",
            "idyllic odyssey",
            "aryam the dreamer",
            "ethereal armor",
            "ethereal fervor",
            "skycaster’s aura",
            "acin, the toymaker",
            "lay low",
            "cursory glance",
            "craving secrets",
            "archive guardian",
            "whistling blades",
            "titan's palace",
            "overwhelming armies",
            "alia, bearer of morning",
            "blessing of morning",
            "heraldry",
            "flare blitz ",
            "legends remembered",
            "archive guardian",
            "meteor harbinger",
            "jara champion",
            "atychiphobia",
            "thought blossom",
            "sage's ashes",
            "perilous treaty",
            "carving secrets",
            "wandering dragonfly",
            "rahit, immaculate architect",
            "mei, the inflitrator",
            "jachsechep, god's wife",
            "burning sulfur",
            "meteor harbinger",
            "junan venomtongue",
            "aerida, envious chronomancer",
            "spell pierce",
            "burning sulfur",
            "mei liva, the exfiltrator",
            "scorch",
            "isochron wand",
            "plaxolotl pyari",
            "jade temple",
            "slyten crystal motherlode",
            "edarna the everforge",
            "horrific progenitor",
            "sunrise river",
            "swarm of the dispossessed",
            "spectral skycruiser",
            "sunrise woods",
            "performer of growth",
            "chiu of the wild realm",
            "eternal reactor",
            "ardy, youthful geomancer",
            "angelfire",
            "brilliant mansion",
            "forgotten pit",
            "epic of inishtu",
            "jade temple",
            "slyten crystal motherlode",
            "magnificent raid",
            "desert wurms",
            "amelie mayn",
            "hirukari, daughter of the sun",
            "ochiji, serpent of seven heads",
            "arcane rebound",
            "bessie, the muscle",
            "arcane rebound",
            "mulchborn behemoth",
            "riftkeeper entity",
            "wild encounter",
            "tarraka-no-oni",
            "answer midnight's call",
            "nadei the wavecaller",
            "set the stage",
            "kazimir’s ban",
            "rujan, the great pumpkin",
            "chikyu champion",
            "precursor sanctum",
            "idravir, the last city",
            "discordant bell",
            "clutch of the coil",
            "supplanter of realities",
            "the sun also rises",
            "blundering clocktower",
            "timeworn crags",
            "petal-weaver alexa",
            "demanding idol",
            "the issbarrens",
            "aerie's pillar",
            "zhedina outskirts",
            "velir the sunderer",
            "imagination unleashed",
            "voliv edgelands",
            "great sable stag",
            "head of ulko",
            "suborn humanity's work",
            "lumbering hillock",
            "derelict town",
            "the flames approach",
            "antali archdruid",
            "powder scatterer",
            "esper command",
            "paragon of purity",
            "extremespeed",
            "judge’s decree",
            "third legion general",
            "dredgeline colossus",
            "xing, the lucky charm",
            "kazimir’s ban",
            "nidhir, the one beyond",
            "dissipate",
            "not all who wander",
            "maktali archivist",
            "lodestone golem",
            "stall fate",
            "silent wayfarer ",
            "moonlight sanctum",
            "crystal wave",
            "lost among the stars",
            "gleaming mirrorweaver",
            "lord rickard dawson",
            "siraj, interplanar thief",
            "lord ellison crain",
            "lazaire’s altar",
            "emperor tzhai",
            "aurora's whisper",
            "aryam, the dreamer",
            "eli’s defiance",
            "antimagic",
            "kaalia's abomination",
            "banish",
            "archivist's torment",
            "enchanting palace",
            "seismic colossus",
            "scintillate",
            "shigurei, the floodbringer",
            "cragbound crusher",
            "golden age",
            "erollin, eccentric collector",
            "gruff smith",
            "guardian of the eclipse",
            "calamitous crash",
            "faradia, honored sovereign",
            "bile of the world",
            "observer of aeons",
            "seal of approval",
            "rune of rejuvenation",
            "dead man's hand",
            "scrapyard sovereign",
            "salvation engine",
]

        names
            .map{|n| db.cards[n]}
            .flat_map{|card| card ? card.printings : []}
            .to_set
    end

    def to_s
        "is:perfect"
    end
end