class ConditionIsMable < Condition
	def search(db)
		names = [
			"afterlife heist",
			"antimagic formula",
			"arbiter of the scales",
			"charting the cosmos",
			"crystal garden",
			"just business",
			"legacy's malediction",
			"leyline alignment field",
			"lost to the ages",
			"meadow's melody",
			"memento mori",
			"mirrorgate",
			"oscanthor, trader's ruin",
			"outsmart",
			"overloaded aethergate",
			"puppeteering",
			"tidal spite",
			"titan's palace",
			"turela, defiant angel",
			"vengeful messenger",
			"wandering souls",
			"arcane rebound",
			"arcanist's dispersal",
			"assault on prosania",
			"barbaric dexterity",
			"beragnian blizzard",
			"burn with rage",
			"collapsing ground",
			"distort reality",
			"forest",
			"gallord's intervention",
			"griptide",
			"groundswell",
			"guilty execution",
			"imminent collision",
			"infuse vitality",
			"island",
			"koth's retaliation",
			"majestic garrison",
			"master echomage",
			"mawdryk's accusation",
			"merkurio's insight",
			"mountain",
			"necrobite",
			"offer to nature",
			"plains",
			"prepare for confrontation",
			"purging reolem",
			"rallios' demise",
			"reality check",
			"ripping wilds",
			"roggar's frenzy",
			"swallowed by the earth",
			"swamp",
			"tharanos' stratagem",
			"tharyen's sadism",
			"the high prairies",
			"threats from the outskirts",
			"time to depart",
			"treetop defense",
			"undying welcome",
			"unstable footing",
			"until the last breath",
			"vaporizing blast",
			"weather the storm",
			"abandoned sanctuary",
			"ambush viper",
			"apothecary's remedy",
			"bane of the folded fan",
			"blades of the many",
			"breath of hao'tai",
			"brothers in arms",
			"call to attention",
			"coax under",
			"come crashing down",
			"consult the dewdrops",
			"demystifying tide",
			"descend into insanity",
			"desecrate antiquities",
			"dragon grip",
			"empowering chant",
			"fell the beast",
			"ferocity of hao'tai",
			"form of the demon",
			"gaze of the golden fox",
			"inundated sanctuary",
			"invoke the wild",
			"kicking crane technique",
			"lost among the lilies",
			"midnight predator",
			"negate",
			"neutralize",
			"recalibrate",
			"resurrection plea",
			"sacred sanctuary",
			"savage sanctuary",
			"shock blast",
			"slicing legion",
			"soulless decree",
			"spidery grasp",
			"spire sanctuary",
			"spitfire",
			"surging stream",
			"the mad sage's scroll",
			"unsettled rivalry",
			"unyielding presence",
			"wander ashore",
			"warrior's meditation",
			"way of kindred mind",
			"wicked rites",
			"wretched sanctuary",
			"aghavaan's wound",
			"ancient ossuary",
			"awakening the dragon",
			"bind in jade",
			"clutch of the coil",
			"day of the emperor",
			"discorporate",
			"dragon's ire",
			"dragonwall samurai",
			"drown in sand",
			"festival of fading lights",
			"festival of roaring dragons",
			"festival of spring blossoms",
			"festival of winter's night",
			"flash of steel",
			"flow of the river",
			"heavenly temple",
			"hone the blade",
			"imperial ricefields",
			"inner thoughts",
			"mokuteki ambusher",
			"oshiruko cleansing",
			"pierce the storm",
			"reversal of fates",
			"sankataar ambushers",
			"searing script",
			"seek the future",
			"serpent's grasp",
			"shinrin blademaster",
			"shinrin spellhunter",
			"shroud of hinasa",
			"shugenja sanctuary",
			"silk crane adept",
			"soul leak",
			"stonesculpting",
			"storm of shadows",
			"sunrise orchard",
			"taiyohata champion",
			"through the mists",
			"touch of the coil",
			"unhallowed graves",
			"voice of sheraku",
			"wayfarer's shrine",
			"wild lightning",
			"will of the emperor",
			"adaptive terrains",
			"armament upgrade",
			"battle fervor",
			"cancel",
			"crafter's mistake",
			"disassemble",
			"divine verdict",
			"druid's deliverance",
			"eradicating flames",
			"explosive implant",
			"fervent assault",
			"fierce instinct",
			"flooded morass",
			"flourishing crevasse",
			"forced idleness",
			"gather forces",
			"gift of undeath",
			"heart of the glade",
			"impulsive action",
			"inspiring personality",
			"laia's intervention",
			"lavatorn fields",
			"logayr, lafterii magistrate",
			"mischievous miscreant",
			"planar alignment",
			"pool of light",
			"repressed potential",
			"resourceful impersonator",
			"rush of strength",
			"scholar's captivation",
			"shoot down",
			"soul pierce",
			"spreading disease",
			"springjack pasture",
			"suicidal impulse",
			"summoner's bane",
			"surprise strike",
			"vanguard's assault",
			"viper's fangs",
			"war golem forge",
			"ward shatter",
			"abrupt volley",
			"amber hills",
			"boiling ridge",
			"bring down",
			"brutal onslaught",
			"clever diversion",
			"danuri charm",
			"darklands charm",
			"denied attempt",
			"dictate of rallios",
			"dictate of the triumvirate",
			"duskwood thicket",
			"element of surprise",
			"elementalize",
			"elspeth's intervention",
			"elusive illusionist",
			"empty the tombs",
			"fellor charm",
			"flame jolt",
			"flooded depths",
			"grim bastion",
			"hazy moorland",
			"intrepid shooter",
			"kill shot",
			"lafterii charm",
			"lafterii trickery",
			"last crusade",
			"magmatic torrent",
			"memories reignited",
			"merkurio's prowess",
			"mirror image",
			"naturalize",
			"obliterating blast",
			"pandora's mending",
			"piling corpses",
			"punish aggression",
			"reconstruct",
			"rehison charm",
			"ritual of blight",
			"rugged fields",
			"ruthless bash",
			"scar shed",
			"search for inspiration",
			"sheltering fog",
			"shield's rebuttal",
			"shifting frontiers",
			"silencing curse",
			"strangle to death",
			"strategic retreat",
			"strike from above",
			"sudden changes",
			"sungrace meadows",
			"sunlit highland",
			"temporal loophole",
			"terrenal might",
			"the shield",
			"unknown shores",
			"unstable experiment",
			"weapon smash",
			"admonish the unruly",
			"adverse reunion",
			"altar of adversity",
			"altar of chaos",
			"altar of creation",
			"altar of destruction",
			"altar of order",
			"angeltouched cavern",
			"angeltouched crag",
			"angeltouched garden",
			"angeltouched marsh",
			"angeltouched saltflat",
			"assertive inaction",
			"bane of identity",
			"beckon the scribes",
			"crisis of body",
			"death in reverse",
			"descended delta",
			"descended marsh",
			"descended meadow",
			"descended mortuary",
			"descended towers",
			"dissolve",
			"divine detention",
			"enforce the cycle",
			"excise from existence",
			"fatal edict",
			"formed anew",
			"fury swipes",
			"lifetwist",
			"lightning chorus",
			"marzen's frenzy",
			"peel from reality",
			"pierce the unruly",
			"proclamation of the tides",
			"provoke the gods",
			"qith maneuver",
			"recombobulate",
			"release from death",
			"repel the unruly",
			"resounding relief",
			"righteous bolt",
			"search for precedent",
			"searing blasphemy",
			"silence of the guilty",
			"spawn from the void",
			"strength from chaos",
			"telling time",
			"test of fear",
			"test of forsaking",
			"tides of chaos",
			"unpredictable bloodshed",
			"verdant trauma",
			"wake from the mire",
			"whim of ifram",
			"zephyr purifier",
			"ada's mischief",
			"aetherial ascent",
			"ahl's study",
			"annihilate aggressor",
			"augment authority",
			"confront death",
			"converted conqueror",
			"crafted coast",
			"destiny forgotten",
			"dire dive",
			"disgrace of kin",
			"dispel delusions",
			"edge of the world",
			"enlightened lizard",
			"essence inversion",
			"exploring the mirrorworlds",
			"fateweaving",
			"flare extensions",
			"foreseen denial",
			"foreseen failure",
			"foretold strength",
			"glintwing replica",
			"guerrilla strike",
			"halls of renown",
			"haunted estate",
			"hour of honor",
			"ichor fling",
			"live",
			"lush outcrop",
			"mirrorwalk",
			"moonsight",
			"nullify naysayer",
			"proclaimed cure",
			"reins of influence",
			"reweave reality",
			"scattering light",
			"show of supremacy",
			"sneak a peek",
			"sodden sorrow",
			"spired canopy",
			"summoner's call",
			"twisted elixir",
			"wait",
			"wightlight",
			"avoid fate",
			"bazaar guardian",
			"blood lashing",
			"chain of decimation",
			"channel the mirror",
			"clinging mire",
			"colpah charmer",
			"crystallized moment",
			"delude",
			"dignity",
			"divert attention",
			"echoing determination",
			"echoing rites",
			"echoing silence",
			"echoing sunder",
			"echoing thunder",
			"faded sacrifice",
			"fallen fanatic",
			"feed into aether",
			"flinging invoker",
			"forge trick",
			"fueled flame",
			"ghastly castle",
			"gleaming veldt",
			"grisly marsh",
			"infiltrate memory",
			"intangible company",
			"learn from mistakes",
			"manifest memories",
			"melt down",
			"mental meltdown",
			"might of the oslyd",
			"mightlight",
			"mindrip",
			"mirrored mirage",
			"mirrorstalk",
			"portent of doom",
			"power jam",
			"refract",
			"safe",
			"sha's summons",
			"sunken cavern",
			"sunny dunes",
			"sword",
			"toggle",
			"antithesis",
			"bath in the solitude",
			"blurring mists",
			"blurry counterpart",
			"brute force",
			"crippling spirit",
			"daunting gaze",
			"dawn silhouette",
			"desert temple",
			"desert warriors",
			"divine denial",
			"excellent architecture",
			"haze raptor",
			"imaginary flames",
			"judge unworthy",
			"life-giving waters",
			"menhet charm",
			"mesmerizing shimmer",
			"mummification",
			"preserving cloak",
			"pyramid lord",
			"sandborn mage",
			"sandmouth dragon",
			"spell dilution",
			"sudden drought",
			"survive",
			"tendrils of corruption",
			"wachet charm",
			"wall of fog",
			"whistled dragons",
			"wurm spawning",
			"annihilate the enemy",
			"arina's defiance",
			"awaken to the skies",
			"break hold",
			"deathwind expanse",
			"deathwind's grasp",
			"duel of intellect",
			"electrokinetic's bolt",
			"essence scatter",
			"firewall trap",
			"gryla canyon",
			"hidden prowess",
			"kimar, lightforger",
			"last parley",
			"lightbringer's touch",
			"moonshadow abyss",
			"opt",
			"plasma arc",
			"priest's altar",
			"pyre trap",
			"raise the alarm",
			"signal distress",
			"simplified life",
			"spellbane's strike",
			"stormcaster's tower",
			"sudden suspension",
			"syncopate",
			"telenian formshaping",
			"trapcatcher's form",
			"akimbo slash",
			"aquatic refuge",
			"arbalest barrage",
			"ascendant's murmur",
			"blazing beam",
			"citadel of denial",
			"crippling fear",
			"dessication ritual",
			"empty the archives",
			"fierce howl",
			"foxflame",
			"harmonious meditation",
			"harrowing infusion",
			"hasty assault",
			"heated dispute",
			"monumental siege",
			"no-man's land",
			"ocean spray",
			"once more with style",
			"organic corrosion",
			"orichi of the cold mist",
			"perimeter siege",
			"pietistic performance",
			"prairie monastery",
			"rhythmic distraction",
			"scorched copse",
			"siphoning slash",
			"staggering brilliance",
			"stand tall",
			"stitch sinew",
			"strike out",
			"sunless ridge",
			"swift savior",
			"temple of brilliance",
			"the way of the fan",
			"toxic spring",
			"wash away",
			"xing, the lucky charm",
			"abinna's consecration",
			"akrianos' command",
			"ardor of the masses",
			"artful diversion",
			"artificer's persuasion",
			"blow to pieces",
			"bonds of quicksilver",
			"brace for battle",
			"branding shackles",
			"burn with demonfire",
			"contempt for the unnatural",
			"dazzling voidmage",
			"delirious fervor",
			"earthenlore blessing",
			"enduring vestige",
			"erika's purge",
			"evasive maneuver",
			"fatresya's command",
			"frostfire geysers",
			"fungal mire",
			"gloomcover steppe",
			"gorandu's majesty",
			"gorillas in the mist",
			"grafted physician",
			"harpoon launching",
			"ishtari's deliverance",
			"jeska's command",
			"kellythross' workshop",
			"kevthra's command",
			"lush oasis",
			"merkurio's command",
			"molten ritual",
			"muster for battle",
			"nightchill grasp",
			"non-stop production",
			"orrery technician",
			"pestilent renewal",
			"pinpoint accuracy",
			"prohibit",
			"purging strike",
			"rampaging tremorwurm",
			"reengineer",
			"reorganized thoughts",
			"replicator mage",
			"rousing chant",
			"seismic strike",
			"shal'draen's rage",
			"shrine of the six pillars",
			"spiraling canyon",
			"stampede instigator",
			"stunning jolt",
			"timely commander",
			"total recall",
			"unpredictable blizzard",
			"vengeful ferocity",
			"violent offensive",
			"volatimancer",
			"absence of the unmaker",
			"ambitious dreams",
			"arcor windfall",
			"ardent charge",
			"arrogant training",
			"bustling docks",
			"change of fortunes",
			"choked estuary",
			"commoners' justice",
			"dance of grace",
			"death's door",
			"deflecting strike",
			"derelict amphitheatre",
			"fall of whiterun harbor",
			"fall of the axe",
			"farmer's repose",
			"flash of inspiration",
			"foreboding ruins",
			"fortified village",
			"game trail",
			"generous offer",
			"harmonized intellect",
			"hasty intervention",
			"ill-advised tactics",
			"interlocked waterways",
			"isolated cloister",
			"left for carrion",
			"melting point",
			"minor melee",
			"misleading doubts",
			"moment of tranquility",
			"painful reminiscence",
			"plunge through the heart",
			"port town",
			"price of power",
			"publicly disgraced",
			"ranger's guile",
			"royal summons",
			"sage's foresight",
			"scraps of memory",
			"seal the tomb",
			"shadowed slums",
			"shatter",
			"social graces",
			"spur to action",
			"steward's tithe",
			"sunken ambitions",
			"surge of duty",
			"swift deployment",
			"talks in hidden hollows",
			"thailen's reprisal",
			"twilight raid",
			"voyage's end",
			"weary steward",
			"whiterun gates",
			"whiterun harbor",
			"withering agony",
			"abandoned battlefield",
			"abandoned cairn",
			"abandoned meadow",
			"abandoned skyroad",
			"abandoned wilderness",
			"academy wastes",
			"alpine meadow",
			"barren desolation",
			"calmed battleground",
			"charbroiled core",
			"chiseled cliffside",
			"cleared vault",
			"cliffside entrance",
			"command tower",
			"dawnlit battlefield",
			"deadwood grove",
			"deeplife cavern",
			"deserted steppe",
			"deserted trail",
			"desolate barrens",
			"exotic xenoreef",
			"fiery chasm",
			"flourishing waterways",
			"forgotten cryovault",
			"forgotten shrine",
			"frigid highlands",
			"frontier base",
			"gleaming hot springs",
			"gnarled henge",
			"grim slums",
			"grove of reversal",
			"haughty chateau",
			"haunted woodlock",
			"highland vale",
			"horizon of origins",
			"imperial barracks",
			"jagged crag",
			"legacy foundations",
			"lush outskirts",
			"mossy shrine",
			"mysterious cataract",
			"ocean monastery",
			"ominous lair",
			"ornamented evergreen",
			"overgrown refuge",
			"quintok station",
			"rainforest spring",
			"roaring cascade",
			"secluded cascade",
			"shardstone rift",
			"shrouded rooftops",
			"sky-high spires",
			"sodden cavern",
			"somber marsh",
			"spires of telenia",
			"stormcharged pyre",
			"strange harbor",
			"sunlit ruins",
			"timber range",
			"tirenan market",
			"torrid geysers",
			"toxic jungle",
			"tranquil stream",
			"unlit alley",
			"wastes",
			"weathered fortress",
			"wildrune thicket",
			"abandoned forge",
			"abandoned hideout",
			"abandoned laboratory",
			"abandoned preserve",
			"abandoned shores",
			"anguished unmaking",
			"blood frenzy",
			"breaking news",
			"choking despair",
			"cloudsnatch",
			"dancing flames",
			"distant thunder",
			"ephemeral support",
			"evanescier greypelt",
			"evanescier priest",
			"guardian's resolve",
			"hold fast",
			"hollow hooligan",
			"insightful blow",
			"living antimagic",
			"lost in fugue",
			"mongrel of grenoui hill",
			"moonshadow remnant",
			"mystic's mantle",
			"paralyzing ennui",
			"precursors' disdain",
			"revenge of the disfigured",
			"split-second decision",
			"stay determined",
			"still the pandemonium",
			"torches raised",
			"absolve",
			"anzen, beyond the sea",
			"blade of mautakesh",
			"chikami castle",
			"dragonwall gates",
			"finishing touches",
			"fires of seishin",
			"himitsu, shigure's legacy",
			"house of forgotten whispers",
			"iaijutsu",
			"imperial port",
			"imposition",
			"inner purity",
			"kami's greed",
			"kurayami shrine",
			"legacy's end",
			"mana corruption",
			"memorial of the fallen",
			"midnight keep",
			"mystic arts",
			"only memories remain",
			"path of the waters",
			"perilous passage",
			"phasmophobia",
			"prayer of drifting lights",
			"saishuteki castle",
			"sanctify",
			"scintillate",
			"seishin dojo",
			"serene form",
			"sevenfold monk",
			"sever limbs",
			"shikai's redoubt",
			"snake tattoo",
			"spirit reflections",
			"stormwake",
			"sunset monastery",
			"tales of old jidai",
			"temple of falling leaves",
			"the last sacred gate",
			"thousand cuts",
			"tower of long shadows",
			"tsang jin, master of the jade sea",
			"unzari ruins",
			"whisper of the winds",
			"worthy of the name",
			"bloodstone halls",
			"brain static",
			"crumbling vestige",
			"due judgement",
			"ember salvo",
			"exclude",
			"freezing maelstrom",
			"galeforce ",
			"harm's way",
			"healer's knack",
			"hill of souls",
			"leech soul",
			"lightning strike",
			"mighty swing",
			"mist lurker",
			"moonlit shore",
			"predatory feast",
			"pull the strings",
			"pummel",
			"redo",
			"rush of thought",
			"sanctum",
			"seabreen nullmage",
			"sink into despair",
			"soul flame",
			"spell shackle",
			"steeled resolve",
			"stoneskin",
			"sudden ambush",
			"trail of rebirth",
			"valley falls",
			"valley mists",
			"vampiric thirst",
			"venomous assault",
			"verdant sanctum",
			"wild fervor",
			"wild ravine",
			"aether tradewinds",
			"ancestral revision",
			"birth of death",
			"blessing of bliss",
			"blood bond",
			"blood ritual",
			"bloodriver",
			"blossoming defense",
			"brush off",
			"child's play",
			"cloudbank",
			"corpsebed",
			"cradle of corruption",
			"devious naiad",
			"drown",
			"drowned weaver",
			"dying wishes",
			"earthrend",
			"eldritch undoing",
			"elrayin, the manaroot",
			"embrace the curse",
			"even death may die",
			"eye of a moment",
			"first carvings",
			"giant growth",
			"gift of eternity",
			"gifted grace",
			"gim-chimya, the invisible",
			"glimpse of beyond",
			"gone with the wind",
			"lapidify",
			"moonlace",
			"mosecf, the sunseeker's path",
			"not all who wander",
			"path to mortality",
			"peek below",
			"predator's hunger",
			"pride of thorns",
			"quickchange",
			"ralora, unforgiving depths",
			"read the entrails",
			"reconsider",
			"reinvigorate",
			"relinquish",
			"ride the waves",
			"river's wrath",
			"school the fish",
			"sea of skies beyond",
			"seedshrine",
			"seeker's end",
			"sever",
			"shifting terrain",
			"spark of faith",
			"spiteful growth",
			"starglare",
			"striptide",
			"sunstage",
			"this too shall pass",
			"thunder wave",
			"unholy offering",
			"united force",
			"vaporize",
			"web of the lost",
			"whirtex",
			"all or nothing",
			"arctic mine",
			"assassin's warning",
			"crumbling precipice",
			"crystal cavern",
			"crystal puncture",
			"cull the citizenry",
			"daunting skyline",
			"days of decay",
			"decrepit crags",
			"empty the streets",
			"failing port",
			"fate transfer",
			"flush with arcor",
			"forgotten consequences",
			"forgotten steppe",
			"glimpse of innocence",
			"grim courtyard",
			"hazy lagoon",
			"ill fated travels",
			"invalidate",
			"judge's decree",
			"loss of focus",
			"martyr's sacrifice",
			"master of disorientation",
			"mental fracture",
			"merchant's district",
			"merchant's guile",
			"morning passages",
			"murmuring falls",
			"nomad's township",
			"pale flotsam",
			"phosphorescent ravine",
			"purge the harbor",
			"rampant summit",
			"resplendent substratum",
			"revelry reverie",
			"rickety guildhall",
			"ruined citadel",
			"scatter riches",
			"sedate tundra",
			"serene trail",
			"shared reminiscence",
			"shifting glade",
			"to say farewell",
			"track prey",
			"untested initiates",
			"valor of the desperate",
			"vibrant rainforest",
			"watchkeeper's prerogative",
			"watchkeeper's retort",
			"wisdom in reflection",
			"aether leak",
			"aetherite slugs",
			"aetherwhirl",
			"arcane heist",
			"atop their high horses",
			"axom, the drifter",
			"bloodthirsty ambusher",
			"cage the mind",
			"canopy ambush",
			"collapsed mine",
			"derelict town",
			"disallow",
			"dispel",
			"fog",
			"fool's gold",
			"forgotten haunt",
			"from the shadows",
			"frontier paragon",
			"full house",
			"ghastly character",
			"ghostly flicker",
			"ghostway",
			"gift of shadows",
			"gun fight",
			"harsh wastes",
			"high noon",
			"judges' shield",
			"luck of the draw",
			"make an entrance",
			"mudslinging",
			"murder",
			"mysteries of the ulek",
			"pocket aces",
			"qilan archer",
			"reach for the sky",
			"recoil",
			"reforge",
			"refund",
			"slinger's showdown",
			"slinger's storm",
			"stand your ground",
			"sunrise bluffs",
			"sunrise prairie",
			"sunrise river",
			"sunrise ruins",
			"sunrise woods",
			"tales of the lingering",
			"the aetherite saloon",
			"train heist",
			"unassuming swineherd",
			"warning shot",
			"aokara commander",
			"backburner",
			"bond of battle",
			"chamber of splendor",
			"champion of the provinces",
			"diffuse",
			"dragonfly shrine",
			"dreams of tomorrow",
			"elemental power",
			"enshrine",
			"fiery embrace",
			"fireshaper adept",
			"grasp of water",
			"honor and glory",
			"imperial legacies",
			"jade temple",
			"kirishima's escort",
			"kuno aokara, ivory crane",
			"mortal will",
			"night ambush",
			"odaya magistrate",
			"palace of reflections",
			"paragon of honor",
			"past, present, future",
			"primal channeler",
			"ride as one",
			"rippling water shugenja",
			"sea cache",
			"searing grace",
			"seek guidance",
			"shengin heartland",
			"smoldering pages",
			"spirit script",
			"strike from the shadows",
			"thunder from above",
			"torrent of wind",
			"vanish",
			"venerable purist",
			"aerie's pillar",
			"aether ascendant",
			"artisan of marrow",
			"blessing of valor",
			"bygone guardian",
			"ceaseless valiant",
			"channeling stone",
			"confirm hypothesis",
			"forgotten pit",
			"lumbering hillock",
			"misleading tactics",
			"rahit's prodigy",
			"rousing rubble",
			"salva tore's vexation",
			"shatter facade",
			"sprout thought",
			"stall fate",
			"submergence",
			"thought blossom",
			"thunderous charge",
			"abandoned den",
			"aegis expertise",
			"ascetic of imbalance",
			"aspect of focus",
			"awoken soul",
			"bloodhunter orca",
			"blow away",
			"breathless gasp",
			"cane dancer",
			"casualty of war",
			"cinder arrows",
			"culi-sae mesmer",
			"culi-sae transfigurer",
			"devastating blow",
			"dragon queen's den",
			"efface",
			"engrave",
			"fateful journey",
			"greenheart den",
			"hibernation den",
			"highlands champion",
			"invocation circle",
			"issbarren warden",
			"issbarrens banishment",
			"lose composure",
			"midnight gaze",
			"nature's claim",
			"pinion peaks",
			"play the coward",
			"raider's den",
			"scornful flames",
			"seek haven",
			"seismic passage",
			"soul stroke",
			"splintering hail",
			"the issbarrens",
			"to the hunt",
			"treacherous conditions",
			"turbulent journey",
			"wake of the beast",
			"wanton cleave",
			"war-torn tundra",
			"warring ways",
			"windwhip",
			"autumn moon",
			"blundering clocktower",
			"canyon creek",
			"clever rejoinder",
			"cloud rock",
			"clouded mind",
			"concord of ravens",
			"crystal grotto",
			"cumulus horizon",
			"dance of fire",
			"evolving wilds",
			"fey grove",
			"frailty",
			"frigid thicket",
			"gorgon's gaze",
			"haunted boughs",
			"hint of exuberance",
			"inspiring journey",
			"intoxicate",
			"legendweaving",
			"lessons learned",
			"moon of the encroaching night",
			"moon of the final dawn",
			"moon of the frozen dusk",
			"moon of the lingering day",
			"moon of the promised day",
			"moonlit hunter",
			"ruined precipice",
			"rush of wonder",
			"small luxuries",
			"soaring canyon",
			"touch of witchcraft",
			"trinkets and charms",
			"verdant bluff",
			"accursed by unborn fates",
			"aethermage's chains",
			"ancient cairns",
			"antimagic",
			"arcane duelist",
			"awaken the nav",
			"catalog the possibilities",
			"chroma, the faerie circle",
			"crack open the cache",
			"darken the skies",
			"deem incomplete",
			"dimensional dodge",
			"dispersive volley",
			"duelist's forms",
			"enigma of seventy scrolls",
			"fae-blessed hunter",
			"field of obelisks",
			"find nothing",
			"finish the job",
			"from ancient tomes",
			"gate to the nav",
			"keep at bay",
			"kindle the cursed",
			"mina and adurnos",
			"mischievous sprite",
			"mysterious absence",
			"nature's defiance",
			"noxious garden",
			"oracle's omission",
			"outland alchemist",
			"overgrown ruins",
			"pact of martyrs",
			"portal to the unknown",
			"price of wisdom",
			"pyremage's last rite",
			"scholar of reflections",
			"seedcall",
			"sever flesh",
			"sower of dreamless sleep",
			"tear through",
			"the barricade strikes",
			"through the ashen gate",
			"touch of the uncanny",
			"twist the threads",
			"twisted stampede",
			"unnoticed in the glade",
			"wanderer's sky",
			"wither",
			"yuroda's blessing",
			"zadyk resourcefulness",
			"acorn assault",
			"ascendant's gate",
			"augmented spawn",
			"backstage rooms",
			"control discourse",
			"cursory glance",
			"cut short",
			"dying breath",
			"evigial winds",
			"exeunt",
			"exit, pursued by a bear",
			"flameblade",
			"grafted experiment",
			"grieved outburst",
			"growing pains",
			"hats off",
			"heist headquarters",
			"hidden hollow",
			"komurk raid",
			"legitimate establishment",
			"loose ends",
			"lost in smoke",
			"miscast",
			"poisoned wine",
			"qililia, the saboteur",
			"rehearse",
			"rei's reinforcements",
			"ruined theater",
			"ruptured citadel",
			"ruptured expanse",
			"ruptured falls",
			"ruptured flats",
			"ruptured grotto",
			"ruptured grove",
			"ruptured meadow",
			"ruptured morass",
			"ruptured square",
			"ruptured trail",
			"saia's price",
			"scathing review",
			"scramble the scouts",
			"scuripi lookout",
			"seedy bar",
			"slay them in the aisles",
			"soulless backstabber",
			"squid pro quo",
			"taken for granite",
			"talent pool",
			"tyrant's reckoning",
			"unraveling",
			"vampiric hunger",
			"aetheric disarm",
			"ancestral warlord",
			"catalina's turf",
			"caylin whirlwind",
			"clutch shot",
			"derail",
			"deviser's cunning",
			"dominik's shack",
			"douse in flame",
			"evening report",
			"failing defenses",
			"forgotten doorway",
			"ganzorig's domain",
			"guiying's gambit",
			"hiroto's refuge",
			"hostile takeover",
			"imperial titan",
			"last stop",
			"magnificent raid",
			"neblus' legacy",
			"ride the storm",
			"riga's workshop",
			"riko's academy",
			"riv's safehouse",
			"spark new life",
			"takumi's headquarters",
			"transformative insights",
			"treacherous toss",
			"tsubasa's redoubt",
			"unforget",
			"xiu's escape",
			"apt countermeasure",
			"atrophy",
			"barren boneyard",
			"bewitching vapors",
			"brazen sacrilege",
			"buried by time",
			"calcified dunes",
			"carpet racers",
			"colossal camouflage",
			"decree of bias",
			"dissipate",
			"due judgment",
			"eccentric musings",
			"el-mazar, wayward palace",
			"flourishing dunes",
			"follow the light",
			"heat ray",
			"highland dunes",
			"immolated grave",
			"obscuring sandstorm",
			"outflank",
			"outspoken seminar",
			"painted bluffs",
			"princely mettle",
			"ravaged monument",
			"ridge warden",
			"rush of adrenaline",
			"sandstreamer",
			"sandswept bazaar",
			"saturated dunes",
			"scimitar techniques",
			"sink into the floor",
			"skeletal oasis",
			"skin from bone",
			"stabilize",
			"stasis snare",
			"strangulate",
			"strike down",
			"stygian dunes",
			"sunrazed ruins",
			"tomb of great drakes",
			"venom infusion",
			"visceral assault",
			"ancient gift",
			"arcanist's spellsurge",
			"aurora's whisper",
			"binding stones",
			"breach the mind",
			"children of the clouds",
			"diabolic designs",
			"dust barrens",
			"fade into mists",
			"gift to the gloam",
			"golden glade",
			"heartless pact",
			"hexfang ascetic",
			"ligos, shadow's source",
			"moonlit pursuit",
			"read the clouds",
			"reckless rage",
			"rend",
			"ritual of coalescence",
			"rius, temple of the grandfather",
			"silent musing",
			"singers' grove",
			"streamlash",
			"the aurora's heart",
			"the court of angels",
			"tranquil moment",
			"verse of fire",
			"waking mists",
			"aetherdrain",
			"art studio",
			"artisan's sorrow",
			"beautiful crescendo",
			"bewildering sight",
			"blessed mausoleum",
			"bog rebirth",
			"book return",
			"burning revelations",
			"captivating jester",
			"coat in petals",
			"coordinated commotion",
			"damning flames",
			"dangerous territory",
			"eerie bayou",
			"elaborate transportation",
			"elegant strike",
			"faradia's grace",
			"fervent strike",
			"fool's errand",
			"forlorn ruin",
			"gift of the bayou",
			"glorious celebration",
			"helena's exaltation",
			"helena's rebuff",
			"intoxicating melody",
			"lakeside park",
			"lazaire's conjuring",
			"luminescent croaker",
			"manhunter kantra",
			"mark of the scaleblight",
			"marsh's veil",
			"murmurs of the bayou",
			"mushroom lagoon",
			"ontarachie bushwhack",
			"parish's command",
			"prayer hall",
			"radiant outburst",
			"reclaim the devout",
			"ritzy parlor",
			"riverboat assault",
			"royal domain",
			"smite the monstrous",
			"sporeflow repulsion",
			"sudden conversion",
			"sunlit plaza",
			"vacated bar",
			"whispers of the ontarachie",
			"witch's invocation",
			"woopip decomposition",
			"zoulev offering",
			"zoulev rebuff",
			"act of repentance",
			"adiran distractor",
			"artist's vista",
			"buy time",
			"chance at redemption",
			"consuming symbiosis",
			"equilibrium paladin",
			"fallacy's sanctifier",
			"felice's defiance",
			"in tragedy",
			"inspire actuality",
			"once abandoned",
			"once betrayed",
			"once denied",
			"once scarred",
			"once shunned",
			"over the horizon",
			"recalculation",
			"refracted thoughts",
			"seek refuge",
			"stark copse",
			"stark hinterlands",
			"stark horizon",
			"stark stream",
			"stark wildfire",
			"through worlds",
			"unbound horizons",
			"wicked blow",
			"abandoned monument",
			"aether gateway",
			"aethermancer's familiar",
			"autumn canopy",
			"beneath the zhedina",
			"blossoming expanse",
			"brine fleet bay",
			"caronas, eon wanderer",
			"cave diving",
			"cloudsteel summit",
			"crater burst",
			"cursed wastes",
			"dreamscape",
			"dustchoked outpost",
			"endless trove",
			"eternal reactor",
			"explorer's ascent",
			"fractured reach",
			"fungal swathe",
			"gathering beacon",
			"ghostspore mire",
			"gilded gulch",
			"glacial shelf",
			"glimmer",
			"grove of embers",
			"guided by the weave",
			"harrowing experience",
			"heart of zhedina",
			"hot streak",
			"idravir, the last city",
			"journey's end",
			"kilnfire",
			"krismite vault",
			"lotus lake",
			"microzoologist",
			"molten falls",
			"monument of queens",
			"morphic verge",
			"nereba, sandchoked archives",
			"notorious smuggler",
			"otherworldly forest",
			"otherworldly gifts",
			"otherworldly island",
			"otherworldly mountain",
			"otherworldly plains",
			"otherworldly swamp",
			"paracosm",
			"planeshift",
			"polyp pools",
			"portal fracture",
			"precursor sanctum",
			"prismatic champion",
			"promethean grotto",
			"rainsculpted gorge",
			"razione racecourse",
			"research experience",
			"rift splicing",
			"shadowcleft hideout",
			"shifting canyon",
			"shifting cascade",
			"shifting crag",
			"shifting grove",
			"shifting morass",
			"shifting spaces",
			"shuddering node",
			"skylight fortress",
			"smuggler's den",
			"soaring rainforest",
			"starlight beacon",
			"steamlit peaks",
			"survival experience",
			"tears of tizuma",
			"threadspinner",
			"timeless shrine",
			"tomb of shifting sands",
			"undermarket guildmaster",
			"untethered spire",
			"voidflare",
			"voliv edgelands",
			"wayfinding",
			"worlds away",
			"woven network",
			"zhedina coastguard",
			"zhedina exchange",
			"zhedina outskirts",
			"zhelid, planar academy",
			"brilliant academy",
			"brilliant archives",
			"brilliant capital",
			"brilliant castle",
			"brilliant citadel",
			"brilliant cityscape",
			"brilliant hub",
			"brilliant mansion",
			"brilliant port",
			"brilliant workshop",
			"city gate",
			"corrupted knowledge",
			"crystallized hope",
			"disable",
			"disqualify",
			"extravagant flair",
			"flamecloaked artisan",
			"frozen moment",
			"herald of wisdom",
			"iken company nightwalker",
			"imagination unleashed",
			"instant of brilliance",
			"irika, wielder of secrets",
			"observer of secret paths",
			"open the secret paths",
			"purging light",
			"reclusive archmage",
			"renewal grove",
			"resonating force",
			"riftway to the other side",
			"runecrested valley",
			"self replication",
			"slay the unkillable",
			"timeworn crags",
			"transplanted citadel",
			"twisted speaker",
			"veil's recovery",
			"veilborn meddler",
			"watch time slip away",
			"crossroads harrier",
			"cutting rejection",
			"drained shore",
			"drought-plagued slum",
			"fluctuating locale",
			"forsaken getaway",
			"grave of an old lord",
			"haunted fairground",
			"hellwaste settlement",
			"imposing barricade",
			"ineffable patronage",
			"keen reflexes",
			"memorial ground",
			"mennin pack",
			"moved by instinct",
			"neo-alchemist's mastery",
			"nixie's edict",
			"open the cryo-chambers",
			"privilege's sway",
			"pulsating mass",
			"reality reversal",
			"risti citadel",
			"scavenger holdout",
			"scavenger hunt",
			"secluded farmstead",
			"sepulchral seas",
			"sudden fatigue",
			"supply run",
			"the ancestors pass judgment",
			"tip of the tongue",
			"trail off",
			"true shot",
			"underhanded employ",
			"warped landscape",
			"wind-blessed guardian",
			"windmill project",
			"aureate panorama",
			"banish the intruders",
			"frozen hinterlands",
			"hazy coppice",
			"inferno lash",
			"jaws of the sea",
			"lowland vista",
			"spellshatter",
			"spires of caulte",
			"sunlit fissure",
			"surge of darkness",
			"testament to heroism",
			"the whisperwoods",
			"towering boughs",
			"veiled by the blizzard",
			"whisperwoods exploration",
			"aether runes",
			"ancient dominion",
			"animorph",
			"arcane refusal",
			"art of evasion",
			"bleak dominion",
			"blind blackguard",
			"bloodfell caves",
			"blossoming sands",
			"brushfire",
			"coastal dominion",
			"desolate dominion",
			"dismal backwater",
			"elegant agility",
			"felling vines",
			"fractured illusion",
			"gleaming river",
			"golden gust",
			"iron hide",
			"join the colony",
			"jungle hollow",
			"lava spill",
			"lunar emissary",
			"lupine ferocity",
			"majestic dominion",
			"murky peat",
			"murmuring typhoon",
			"paint over",
			"pith wilt",
			"plaxolotl pyari",
			"primal dominion",
			"pristine dominion",
			"prodigious panya",
			"reticulate chemist",
			"rip to shreds",
			"rugged dominion",
			"rugged ferocity",
			"rugged highlands",
			"sandblast",
			"scoured barrens",
			"shadow stalker",
			"spirit transfusion",
			"stalwart dominion",
			"sunwashed spires",
			"swiftwater cliffs",
			"thornwood falls",
			"tranquil cove",
			"tropical grove",
			"twilight ambush",
			"unbracing rain",
			"vast savannah",
			"verdant dominion",
			"vibrant flames",
			"wind ward",
			"wind-scarred crag",
			"wisdom beyond age",
			"a planet far, far away",
			"advanced schematics",
			"barren vista",
			"between life and death",
			"beyond humanity",
			"bloody business",
			"blooming vista",
			"bulletproof will",
			"burning up",
			"convert to resources",
			"cosmic sinkhole",
			"deepbrush operative",
			"destructive ambition",
			"embrace the abominable",
			"enter mephisto's gate",
			"essential override",
			"fiery erasure",
			"galactic detonation",
			"glacial vista",
			"grotesque presence",
			"ground bound",
			"growing up",
			"hall of random access memories",
			"head on collision",
			"hero's downfall",
			"human frailty",
			"ignition point",
			"lay claim to nature",
			"living vista",
			"lost among the stars",
			"marshy vista",
			"nebula of empty gold",
			"new divide",
			"nimble explorer",
			"olten skywhale",
			"one bad night",
			"out-of-body experience",
			"persevere",
			"planeswalker's insight",
			"predatory psion",
			"prismatic cavern",
			"slyten crystal motherlode",
			"space jelly swarm",
			"space oddity",
			"speck of dust",
			"speed of darkness",
			"tt-23 aegis",
			"take a walk",
			"the tomb of precursors",
			"thorn-touch abomination",
			"thunder road",
			"want it all",
			"whatever it takes",
			"when the stars align",
			"aether pull",
			"ambush gharial",
			"arcane sanctum",
			"bant command",
			"bask in fire",
			"bigroot valley",
			"bleak shoreline",
			"brutal struggle",
			"calamitous rampage",
			"canopy assault",
			"caustic mangrove",
			"charred marsh",
			"clairvoyant insight",
			"cloudcover heights",
			"crumbling necropolis",
			"disperse",
			"erupting territory",
			"esper command",
			"essence erasure",
			"exenterate",
			"fathom the forbidden",
			"fletcher's precision",
			"forbidding isle",
			"gloomtide gulf",
			"grixis command",
			"hallucinate",
			"hazy summits",
			"idyllic oasis",
			"jhessian cavalier",
			"jund command",
			"jungle shrine",
			"kaleidoscape",
			"lichen's grasp",
			"lush coast",
			"mage's warding",
			"magma spray",
			"mortal finish",
			"naya command",
			"omen of nefarox",
			"pain's embrace",
			"peaceful passage",
			"perilous sojourn",
			"radiant resolve",
			"recraft in steel",
			"savage lands",
			"sculpted observatory",
			"seaside citadel",
			"sharuum, archmagocrat",
			"sigil of fortitude",
			"somber meadow",
			"sphinx's scrutiny",
			"subduing serum",
			"sunstrike",
			"terramorphic expanse",
			"thunderscorn",
			"tranquil repose",
			"twisting fissure",
			"vectis entrancer",
			"vibrant expulsion",
			"bounty of the gardens",
			"center of culture",
			"consult the scriptures",
			"crescent of possibilities",
			"day of rest",
			"dehmi, origin seeker",
			"eli's grit",
			"emissary of dark tides",
			"epic of ekebram",
			"epic of hannaru",
			"epic of the lovers",
			"gilded blade",
			"glimpse of fate",
			"godchosen valor",
			"grapple with the past",
			"harrow",
			"heartland's protection",
			"imperial achievement",
			"imperial claim",
			"inspired charge",
			"keeper of codices",
			"many-voiced tower",
			"mustering grounds",
			"oppress the weak",
			"pierce the sky",
			"pound by pound",
			"rupture spire",
			"ruthless advancement",
			"savage takedown",
			"secrets of creation",
			"seeker amalgam",
			"shock",
			"spell pierce",
			"strongarm",
			"sure strike",
			"torrent of ankuliths",
			"water into wine",
			"wondrous bazaar",
			"acro bat",
			"adrenaline",
			"aeroblast",
			"barrier",
			"call back",
			"cavern carver",
			"chikyu league arena",
			"dreamnapper",
			"duplicate",
			"egg bomb",
			"elemental of surprise",
			"event horizon",
			"extremespeed",
			"familiar's ruse",
			"farewell",
			"fierce lunge",
			"firemane fox",
			"fishing trip",
			"flamethrower",
			"focus energy",
			"forgotten temple",
			"fresh carrion",
			"garden guardian",
			"gene pool",
			"ghastly tether",
			"healing center",
			"hidden sprout",
			"ice path",
			"lake of rage",
			"magma crawler",
			"mighty beetle",
			"muggy mire",
			"natural cure",
			"nurse trainee",
			"ominous wind",
			"poison point",
			"power plant",
			"power of love",
			"practice range",
			"quiet retreat",
			"rapid rodent",
			"rest",
			"revitalize",
			"ruined lab",
			"ruined shrine",
			"run away",
			"safe from harm",
			"seal of approval",
			"snatch",
			"still waters",
			"sucker punch",
			"sunset herald",
			"tangling vines",
			"thundermane fox",
			"time stands still",
			"treasure beach",
			"unburdened",
			"victory road",
			"viper ambush",
			"volt vermin",
			"wandering hamlet",
			"warden of time",
			"whirling winds",
			"whirlpool ride",
			"wishing star",
			"work up",
			"all for one",
			"autointerment",
			"bushwhack",
			"cannonblast",
			"cascade drake",
			"civil discourse",
			"depth lurker",
			"expunge the terrors",
			"fiery cannonade",
			"fiery temper",
			"fight song",
			"flaming point technique",
			"fog at sea",
			"forged alliance",
			"good night's sleep",
			"keelhaul",
			"law enforcement",
			"mable of the sea's whimsy",
			"pick up the pieces",
			"pirate's hideout",
			"plummet",
			"run through",
			"sail the open sea",
			"shipwrecked",
			"sink",
			"siren's song",
			"skulduggery",
			"sudden storm",
			"thicket mimicry",
			"visions of oblivion",
			"anemone cluster",
			"aquatic might",
			"blood in the water",
			"bloodthirsty jaws",
			"buried at sea",
			"cast out",
			"circling predators",
			"coralcrown's banishment",
			"coralight castle",
			"coralight lifebloom",
			"crush the hull",
			"drag beneath",
			"driftwood throne's rule",
			"emerge from the reeds",
			"encapsulate",
			"enchanting palace",
			"feel the flow",
			"finish off",
			"gaze deeper",
			"gobble up",
			"grim, dawson's vassal",
			"grisly ruins",
			"guppyfin duelist",
			"keep in line",
			"krill-clan guardian",
			"lie in wait",
			"lightning-fast lionfish",
			"majestic hippocamp",
			"mina, jeweled minnow",
			"molten basin",
			"paradise reef",
			"ruin dive",
			"shanty town",
			"smell blood",
			"tectonic chateau",
			"tentacle lash",
			"thrill of possibility",
			"tideflow wardings",
			"truth beyond belief",
			"typhoon caverns",
			"vibrant sandbar",
			"volcanic catastrophe",
			"volcanic hollow",
			"weight of oceans",
			"wilt",
			"end of all things",
			"forbidden burial",
			"inescapable fate",
			"invent the future",
			"iroshi, blade of the old ways",
			"lay low",
			"pixie procurer",
			"powder scatterer",
			"reveal eternities",
			"ria-demian charm",
			"solar flare",
			"abrupt duplication",
			"affluent cetanthrope",
			"backstab",
			"bed rest",
			"blessing of immunity",
			"coastal metropolis",
			"critical strike",
			"crowded tavern",
			"cunning mimic",
			"devious plot",
			"eclectic tactics",
			"eldritch invitation",
			"expel from the dungeon",
			"fast travel",
			"fertile steppe",
			"flawless tactics",
			"flooding magma",
			"fragment mind",
			"freeze in place",
			"heroic return",
			"hurl from existence",
			"improbable aim",
			"invoke the divine",
			"lag spike",
			"lost progress",
			"magma bolt",
			"mending valkyrie",
			"momentous blow",
			"nidhir, the one beyond",
			"no way out",
			"ocean's edge kraken",
			"polymorphist's gift",
			"relic corrosion",
			"rogue's passage",
			"save the village",
			"scale factor",
			"spawning barrens",
			"sudden absence",
			"thalassic borough",
			"thornweald cavalier",
			"time fissure",
			"unravel",
			"unsummon",
			"walk through walls",
			"wild peak",
			"admonish",
			"aeren hellfire",
			"allure of alratha",
			"alratha, pearl of the sand sea",
			"cold shoulder",
			"collapsing ridges",
			"confront the riddlemaster",
			"conto sika, ruined glory",
			"crest",
			"daring escape",
			"daunt",
			"death rites",
			"decisive arcanist",
			"desert's hearth",
			"destined calamity",
			"duel amongst dunes",
			"ecological refuge",
			"exhaust",
			"ferocity of the sands",
			"fiery burst",
			"final hour",
			"grave robbery",
			"harmonic charm",
			"heatwave",
			"hero's command",
			"inescapable blaze",
			"leave for dead",
			"lofty denial",
			"lost and alone",
			"mage studies",
			"mage's command",
			"nature charm",
			"oasis' grandeur",
			"oasiscrafting",
			"open the tomb",
			"path of fire",
			"reytha's discovery",
			"roland's confluence",
			"sand twister",
			"sandstorm charm",
			"sandwurm's command",
			"scholar of necromancy",
			"search the archives",
			"silent wayfarer",
			"sinister charm",
			"spectral wings",
			"spiritual charm",
			"splitting image",
			"stormcalling",
			"study",
			"swaying sands",
			"tara's confluence",
			"tara's lament",
			"the sun rises",
			"thief's command",
			"trade route bandit",
			"trial recruitment",
			"verdant oasis",
			"way of the warrior",
			"annihilation",
			"become nothing",
			"breach the lilies",
			"clarity of self",
			"elusive hunter",
			"embrace of mist",
			"fade",
			"fields of worship",
			"flesh willing",
			"fold will",
			"gentle omens",
			"give to sacred halls",
			"grasp for understanding",
			"harvest flesh",
			"heavens claim their due",
			"illusory stag",
			"inscrutable realms",
			"inviolable realms",
			"keep what was lost",
			"martial mastery",
			"mortal deeds",
			"mortal realms",
			"pull away",
			"pull from beyond",
			"reduce to naught",
			"tandem glory",
			"tempting realms",
			"through shattered senses",
			"unravel prophecy",
			"wild realms",
			"ancestral guidance",
			"assassin of fahrib",
			"assault of the conscripted",
			"avaz citadel",
			"avaz sanctuary",
			"avaz temple",
			"blessing of golna",
			"call of the huma",
			"change of station",
			"chosen of aminatou",
			"collapsing ramparts",
			"condescend",
			"contemplate the cosmos",
			"cosmic coalescing",
			"cosmic lineage",
			"courageous stand",
			"danaj citadel",
			"danaj sanctuary",
			"danaj temple",
			"delve for treasures",
			"desert's veil",
			"dispute",
			"fall from the heavens",
			"fiery truthseeker",
			"fight for succession",
			"forced germination",
			"fury of hadak",
			"gathering of minds",
			"giver of martoob",
			"grasp of the sands",
			"guidance from above",
			"hidden cache",
			"hidden garden entrance",
			"imposing databdara",
			"joyous connection",
			"kaneh citadel",
			"kaneh sanctuary",
			"kaneh temple",
			"lax gambit",
			"marketplace crossroads",
			"martoob's message",
			"mercantile satrapy",
			"mindscape denial",
			"narrow diversion",
			"neutral citystate",
			"nizev citadel",
			"nizev sanctuary",
			"nizev temple",
			"peek into the future",
			"peer into the cosmos",
			"plan for adventure",
			"poison the blade",
			"rahstahde truthseeker",
			"rapid transformation",
			"righteous combat",
			"rite of ends",
			"satrapy merchant",
			"shifting city",
			"shomi's journey",
			"shrine to those gone",
			"soli citadel",
			"soli sanctuary",
			"soli temple",
			"surreal bakhtak",
			"swindle the rapacious",
			"triplicate",
			"tyrus, giver to all",
			"beckon of the wild",
			"civilization's cost",
			"crack in time",
			"crystal wave",
			"entelan deep storage",
			"pyretic cyclone",
			"spectrum archmage",
			"spike wall trap",
			"wisdom of the leylines",
			"bow or burn",
			"starjump",
			"decide boundaries",
			"eldritch emergence",
			"forbidden treasure",
			"bustling harbor",
			"dreary township",
			"glittering grove",
			"monsoon lagoon",
			"urban wastelands",
			"starved oasis",
			"tenuous existence",
			"duplicated dismantler",
			"make into mist",
			"parasitic rebirth",
			"face the truth",
			"obscoriate",
			"deus ex machina",
			"dustridden sepulcher",
			"risti workshop",
			"flourishing lowlands",
			"forgotten monument",
			"pathway of lost sultans",
			"raintouched basin",
			"scoured mesa",
			"silent ridge",
			"windworn spires",
			"sandstorm sentinel",
			"arcane oasis",
			"arid causeway",
			"bloodsand gulch",
			"blooming needles",
			"crumbling aqueduct",
			"desiccated trail",
			"dunesea expanse",
			"humble hamlet",
			"resurgent oasis",
			"rot-sand ruins",
			"sundappled scrub",
			"chigau market outskirts",
			"dha-bukan, jewel of the dunes",
			"eroded sanctuary",
			"telenian adornments",
			"journey of self-discovery",
			"tale of the wayward titan",
			"rally the railguard",
			"dunehaze revolutionary",
			"hisashi's repose",
			"initiation of the lafterii",
			"glimpse the stars",
			"shinrei's ruse",
			"into the flood realm",
			"bundi, prodigious steed",
			"nestled delta",
			"a villain revealed",
			"gifts of the abyss",
			"jolt awake",
			"enter the mosh pit",
			"ire of ancient tomes",
			"roggar's mastery",
			"crackle across kahembo",
			"harvesters gone haywire",
			"siamang tale-singer",
			"out of fashion",
			"curse of ceaseless pursuit",
			"bellow of the highlands",
			"terrors of cuxuri trench",
			"lizaveth's surveyor",
			"step into the beyond",
			"hell or high water",
			"beneath the horizon",
			"blistering boneyard",
			"shrine of the world-shepherd",
			"bahum's absolution",
			"scorn the ordinary",
			"secrets of coralight court",
			"justicar overseer",
			"farmyard",
			"legacy of northrime",
			"moment of heroism",
			"pawsitive vibes",
			"tidal trickster",
			"turtle up",
			"send back",
			"scary stories",
			"highpoint guru",
			"consult the ancestors",
			"hard bargain",
			"uncaged fury",
			"triumphant return",
			"epic boss fight",
			"tinyvale watchkeep",
			"for tinyvale!",
			"ruffled scrum",
			"treetop buck",
			"fluffpuff frenzy",
			"tinyvale treetops",
			"bleakrealm moor",
			"dawn hill outskirts",
			"fabled passage",
			"flamingo rock",
			"frondpond grotto",
			"gloomhollow woodlock",
			"highpoint shrine",
			"humble abode",
			"fang den jaws",
			"slipsand oasis",
			"out of pockets",
			"exotic isle",
			"good day's catch",
			"valorous stance",
			"hoof cliff horngrove",
			"ssytai, idleglen adept",
			"salty dog",
			"crossroads town",
			"flurry of knives",
			"northrime aurora",
			"sigilwing familiar",
			"unbalancing technique",
			"off the handle",
			"give 'em the slip",
			"bonetooth ritual",
			"tinyvale tactics",
			"seven seas scourge",
			"unhappy ending",
			"mischievous capuchin",
			"rugged expanse",
			"eon campfire",
			"leafdown ambusher",
			"replacement technique",
			"blazing outro",
			"mattia, hero of tinyvale",
			"adventurers, assemble!",
			"cast a wide net",
			"impromptu escapade",
			"breathtaking valley",
			"sweep the leg",
			"panya of lands unknown",
]

		names
			.map{|n| db.cards[n]}
			.flat_map{|card| card ? card.printings : []}
			.to_set
	end

	def to_s
		"mable"
	end
end