class ConditionIsPlayable < Condition
    def search(db)
        names = [
            "wayfarer's shrine",
            "pith wilt",
            "seal the tomb",
            "nebula of empty gold",
            "duress",
            "stand unassailable",
            "flooded depths",
            "murmuring falls",
            "mysterious cataract",
            "shifting glade",
            "grim bastion",
            "magmatic torrent",
            "crystal cavern",
            "nomad's township",
            "lush oasis",
            "monument of queens",
            "crumbling precipice",
            "sedate tundra",
            "fungal mire",
            "shardstone rift",
            "stolen secrets",
            "amber hills",
            "flooded morass",
            "soul gate",
            "arctic mine",
            "out-of-body experience",
            "ocean monastery",
            "nereba, sandchoked archives",
            "titan snare",
            "barren desolation",
            "scorch",
            "exeunt",
            "sacrificial bull",
            "mana ascetic",
            "timber range",
            "event horizon",
            "memento mori",
            "lumbering hillock",
            "resplendent substratum",
            "cursory glance",
            "descend on the helpless",
            "lavatorn fields",
            "rampant summit",
            "frostfire geysers",
            "prying inquiry",
            "recall forgotten eons",
            "oracle's vision",
            "gloomcover steppe",
            "journey's end",
            "roggar's frenzy",
            "pool of light",
            "whisperwoods exploration",
            "sunlit highland",
            "negate",
            "still the pandemonium",
            "corpsebed",
            "shal'draen's rage",
            "forgotten steppe",
            "murky peat",
            "cosmic sinkhole",
            "shikai's redoubt",
            "thought blossom",
            "singularity's grasp",
            "flourishing crevasse",
            "wheat from chaff",
            "heart of the glade",
            "portal fracture",
            "violent collapse",
            "mirrorgate",
            "intrepid",
            "tropical grove",
            "mpumo, who stands alone",
            "cane dancer",
            "xanigan, the darkened cloud",
            "nature's claim",
            "vibrant rapture",
            "stormsurge",
            "voidflare",
            "gleaming river",
            "tsang jin, master of the jade sea",
            "tenacious guide",
            "monkeyshines",
            "bahum, the warden",
            "rage of the ravaged",
            "a planet far, far away",
            "chi lee of the underworld",
            "hierarch ranger",
            "destructive ambition",
            "banished companion",
            "dark bargain",
            "children of the clouds",
            "villainy",
            "heart of zhedina",
            "cradle of corruption",
            "jobiah, devoted farmer",
            "spiraling canyon",
            "find happiness in misery",
            "guiding light",
            "etherium abrogator",
            "jade vault reclaimer",
            "leyran alpha",
            "union rail strikebreaker",
            "unjust sentence",
            "departed evangel",
            "basat charm",
            "brine fleet bay",
            "northern express line",
            "anzen, beyond the sea",
            "unearth",
            "the high prairies",
            "mana confluence",
            "temporary treason",
            "sunwashed spires",
            "spell pierce",
            "unquenched greed",
            "once abandoned",
            "unceasing flames",
            "prodigious panya",
            "ancestral council",
            "antimagic",
            "rakkiri dissident",
            "sea of skies beyond",
            "ignition ritual",
            "inishtu, desert healer",
            "bounty of the gardens",
            "scion of torrents",
            "stalwart dominion",
            "antithesis",
            "seek prophecy",
            "endless discoveries",
            "veilborn meddler",
            "face the dawn",
            "sigil of radiance",
            "mindstorm's eye",
            "tamiyo, lunar arcanist",
            "terraformer's globe",
            "imperial claim",
            "solar flare",
            "sights beyond",
            "lucien, the grifter",
            "sporeflow protector",
            "vast savannah",
            "volatile stonework",
            "impden mother",
            "heist headquarters",
            "end of days",
            "neutralize",
            "fiery erasure",
            "tiny heroine totti",
            "reveal eternities",
            "warded tome",
            "epic encounter",
            "suitor of the sea",
            "polyp pools",
            "rock",
            "stay determined",
            "verdant dominion",
            "invalidate",
            "aiel tazan",
            "rot",
            "shadowband consul",
            "bant command",
            "kellythross' workshop",
            "shugenja sanctuary",
            "plasma addict",
            "tal, locus sentry",
            "pay up",
            "mabil fardancer",
            "bloodriver",
            "seto san, the dragonblade",
            "chains of subdual",
            "dead man's party",
            "brazen sacrilege",
            "dreamsight well",
            "fogspewer",
            "dovon, verdant experimenter",
            "kati evalin, world wanderer",
            "setting sun",
            "ostracizer orb",
            "chikyu champion",
            "profane emissary",
            "fractured reach",
            "galvan coal line",
            "bessie's brood",
            "opt",
            "theocracy",
            "fair trial",
            "ceaseless stalker",
            "leija's greenblade",
            "tidehollow lich",
            "deform sanity",
            "civilization's cost",
            "beneath the zhedina",
            "earthbreaker behemoth",
            "kaur, end of lies",
            "ruin delver",
            "sabne's autumn",
            "last passage",
            "twilight ambush",
            "parrot pools",
            "avatar of basat",
            "redtail fencer",
            "hugo of the shadowstaff",
            "performer of ambition",
            "glistening chalice",
            "smoldering pages",
            "seedshrine",
            "grim slums",
            "primal ruffian",
            "seabreen nullmage",
            "rousing rubble",
            "velir the sunderer",
            "all-enduring mafua",
            "lumenbay flyer line",
            "precursor sanctum",
            "budding companion",
            "putrid lurker",
            "bottled lightning",
            "promethean grotto",
            "idyllic odyssey",
            "iviana, speaker of fangs",
            "distant thunder",
            "perilous passage",
            "avatar of the natural",
            "helene trant",
            "tend to the grove",
            "potion of inhibition",
            "archive guardian",
            "autumnal watch",
            "gilded gearhulk",
            "calamitous crash",
            "eli windsors, lone gun",
            "priestess of simplicity",
            "brushcover elf",
            "long forgotten",
            "what lurks beyond",
            "crystal wave",
            "irika, wielder of secrets",
            "explorer's fate",
            "conjure realities",
            "monument to the fallen man",
            "beckon of the wild",
            "ruinous naga",
            "endless helpless souls",
            "dispel",
            "herald of oblivion",
            "blood jade prophet",
            "facsimile of divinity",
            "noble's hedonism",
            "glitch, galactic muse",
            "temporal resuscitation",
            "ignition point",
            "aerie's pillar",
            "no rest",
            "dark rite cultist",
            "farseek",
            "tyrant of tributes",
            "ever-gnawing rat",
            "scion of flourishing",
            "thunder road",
            "new divide",
            "oppress the weak",
            "siesa tremund",
            "the afterlife takes its due",
            "anomalion",
            "resonating force",
            "arcane chronometer",
            "staff of equilibrium",
            "academic's claymore",
            "scuttling gnat",
            "flaming point technique",
            "corvid heretic",
            "replicator mage",
            "plaxolotl pyari",
            "self replication",
            "diffuse",
            "bearer of the lantern",
            "sunken ambitions",
            "end of all things",
            "sorcerous spyglass",
            "miyoga firebird",
            "lhosei of the ghost peak",
            "answer midnight's call",
            "gift of the phoenix",
            "fateful journey",
            "soul leak",
            "into waridi valley",
            "nightwatch rallier",
            "tendrilsnare",
            "babyscale bruiser",
            "hellion devastator",
            "majestic dominion",
            "stalked healer",
            "strike from the shadows",
            "jara champion",
            "sevid, the lookout",
            "servant of armageddon",
            "tinkerer's tools",
            "channeling stone",
            "scion of fecundity",
            "danithra muckbruiser",
            "vaultkeeper",
            "flesh to rot",
            "mastery of the veil",
            "barren boneyard",
            "explore",
            "azun, sheriff of daisite",
            "palace of reflections",
            "bitter duckling",
            "nacatl skirmisher",
            "scion of desolation",
            "martial maestro",
            "crystal garden",
            "roggar's gambit",
            "shifting grove",
            "silent wanderer",
            "mystic arts",
            "titanic fossil",
            "abscond",
            "egg of avarice",
            "helena, the awakener",
            "azamir, wayward titan",
            "social graces",
            "emerabi's disciple",
            "marisa of the gravehowl",
            "mausoleum suffragan",
            "canyon creek",
            "dawson's loot",
            "fulmen, aether prodigy",
            "forked pillar",
            "croakfolk troubadour",
            "ride the storm",
            "scion of storms",
            "veteran lifeforger",
            "squid pro quo",
            "cleared vault",
            "will of a fickle lord",
            "fellor charm",
            "pristine dominion",
            "curse of the drow",
            "lord ellison crain",
            "turi of hollow depths",
            "forbidden burial",
            "resign to madness",
            "frailty",
            "krismite vault",
            "sadistic indulgence",
            "ethereal armor",
            "rune-scribe's apprentice",
            "seismic colossus",
            "currency",
            "oshin, keeper of the shoal",
            "arpechian champion",
            "verdant bluff",
            "noxious upwelling",
            "curse of bleeding",
            "tt-23 aegis",
            "stormshaper adept",
            "masahita, bloodtongue",
            "flare blitz",
            "consult the dewdrops",
            "primal dominion",
            "cosmic war",
            "meteor volley",
            "cognitive fumigator",
            "ambitious necromancer",
            "forbidden brew",
            "paragon of honor",
            "seto san, the sacred hand",
            "elrayin, the manaroot",
            "shining crusader",
            "witch's invocation",
            "conspiracy of ravens",
            "ravaged monument",
            "conjuring of locusts",
            "golden touch",
            "hall of random access memories",
            "sun yun, master of self",
            "unforget",
            "coastal dominion",
            "rain of ruin",
            "pitchpyre curse",
            "caulte axeslinger",
            "lay low",
            "hellbent speed",
            "enlightened sigil",
            "ayala's concord",
            "exergetic chains",
            "stormwake",
            "hub of innovation",
            "rugged dominion",
            "moment of tranquility",
            "cranial violation",
            "angel of succor",
            "dead-set duo",
            "finish off",
            "silent hypnotist",
            "waxing angel",
            "powder scatterer",
            "lord rokai",
            "lodestone golem",
            "aguri, shadow of doubt",
            "xira, scatterer of seeds",
            "caller of hunger",
            "adiran distractor",
            "tether of simplicity",
            "sage's ashes",
            "mysterious coffer",
            "serene prayer",
            "lazaire's conjuring",
            "scintillate",
            "kaalia's abomination",
            "desolate dominion",
            "bogborn charger",
            "watch from above",
            "mari, dawn resurgent",
            "cadre hawk",
            "timestream sentinel",
            "imagination unleashed",
            "sedraxis trepanator",
            "a journey begins",
            "rift splicing",
            "mystery of the crashed craft",
            "howling shieldbreaker",
            "convert to resources",
            "keeper of the sanctum",
            "the moon rises",
            "reinvent",
            "truth unveiled",
            "blundering clocktower",
            "persevere",
            "shengin renegade",
            "backstage rooms",
            "slashing pangolin",
            "anguished unmaking",
            "crewmaster gillo",
            "lord rickard dawson",
            "unlit alley",
            "haunted boughs",
            "tear loose",
            "flawless counterfeit",
            "devised companions",
            "gallord's ascension",
            "slaffield workgate",
            "camouflaged sprareos",
            "the last sacred gate",
            "unlikeliest heroes",
            "conflux ravager",
            "xiong mao, the intrepid",
            "garth of the chimera",
            "death pits hawker",
            "shifting cascade",
            "sun-sigil ordainer",
            "hit the bottom",
            "sunrazed ruins",
            "timely reinforcements",
            "young necromancer",
            "gateblessed explorer",
            "hunter's hideout",
            "charming marauder",
            "imagine",
            "essential override",
            "burning revelations",
            "magmatic cache",
            "shimmering dragon",
            "lone survivor",
            "madcap mercenary",
            "heart of the deadwood",
            "heraldry",
            "far wandering guardian",
            "ol' sycamore",
            "thievery",
            "earthfeeder worm",
            "mark of dark opulence",
            "cumulus horizon",
            "holcomb of the peregrine",
            "soul warden",
            "master of tranquility",
            "liliana at the brink",
            "into the unknown",
            "moonlight sanctum",
            "shifting crag",
            "all or nothing",
            "buy time",
            "rippling curtain",
            "left on the wayside",
            "abandoned monument",
            "chratteri restoration",
            "centered acolyte",
            "profound introspection",
            "oil driller",
            "unleash the dragon",
            "blessed spellroot",
            "deflecting strike",
            "rain zai, spiritscale",
            "anuran encounters",
            "suzume oshiruko",
            "purging watchkeeper",
            "remembrance of light",
            "whisperwoods phoenix",
            "zhedina bazaar",
            "chantwood channeler",
            "logger recluse",
            "flora acolyte",
            "sewer pack",
            "champion of scales",
            "vivid mirage",
            "maghbri oracle",
            "aerial adept",
            "forgotten shrine",
            "reckless festivities",
            "infuse the apparatus",
            "ruined precipice",
            "forgotten pit",
            "avatar of plume de val",
            "council's will",
            "crystal conjuration",
            "marshy marauder",
            "power plant",
            "clockwork gaucho",
            "xirix, the usurper",
            "void portal",
            "hazy moorland",
            "ria-demian charm",
            "banish",
            "forgemaster's altar",
            "shadowed slums",
            "wealth of the underbrush",
            "warhound shuja",
            "shinrei of the ghosting way",
            "ethereal spellmaster",
            "featherfall ascetic",
            "recurring abomination",
            "merchant of false lives",
            "mountain bighorn",
            "head of ulko",
            "seeker of mysteries",
            "rootwarper",
            "seeker lizaveth",
            "kinken, the dragon's breath",
            "forgotten lessons",
            "soul release",
            "one with the world",
            "culling blade",
            "recoil",
            "legitimate establishment",
            "othersea submersible",
            "fey grove",
            "miner's barracks",
            "shinrin spellhunter",
            "parish paragon",
            "hexfang ascetic",
            "merciful yuroda",
            "junktrawler",
            "fireshaper adept",
            "sealed mausoleum",
            "the flames approach",
            "zoulev offering",
            "shifting canyon",
            "paracosm",
            "champion of destinies",
            "ajani resolute",
            "imperial port",
            "false vitality",
            "last stop",
            "soul pierce",
            "sanaito, alone",
            "anarchy storm",
            "cinderblade",
            "rend",
            "starlight beacon",
            "reflected moment",
            "bal's descent",
            "echoing knowledge",
            "gaze deeper",
            "source decay",
            "spectral skycruiser",
            "tomb steward",
            "choking despair",
            "ghastly ferry",
            "root dancer",
            "judge's decree",
            "from ancient tomes",
            "emissary of antiquity",
            "unity spheres",
            "starjump",
            "flatboat artisan",
            "master of elements",
            "memories reignited",
            "deadwood terror",
            "forbidden truths",
            "resurging rhino",
            "collapse the pillars",
            "blossoming defense",
            "hymn of fury",
            "impish delights",
            "ethereal fervor",
            "ivenge, false god",
            "witch of spring's promise",
            "the court of angels",
            "sera of coppercove",
            "plasma blader",
            "minister of madness",
            "hashiro's devoted",
            "once scarred",
            "chemical grenade",
            "mossy companion",
            "erollin, eccentric collector",
            "kantra of old majik",
            "unassuming swineherd",
            "entrail elemental",
            "accursed by unborn fates",
            "tidal spite",
            "worried vulpine",
            "glymna blackrune",
            "edarna the everforge",
            "ill fated travels",
            "vythraktos, master necromancer",
            "under the sea",
            "lilyreed triton",
            "coralight champion",
            "first general of the wards",
            "fae-blessed attendant",
            "aethermancer's familiar",
            "bleak dominion",
            "chikami castle",
            "qililia, the saboteur",
            "amber reserves",
            "coercive methods",
            "fierce combatant",
            "monsoon lagoon",
            "adam of the ironside",
            "fiery burst",
            "shigurei, the floodbringer",
            "ornate incense",
            "champion of the fae",
            "vibrant flames",
            "astute prophet",
            "orichi of the cold mist",
            "petal-weaver alexa",
            "border guardian",
            "exploring the mirrorworlds",
            "relic heist",
            "dreamsteel paladin",
            "mystic's mantle",
            "razione racecourse",
            "rejoicing aristocrats",
            "zegarra, the rival",
            "dreadfire tyrant",
            "bahum's penance",
            "fanciful bloom",
            "reforge",
            "vengeful messenger",
            "chiu of the wild realm",
            "herald of wisdom",
            "arcane duelist",
            "worlds away",
            "mettalia, light from above",
            "favorable winds",
            "edith waunt",
            "possibility scope",
            "slaughterkeg",
            "advocate of the hunt",
            "emperor's retainer",
            "ema, the traveler",
            "soaring canyon",
            "hesediel, the reborn",
            "plasma enforcer",
            "shifting morass",
            "corrupted memory",
            "mana confluence",
            "wayfaring pilgrim",
            "crossing the fog",
            "vanish",
            "threshing sundew",
            "soulblade",
            "diasune immolator",
            "xing, the lucky charm",
            "gilded gulch",
            "shawlbinder",
            "spellbane adept",
            "sword of tides and time",
            "supreme mechanothurge",
            "overgrown refuge",
            "dragoncalling",
            "awaken to the skies",
            "boundless evolution",
            "rafiq the magnanimous",
            "fatal edict",
            "nidohagane warfans",
            "journey to the otherworlds",
            "inoshi the wild boar",
            "paragon of purity",
            "caustic caterpillar",
            "find nothing",
            "kazimir's ban",
            "skypath pilgrimage",
            "aureate panorama",
            "culminating despair",
            "valencia of the concordant",
            "experimental battle armor",
            "qilan wanderer",
            "tranquil ascetic",
            "hannaru's courage",
            "all that glitters",
            "gyreon pickpocket",
            "frigid thicket",
            "searle of the tempest",
            "wave of decay",
            "aquilifer axelius",
            "jak, daring vanguard",
            "eye of the beholder",
            "clean-up crew",
            "brutal blow",
            "sear flesh",
            "soul's attendant",
            "carnival yatiri",
            "planeswalker's insight",
            "possibility engine",
            "coppergild mercenary",
            "zhedina envoys",
            "onyx ritualist",
            "demolitionist deviser",
            "forgemaster's charm",
            "edge of the water",
            "nightmare riders",
            "duelist's forms",
            "by the sea",
            "fidelity of the pure",
            "unstable footing",
            "great sable stag",
            "culminating wisdom",
            "kinjiru assailant",
            "zhedina valiant",
            "wild lifescale",
            "vicious slasher",
            "insurgent ballads",
            "founding hero",
            "powercell engineer",
            "wisdom in reflection",
            "merrow legendmaker",
            "skycaster's aura",
            "right to rule",
            "warden of silence",
            "duskwood vanguard",
            "dragongate",
            "return to form",
            "stonewood sanctuary",
            "refract",
            "blade of the serpent",
            "soulbreaker of mautakesh",
            "sankataar scourge",
            "clutch of the coil",
            "endless expedition",
            "brutality",
            "offerings to the deathless",
            "nightmares unseen",
            "rustshell crustacean",
            "lt. daisy saxon",
            "willow spirit",
            "stormcaller sentinel",
            "idyll",
            "procedural genesis",
            "enter mephisto's gate",
            "highland dunes",
            "between life and death",
            "cobbled transport",
            "isolated",
            "platinum colossus",
            "blood ritual",
            "art of evasion",
            "wellspring of creation",
            "salim and certo",
            "photon barricade",
            "shrine of the six pillars",
            "tear through",
            "indomitable bear",
            "sinister pact",
            "blazing volley",
            "dehmi, origin seeker",
            "guard of cuirassiers",
            "sunrise prairie",
            "illusionary steed",
            "shatter the mask",
            "corecharge",
            "reflect on serenity",
            "whirlpool ride",
            "myrmidon's warhead",
            "unified theory",
            "festival of winter's night",
            "flourishing dunes",
            "awaken the nav",
            "farmer's repose",
            "flash of inspiration",
            "lady genvieve of caulder",
            "sharuum, archmagocrat",
            "bahum, penitent",
            "hirukari, daughter of the sun",
            "student of the coil",
            "scion of scales",
            "fang of mautakesh",
            "touch of the coil",
            "serpent's grasp",
            "frilled drakeling",
            "rest",
            "crystal grotto",
            "adiran scryers",
            "reweave reality",
            "artificer's gift",
            "salva tore",
            "duskwood thicket",
            "militant youth",
            "path of fire",
            "immolated grave",
            "greypelt initiate",
            "ainok lout",
            "bourasan highguard",
            "ainok caretaker",
            "ainok alpha",
            "ainok hunter",
            "raiun bay admiral",
            "dust barrens",
            "reconstruct",
            "overgrowth guardian",
            "blissful lull",
            "pyroclastic maw",
            "pyremage's knack",
            "stolen cache",
            "the aetherite saloon",
            "volcanic pounce",
            "withering husk",
            "lost in smoke",
            "ironeyes desperado",
            "molten falls",
            "legends remembered",
            "interan soothsayer",
            "sunblessed orator",
            "naya command",
            "mobilize the heavenly",
            "thallid cultivator",
            "master of imports",
            "reenter orbit",
            "bloodbraid ritualist",
            "xenocrata's fleet",
            "helping hand",
            "adoroth, the baneful",
            "hanabira, kogane's legacy",
            "wicked blow",
            "puppeteering",
            "animorph",
            "ruchi, the effervescent",
            "heirloom",
            "spotless mind",
            "joyous explorer",
            "immortalize in stone",
            "risen looter",
            "tower of long shadows",
            "voidlife orbs",
            "fireheart channeler",
            "exiled necromancer",
            "zhedina outskirts",
            "iron signet",
            "jade temple",
            "shemesh, nomad chieftain",
            "sarrutu flamebinder",
            "emissary of dark tides",
            "turin's study",
            "behemoth channeler",
            "myrmidon, coralight exile",
            "master negotiator",
            "suisei the southern star",
            "dawson's collector",
            "heaven, presidential ship",
            "ralora, unforgiving depths",
            "mind-mute",
            "lucien, the ravenous",
            "rainy night lovers",
            "vasille rioters",
            "protective memory",
            "evaldi's muse",
            "krismite purveyor",
            "encapsulate",
            "the erased",
            "mele, the onemother",
            "seek the future",
            "wandering souls",
            "kaor awoken",
            "festival of fading lights",
            "foreseen denial",
            "raid the forgotten tomb",
            "idravir, the last city",
            "harriet, liberated wildborn",
            "rilken forcefield keeper",
            "imperial silks",
            "rainbow phoenix",
            "reclamation grovesculptor",
            "brilliant citadel",
            "festival of roaring dragons",
            "syrina, the dragon queen",
            "earthchannel apprentice",
            "arcanist's reaver",
            "cloudbank",
            "rakkiri initiate",
            "fox of the orange orchard",
            "third legion general",
            "thundermane fox",
            "barricade patrol",
            "temporal insight",
            "rocket admin",
            "etherium leviathan",
            "ruinous proselyte",
            "helm of the infinite",
            "legacy warmask",
            "derelict town",
            "reflect upon the past",
            "sunrise orchard",
            "junan venomtongue",
            "oracle's ploy",
            "bewitching vapors",
            "titan's palace",
            "derevi's adjutant",
            "mirai, spring's promise",
            "fateful eruption",
            "the whisperwoods",
            "hasty intervention",
            "fathom diver",
            "inked summoner",
            "cursed scroll",
            "lava plume",
            "channel the mirror",
            "confining priest",
            "imperial coins",
            "heathen rise",
            "iterative design",
            "sevenfold summoner",
            "shroud of hinasa",
            "ascension",
            "alvarez of the huntsman",
            "entrancing light",
            "spring renewal",
            "terraformer's globe",
            "hero's downfall",
            "spitfireling",
            "gathering the gang",
            "dragon's ire",
            "vedlinn ross",
            "blind blackguard",
            "worlds colliding",
            "brilliant academy",
            "kantra of bounty",
            "colossal achievement",
            "only memories remain",
            "fleeting thoughts",
            "grove of embers",
            "starlit raze",
            "autumn canopy",
            "isochron wand",
            "calamity dragon",
            "spectacle of innovation",
            "sandswept bazaar",
            "guardian of the divergent",
            "performer of growth",
            "antali archdruid",
            "summit guardian",
            "cloudcover heights",
            "bond of battle",
            "strike down the usurpers",
            "stickup",
            "death in reverse",
            "leery sortie",
            "abandoned laboratory",
            "callow survivors",
            "final reckoning",
            "buried by time",
            "sprout thought",
            "bittersweet reunion",
            "rush of wonder",
            "house of forgotten whispers",
            "vengeant precursor",
            "extravagant flair",
            "iron warden",
            "bearer of fables",
            "sword of monsters and men",
            "villains: the musical",
            "magister of impotence",
            "careless violence",
            "glorybound chorister",
            "kaor's tithe",
            "k-17 drone",
            "tomb of shifting sands",
            "imposition",
            "strongarm",
            "mountain runt",
            "helena's rebuff",
            "appeal to the ancestors",
            "tabia of the lionheart",
            "collector of histories",
            "mieng, who dances with dragons",
            "abandoned meadow",
            "shoalshine",
            "coralight mystic",
            "scramble the scouts",
            "day of the emperor",
            "tranquil repose",
            "ambition's crown",
            "gift of eternity",
            "takeda taro",
            "madelon, merchant's heir",
            "lizhao, lord of the yaogu",
            "bustling harbor",
            "globule of sanctuary",
            "rokai's vassal",
            "mind-pryer",
            "urak, voice of the horde",
            "weeping soul",
            "chronofracture",
            "inquirer, roaming rover",
            "disallow",
            "damning flames",
            "crystal cauldron",
            "claimed by the veil",
            "obliterating blast",
            "whiterun gates",
            "untethered disciple",
            "guardian's revocation",
            "torch the city",
            "vali, planar researcher",
            "ligos, shadow's source",
            "decree of bias",
            "tinkering swarm",
            "herald of heroes",
            "calming dromoryx",
            "abandoned cairn",
            "wightlight",
            "volta, construct consultant",
            "one",
            "vithian arcanist",
            "conscription",
            "rallios' return",
            "master of masks",
            "maelstrom elemental",
            "cloud rock",
            "spilling secrets",
            "tears of tizuma",
            "journey through kareki",
            "calcified dunes",
            "caronas, eon wanderer",
            "phantom threader",
            "prismatic champion",
            "sundering sage",
            "passionate congregation",
            "selene the cruel",
            "cypress, the wayfarer",
            "burning up",
            "burning heels",
            "magdel, caller of souls",
            "gilded spyglass",
            "shizen, the thousand steps",
            "servant of precursors",
            "disassociate",
            "artificer's prowess",
            "reverent flame",
            "expedition map",
            "virtual terrain",
            "sandstreamer",
            "aether pull",
            "rawthlin market line",
            "ambitious dreams",
            "awakening the dragon",
            "bahet, god of destruction",
            "ifram, god of chaos",
            "trapcatcher's form",
            "buoyant thoughts",
            "scourge of the skies",
            "heartwalker",
            "searing script",
            "armadillo cloak",
            "demanding idol",
            "seedy bar",
            "ice path",
            "herald of the departed",
            "the dominomicon",
            "voiceless assailant",
            "thunderhoof mammoth",
            "derail",
            "secret stash",
            "propagation blade",
            "coralight lifebloom",
            "twin lis of the divine realm",
            "seedcall",
            "blessing of morning",
            "fleeting memory",
            "elemental of surprise",
            "apprentice summoner",
            "wayward afflicted",
            "festering waif",
            "duskwood revolutionary",
            "prophet of pacifism",
            "grim armory",
            "sungrace meadows",
            "horizon wayfarer",
            "fungal swathe",
            "acin, the toymaker",
            "from peace and purpose",
            "vitality of blossoms",
            "grove's respite",
            "vibrant sandbar",
            "prismatic cavern",
            "njel crocodile",
            "seek the lost child",
            "confront the riddle master",
            "phantasmal owl",
            "nightcloak ritualist",
            "fate transfer",
            "choir of the lost",
            "curse-blood morrigan",
            "planar eviction",
            "hao'tai, the ancient one",
            "unorthodox methods",
            "aurora, soulweaver",
            "emperor azuma hashiro",
            "carrionpult",
            "twisted archangel",
            "blood harvest",
            "foulweather effigy",
            "equilibrium paladin",
            "woopip bruiser",
            "lightless hedron",
            "through the ashen gate",
            "champion of the red dawn",
            "hembwe, the all-mother's hand",
            "volcanic terror",
            "meteor harbinger",
            "duel of intellect",
            "scorned figurant",
            "dregscape chant",
            "avid researcher",
            "spinebreak",
            "blossom-sower witch",
            "enemies of my enemy",
            "idyllic oasis",
            "bleak shoreline",
            "fatresya, protector of the people",
            "shambling morass",
            "hunt the monstrous",
            "ancient counsel",
            "risen raven",
            "gorbes index",
            "battlesuit prototyping",
            "destabilizing the rifts",
            "synapstorm",
            "raiding gnoll-band",
            "equanimity",
            "ephemeral support",
            "crossing the rifts",
            "the warrior within",
            "manifest memories",
            "curator of cures",
            "pakka, the shadowcloak",
            "seek refuge",
            "everything black",
            "artisan's fountain",
            "tea of augury",
            "soul of iscathia",
            "enjoy the silence",
            "bury the past",
            "arcor diamond",
            "meddling gargoyle",
            "sticky fingers",
            "sporegraft",
            "shokan captain",
            "sword of silver and gold",
            "hidden hollow",
            "fallen ideal",
            "withering agony",
            "time in a bottle",
            "beckoner of horrors",
            "demystifying tide",
            "mirror image",
            "el-mazar, wayward palace",
            "borsuppa scavenger",
            "the future is now",
            "eradicating flames",
            "paincaller",
            "turela, defiant angel",
            "rampant growth",
            "miyoga dragonsoul",
            "crimson hellmaw",
            "ferocious desert-hunter",
            "rewrite fate",
            "invisibility cloak",
            "rhys, keeper of scriptures",
            "windwielder",
            "aleryn, trapseeker",
            "skeigr, skhorvall flagship",
            "mennin reclamation",
            "suburban runebrawler",
            "scout the terrain",
            "zadyk resourcefulness",
            "bessie",
            "rogg, chaos treader",
            "elaborate transportation",
            "lerithan rebel",
            "journey to the zhedina",
            "rylei wakebreaker",
            "high sovereign thura",
            "idol of the dead god",
            "chiheisen, terrace of serenity",
            "masquerading bohemian",
            "blood bond",
            "theurgist of the depths",
            "reckless pyremage",
            "taiyohata champion",
            "enlightenment",
            "cosmostorm rider",
            "scraps of memory",
            "sleight of hand",
            "dominik's shack",
            "realmwalker domovoi",
            "sword",
            "repent's champion",
            "sunstage",
            "rehearse",
            "fardancer liege",
            "find greater purpose",
            "stormwing raven",
            "trailbloomer",
            "vivid march",
            "spirit pendant",
            "sworn cohort",
            "consult ancient knowledge",
            "improbable aim",
            "crystal wave",
            "raid the cursed temple",
            "seek the buried relic",
            "ildirin, the apex blade",
            "moon of the encroaching night",
            "killdrone assembly works",
            "encampment blimp",
            "evigian noble",
            "erika's purge",
            "haunted fairground",
            "petrify",
            "citadel of denial",
            "resounding relief",
            "globule of intuition",
            "hermit's travels",
            "wurmscape",
            "searing pulse",
            "bloodboil harlequin",
            "in tragedy",
            "inferno lash",
            "dazzling display",
            "game trail",
            "novaheart guardian",
            "autumn fae",
            "coward's compulsion",
            "golden age",
            "sudden decompression",
            "glowspore grove",
            "shina taiyohata",
            "mortal pilgrimage",
            "seal of approval",
            "from beyond the grave",
            "shuddering node",
            "light knight",
            "solar flair",
            "oslyd dreamer",
            "rangewalker pyromancer",
            "splitting phantasm",
            "twinned slasher",
            "crystallized moment",
            "mirrorstorm",
            "glorysinger",
            "terror of the tides",
            "bogsworn club",
            "bone saw",
            "reality reversal",
            "chitinborn sentry",
            "glittering narwhal",
            "sire of empires",
            "enchanting palace",
            "heroic crusader",
            "evavin duelist",
            "jund command",
            "egg bomb",
            "bow or burn",
            "imaginary flames",
            "phantasmal possession",
            "kiri, cloudwalker",
            "backwoods cultivator",
            "archlegislator",
            "silkweaver matron",
            "price of wisdom",
            "court beastmaster",
            "fate tracer",
            "formidable bulkvine",
            "haruna, master architect",
            "battlewise strategist",
            "buttress formation",
            "raving rover",
            "jara incarnation",
            "shushing usher",
            "butcher of shallow graves",
            "scuripi lookout",
            "plains island",
            "march of the gray",
            "slightly mad",
            "stratospheric bombardment",
            "khalizors' last stand",
            "soul of new alores",
            "heretical summons",
            "animus vox",
            "alive and on top",
            "united force",
            "cathartic reunion",
            "great and small",
            "miraculous genesis",
            "painwield explorer",
            "architect of the derezzed",
            "hallowed executioner",
            "search for inspiration",
            "midnight's pale moon",
            "gate to the nav",
            "aetherdrain",
            "caress the fleets",
            "xoqal, world eater",
            "riv's safehouse",
            "archangel of bliss",
            "sculler's oar",
            "hostile atmosphere",
            "starlight seraph",
            "in the face of divinity",
            "elvish songseeker",
            "foretold strength",
            "ontarachie hunter",
            "mortality keeper",
            "awaken to the new world",
            "sylvan scrying",
            "vectis entrancer",
            "mindbreak artisan",
            "cranial archive",
            "control discourse",
            "meteor fall",
            "light within shadow",
            "asharo's handmaiden",
            "fiery embrace",
            "kin of the rainforest",
            "mercurial chameleon",
            "time after time",
            "depth charger",
            "trainee karina oblay",
            "ascendant's murmur",
            "masaru, aspiring champion",
            "charming nereid",
            "conchspear hunter",
            "raloran tidecaller",
            "pitchwater singer",
            "schoolstrider",
            "feeding time",
            "seadrake rider",
            "pristine duelist",
            "imperial defenses",
            "ridge warden",
            "the banishment of seh'a",
            "consult the scriptures",
            "under cover of dark",
            "mystic mackerel",
            "organic corrosion",
            "lumbering egil",
            "hunting experience",
            "silt lurker",
            "snuff out the light",
            "danithra inquisitor",
            "fuhai-no-oni",
            "little kibo",
            "himitsu, shigure's legacy",
            "antimagic formula",
            "quell mutiny",
            "epic of jobiah",
            "tsolmon, the huntress",
            "aether road caravan",
            "phasmopillar",
            "requiem of the fallen",
            "berylscale alaj",
            "riko, the paragon",
            "the sun also rises",
            "abandoned skyroad",
            "pillar of flame",
            "aelinn, serpent's voice",
            "heart's desire",
            "siraj, interplanar thief",
            "moved by instinct",
            "bvala, queen of the swarm",
            "abandoned wilderness",
            "otherworldly forest",
            "greypelt brute",
            "nip at the heel",
            "sphinx of ill omens",
            "clever rejoinder",
            "decide boundaries",
            "rugged fields",
            "imperial barracks",
            "tectonic chateau",
            "risti inquisitor",
            "fragment mind",
            "selvar's defiance",
            "saishuteki castle",
            "woven network",
            "bahet's emissary",
            "phantasmal stalker",
            "sand scorpion",
            "contagious deathspore",
            "untested initiates",
            "winter's whelp",
            "slayer of the famed",
            "fourth eye assassin",
            "ingredient scroungers",
            "shedding of the coils",
            "kurayami shrine",
            "depthlight salvager",
            "thornweald archer",
            "avoid fate",
            "hollow wanderer",
            "fretport mob",
            "precursor filtercruiser",
            "seek the maker's egg",
            "lofty denial",
            "nimbus glider",
            "kotis, promised general",
            "volcano tyrant",
]

        names
            .map{|n| db.cards[n]}
            .flat_map{|card| card ? card.printings : []}
            .to_set
    end

    def to_s
        "is:playable"
    end
end