class ConditionIsCanon< Condition
  def search(db)
    names = [
      "fog",
      "giant growth",
      "icy manipulator",
      "shatter",
      "avoid fate",
      "scaled wurm",
      "snow-covered forest",
      "snow-covered island",
      "snow-covered mountain",
      "snow-covered plains",
      "snow-covered swamp",
      "ancestral memories",
      "dissipate",
      "mana prism",
      "pacifism",
      "rampant growth",
      "wind drake",
      "harrow",
      "conviction",
      "heat of battle",
      "shock",
      "ravenous rats",
      "sleight of hand",
      "curiosity",
      "merfolk looter",
      "soul warden",
      "duress",
      "heat ray",
      "unearth",
      "strategic planning",
      "straw soldiers",
      "arrest",
      "armadillo cloak",
      "exclude",
      "opt",
      "prohibit",
      "recoil",
      "recover",
      "enlistment officer",
      "auramancer",
      "demolish",
      "naturalize",
      "wall of hope",
      "gilded lotus",
      "raise the alarm",
      "aether snap",
      "farseek",
      "peel from reality",
      "quickchange",
      "seismic spike",
      "telling time",
      "burning-tree shaman",
      "drowned rusalka",
      "ghostway",
      "assassinate",
      "cancel",
      "cloudchaser kestrel",
      "moonlace",
      "tendrils of corruption",
      "terramorphic expanse",
      "brute force",
      "lavacore elemental",
      "coalition relic",
      "mass of ghouls",
      "snake cult initiation",
      "storm entity",
      "thornweald archer",
      "familiar's ruse",
      "disperse",
      "idyllic tutor",
      "negate",
      "fate transfer",
      "polluted bonds",
      "springjack pasture",
      "arcane sanctum",
      "bone splinters",
      "crumbling necropolis",
      "etherium sculptor",
      "fatestitcher",
      "jungle shrine",
      "magma spray",
      "savage lands",
      "seaside citadel",
      "bone saw",
      "kaleidostone",
      "rupture spire",
      "disentomb",
      "divination",
      "divine verdict",
      "essence scatter",
      "great sable stag",
      "harm's way",
      "rise from the grave",
      "seismic strike",
      "sign in blood",
      "solemn offering",
      "warpath ghoul",
      "beast hunt",
      "heartstabber mosquito",
      "mold shambler",
      "summoner's bane",
      "vastwood gorger",
      "aether tradewinds",
      "dispel",
      "explore",
      "goblin roughrider",
      "groundswell",
      "lodestone golem",
      "nature's claim",
      "evolving wilds",
      "goblin arsonist",
      "goblin tunneler",
      "prophetic prism",
      "runed servitor",
      "soul's attendant",
      "blood tithe",
      "cultivate",
      "elixir of immortality",
      "inspired charge",
      "bonds of quicksilver",
      "strider harness",
      "lead the stampede",
      "morbid plunder",
      "command tower",
      "angelic destiny",
      "manalith",
      "timely reinforcements",
      "brimstone volley",
      "dead weight",
      "furor of the bitten",
      "prey upon",
      "smite the monstrous",
      "black cat",
      "griptide",
      "blood artist",
      "builder's blessing",
      "favorable winds",
      "ghostly flicker",
      "human frailty",
      "pillar of flame",
      "archaeomancer",
      "captain's call",
      "murder",
      "sentinel spider",
      "smelt",
      "cobblebrute",
      "druid's deliverance",
      "knightly valor",
      "stealer of secrets",
      "blood bairn",
      "dissolve",
      "hero's downfall",
      "lightning strike",
      "read the bones",
      "unknown shores",
      "disciple of deceit",
      "mana confluence",
      "oppressive rays",
      "invasive species",
      "reclamation sage",
      "bloodfell caves",
      "blossoming sands",
      "cranial archive",
      "dismal backwater",
      "dragon grip",
      "jungle hollow",
      "kill shot",
      "rugged highlands",
      "scoured barrens",
      "swiftwater cliffs",
      "thornwood falls",
      "tormenting voice",
      "tranquil cove",
      "wind-scarred crag",
      "frost walker",
      "sandblast",
      "lightwalker",
      "caustic caterpillar",
      "tainted remedy",
      "ancient crab",
      "natural state",
      "stormchaser mage",
      "anguished unmaking",
      "choked estuary",
      "ethereal guidance",
      "foreboding ruins",
      "fortified village",
      "game trail",
      "port town",
      "sanitarium skeleton",
      "warped landscape",
      "faith unbroken",
      "blossoming defense",
      "cathartic reunion",
      "long-finned skywhale",
      "ice over",
      "blazing volley",
      "bone picker",
      "painted bluffs",
      "one with the wind",
      "sorcerous spyglass",
      "vanquisher's banner",
      "ravenous chupacabra",
      "reckless rage",
      "fervent strike",
      "pierce the sky",
      "aggressive instinct",
      "mana geode",
      "agonizing syphon",
      "arcane signet",
    ]

    names
      .map{|n| db.cards[n]}
      .flat_map{|card| card ? card.printings : []}
      .to_set
  end

  def to_s
    "is:canon"
  end
end