class ConditionIsPlayable < Condition
	def search(db)
		names = [
			"wayfarer's shrine",
			"seal the tomb",
			"pith wilt",
			"nebula of empty gold",
			"stand unassailable",
			"mysterious cataract",
			"flooded depths",
			"murmuring falls",
			"duress",
			"magmatic torrent",
			"shifting glade",
			"crystal cavern",
			"grim bastion",
			"nomad's township",
			"crumbling precipice",
			"shardstone rift",
			"sedate tundra",
			"lush oasis",
			"stolen secrets",
			"monument of queens",
			"amber hills",
			"fungal mire",
			"flooded morass",
			"event horizon",
			"ocean monastery",
			"sacrificial bull",
			"out-of-body experience",
			"titan snare",
			"timber range",
			"arctic mine",
			"soul gate",
			"lumbering hillock",
			"barren desolation",
			"lavatorn fields",
			"frostfire geysers",
			"mana ascetic",
			"resplendent substratum",
			"scorch",
			"exeunt",
			"recall forgotten eons",
			"rampant summit",
			"cosmic sinkhole",
			"memento mori",
			"nereba, sandchoked archives",
			"cursory glance",
			"corpsebed",
			"journey's end",
			"pool of light",
			"descend on the helpless",
			"shal'draen's rage",
			"oracle's vision",
			"gloomcover steppe",
			"prying inquiry",
			"sunlit highland",
			"roggar's frenzy",
			"still the pandemonium",
			"shikai's redoubt",
			"thought blossom",
			"wheat from chaff",
			"forgotten steppe",
			"negate",
			"portal fracture",
			"mpumo, who stands alone",
			"flourishing crevasse",
			"heart of the glade",
			"violent collapse",
			"mirrorgate",
			"singularity's grasp",
			"murky peat",
			"voidflare",
			"cane dancer",
			"bahum, the warden",
			"monkeyshines",
			"tropical grove",
			"rage of the ravaged",
			"spell pierce",
			"nature's claim",
			"stormsurge",
			"hierarch ranger",
			"banished companion",
			"jobiah, devoted farmer",
			"chi lee of the underworld",
			"mana confluence",
			"a planet far, far away",
			"tsang jin, master of the jade sea",
			"heart of zhedina",
			"tenacious guide",
			"etherium abrogator",
			"cradle of corruption",
			"gleaming river",
			"spiraling canyon",
			"children of the clouds",
			"basat charm",
			"unearth",
			"the high prairies",
			"anzen, beyond the sea",
			"northern express line",
			"unjust sentence",
			"solar flare",
			"guiding light",
			"jade vault reclaimer",
			"destructive ambition",
			"bounty of the gardens",
			"brine fleet bay",
			"find happiness in misery",
			"antimagic",
			"departed evangel",
			"inishtu, desert healer",
			"unceasing flames",
			"leyran alpha",
			"dark bargain",
			"imperial claim",
			"sunwashed spires",
			"once abandoned",
			"union rail strikebreaker",
			"ignition ritual",
			"stalwart dominion",
			"unquenched greed",
			"intrepid",
			"villainy",
			"tamiyo, lunar arcanist",
			"prodigious panya",
			"rakkiri dissident",
			"tiny heroine totti",
			"sea of skies beyond",
			"epic encounter",
			"vibrant rapture",
			"pay up",
			"terraformer's globe",
			"face the dawn",
			"suitor of the sea",
			"seek prophecy",
			"reveal eternities",
			"scion of torrents",
			"polyp pools",
			"bant command",
			"ancestral council",
			"veilborn meddler",
			"verdant dominion",
			"temporary treason",
			"ostracizer orb",
			"sights beyond",
			"volatile stonework",
			"impden mother",
			"end of days",
			"shugenja sanctuary",
			"warded tome",
			"mindstorm's eye",
			"lucien, the grifter",
			"rock",
			"sigil of radiance",
			"neutralize",
			"tal, locus sentry",
			"bloodriver",
			"aiel tazan",
			"rot",
			"seto san, the dragonblade",
			"fiery erasure",
			"heist headquarters",
			"dreamsight well",
			"profane emissary",
			"chikyu champion",
			"shadowband consul",
			"antithesis",
			"fogspewer",
			"idyllic odyssey",
			"rousing rubble",
			"imperial siege",
			"earthbreaker behemoth",
			"plasma addict",
			"dovon, verdant experimenter",
			"sporeflow protector",
			"theocracy",
			"kaur, end of lies",
			"tidehollow lich",
			"fair trial",
			"last passage",
			"fractured reach",
			"bessie's brood",
			"kati evalin, world wanderer",
			"hugo of the shadowstaff",
			"mabil fardancer",
			"ruin delver",
			"long forgotten",
			"vast savannah",
			"invalidate",
			"brazen sacrilege",
			"leija's greenblade",
			"dead man's party",
			"redtail fencer",
			"galvan coal line",
			"deform sanity",
			"velir the sunderer",
			"seedshrine",
			"scorch",
			"lumenbay flyer line",
			"setting sun",
			"opt",
			"endless helpless souls",
			"seabreen nullmage",
			"avatar of basat",
			"smoldering pages",
			"civilization's cost",
			"beneath the zhedina",
			"sabne's autumn",
			"twilight ambush",
			"grim slums",
			"kellythross' workshop",
			"calamitous crash",
			"parrot pools",
			"promethean grotto",
			"performer of ambition",
			"budding companion",
			"tend to the grove",
			"conjure realities",
			"primal ruffian",
			"end of all things",
			"glistening chalice",
			"bottled lightning",
			"aerie's pillar",
			"avatar of the natural",
			"brushcover elf",
			"eli windsors, lone gun",
			"distant thunder",
			"glitch, galactic muse",
			"farseek",
			"tendrilsnare",
			"new divide",
			"mosecf, the sunseeker's path",
			"tyrant of tributes",
			"ever-gnawing rat",
			"priestess of simplicity",
			"ignition point",
			"autumnal watch",
			"flaming point technique",
			"dawson's loot",
			"mystery of the crashed craft",
			"rift splicing",
			"chains of subdual",
			"bearer of the lantern",
			"all-enduring mafua",
			"helene trant",
			"oppress the weak",
			"staff of equilibrium",
			"academic's claymore",
			"sunken ambitions",
			"thunder road",
			"iviana, speaker of fangs",
			"resonating force",
			"temporal resuscitation",
			"diffuse",
			"the afterlife takes its due",
			"scuttling gnat",
			"gift of the phoenix",
			"garth of the chimera",
			"forked pillar",
			"ruinous naga",
			"hellion devastator",
			"answer midnight's call",
			"corvid heretic",
			"self replication",
			"noble's hedonism",
			"seismic colossus",
			"precursor sanctum",
			"gilded gearhulk",
			"arcane chronometer",
			"beckon of the wild",
			"ceaseless stalker",
			"lhosei of the ghost peak",
			"dispel",
			"noxious upwelling",
			"herald of oblivion",
			"stalked healer",
			"danithra muckbruiser",
			"nightwatch rallier",
			"channeling stone",
			"azun, sheriff of daisite",
			"facsimile of divinity",
			"fateful journey",
			"anomalion",
			"babyscale bruiser",
			"blood jade prophet",
			"bitter duckling",
			"perilous passage",
			"plaxolotl pyari",
			"palace of reflections",
			"monument to the fallen man",
			"what lurks beyond",
			"explore",
			"titanic fossil",
			"turi of hollow depths",
			"vaultkeeper",
			"verdant bluff",
			"miyoga firebird",
			"irika, wielder of secrets",
			"martial maestro",
			"emerabi's disciple",
			"lord rickard dawson",
			"nacatl skirmisher",
			"powder scatterer",
			"canyon creek",
			"duress",
			"helena, the awakener",
			"ride the storm",
			"into waridi valley",
			"azamir, wayward titan",
			"putrid lurker",
			"social graces",
			"egg of avarice",
			"curse of the drow",
			"primal dominion",
			"roggar's gambit",
			"lord ellison crain",
			"forbidden burial",
			"embodied soul",
			"desolate dominion",
			"pristine dominion",
			"strike from the shadows",
			"marisa of the gravehowl",
			"fulmen, aether prodigy",
			"ria-demian charm",
			"mausoleum suffragan",
			"corrupted memory",
			"mastery of the veil",
			"cleared vault",
			"crystal garden",
			"shifting grove",
			"archive guardian",
			"mari, dawn resurgent",
			"oshin, keeper of the shoal",
			"cognitive fumigator",
			"caulte axeslinger",
			"replicator mage",
			"dark rite cultist",
			"tinkerer's tools",
			"mystic arts",
			"currency",
			"meteor volley",
			"dead-set duo",
			"finish off",
			"lay low",
			"silent hypnotist",
			"arpechian champion",
			"veteran lifeforger",
			"will of a fickle lord",
			"fellor charm",
			"marinton-ravengulch line",
			"sorcerous spyglass",
			"mysterious coffer",
			"resign to madness",
			"scion of fecundity",
			"coastal dominion",
			"consult the dewdrops",
			"cosmic war",
			"elrayin, the manaroot",
			"pitchpyre curse",
			"krismite vault",
			"sadistic indulgence",
			"servant of armageddon",
			"witch's invocation",
			"rain of ruin",
			"imagination unleashed",
			"masahita, bloodtongue",
			"waxing angel",
			"sage's ashes",
			"flare blitz",
			"frailty",
			"emissary of antiquity",
			"scion of flourishing",
			"siesa tremund",
			"kaalia's abomination",
			"cranial violation",
			"angel of succor",
			"squid pro quo",
			"no rest",
			"xiong mao, the intrepid",
			"seto san, the sacred hand",
			"profound introspection",
			"curse of bleeding",
			"crewmaster gillo",
			"crystal conjuration",
			"sedraxis trepanator",
			"gaze deeper",
			"shifting cascade",
			"a journey begins",
			"haunted boughs",
			"admonish",
			"jara champion",
			"scintillate",
			"golden touch",
			"whiterun ordainer",
			"stormshaper adept",
			"moment of tranquility",
			"bogborn charger",
			"madcap mercenary",
			"abandoned monument",
			"chratteri restoration",
			"backstage rooms",
			"cadre hawk",
			"timestream sentinel",
			"conspiracy of ravens",
			"silent wanderer",
			"explorer's fate",
			"unlit alley",
			"conjuring of locusts",
			"shining crusader",
			"unlikeliest heroes",
			"rugged dominion",
			"watch from above",
			"truth unveiled",
			"kinken, the dragon's breath",
			"last stop",
			"far wandering guardian",
			"slashing pangolin",
			"one with the world",
			"sun-sigil ordainer",
			"mark of dark opulence",
			"cumulus horizon",
			"prying inquiry",
			"hit the bottom",
			"flawless counterfeit",
			"lodestone golem",
			"sun yun, master of self",
			"scion of desolation",
			"persevere",
			"heart of the deadwood",
			"ayala's concord",
			"conflux ravager",
			"heraldry",
			"soul leak",
			"unexplored regions",
			"forbidden brew",
			"ethereal armor",
			"clockwork gaucho",
			"death pits hawker",
			"source decay",
			"hazy moorland",
			"burning revelations",
			"left on the wayside",
			"scion of storms",
			"sevid, the lookout",
			"shimmering dragon",
			"howling shieldbreaker",
			"unforget",
			"anguished unmaking",
			"thievery",
			"earthfeeder worm",
			"brutal blow",
			"holcomb of the peregrine",
			"xirix, the usurper",
			"void portal",
			"deflecting strike",
			"zhelid, planar academy",
			"essential override",
			"devised companions",
			"the flames approach",
			"keeper of the sanctum",
			"stormwake",
			"reinvent",
			"ravaged monument",
			"head of ulko",
			"shifting canyon",
			"tt-23 aegis",
			"shifting crag",
			"magmatic cache",
			"tether of simplicity",
			"croakfolk troubadour",
			"lazaire's conjuring",
			"ardy, youthful geomancer",
			"lone survivor",
			"ambitious necromancer",
			"convert to resources",
			"oil driller",
			"charming marauder",
			"imagine",
			"power plant",
			"blessed spellroot",
			"fey grove",
			"recoil",
			"sealed riftway",
			"potion of inhibition",
			"moonlight sanctum",
			"zegarra, the rival",
			"camouflaged sprareos",
			"the last sacred gate",
			"hub of innovation",
			"timely reinforcements",
			"seeker of mysteries",
			"tear loose",
			"imperial port",
			"flesh to rot",
			"rootwarper",
			"aerial adept",
			"forgotten shrine",
			"reckless festivities",
			"find nothing",
			"ruined precipice",
			"all or nothing",
			"buy time",
			"legitimate establishment",
			"marshy marauder",
			"minister of madness",
			"maghbri oracle",
			"hall of random access memories",
			"gateblessed explorer",
			"chantwood channeler",
			"starjump",
			"seeker lizaveth",
			"crack open the cache",
			"worried vulpine",
			"paragon of honor",
			"lord rokai",
			"soul pierce",
			"forgotten lessons",
			"young necromancer",
			"cinderblade",
			"unleash the dragon",
			"coralight champion",
			"culling blade",
			"liliana at the brink",
			"plasma blader",
			"miner's barracks",
			"council's will",
			"monsoon lagoon",
			"othersea submersible",
			"fiery burst",
			"menna al-mejjat",
			"fireshaper adept",
			"exergetic chains",
			"soul warden",
			"soul's attendant",
			"parish paragon",
			"blundering clocktower",
			"master of tranquility",
			"paracosm",
			"whisperwoods phoenix",
			"champion of destinies",
			"ajani resolute",
			"false vitality",
			"caller of hunger",
			"sunrazed ruins",
			"sanaito, alone",
			"soul release",
			"infuse the apparatus",
			"hunter's hideout",
			"rend",
			"impish delights",
			"forgotten pit",
			"echoing knowledge",
			"advocate of the hunt",
			"nightmares unseen",
			"merchant of false lives",
			"soaring canyon",
			"adam of the ironside",
			"qililia, the saboteur",
			"zoulev offering",
			"rippling curtain",
			"from ancient tomes",
			"vivid mirage",
			"zhedina bazaar",
			"sealed mausoleum",
			"champion of scales",
			"unity spheres",
			"memories reignited",
			"deadwood terror",
			"forbidden truths",
			"wealth of the underbrush",
			"remembrance of light",
			"resurging rhino",
			"slaffield workgate",
			"tidal spite",
			"serene prayer",
			"glymna blackrune",
			"edarna the everforge",
			"collapse the pillars",
			"shadowed slums",
			"hymn of fury",
			"first general of the wards",
			"fae-blessed attendant",
			"slaughterkeg",
			"sera of coppercove",
			"bal's descent",
			"plasma enforcer",
			"frigid thicket",
			"edith waunt",
			"reflected moment",
			"terraformer's globe",
			"bleak dominion",
			"witch of spring's promise",
			"the court of angels",
			"ghastly ferry",
			"entrail elemental",
			"vengeful messenger",
			"accursed by unborn fates",
			"tomb steward",
			"blossoming defense",
			"vythraktos, master necromancer",
			"caustic caterpillar",
			"anarchy storm",
			"under the sea",
			"worlds away",
			"shengin renegade",
			"lilyreed triton",
			"flora acolyte",
			"hannaru's courage",
			"ethereal fervor",
			"root dancer",
			"wave of decay",
			"warhound shuja",
			"chikami castle",
			"rustshell crustacean",
			"coercive methods",
			"shifting morass",
			"idyll",
			"negate",
			"idravir, the last city",
			"crossing the fog",
			"amber reserves",
			"fierce combatant",
			"junktrawler",
			"dreadfire tyrant",
			"bahum's penance",
			"overgrown refuge",
			"flatboat artisan",
			"master of elements",
			"fanciful bloom",
			"reforge",
			"stabilize",
			"kantra of old majik",
			"chiu of the wild realm",
			"herald of wisdom",
			"nidohagane warfans",
			"arcane duelist",
			"skypath pilgrimage",
			"mettalia, light from above",
			"banish",
			"merciful yuroda",
			"qilan wanderer",
			"tranquil ascetic",
			"skycaster's aura",
			"all that glitters",
			"performer of desire",
			"mina, jeweled minnow",
			"the moon rises",
			"emperor's retainer",
			"ema, the traveler",
			"possibility scope",
			"willow spirit",
			"favorable winds",
			"stormcaller sentinel",
			"sear flesh",
			"suzume oshiruko",
			"jak, daring vanguard",
			"hesediel, the reborn",
			"crystal grotto",
			"path of fire",
			"ivenge, false god",
			"senaturian legion",
			"forgotten steppe",
			"judge's decree",
			"vibrant flames",
			"sword of tides and time",
			"razione racecourse",
			"supreme mechanothurge",
			"spellbane adept",
			"dragoncalling",
			"awaken to the skies",
			"ethereal spellmaster",
			"boundless evolution",
			"unassuming swineherd",
			"rafiq the magnanimous",
			"fatal edict",
			"inoshi the wild boar",
			"paragon of purity",
			"ill fated travels",
			"founding hero",
			"kazimir's ban",
			"merrow legendmaker",
			"aureate panorama",
			"culminating despair",
			"valencia of the concordant",
			"experimental battle armor",
			"aquilifer axelius",
			"eye of the beholder",
			"clean-up crew",
			"aethermancer's familiar",
			"logger recluse",
			"zhedina outskirts",
			"searle of the tempest",
			"artificer's gift",
			"rousing rubble",
			"shardstone rift",
			"rejoicing aristocrats",
			"duelist's forms",
			"recurring abomination",
			"unstable footing",
			"decree of bias",
			"great sable stag",
			"indomitable bear",
			"once scarred",
			"kinjiru assailant",
			"dehmi, origin seeker",
			"wild lifescale",
			"zhedina envoys",
			"sunrise prairie",
			"vicious slasher",
			"insurgent ballads",
			"soliloquy",
			"powercell engineer",
			"myrmidon's warhead",
			"offerings to the deathless",
			"chemical grenade",
			"master negotiator",
			"brutality",
			"exiled necromancer",
			"duskwood thicket",
			"evaldi's muse",
			"lt. daisy saxon",
			"dragongate",
			"sanding",
			"krismite purveyor",
			"duskwood vanguard",
			"endless expedition",
			"refract",
			"selvar's defiance",
			"starlight beacon",
			"return to form",
			"highland dunes",
			"stonewood sanctuary",
			"rune-scribe's apprentice",
			"blade of the serpent",
			"soulbreaker of mautakesh",
			"sankataar scourge",
			"clutch of the coil",
			"procedural genesis",
			"into the unknown",
			"relic heist",
			"tear through",
			"sinister pact",
			"blazing volley",
			"shigurei, the floodbringer",
			"zhedina valiant",
			"guard of cuirassiers",
			"culminating wisdom",
			"oracle's omission",
			"illusionary steed",
			"shatter the mask",
			"shawlbinder",
			"corecharge",
			"adoroth, the baneful",
			"hanabira, kogane's legacy",
			"whirlpool ride",
			"wisdom in reflection",
			"wayfaring pilgrim",
			"rest",
			"iterative design",
			"bahum, penitent",
			"protective memory",
			"gyreon pickpocket",
			"militant youth",
			"reweave reality",
			"adiran scryers",
			"frilled drakeling",
			"lady genvieve of caulder",
			"oracle's ploy",
			"sharuum, archmagocrat",
			"rawthlin market line",
			"hirukari, daughter of the sun",
			"vanish",
			"student of the coil",
			"scion of scales",
			"fang of mautakesh",
			"touch of the coil",
			"serpent's grasp",
			"ralora, unforgiving depths",
			"encapsulate",
			"seek the future",
			"the erased",
			"mele, the onemother",
			"portal fracture",
			"planeswalker's insight",
			"shrine of the six pillars",
			"stolen cache",
			"possibility engine",
			"spectral skycruiser",
			"coppergild mercenary",
			"volcanic pounce",
			"withering husk",
			"ironeyes desperado",
			"shinrin spellhunter",
			"stickup",
			"interan soothsayer",
			"rakkiri initiate",
			"fox of the orange orchard",
			"third legion general",
			"thundermane fox",
			"sunblessed orator",
			"naya command",
			"mobilize the heavenly",
			"thallid cultivator",
			"seeker of untouched beauty",
			"threshing sundew",
			"master of imports",
			"reenter orbit",
			"bloodbraid ritualist",
			"etherium leviathan",
			"ornate incense",
			"helping hand",
			"ruinous proselyte",
			"wicked blow",
			"puppeteering",
			"animorph",
			"unified theory",
			"ruchi, the effervescent",
			"heirloom",
			"dawson's collector",
			"iron signet",
			"sarrutu flamebinder",
			"onyx ritualist",
			"behemoth channeler",
			"mind-mute",
			"lucien, the ravenous",
			"rainy night lovers",
			"vasille rioters",
			"bustling harbor",
			"farmer's repose",
			"entrancing light",
			"one bad night",
			"raid the forgotten tomb",
			"alvarez of the huntsman",
			"mable of the sea's whimsy",
			"fireheart channeler",
			"blood ritual",
			"awaken the nav",
			"right to rule",
			"jade temple",
			"shemesh, nomad chieftain",
			"emissary of dark tides",
			"imposition",
			"turin's study",
			"myrmidon, coralight exile",
			"suisei the southern star",
			"heaven, presidential ship",
			"grove's respite",
			"alratha, pearl of the sand sea",
			"descend upon the tomb",
			"flooded depths",
			"frostfire geysers",
			"magmatic torrent",
			"fungal mire",
			"lumbering hillock",
			"shikai's redoubt",
			"sunlit highland",
			"cobbled transport",
			"carnival yatiri",
			"the aetherite saloon",
			"forgemaster's charm",
			"rainbow phoenix",
			"brilliant citadel",
			"festival of roaring dragons",
			"lost in smoke",
			"tinkering swarm",
			"arcanist's reaver",
			"cloudbank",
			"molten falls",
			"death in reverse",
			"salim and certo",
			"rocket admin",
			"sprout thought",
			"reflect on serenity",
			"helm of the infinite",
			"legacy warmask",
			"isolated",
			"imperial coins",
			"spotless mind",
			"raiun bay admiral",
			"the whisperwoods",
			"sevenfold summoner",
			"confining priest",
			"shroud of hinasa",
			"sungrace meadows",
			"ascension",
			"fungal swathe",
			"inked summoner",
			"fateful eruption",
			"spring renewal",
			"tower of long shadows",
			"observer of aeons",
			"extravagant flair",
			"lava plume",
			"confront the riddle master",
			"demolitionist deviser",
			"junan venomtongue",
			"voidlife orbs",
			"bewitching vapors",
			"titan's palace",
			"soulblade",
			"derevi's adjutant",
			"mirai, spring's promise",
			"hasty intervention",
			"fathom diver",
			"flash of inspiration",
			"elixir of immortality",
			"risen looter",
			"cursed scroll",
			"channel the mirror",
			"heathen rise",
			"phantasmal owl",
			"grixis command",
			"ocean monastery",
			"lavatorn fields",
			"cold shoulder",
			"sunset monastery",
			"nomad's township",
			"corpsebed",
			"crumbling precipice",
			"grove of embers",
			"rilken forcefield keeper",
			"starlit raze",
			"imperial silks",
			"by the sea",
			"wisdom of the leylines",
			"autumn canopy",
			"isochron wand",
			"rhyolithic hellkite",
			"calamity dragon",
			"sandswept bazaar",
			"hexfang ascetic",
			"earthchannel apprentice",
			"performer of growth",
			"antali archdruid",
			"summit guardian",
			"cloudcover heights",
			"bond of battle",
			"strike down the usurpers",
			"invoking the name",
			"abandoned laboratory",
			"callow survivors",
			"final reckoning",
			"buried by time",
			"master of masks",
			"bittersweet reunion",
			"rush of wonder",
			"house of forgotten whispers",
			"abandoned meadow",
			"coralight mystic",
			"sunrise orchard",
			"lizhao, lord of the yaogu",
			"globule of sanctuary",
			"takeda taro",
			"kaor's tithe",
			"madelon, merchant's heir",
			"rokai's vassal",
			"seek the lost child",
			"iron warden",
			"bearer of fables",
			"sword of monsters and men",
			"magister of impotence",
			"careless violence",
			"glorybound chorister",
			"k-17 drone",
			"stormwing ultrateryx",
			"tomb of shifting sands",
			"strongarm",
			"sewer pack",
			"suburban runebrawler",
			"burning up",
			"festival of winter's night",
			"mountain runt",
			"helena's rebuff",
			"appeal to the ancestors",
			"tabia of the lionheart",
			"collector of histories",
			"mieng, who dances with dragons",
			"shoalshine",
			"scramble the scouts",
			"day of the emperor",
			"tranquil repose",
			"ambition's crown",
			"gift of eternity",
			"consult ancient knowledge",
			"urak, voice of the horde",
			"volcano tyrant",
			"murmuring falls",
			"crystal cavern",
			"murmuring falls",
			"transplanted citadel",
			"singularity's grasp",
			"grim bastion",
			"encore of the phoenix",
			"rampant summit",
			"pyremage's knack",
			"foreseen denial",
			"damning flames",
			"crystal cauldron",
			"claimed by the veil",
			"obliterating blast",
			"whiterun gates",
			"guardian's revocation",
			"worlds colliding",
			"torch the city",
			"ligos, shadow's source",
			"calming dromoryx",
			"syrina, the dragon queen",
			"abandoned cairn",
			"wightlight",
			"volta, construct consultant",
			"one",
			"vithian arcanist",
			"conscription",
			"rallios' return",
			"blind blackguard",
			"xenocrata's fleet",
			"blissful lull",
			"kaor awoken",
			"maelstrom elemental",
			"cloud rock",
			"edge of the water",
			"twin lis of the divine realm",
			"wayward afflicted",
			"festering waif",
			"duskwood revolutionary",
			"prophet of pacifism",
			"grim armory",
			"from peace and purpose",
			"ice path",
			"prismatic cavern",
			"clever rejoinder",
			"njel crocodile",
			"vibrant sandbar",
			"shizen, the thousand steps",
			"hashiro's devoted",
			"servant of precursors",
			"pyroclastic maw",
			"disassociate",
			"artificer's prowess",
			"reverent flame",
			"expedition map",
			"gilded spyglass",
			"virtual terrain",
			"sandstreamer",
			"aether pull",
			"ambitious dreams",
			"festival of fading lights",
			"awakening the dragon",
			"bahet, god of destruction",
			"ifram, god of chaos",
			"trapcatcher's form",
			"buoyant thoughts",
			"scourge of the skies",
			"heartwalker",
			"searing script",
			"armadillo cloak",
			"demanding idol",
			"kin of the rainforest",
			"seedy bar",
			"herald of the departed",
			"the dominomicon",
			"voiceless assailant",
			"thunderhoof mammoth",
			"chiheisen, terrace of serenity",
			"derail",
			"kantra of bounty",
			"derelict town",
			"secret stash",
			"propagation blade",
			"salvage titan",
			"coralight lifebloom",
			"seedcall",
			"greypelt initiate",
			"ainok lout",
			"bourasan highguard",
			"ainok alpha",
			"ainok caretaker",
			"ainok hunter",
			"blessing of morning",
			"fleeting memory",
			"elemental of surprise",
			"apprentice summoner",
			"reconstruct",
			"abandoned preserve",
			"horizon wayfarer",
			"bvala, queen of the swarm",
			"acin, the toymaker",
			"vitality of blossoms",
			"lofty denial",
			"stolen secrets",
			"mindwave rod",
			"arctic mine",
			"cane dancer",
			"shifting glade",
			"wayfarer's shrine",
			"gloomcover steppe",
			"lush oasis",
			"scorch",
			"plasma arc",
			"duress",
			"barren desolation",
			"cradle of corruption",
			"shifting grove",
			"nature's claim",
			"perpetual motion machine",
			"kellythross' workshop",
			"through the ashen gate",
			"champion of the red dawn",
			"hembwe, the all-mother's hand",
			"wandering souls",
			"untethered disciple",
			"volcanic terror",
			"meteor harbinger",
			"duel of intellect",
			"scorned figurant",
			"dregscape chant",
			"avid researcher",
			"spinebreak",
			"leery sortie",
			"blossom-sower witch",
			"disallow",
			"mortal pilgrimage",
			"enemies of my enemy",
			"idyllic oasis",
			"bleak shoreline",
			"fatresya, protector of the people",
			"shambling morass",
			"glorysinger",
			"hunt the monstrous",
			"weeping soul",
			"ancient counsel",
			"enlightenment",
			"taiyohata champion",
			"reckless pyremage",
			"cosmostorm rider",
			"realmwalker domovoi",
			"scraps of memory",
			"sword",
			"repent's champion",
			"sunstage",
			"gathering the gang",
			"turela, defiant angel",
			"find greater purpose",
			"magdel, caller of souls",
			"vengeant precursor",
			"stormwing raven",
			"trailbloomer",
			"sworn cohort",
			"theurgist of the depths",
			"rampant growth",
			"sticky fingers",
			"sporegraft",
			"shokan captain",
			"ring of souls",
			"sword of silver and gold",
			"hidden hollow",
			"fallen ideal",
			"only memories remain",
			"withering agony",
			"time",
			"time in a bottle",
			"beckoner of horrors",
			"demystifying tide",
			"meddling gargoyle",
			"mirror image",
			"gilded gulch",
			"el-mazar, wayward palace",
			"warden of the dead",
			"cypress, the wayfarer",
			"borsuppa scavenger",
			"the future is now",
			"eradicating flames",
			"paincaller",
			"miyoga dragonsoul",
			"crimson hellmaw",
			"ferocious desert-hunter",
			"rewrite fate",
			"invisibility cloak",
			"rhys, keeper of scriptures",
			"windwielder",
			"joyous explorer",
			"aleryn, trapseeker",
			"skeigr, skhorvall flagship",
			"mennin reclamation",
			"scout the terrain",
			"zadyk resourcefulness",
			"bessie",
			"starbane elemental",
			"rogg, chaos treader",
			"elaborate transportation",
			"lerithan rebel",
			"journey to the zhedina",
			"rylei wakebreaker",
			"high sovereign thura",
			"idol of the dead god",
			"journey through kareki",
			"hinode, the sacred summit",
			"masquerading bohemian",
			"blood bond",
			"daisy, the heart of chasmek",
			"phantom threader",
			"sleight of hand",
			"dominik's shack",
			"moved by instinct",
			"rehearse",
			"fardancer liege",
			"vivid march",
			"spirit pendant",
			"improbable aim",
			"raid the cursed temple",
			"seek the buried relic",
			"ildirin, the apex blade",
			"searing insult",
			"magmatic torrent",
			"prying inquiry",
			"nightmares unseen",
			"wheat from chaff",
			"shikai's redoubt",
			"diffuse",
			"wayfarer's shrine",
			"unceasing flames",
			"negate",
			"seek prophecy",
			"amber hills",
			"spiraling canyon",
			"flooded morass",
			"hall of random access memories",
			"negate",
			"scion of calamities",
			"tyrant of tributes",
			"rock",
			"ferrofy",
			"globule of intuition",
			"hermit's travels",
			"wurmscape",
			"searing pulse",
			"colossal achievement",
			"reclamation grovesculptor",
			"bloodboil harlequin",
			"in tragedy",
			"inferno lash",
			"dazzling display",
			"game trail",
			"novaheart guardian",
			"autumn fae",
			"coward's compulsion",
			"golden age",
			"sudden decompression",
			"glowspore grove",
			"shina taiyohata",
			"seal of approval",
			"from beyond the grave",
			"shuddering node",
			"light knight",
			"solar flair",
			"oslyd dreamer",
			"rangewalker pyromancer",
			"splitting phantasm",
			"twinned slasher",
			"crystallized moment",
			"mirrorstorm",
			"terror of the tides",
			"bogsworn club",
			"bone saw",
			"reality reversal",
			"chitinborn sentry",
			"glittering narwhal",
			"sire of empires",
			"enchanting palace",
			"heroic crusader",
			"evavin duelist",
			"jund command",
			"egg bomb",
			"silt lurker",
			"snuff out the light",
			"fuhai-no-oni",
			"little kibo",
			"himitsu, shigure's legacy",
			"antimagic formula",
			"quell mutiny",
			"woopip bruiser",
			"abandoned skyroad",
			"lightless hedron",
			"decide boundaries",
			"cloudsteel summit",
			"rugged fields",
			"imperial barracks",
			"tectonic chateau",
			"risti inquisitor",
			"fragment mind",
			"reconstruct",
			"farseek",
			"painwield explorer",
			"architect of the derezzed",
			"tea of augury",
			"hallowed executioner",
			"search for inspiration",
			"selene the cruel",
			"nightmare riders",
			"midnight's pale moon",
			"gate to the nav",
			"aetherdrain",
			"caress the fleets",
			"xoqal, world eater",
			"riv's safehouse",
			"archangel of bliss",
			"hostile atmosphere",
			"immolated grave",
			"starlight seraph",
			"in the face of divinity",
			"masha's lightbound",
			"elvish songseeker",
			"foretold strength",
			"ontarachie hunter",
			"mortality keeper",
			"awaken to the new world",
			"sylvan scrying",
			"vectis entrancer",
			"mindbreak artisan",
			"arcor diamond",
			"killdrone assembly works",
			"cranial archive",
			"control discourse",
			"meteor fall",
			"light within shadow",
			"asharo's handmaiden",
			"dragon's ire",
			"fiery embrace",
			"mercurial chameleon",
			"time after time",
			"depth charger",
			"trainee karina oblay",
			"ascendant's murmur",
			"masaru, aspiring champion",
			"charming nereid",
			"conchspear hunter",
			"raloran tidecaller",
			"pitchwater singer",
			"schoolstrider",
			"feeding time",
			"seadrake rider",
			"pristine duelist",
			"imperial defenses",
			"ridge warden",
			"calcified dunes",
			"the banishment of seh'a",
			"consult the scriptures",
			"under cover of dark",
			"fate transfer",
			"soul of iscathia",
			"mystic mackerel",
			"organic corrosion",
			"lumbering egil",
			"overgrowth guardian",
			"epic of jobiah",
			"tsolmon, the huntress",
			"aether road caravan",
			"phasmopillar",
			"requiem of the fallen",
			"unorthodox methods",
			"berylscale alaj",
			"riko, the paragon",
			"the sun also rises",
			"pillar of flame",
			"aelinn, serpent's voice",
			"heart's desire",
			"siraj, interplanar thief",
			"the warrior within",
			"abandoned wilderness",
			"otherworldly forest",
			"greypelt brute",
			"nip at the heel",
			"sphinx of ill omens",
			"curator of cures",
			"prismatic champion",
			"saishuteki castle",
			"woven network",
			"bahet's emissary",
			"phantasmal stalker",
			"sand scorpion",
			"contagious deathspore",
			"untested initiates",
			"winter's whelp",
			"slayer of the famed",
			"fourth eye assassin",
			"ingredient scroungers",
			"shedding of the coils",
			"kurayami shrine",
			"depthlight salvager",
			"thornweald archer",
			"avoid fate",
			"hollow wanderer",
			"fretport mob",
			"precursor filtercruiser",
			"seek the maker's egg",
			"nimbus glider",
			"kotis, promised general",
			"burning heels",
			"hunting experience",
			"warden of the dead",
			"shionoshio, ocean's vow",
			"rod of marble row",
			"hanabira, kogane's legacy",
			"runeclad seeker",
			"roggar's frenzy",
			"union rail strikebreaker",
			"veteran lifeforger",
			"self replication",
			"landbound connoisseur",
			"scuripi lookout",
			"cane dancer",
			"resplendent substratum",
			"sedate tundra",
			"mysterious cataract",
			"children of the clouds",
			"bind in jade",
			"stormsurge",
			"sunken ambitions",
			"kimar, lightforger",
			"resounding relief",
			"aerie's pillar",
			"pith wilt",
			"departed evangel",
			"harm's way",
			"azun, sheriff of daisite",
			"thailen, heir to daeland",
			"nadei the wavecaller",
			"overwhelming armies",
			"fleeting discoveries",
			"reyhsia, truth chaser",
			"kai'dwo, eternal ravager",
			"reflected worldwalker",
			"tidehollow lich",
			"vaultkeeper",
			"impden mother",
			"cradle of corruption",
			"what lurks beyond",
			"wild dogs of the night",
			"jade vault reclaimer",
			"tara, duneblessed",
			"shugenja sanctuary",
			"mana confluence",
]

		names
			.map{|n| db.cards[n]}
			.flat_map{|card| card ? card.printings : []}
			.to_set
	end

	def to_s
		"is:playable"
	end
end
