class ConditionIsStaple < Condition
    def search(db)
        names = [
            "wayfarer's shrine",
            "cursory glance",
            "nereba, sandchoked archives",
            "seal the tomb",
            "murmuring falls",
            "duress",
            "pith wilt",
            "intrepid",
            "memento mori",
            "flooded depths",
            "shifting glade",
            "nomad's township",
            "stand unassailable",
            "exeunt",
            "negate",
            "crystal cavern",
            "cold grave",
            "grim bastion",
            "magmatic torrent",
            "mysterious cataract",
            "vibrant rapture",
            "flooded morass",
            "xanigan, the darkened cloud",
            "mana ascetic",
            "abscond",
            "prying inquiry",
            "nebula of empty gold",
            "lush oasis",
            "fungal mire",
            "ocean monastery",
            "roggar's frenzy",
            "arctic mine",
            "soul gate",
            "descend on the helpless",
            "forgotten steppe",
            "dark bargain",
            "seek prophecy",
            "frostfire geysers",
            "shal'draen's rage",
            "sedate tundra",
            "resplendent substratum",
            "snowfield mother",
            "union rail strikebreaker",
            "tenacious guide",
            "voidflare",
            "unbreachable walls",
            "villainy",
            "temporary treason",
            "murky peat",
            "kyne's devoted",
            "crumbling precipice",
            "barren desolation",
            "singularity's grasp",
            "endless discoveries",
            "recall forgotten eons",
            "sandscatter",
            "timber range",
            "violent collapse",
            "rampant summit",
            "gleaming river",
            "scorch",
            "antithesis",
            "pool of light",
            "lavatorn fields",
            "out-of-body experience",
            "spiraling canyon",
            "leyran alpha",
            "thought blossom",
            "monument of queens",
            "destructive ambition",
            "portal fracture",
            "ancestral council",
            "crystal wave",
            "stolen secrets",
            "explorer's fate",
            "still the pandemonium",
            "invalidate",
            "archive guardian",
            "honorless offering",
            "find happiness in misery",
            "journey's end",
            "lucien, the grifter",
            "nature's claim",
            "unending sands",
            "tsang jin, master of the jade sea",
            "gloomcover steppe",
            "oracle's vision",
            "cane dancer",
            "conjure realities",
            "soul leak",
            "unceasing flames",
            "arcane genesis",
            "titan snare",
            "heart of zhedina",
            "flesh to rot",
            "aerie's pillar",
            "deem unworthy",
            "stormsurge",
            "veilborn meddler",
            "vast savannah",
            "sea cache",
            "dovah's ire",
            "sea of skies beyond",
            "remorse",
            "mabil fardancer",
            "unraveling",
            "children of the clouds",
            "flourishing crevasse",
            "sevid, the lookout",
            "brine fleet bay",
            "mountain spring",
            "tropical grove",
            "no rest",
            "aiel tazan",
            "dovon, verdant experimenter",
            "precursor sanctum",
            "self replication",
            "lumenbay flyer line",
            "weathered oasis",
            "jade vault reclaimer",
            "siesa tremund",
            "prodigious panya",
            "nightwatch rallier",
            "veteran lifeforger",
            "sparking automaton",
            "dispel",
            "the moon rises",
            "cradle of corruption",
            "helene trant",
            "monument to the fallen man",
            "crossing the fog",
            "heist headquarters",
            "scion of desolation",
            "chi lee of the underworld",
            "mirrorgate",
            "sunwashed spires",
            "whisperwood exploration",
            "scion of flourishing",
            "paragon of honor",
            "shikai's redoubt",
            "wicked weaving",
            "ignition ritual",
            "iviana, speaker of fangs",
            "antimagic",
            "stormshaper adept",
            "nocturnal's informant",
            "once scarred",
            "champion of the fae",
            "hexfang ascetic",
            "dockyard swindling",
            "replicator mage",
            "sporeflow protector",
            "neutralize",
            "logger recluse",
            "possibility engine",
            "frailty",
            "ethereal armor",
            "corpsebed",
            "northern holdout",
            "suzume oshiruko",
            "stormchaser mage",
            "masahita, bloodtongue",
            "croakfolk troubadour",
            "what lurks beyond",
            "rakkiri dissident",
            "aguri, shadow of doubt",
            "kellythross' workshop",
            "ornate interior",
            "barren boneyard",
            "lumbering hillock",
            "zhedina envoys",
            "cyone, expedition captain",
            "mindstorm's eye",
            "beckon of the wild",
            "by the sea",
            "worlds colliding",
            "golden glade",
            "ravaged monument",
            "anuran encounters",
            "demolitionist deviser",
            "irika, wielder of secrets",
            "shinrin spellhunter",
            "holy war",
            "bahum, the warden",
            "rock",
            "unjust sentence",
            "untethered disciple",
            "between life and death",
        names
            .map{|n| db.cards[n]}
            .flat_map{|card| card ? card.printings : []}
            .to_set
    end

    def to_s
        "is:staple"
    end
end