class ConditionIsPlayed < Condition
	def search(db)
		names = [
			"mountain",
			"swamp",
			"island",
			"wayfarer's shrine",
			"plains",
			"mirrorgate",
			"metal munch",
			"scorch",
			"nebula of empty gold",
			"forest",
			"seal the tomb",
			"crystal cavern",
			"valdez, leafdown vagabond",
			"spell pierce",
			"shikai's redoubt",
			"cosmic sinkhole",
			"crumbling precipice",
			"nomad's township",
			"duress",
			"shardstone rift",
			"magmatic torrent",
			"pay up",
			"murmuring falls",
			"grim bastion",
			"pith wilt",
			"flooded depths",
			"barren desolation",
			"shifting glade",
			"imperial siege",
			"stand unassailable",
			"frostfire geysers",
			"sear flesh",
			"mysterious cataract",
			"blood jade prophet",
			"polyp pools",
			"rampant summit",
			"voidflare",
			"sealed riftway",
			"rift splicing",
			"shi hou's command",
			"the flames approach",
			"monument of queens",
			"sedate tundra",
			"lavatorn fields",
			"forgotten steppe",
			"corpsebed",
			"flooded morass",
			"lush oasis",
			"timber range",
			"arctic mine",
			"portal fracture",
			"ragavan, most wanted",
			"ocean monastery",
			"unrivaled fireweaver",
			"solar flare",
			"firehearth halls",
			"profane emissary",
			"forbidden treasure",
			"shan jun's command",
			"veindrinker's cabalist",
			"long forgotten",
			"out-of-body experience",
			"fungal mire",
			"prying inquiry",
			"exeunt",
			"sunlit highland",
			"enopraxia's endeavor",
			"resplendent substratum",
			"lumbering hillock",
			"dark bargain",
			"secrets of coralight court",
			"chronicles of the kitsune",
			"olten surveyor",
			"gloomcover steppe",
			"admonish",
			"niu mo wang, ashen absolution",
			"wave of decay",
			"conquer psyche",
			"pool of light",
			"sacrificial bull",
			"sesilius of wicked ways",
			"kai'zhou, the purifier",
			"lt. daisy saxon",
			"relic corrosion",
			"oracle's vision",
			"recall forgotten eons",
			"shal'draen's rage",
			"rapacious rattler",
			"still the pandemonium",
			"rakkiri dissident",
			"ready for anything",
			"exhilarating prescience",
			"swarming midden",
			"monkeyshines",
			"unstoppable slaughter",
			"cursory glance",
			"violent collapse",
			"cane dancer",
			"prodigious panya",
			"valeri kripac",
			"journey's end",
			"anointed cursebreaker",
			"unjust sentence",
			"alratha, pearl of the sand sea",
			"anzen, beyond the sea",
			"flourishing crevasse",
			"renewal grove",
			"crest",
			"roggar's frenzy",
			"leafdown sizzlemage",
			"lost through dreams",
			"mattia, hero of tinyvale",
			"unburdened rage",
			"forbidden palace",
			"ominous palace",
			"jejun, dark hunter",
			"emissary of antiquity",
			"invalidate",
			"forked pillar",
			"tunu, ancient shaper",
			"civilization's cost",
			"banished companion",
			"ramzi, traveling merchant",
			"heart of the glade",
			"embodied soul",
			"ruin delver",
			"qi-long gust",
			"tal, locus sentry",
			"ignition ritual",
			"singularity's grasp",
			"basat charm",
			"enter mephisto's gate",
			"beat & batter",
			"seek prophecy",
			"terraformer's globe",
			"stormsurge",
			"amber hills",
			"conspiracy of ravens",
			"lumenbay flyer line",
			"ominous discovery",
			"commanding princess",
			"auros, the red king",
			"xifang hu, light within",
			"mana ascetic",
			"strike from the shadows",
			"guiding light",
			"celestial banishment",
			"whisperwoods exploration",
			"tyrant of tributes",
			"aerie's pillar",
			"villainy",
			"unceasing flames",
			"northern express line",
			"new divide",
			"flamecaller's command",
			"caylin whirlwind",
			"intrepid",
			"babyscale bruiser",
			"wheat from chaff",
			"bessie's brood",
			"event horizon",
			"dovon, verdant experimenter",
			"tiny heroine totti",
			"holdsteady engine",
			"cinderhoof minotaur",
			"imperial claim",
			"ostracizer orb",
			"primal resurgence",
			"expose",
			"leyran alpha",
			"unearth",
			"rot",
			"gift of the phoenix",
			"lay bare ambitions",
			"sigil of radiance",
			"fogspewer",
			"memento mori",
			"oozing yaoguai",
			"oriq soulweaver",
			"justiciar overseer",
			"serene chapel",
			"mystery of the crashed craft",
			"forsaken palace",
			"roggar's gambit",
			"extraction mercenary",
			"lotus barrens",
			"here with you",
			"fiery erasure",
			"kai'oro, grave betrayer",
			"thought blossom",
			"heart of zhedina",
			"miserable discovery",
			"self replication",
			"infectious ego",
			"inishtu, desert healer",
			"rushwater raider",
			"qi block",
			"kinken, the dragon's breath",
			"veilborn meddler",
			"jade vault reclaimer",
			"channeler of the veil",
			"hierarch ranger",
			"neutralize",
			"petal scatterer",
			"herald of oblivion",
			"reveal eternities",
			"chi lee of the underworld",
			"thunder road",
			"esalia, steward of caer crann",
			"azos, tyrant of bleakrealm",
			"montane palace",
			"unraveling",
			"deform sanity",
			"tyrant's breath",
			"beneath the zhedina",
			"distant thunder",
			"subdue false idols",
			"brazen sacrilege",
			"powder scatterer",
			"tahli's council",
			"witch of spring's promise",
			"hungering cult",
			"hemley eggfeather",
			"lisa, the daughter",
			"retire",
			"careless violence",
			"unexplored regions",
			"calamitous crash",
			"opalescent palace",
			"envoy of divine progress",
			"channeling stone",
			"suitor of the sea",
			"tsang jin, master of the jade sea",
			"unhappy ending",
			"seeker of untouched beauty",
			"become immersed",
			"eminent palace",
			"tanya, leader of the pack",
			"eidolic palace",
			"endless helpless souls",
			"el, humble apprentice",
			"descend on the helpless",
			"reclamation grovesculptor",
			"devised companions",
			"calciform wastes",
			"abscond",
			"agent of deception",
			"sultan of avarice",
			"lord of the bubbledome",
			"qililia's scavenger",
			"dancer of the great current",
			"olantin pearlreader",
			"wave racer",
			"cosmic coalescing",
			"scrap metal",
			"sunken ambitions",
			"timeworn crags",
			"master negotiator",
			"theocracy",
			"arpechian champion",
			"children of the clouds",
			"confining priest",
			"radiant palace",
			"stormshaper adept",
			"left on the wayside",
			"rod of marble row",
			"bloodriver",
			"fulmen, aether prodigy",
			"in dire straits",
			"traitor's execution",
			"charming marauder",
			"rawthlin market line",
			"miss margaret barton",
			"irbek, crocodile hunter",
			"rousing rubble",
			"seto san, the dragonblade",
			"setting sun",
			"korrinary warcaller",
			"disciple of faradia",
			"bonetooth darter",
			"helena, the awakener",
			"legion angel",
			"no good deed goes unpunished",
			"celestial mandate",
			"cresting bay",
			"sights beyond",
			"blossoming expanse",
			"small luxuries",
			"ancestral council",
			"aiel tazan",
			"arrive, surrounded by petals",
			"selective breeding",
			"seismic colossus",
			"starlit raze",
			"brutalize",
			"soul warden",
			"weeping lotus",
			"canyon creek",
			"mortal benediction",
			"brutal blow",
			"mable of the sea's whimsy",
			"helene, bound by might",
			"spirit script",
			"inked summoner",
			"jara champion",
			"convert to resources",
			"nacatl skirmisher",
			"engrave",
			"zaukar of the ancient ways",
			"buy time",
			"bustling marketplace",
			"henros, royal herald",
			"creative salvage",
			"wayfarer's lantern",
			"crumbling shrine",
			"twisted masterwork",
			"end of all things",
			"curse of encroaching waters",
			"sofia, fortune's fated",
			"stalwart dominion",
			"invoking the name",
			"nature's claim",
			"lucien, the grifter",
			"nihilistic shock trooper",
			"mindrip",
			"stolen secrets",
			"call of the huma",
			"salome",
			"a most important prince",
			"antithesis",
			"bloodstained calamity",
			"soul pierce",
			"den of vice",
			"crewmaster gillo",
			"ajani enlightened",
			"whiterun ordainer",
			"danithra muckbruiser",
			"tenuous existence",
			"bleak dominion",
			"serene palace",
			"antimagic",
			"thrasios's endeavor",
			"pestilent scavenger",
			"performer of ambition",
			"somber river bearer",
			"volatile stonework",
			"monument to the fallen man",
			"answer midnight's call",
			"curse of bleeding",
			"vaultkeeper",
			"operation 433",
			"cognitive fumigator",
			"find nothing",
			"fungal swathe",
			"jerrold, fugitive",
			"destructive ambition",
			"a rush of stillness in the air",
			"prove worthy",
			"archaeological experience",
			"ferocious flame",
			"ayala's concord",
			"boxue and ma'long",
			"ameret, hope of night",
			"diffuse",
			"gate of realms",
			"wiretapper",
			"last request",
			"through the ashen gate",
			"greenwood outrider",
			"graide, voice of autumn",
			"parish paragon",
			"reduce to naught",
			"selvar's defiance",
			"soul's attendant",
			"vivid march",
			"sea cache",
			"reminiscence",
			"hegemony monarch",
			"fractured reach",
			"oracle's ploy",
			"seaside grotto",
			"the afterlife takes its due",
			"mina, jeweled minnow",
			"elaborate transportation",
			"ashe of the winged steed",
			"through the divine gate",
			"ominous dragoncaller",
			"kalemn weller",
			"petal-weaver alexa",
			"breach the lilies",
			"mosecf, the sunseeker's path",
			"sunrise river",
			"shifty fink",
			"union rail strikebreaker",
			"unstill unlife",
			"intisuyu's masterpiece",
			"end of the rainbow",
			"illuminated firebird",
			"ria-demian charm",
			"condor clearings",
			"refraction diver",
			"fireshaper adept",
			"unassuming swineherd",
			"hsu fu, architect of sunrise",
			"vielle, undercity wayfarer",
			"paint with starflame",
			"dragon's eye descendant",
			"what lurks beyond",
			"a planet far, far away",
			"enraptured countess",
			"judge's decree",
			"ancient dominion",
			"chigau, the red market",
			"citadel gates",
			"seedshrine",
			"delve for treasures",
			"banishing initiate",
			"beckon of the wild",
			"tendrilsnare",
			"ghulish unearthing",
			"prince of stars",
			"aiko, tranquil fury",
			"leyline invoker",
			"darksand acolyte",
			"thin the veil",
			"minotaur skullsmasher",
			"shi hou, the sun king",
			"warhound shuja",
			"flaming point technique",
			"steward of empire's cradle",
			"anax's endeavor",
			"mpumo, who stands alone",
			"cranial violation",
			"gleaming river",
			"jak, daring vanguard",
			"shifting cascade",
			"sigil of the many",
			"pineblight caribou",
			"void portal",
			"bant command",
			"clockwork gaucho",
			"earthbreaker behemoth",
			"power plant",
			"zhelid, planar academy",
			"plasma enforcer",
			"spilling secrets",
			"masahita, bloodtongue",
			"tidehollow lich",
			"observer of aeons",
			"cumulus horizon",
			"pristine dominion",
			"hidden garden entrance",
			"ambition's crown",
			"disassociate",
			"dustridden sepulcher",
			"clean-up crew",
			"just business",
			"yri, the daring blade",
			"overgrowth guardian",
			"pensive songwriter",
			"the past is gone",
			"fardancer liege",
			"thassa, the implacable tide",
			"daisy, the heart of chasmek",
			"glymna blackrune",
			"crowded tavern",
			"imperial achievement",
			"caulte axeslinger",
			"xira, scatterer of seeds",
			"silent wanderer",
			"faradia's anointed",
			"plasma addict",
			"fierce combatant",
			"sink into the floor",
			"learn through error",
			"mourn no more",
			"antali archdruid",
			"bind the mind",
			"vir of the starskipper",
			"onya the gilded",
			"martial maestro",
			"black hole musings",
			"tidal spite",
			"helene, steel of the exiled",
			"dragon's breath throatsinger",
			"operative sporty",
			"keeper of the sanctum",
			"promethean grotto",
			"cai lan, the puppeteer",
			"lord rokai",
			"silent hypnotist",
			"scuttling gnat",
			"little pig",
			"scion of silence",
			"taranika's endeavor",
			"surge of darkness",
			"emperor's retainer",
			"fleeting moments",
			"forbidden shiangshi arts",
			"soaring canyon",
			"ruined precipice",
			"meteor volley",
			"crystal wave",
			"precursor sanctum",
			"bahum, the warden",
			"isolated",
			"inexorable epidemic",
			"warden of silence",
			"mark of dark opulence",
			"aguri, shadow of doubt",
			"verdant dominion",
			"sporeflow protector",
			"mei's collection",
			"castigated sister",
			"ring of souls",
			"aethermancer's familiar",
			"concordant palace",
			"bitter duckling",
			"mei liva, the broken",
			"angelic barracks",
			"archivist's torment",
			"naogui the lotus-charmed",
			"plaxolotl pyari",
			"thriving budling",
			"nyxfall",
			"barx, interplanar mastermind",
			"brimstone oration",
			"lady genvieve of caulder",
			"dark behemoth",
			"godwatcher",
			"getaway rider",
			"warfield excavator",
			"rocket admin",
			"dreams come true",
			"encylopetia",
			"goblin chariot",
			"eldritch egg",
			"insipid metamorph",
			"ever-gnawing rat",
			"wildbond aspirant",
			"halcyon daze",
			"sunset monastery",
			"twilight blade",
			"fleeting resonance",
			"paul, rock bottom",
			"legitimate establishment",
			"sunflower fields",
			"witch-queen yarag",
			"provoke the gods",
			"posey, of the seal cloak",
			"pupil of lightning",
			"sukhar, consort to the dark",
			"blessed spellroot",
			"collect rotting remains",
			"powercell cultivator",
			"supernova",
			"underpass sentinel",
			"shimmering dragon",
			"miyoga firebird",
			"moonlight sanctum",
			"kaur, end of lies",
			"crystal grotto",
			"against the waves",
			"leija's greenblade",
			"vaeldan's liberator",
			"rippling curtain",
			"chikami castle",
			"deadly harpoon",
			"death pits trophy",
			"jerrold's wretched cure",
			"crimson curtain favored",
			"tsolmon, the huntress",
			"archaezus, dark salvation",
			"compelling pariah",
			"hoarding crab",
			"from the forest's heart",
			"down with the ship",
			"xiyue dragondancer",
			"rahit, arcane tutor",
			"forest fellowship",
			"many-voiced tower",
			"sunrise bluffs",
			"crossing the fog",
			"tegan, the sparrowhawk",
			"ema, the traveler",
			"lone survivor",
			"protective memory",
			"bizarre dreams",
			"i-6 dragoon",
			"tranquil moment",
			"prismatic cavern",
			"henry, river cities mayor",
			"velir the sunderer",
			"lord ellison crain",
			"temporal resuscitation",
			"ma'long, the skystorm",
			"meteor harbinger",
			"culminating chaos",
			"dawson's collector",
			"aukan, swift hawk",
			"pathless shallows",
			"soliloquy",
			"dayang's displeasure",
			"artificer's persuasion",
			"unbound expanse",
			"mennin pack",
			"follow the light",
			"slippery bunyip",
			"sharuum, archmagocrat",
			"rei's reinforcements",
			"fluffpuff whisperer",
			"critters' companion",
			"impden mother",
			"the lost titan",
			"operative baby",
			"paw valley alpha",
			"banish the intruders",
			"iroshi, blade of the old ways",
			"kanaan wardriver",
			"twin lis of the divine realm",
			"relonche cavalry",
			"kan, triumvirate tactician",
			"hunter's mark",
			"curse of grasping air",
			"overactive imagination",
			"tea of augury",
			"primal dominion",
			"mausoleum resident",
			"dawn hill forgemaster",
			"keeper of secret havens",
			"vorreia's farsight",
			"megalokraken",
			"stalked healer",
			"margyd's celebrant",
			"hope spot",
			"muktann protectors",
			"petal blade",
			"fox of the mushroom forest",
			"crystalcatcher",
			"losing my religion",
			"shared reminiscence",
			"fulfill twisted dreams",
			"last stop",
			"osk, the maker's pet",
			"peer into the cosmos",
			"salome breaks the lies",
			"call the backup actors",
			"tabia of the lionheart",
			"blank pages",
			"procedural genesis",
			"astral cerberus",
			"festival sabotage",
			"capture brilliance",
			"soul gate",
			"barbed reef",
			"transplanted citadel",
			"milunda, prairie prince",
			"aether road caravan",
			"reckless impulse",
			"solar hatching",
			"plasma blader",
			"bal's descent",
			"voidbringer",
			"hoof cliff horngrove",
			"ophidian oracle",
			"blood tide",
			"eye of the beholder",
			"dedicated bushwacker",
			"queen andarli, the fierce",
			"farseek",
			"malefic portal",
			"cradle of civilization",
			"rain of ruin",
			"unlit alley",
			"helena's rebuff",
			"calamity rose",
			"one",
			"master of masks",
			"devoted artistry",
			"adiran scryers",
			"finish off",
			"master of munitions",
			"hazy moorland",
			"sphinx of ill omens",
			"azun, sheriff of daisite",
			"bearer of the lantern",
			"duchess odelia vii",
			"astrid, disgruntled princess",
			"primal ruffian",
			"brushcover elf",
			"duskwood revolutionary",
			"mutilated warrior",
			"rule the world",
			"iron warden",
			"assessment of virtue",
			"backburner",
			"shifting grove",
			"turi of hollow depths",
			"fiery truthseeker",
			"chikyu champion",
			"tempered ankulim",
			"kellythross' workshop",
			"howling shieldbreaker",
			"snow drift",
			"ivenge's evangel",
			"pristine chapel",
			"the investigation of dr. vaughn",
			"ardy, youthful geomancer",
			"green elemental circle",
			"stolen cache",
			"hermetic meditation",
			"ritual of soot",
			"waking pollution",
			"demolitionist deviser",
			"fireheart channeler",
			"ravenous extra",
			"pakka, the shadowcloak",
			"shadowed slums",
			"facsimile of divinity",
			"experiment zero",
			"feathersword duelist",
			"desolate dominion",
			"distilled inspiration",
			"find greater purpose",
			"intrepid captain",
			"byron's gambit",
			"binding stones",
			"eternal deliverance",
			"elder prophesier",
			"lost knowledge",
			"by the sea",
			"calming dromoryx",
			"mieng, who dances with dragons",
			"astralhorn familiar",
			"vassal of the wild",
			"paygan archer",
			"clock of seasons",
			"crater burst",
			"neural contagion",
			"futuretheft",
			"redo",
			"dragoncalling",
			"thallid cultivator",
			"isochron wand",
			"impromptu escapade",
			"healing center",
			"protect the farm",
			"dispel",
			"dredgeline colossus",
			"thunder wave",
			"ignition engine",
			"privilege's sway",
			"grixis command",
			"sweet nothings",
			"space oddity",
			"true-form revelation",
			"gilded gulch",
			"blind blackguard",
			"eminent extraction engine",
			"strongarm",
			"flotsam",
			"scathing review",
			"cloudsteel summit",
			"gateblessed explorer",
			"speed of darkness",
			"whatever it takes",
			"sacred songs",
			"phantasmal owl",
			"karaja hetegex",
			"social graces",
			"grove's respite",
			"damning flames",
			"shatter facade",
			"tranquil repose",
			"derelict town",
			"the aurora's heart",
			"kantra of bounty",
			"chratteri restoration",
			"ancient ossuary",
			"rain zai, spiritscale",
			"dead man's party",
			"sealed evil in a cage",
			"fallacy's sanctifier",
			"shuilong technique",
			"unwrite",
			"ephara's watcher",
			"scarlet mist",
			"esmerie, skysworn general",
			"biocultivator",
			"dustchoked outpost",
			"crossroads harrier",
			"seabreen nullmage",
			"counting clouds",
			"dawnwisp vents",
			"imagine",
			"imposition",
			"fey grove",
			"bogsworn club",
			"phalanx beetle",
			"sword",
			"wise old oak",
			"amelie mayn",
			"into the woods",
			"tt-20 salvation",
			"lightblessed claymore",
			"take a walk",
			"archive guardian",
			"calcified dunes",
			"shawlbinder",
			"temporal insight",
			"caravan guard",
			"leafdown glimmerfox",
			"corecharge",
			"marin polgek, academy heiress",
			"price of memories",
			"as a matter of course",
			"xiong mao, the intrepid",
			"ghostspore mire",
			"summit guardian",
			"a sucker for you",
			"phoberos ragehorn",
			"seek the maker's egg",
			"hidden hollow",
			"kati evalin, world wanderer",
			"tropical grove",
			"shining crusader",
			"doom",
			"conjured acropolis",
			"merrow legendmaker",
			"iekin's portal",
			"aurora hydra",
			"pallid herald",
			"light within shadow",
			"reyhsia, the honorless",
			"foulweather effigy",
			"power jam",
			"corrupted memory",
			"roots from ruin",
			"bahum, penitent",
			"golden company tactics",
			"bogborn exorcist",
			"eryth, mire dredger",
			"mieng of the pyre waltz",
			"mia, into the unknown",
			"sakaki, rocket gang boss",
			"cave of pleonexia",
			"hookhand freebooter",
			"olson's flockmaster",
			"heists most daring",
			"confident amateur",
			"gathering the gang",
			"sunlit meadow",
			"rainbow phoenix",
			"abundant harvest",
			"test of forsaking",
			"shionoshio, ocean's vow",
			"irika, wielder of secrets",
			"light the fuse",
			"victory over phyrexia",
			"prismatic panes",
			"vanish",
			"rethia cultivator",
			"far wandering guardian",
			"art of evasion",
			"martoob beastkeeper",
			"seeker of mysteries",
			"illusionary steed",
			"relic heist",
			"swarm of the dispossessed",
			"lofty denial",
			"vedalken reshaper",
			"once scarred",
			"whimwing",
			"luminescent feathrets",
			"debaser of truth",
			"operative ginger",
			"salome's messenger",
			"aquilifer axelius",
			"secret-hoarder",
			"faerie infiltration",
			"griffin country",
			"vicious slasher",
			"essential override",
			"brightflame phoenix",
			"sturdy outpost",
			"improbable aim",
			"bright future",
			"yujei, crane companion",
			"abandoned monument",
			"ancient counsel",
			"pretty savage",
			"treasure beach",
			"boiling ridge",
			"essence erasure",
			"giradrus, ashen master",
			"calamari dragon",
			"circling predators",
			"elmare's grandeur",
			"chaos is your redemption",
			"willow spirit",
			"avatar of basat",
			"gale conjurant",
			"the pyleas, siona's pride",
			"edge of the water",
			"day of the emperor",
			"scramble the scouts",
			"mark of the scaleblight",
			"vantage point",
			"speak no evil",
			"speaker of the iris",
			"studies past",
			"dawn silhouette",
			"speaker of deliverance",
			"blood frenzy",
			"polytheism",
			"flourishing dunes",
			"sundappled scrub",
			"bind the great evil",
			"reclamation sage",
			"ruined shrine",
			"bahum's penance",
			"release from death",
			"gate to the beyond",
			"boneyard pass",
			"staff of equilibrium",
			"death in reverse",
			"warbringer titan",
			"mechanomind researcher",
			"animus seer",
			"twelve thousand eyes",
			"wastes scrambler",
			"veteran lifeforger",
			"lady heiffyd",
			"heddwyn, the law",
			"aerida, envious chronomancer",
			"barten's journal",
			"damian, the boss",
			"nel toth shaman",
			"rustshell crustacean",
			"serene prayer",
			"tear loose",
			"limb extension and generation system",
			"biohazard",
			"armament upgrade",
			"consuming symbiosis",
			"priestess of simplicity",
			"crypt tutor",
			"bioluminescent display",
			"repurposed killdrone",
			"eternal wanderings",
			"holding out for a hero",
			"nidohagane warfans",
			"shrouded sanctuary",
			"blundering clocktower",
			"shizen, the thousand steps",
			"fiery temper",
			"coralight paladin",
			"spectral chains",
]

		names
			.map{|n| db.cards[n]}
			.flat_map{|card| card ? card.printings : []}
			.to_set
	end

	def to_s
		'is:played'
	end
end