class ConditionIsAshe < Condition
	def search(db)
		names = [
			"bretala of redsky",
			"dragoncalling",
			"lady ashtongue",
			"warrior's request",
			"brass dragon",
			"crimson hellmaw",
			"hao'tai, the ancient one",
			"mieng, who dances with dragons",
			"peakblazer dragon",
			"tseng, warden of the peak",
			"xiusheng of the dragon realm",
			"miyoga dragonsoul",
			"newborn dragon",
			"raidragos' avenger",
			"wingless dragon",
			"reckoner of man",
			"shimmering dragon",
			"ferocious desert-hunter",
			"sandmouth dragon",
			"whistled dragons",
			"dragonfire fury",
			"doombringer dragon",
			"dragon initiate",
			"dynamic wyvern",
			"fang, the lavaclasm",
			"cataclysmic skytyrant",
			"loot hoarder dragon",
			"vestige of skithiryx",
			"ryukami, the first sovereign",
			"sovereign of old jidai",
			"scourge of the skies",
			"searshot dragon",
			"dragonmaw wurm",
			"dragonsoul disciple",
			"scales of seishin",
			"scaletongue mistress",
			"dragon queen's disciple",
			"syrina, the dragon queen",
			"syrina's brood",
			"warfury dragon",
			"twinfire dragon",
			"dragongate",
			"emissary of antiquity",
			"rubble scavenger",
			"trove tyrant",
			"rimebreath tyrant",
			"vindictive regent",
			"ontarachie apex",
			"champion of scales",
			"dreadfire tyrant",
			"rhyolithic hellkite",
			"calamity dragon",
			"novaheart dragon",
			"frostbreath dragon",
			"kaor awoken",
			"molten incubation",
			"skyscreecher dragon",
			"starborne hellkite",
			"hellkite omnivore",
			"jund command",
			"kaalia, sky's end",
			"kaalia's abomination",
			"sangrite dragon",
			"scorchpass sovereign",
			"tharrsus, tyrant's scion",
			"scavenging hilakites",
			"chikyu champion",
			"sunset herald",
			"tyrant of tributes",
			"adoroth, the baneful",
			"giradrus, ashen master",
			"harbinger of giradrus",
			"pyre apostle",
			"the winged steed",
			"anemothrys, reefcrown",
			"calamari dragon",
			"gold retriever",
			"molting linnorm",
			"nidhir, the one beyond",
			"raid the dragon's lair",
			"volcano tyrant",
			"herald of flame",
			"hadak, end of progress",
			"zenith of greed",
			"scrapyard sovereign",
			"iviana, speaker of fangs",
			"synchronous hellkite",
			"horizon sovereign",
			"dragonglass harp",
			"dragon's breath throatsinger",
			"ashe of thewinged steed",
			"vidal's conjurant",
			"bleakrealm mini-menace",
			"seven seas scourge",
			"azos, tyrant of bleakrealm",
			"shoal dragon",
]

		names
			.map{|n| db.cards[n]}
			.flat_map{|card| card ? card.printings : []}
			.to_set
	end

	def to_s
		"ashe"
	end
end