class ConditionTinbeard < Condition
	def search(db)
		names = [
			"academic's claymore",
			"calamitous crash",
			"crystal garden",
			"curse-blood morrigan",
			"daring skythief",
			"epic score",
			"hunter's hideout",
			"leyline alignment field",
			"lost to the ages",
			"mirrorgate",
			"overloaded aethergate",
			"the aether lens",
			"the knowledge hub",
			"titan's palace",
			"voidlife orbs",
			"atemporal blade",
			"batrest, fellor leader",
			"bone saw",
			"cannon fodder",
			"chronomancer's bauble",
			"collapsing ground",
			"cranial archive",
			"fellor ironborn",
			"feral cleaver",
			"flamewaker's staff",
			"forest",
			"imminent collision",
			"island",
			"lodestone colossus",
			"massive waraxe",
			"mountain",
			"offer to nature",
			"plains",
			"purifying light",
			"rallying banner",
			"ripping wilds",
			"ruin salvager",
			"savrios' masterpiece",
			"sentinel's longbow",
			"shrapnelcrafter",
			"sigil of destruction",
			"sigil of duty",
			"sigil of savagery",
			"soulstone shard",
			"stonework vigilante",
			"swamp",
			"the high prairies",
			"tinkerer's tools",
			"unstable footing",
			"wanderer's talisman",
			"warmonger contraption",
			"weaponize",
			"wings of the arcanomancer",
			"abandoned sanctuary",
			"admirer of the lost",
			"albino drake",
			"assassin's shuriken",
			"brass dragon",
			"breath of fresh air",
			"caress the fleets",
			"dancing blades",
			"demystifying tide",
			"desecrate antiquities",
			"draconic bulwark",
			"endangered rhino",
			"entangled roots",
			"fei'xing the marvelous",
			"fell the beast",
			"general of the folded fan",
			"inspiring effigy",
			"inundated sanctuary",
			"kou, primal shepherd",
			"magnificent liturgy",
			"obscure apostle",
			"pious flutist",
			"reverent flame",
			"ruinous glutton",
			"sacred sanctuary",
			"savage sanctuary",
			"spire sanctuary",
			"statuary forge",
			"the first idol",
			"trophy collector",
			"tyrannic judgment",
			"unyielding presence",
			"vial of dragonfire",
			"way of kindred mind",
			"wicked rites",
			"wretched sanctuary",
			"wun su, guru of the staff",
			"aghavaan's corrupter",
			"aghavaan's wound",
			"ancient ossuary",
			"asharo's yoroi",
			"celestial o-yoroi",
			"clutch of the coil",
			"cursed scroll",
			"dragon's wake",
			"dragonwall fragment",
			"festival of roaring dragons",
			"giku weaponsmith",
			"heavenly temple",
			"imperial ricefields",
			"kenshiro's yoroi",
			"kiyomi's yoroi",
			"kogane's yoroi",
			"kowareta scrounger",
			"palace of heavenly sovereigns",
			"raiun bay junk",
			"sage's ashes",
			"shigure's yoroi",
			"shugenja sanctuary",
			"stonesculpting",
			"sunrise orchard",
			"wayfarer's shrine",
			"yamisaran guard",
			"adaptive terrains",
			"ankryss' staff",
			"artificer's workshop",
			"berserker's axe",
			"bloodstained knife",
			"cartographer's chart",
			"crafted wings",
			"crafter's mistake",
			"disassemble",
			"flooded morass",
			"flourishing crevasse",
			"heart of the glade",
			"kragnoss' arsenal",
			"lavatorn fields",
			"logayr's tome",
			"mighty colossus",
			"monolith of ages",
			"monument of the masses",
			"moreena's banner",
			"natural growth",
			"pennon blade",
			"planar alignment",
			"pool of light",
			"reclamation sage",
			"sentient contraption",
			"sorcerer's staff",
			"springjack pasture",
			"stonework idol",
			"sword of the brave",
			"twinforged golem",
			"vythraktos' dagger",
			"war golem forge",
			"well of eternity",
			"abrupt volley",
			"amber hills",
			"boiling ridge",
			"duskwood thicket",
			"dusty record",
			"erudite's tome",
			"expendable contraption",
			"flooded depths",
			"grim bastion",
			"hazy moorland",
			"helm of the anointer",
			"inscrutable elixir",
			"magmatic torrent",
			"monument of war",
			"naturalize",
			"possibility grinder",
			"rugged fields",
			"saboteur's amulet",
			"sealed mausoleum",
			"sellsword contraption",
			"sentinel of latter days",
			"shifting frontiers",
			"sigil of brutality",
			"sigil of growth",
			"sigil of ingenuity",
			"sigil of malice",
			"sigil of unity",
			"sungrace meadows",
			"sunlit highland",
			"unknown shores",
			"veteran's plate",
			"wardbane mystic",
			"warrior's blade",
			"weapon smash",
			"altar of adversity",
			"altar of chaos",
			"altar of creation",
			"altar of destruction",
			"altar of devotion",
			"altar of order",
			"angel's codex",
			"angeltouched cavern",
			"angeltouched crag",
			"angeltouched garden",
			"angeltouched golem",
			"angeltouched marsh",
			"angeltouched saltflat",
			"avatar of being",
			"chemical grenade",
			"descended delta",
			"descended marsh",
			"descended meadow",
			"descended mortuary",
			"descended towers",
			"divining lens",
			"enforce the cycle",
			"helm of the devoted",
			"marzen's grimoire",
			"meditant's halo",
			"protector of the innocent",
			"saghira, divinity's usurper",
			"seraph's remnant",
			"shrine to the shrouded",
			"verdant trauma",
			"ahl's study",
			"ancient gleam",
			"bottled fate",
			"bygone blade",
			"carrionpult",
			"crafted behemoth",
			"crafted coast",
			"dire dive",
			"edge of the world",
			"ferrofy",
			"gleamhorn elk",
			"halls of renown",
			"haunted estate",
			"helm of the infinite",
			"lush outcrop",
			"mark of majesty",
			"might of the dylso",
			"prophecized plating",
			"prophetic blade",
			"reclaim relics",
			"seeker's garment",
			"seeker's guardian",
			"spired canopy",
			"stolen strain",
			"sword of memories",
			"the sun's last setting",
			"warrior's cloak",
			"bazaar guardian",
			"bronze giant",
			"cultist's dagger",
			"curious statue",
			"duela alchemist",
			"duela duelist",
			"duela science kit",
			"echoing sunder",
			"ensouler of blades",
			"excavation engine",
			"fine craftsmanship",
			"forging blade",
			"fortified flightsuit",
			"ghastly castle",
			"gleaming veldt",
			"grisly marsh",
			"melt down",
			"memory collector",
			"might of the oslyd",
			"mirage bracers",
			"reforged relic",
			"shard flower",
			"shard sword",
			"shimmersting",
			"sunken cavern",
			"sunny dunes",
			"tunnel map",
			"desert temple",
			"giant dromad",
			"rockpounding saurian",
			"staff of authority",
			"aetherforge",
			"alenian warhammer",
			"artian, phyrexian architect",
			"artificer's gift",
			"awaken to the skies",
			"bird call",
			"counteredge blade",
			"deathwind detonator",
			"deathwind expanse",
			"devastating impact",
			"ehsae, entelan skycraft",
			"elementalist's blade",
			"encrypted dagger",
			"forgemaster's altar",
			"frostborn skyrunner",
			"gryla canyon",
			"interan skycaster",
			"lightsteel enforcer",
			"lighttoxin arcrunner",
			"moonshadow abyss",
			"phyrexian arcforger",
			"phyrexian firemaster",
			"phyrexian snapjaw",
			"priest's altar",
			"relitian sentry",
			"reliya's construct",
			"steelcharm obliterator",
			"stormcaster's tower",
			"veteran lifeforger",
			"virtual terrain",
			"zephyrglider",
			"ancestral shrine",
			"aquatic refuge",
			"barreling chariot",
			"citadel of denial",
			"corpsekisser",
			"golden grizzly",
			"granite sibyl",
			"hayuan, the misjudged",
			"heping's armistice chains",
			"hypnotic halo",
			"illustrious lantern",
			"inciting blade",
			"ing'wei's crystal top",
			"kai'dwo, eternal ravager",
			"mausoleum rite",
			"monumental siege",
			"naiad of the glen",
			"no-man's land",
			"once more with style",
			"organic corrosion",
			"perimeter siege",
			"plagued skull",
			"prairie monastery",
			"scorched copse",
			"shara, the last leviathan",
			"sinister saber",
			"sunless ridge",
			"temple of brilliance",
			"temporary armory",
			"toxic spring",
			"vial of ice",
			"artificer's persuasion",
			"blow to pieces",
			"branding shackles",
			"centipede engine",
			"coalition relic",
			"contempt for the unnatural",
			"crystalline golem",
			"earthenlore disciple",
			"enduring vestige",
			"escape hatch",
			"fatresya's ankh",
			"fatresya's command",
			"foundryborn ingester",
			"frostfire geysers",
			"fungal mire",
			"gifted arcanomancer",
			"glitched carcass",
			"gloomcover steppe",
			"grafted physician",
			"grafted weaponry",
			"igniting lavaling",
			"infiltrate demmurya",
			"insidious terror",
			"insurgent's blade",
			"jeska, neolition leader",
			"kellythross, master artificer",
			"kellythross' workshop",
			"knowledge extractor",
			"loot hoarder dragon",
			"lush oasis",
			"mechanical masterpiece",
			"metalwork machinist",
			"meticulous dissector",
			"mindbreak artisan",
			"necrosavant's staff",
			"network sabotage",
			"non-stop production",
			"orrery technician",
			"phyrexian illbearer",
			"phyrexian scraphandler",
			"psychic grid",
			"reengineer",
			"scrapgear contraption",
			"scrapyard aberration",
			"shrine of the six pillars",
			"smoldering blade",
			"spellbound gauntlet",
			"spinegraft disabler",
			"spiraling canyon",
			"steel hunter",
			"stunning jolt",
			"unstable orb",
			"vanquish the obsolete",
			"vaultkeeper",
			"vedalken machinist",
			"vedalken wingcrafter",
			"walking platform",
			"wingcrafter's legacy",
			"a lady's favor",
			"ambition's crown",
			"ancestral zweihander",
			"beneath the lilies",
			"bustling docks",
			"captain of the exiled",
			"choked estuary",
			"cloak of the exiled",
			"dead man's armor",
			"derelict amphitheatre",
			"farmer's repose",
			"ferris, the sapphire storm",
			"ferris's crewmate",
			"foreboding ruins",
			"fortified village",
			"game trail",
			"helene, steel of the exiled",
			"interlocked waterways",
			"iron signet",
			"isolated cloister",
			"jailer's manacles",
			"port town",
			"shadowed slums",
			"shatter",
			"sunpiercing bow",
			"thief's harness",
			"vial of arcor",
			"whiterun gates",
			"whiterun harbor",
			"yvette, the golden gull",
			"abandoned battlefield",
			"abandoned cairn",
			"abandoned meadow",
			"abandoned skyroad",
			"abandoned wilderness",
			"academy wastes",
			"alpine meadow",
			"arcane signet",
			"barren desolation",
			"calmed battleground",
			"charbroiled core",
			"chiseled cliffside",
			"cleared vault",
			"cliffside entrance",
			"command tower",
			"dawnlit battlefield",
			"deadwood grove",
			"deeplife cavern",
			"deserted steppe",
			"deserted trail",
			"desolate barrens",
			"exotic xenoreef",
			"fiery chasm",
			"flourishing waterways",
			"forgotten cryovault",
			"forgotten shrine",
			"frigid highlands",
			"frontier base",
			"gleaming hot springs",
			"gnarled henge",
			"grim slums",
			"grove of reversal",
			"haughty chateau",
			"haunted woodlock",
			"highland vale",
			"horizon of origins",
			"imperial barracks",
			"jagged crag",
			"legacy foundations",
			"lush outskirts",
			"mossy shrine",
			"mysterious cataract",
			"ocean monastery",
			"ominous lair",
			"ornamented evergreen",
			"overgrown refuge",
			"quintok station",
			"rainforest spring",
			"roaring cascade",
			"secluded cascade",
			"shardstone rift",
			"shrouded rooftops",
			"sigil of creation",
			"sigil of martyrdom",
			"sky-high spires",
			"sodden cavern",
			"somber marsh",
			"spires of telenia",
			"stormcharged pyre",
			"strange harbor",
			"sunlit ruins",
			"timber range",
			"tirenan market",
			"torrid geysers",
			"toxic jungle",
			"tranquil stream",
			"unlit alley",
			"wastes",
			"weathered fortress",
			"wildrune thicket",
			"abandoned forge",
			"abandoned hideout",
			"abandoned laboratory",
			"abandoned preserve",
			"abandoned shores",
			"agent of vitu-ghazi",
			"boneforged arms",
			"breaking news",
			"descent of the stars",
			"doctored trail",
			"flood of information",
			"fractal findings",
			"insightful blow",
			"looking glass",
			"revenge of the disfigured",
			"skull of the world",
			"stalked healer",
			"still the pandemonium",
			"thomar's sowing",
			"wheat from chaff",
			"anzen, beyond the sea",
			"asahi yoroi",
			"bladed warfan",
			"chikami castle",
			"dragonwall gates",
			"emblem of aghavaan",
			"envenomed shuriken",
			"eternal inheritance",
			"fortune charm",
			"hanabira, kogane's legacy",
			"himitsu, shigure's legacy",
			"house of forgotten whispers",
			"imperial katana",
			"imperial mox",
			"imperial port",
			"inscribed histories",
			"kameno yoroi",
			"kami's greed",
			"kasai, asharo's legacy",
			"ketsueki, kiyomi's legacy",
			"kiri yoroi",
			"kurayami shrine",
			"legacy's end",
			"mask of shikai",
			"memorial of the fallen",
			"midnight keep",
			"mysterious coffer",
			"nidohagane warfans",
			"pagoda of longevity",
			"perilous passage",
			"raiun bay scourge",
			"saishuteki castle",
			"sea hunter",
			"seishin dojo",
			"seishin's edge",
			"sekitsui yoroi",
			"shadow lantern",
			"shaping dragonsteel",
			"shikai's redoubt",
			"shionoshio, ocean's vow",
			"shugenja's journal",
			"soulstone",
			"spellblade",
			"sunset monastery",
			"sword of silver and gold",
			"temple of falling leaves",
			"the last sacred gate",
			"tower of long shadows",
			"uguisu, kenshiro's legacy",
			"unzari ruins",
			"zahar, aghavaan's legacy",
			"adaptive servitor",
			"ancient saber",
			"ancient statue",
			"astral dynamo",
			"automated blademaster",
			"blade of the many",
			"bloodstone halls",
			"carved dagger",
			"convergence colossus",
			"crude tablet",
			"crumbling vestige",
			"dominion crown",
			"forced sprouting",
			"hill of souls",
			"ironsmash wrecker",
			"javelin",
			"mana prism",
			"moonlit shore",
			"paladin's blade",
			"planar processor",
			"scrapper construct",
			"skeleton shield",
			"spirit pendant",
			"steel swarmer",
			"unstable borer",
			"valley falls",
			"verdant sanctum",
			"wayfarer's lantern",
			"wild ravine",
			"blight seed",
			"bloodriver",
			"cloudbank",
			"corpsebed",
			"cradle of corruption",
			"elrayin, the manaroot",
			"gorran totem",
			"liquefaction",
			"monkey trinket",
			"mosecf, the sunseeker's path",
			"ralora, unforgiving depths",
			"revert to dust",
			"sea of skies beyond",
			"seedshrine",
			"seeker sword",
			"striptide",
			"sunstage",
			"tempest core",
			"abandoned memorial",
			"arcor diamond",
			"arctic mine",
			"artisan's masterpiece",
			"battered steel",
			"callow survivors",
			"crumbling precipice",
			"crystal cavern",
			"daunting skyline",
			"decrepit crags",
			"discordant bell",
			"dockyard swindling",
			"elixir of immortality",
			"failing port",
			"false-cure smuggler",
			"flintlock pioneer",
			"forgotten steppe",
			"grim courtyard",
			"hazy lagoon",
			"madelon, merchant's heir",
			"merchant's district",
			"murmuring falls",
			"nomad's township",
			"phosphorescent ravine",
			"plague mask",
			"rallying horn",
			"rampant summit",
			"raven's standard",
			"resplendent substratum",
			"rickety guildhall",
			"ruined citadel",
			"sedate tundra",
			"serene trail",
			"shifting glade",
			"vibrant rainforest",
			"vigilante's cowl",
			"weight of sin",
			"aetherite dagger",
			"aetherite shackles",
			"aetherite vein",
			"aetherlock effigy",
			"aetherlock pistol",
			"arcane heist",
			"bearidge charmer",
			"binding lasso",
			"bounty leveler",
			"calamity rose",
			"cruel effigy",
			"dead man's hand",
			"derelict town",
			"derelict watcher",
			"dreamkeeper",
			"embed",
			"forgotten haunt",
			"foulweather effigy",
			"gambler's dice",
			"ghostly flicker",
			"haunting bard",
			"heavy moneybag",
			"mighty totem",
			"miner's barracks",
			"moonlit lurker",
			"murderkeep",
			"needle doll",
			"nightrail fence",
			"old-world forgotten",
			"penny dreadful",
			"pickpocket",
			"reforge",
			"resolute scarecrow",
			"sandbluff confiscator",
			"scoundrel's aetherlock",
			"shredding sword",
			"stolen cache",
			"sunrise bluffs",
			"sunrise prairie",
			"sunrise river",
			"sunrise ruins",
			"sunrise woods",
			"the aetherite saloon",
			"the wicker lord",
			"tumblewalker",
			"ulek guardian",
			"worn saddle",
			"chamber of splendor",
			"dragonfly shrine",
			"hundred-year blade",
			"imperial coins",
			"imperial silks",
			"jade temple",
			"jade vault reclaimer",
			"palace of reflections",
			"proffered heirloom",
			"scales of seishin",
			"shengin heartland",
			"smoldering pages",
			"soulkindle lantern",
			"stonework infantry",
			"sundering sage",
			"terracotta legion",
			"the imperial collection",
			"the serpent throne",
			"throwing stones",
			"torrent of wind",
			"warfan of changing winds",
			"aerie's pillar",
			"bygone guardian",
			"channeling stone",
			"clockwork spellwork",
			"forgotten pit",
			"giltwork legacy",
			"gruff smith",
			"lumbering hillock",
			"mechanized ideal",
			"possibility matrix",
			"rousing rubble",
			"spellslinger's gauntlet",
			"spellwork bulwark",
			"warded tome",
			"abandoned den",
			"awoken soul",
			"bearhide cloak",
			"bjarndyr outfitter",
			"blood hunter's spear",
			"bloodguard's hand",
			"casualty of war",
			"chains of subdual",
			"culi-sae exonerator",
			"demolish",
			"dragon queen's den",
			"dragonfire longboat",
			"frostfield swordsman",
			"ghastly ferry",
			"ghoulsaber",
			"greenheart den",
			"heartless host",
			"hearty karv",
			"hibernation den",
			"ice over",
			"icy manipulator",
			"monument to the fallen man",
			"nature's claim",
			"oaken longbow",
			"pillager's sloop",
			"raider's den",
			"ruthless conscript",
			"short sword",
			"skeigr, skhorvall flagship",
			"staff of equilibrium",
			"the issbarrens",
			"to the hunt",
			"unending voracity",
			"viking greataxe",
			"wanton cleave",
			"war-torn tundra",
			"weathered skiff",
			"autumn moon",
			"blundering clocktower",
			"burnished plate",
			"canyon creek",
			"climber's gear",
			"cloud rock",
			"crystal grotto",
			"cumulus horizon",
			"evolving wilds",
			"expedition map",
			"fey grove",
			"foraging gear",
			"frigid thicket",
			"glacial buttress",
			"haunted boughs",
			"honey wagon",
			"humored outlaw",
			"lumber camp",
			"marked coin",
			"moon of the encroaching night",
			"moon of the final dawn",
			"moon of the frozen dusk",
			"moon of the lingering day",
			"moon of the promised day",
			"rolling homestead",
			"ruined precipice",
			"soaring canyon",
			"tinkering swarm",
			"verdant bluff",
			"vibrant balloon",
			"witch's abode",
			"wooden toys",
			"ancient cairns",
			"archivist heretic",
			"blossom-sower witch",
			"buried glade historian",
			"catalog the possibilities",
			"chroma, the faerie circle",
			"chromatic pendant",
			"coiling mystic",
			"crack open the cache",
			"demanding idol",
			"dragongate",
			"field of obelisks",
			"force back",
			"gate to the nav",
			"guidestone",
			"herald of desolations",
			"immortalize in stone",
			"keen-eyed gemcutter",
			"lodestone sword",
			"mysterious absence",
			"nexus of possibilities",
			"noxious garden",
			"orb of undoing",
			"overgrown ruins",
			"paradox sculptor",
			"paranoid archivist",
			"prying inquiry",
			"return to earth",
			"rite of lost timelines",
			"rune of rejuvenation",
			"runic pillars",
			"salvation engine",
			"seeker lizaveth",
			"serafina's gift",
			"sift through false leads",
			"stonefall golem",
			"the volostoy key",
			"through the ashen gate",
			"tinkerer's assistant",
			"tracer sigil",
			"wanderer's sky",
			"amulet of loyalties",
			"ascendant's gate",
			"atlas of worlds",
			"awestone",
			"ayshea tome",
			"backstage rooms",
			"backstage tinkers",
			"bahum, the warden",
			"cadalon experimenter",
			"cadalon inspector",
			"cadalon outfitter",
			"chromatic lantern",
			"chronovore clock",
			"clock of seasons",
			"coffers of kovach",
			"control discourse",
			"crux pinnacle",
			"crystal cauldron",
			"dragonfire blade",
			"drop of envy",
			"duelist's choice",
			"dying breath",
			"eldritch egg",
			"elsewhere mirror",
			"encrypted monument",
			"enlightened sigil",
			"eternity pendant",
			"ghost light",
			"gilded cipher",
			"gilded lotus",
			"glistening chalice",
			"goblet of unhallowed blood",
			"golden helm",
			"grab bag",
			"harms dealer",
			"heist headquarters",
			"hidden hollow",
			"invisibility cloak",
			"isochron wand",
			"joyous chromatelk",
			"kiku, the gadgeteer",
			"legitimate establishment",
			"lightless hedron",
			"living script",
			"lodestone golem",
			"loose ends",
			"lost memories",
			"lucien, the grifter",
			"malign growth",
			"mentorb",
			"mindlock field",
			"mirrored mask",
			"mnemonic curator",
			"moonlit charmer",
			"multipurpose mannequin",
			"platinum colossus",
			"posthumous informant",
			"prismatic panes",
			"pristine frame",
			"prophetic prism",
			"questionable methods",
			"ravage relics",
			"ring of souls",
			"ruined theater",
			"ruptured citadel",
			"ruptured expanse",
			"ruptured falls",
			"ruptured flats",
			"ruptured grotto",
			"ruptured grove",
			"ruptured meadow",
			"ruptured morass",
			"ruptured square",
			"ruptured trail",
			"ruststep centipede",
			"saia's protege",
			"scathing review",
			"scuripi collector",
			"seedy bar",
			"seer's sphere",
			"servant of armageddon",
			"seven-year step",
			"shared trove",
			"shining crusader",
			"skeleton keyring",
			"skybreaker hook",
			"sorcerous spyglass",
			"soul gate",
			"spectral skycruiser",
			"stage dressing",
			"starforge armor",
			"steamquiver strix",
			"stormcannon gauntlet",
			"sundial of the infinite",
			"sword of redemption",
			"sword of truth and lies",
			"talent pool",
			"the dominomicon",
			"the stranger's play",
			"theater mask",
			"time cube",
			"titan snare",
			"tome of loss",
			"trap door",
			"treasury keyper",
			"truth extractor",
			"uncovered idol",
			"undercity vendor",
			"vault sentinel",
			"vile infiltrator",
			"walking armory",
			"warlord's mantle",
			"warrior's bane",
			"whispering halls",
			"wistful automaton",
			"worldslayer",
			"armored transports",
			"bank job",
			"brazen blackguard",
			"catalina's turf",
			"devised battlesuit",
			"devised companions",
			"dominik's shack",
			"dragonwrought engineer",
			"elderbane rifle",
			"elections tampering",
			"emmerich, the negotiator",
			"evening report",
			"forgotten doorway",
			"galvan coal line",
			"ganzorig's domain",
			"gilded gunman",
			"gleeful deviser",
			"grifter's diversion",
			"grizzled stoker",
			"guiying's gambit",
			"hellbent speed",
			"henrike clevain, rail baron",
			"hiroto's refuge",
			"imperial titan",
			"keep the peace",
			"lumenbay flyer line",
			"lumenbay jailer",
			"marinton-ravengulch line",
			"marshal jin guiying",
			"modular mercenary",
			"mountain-western inventor",
			"neblus' legacy",
			"northern express line",
			"rawthlin market line",
			"relic heist",
			"ride the storm",
			"riga's workshop",
			"riko's academy",
			"riv's safehouse",
			"scrapyard raiders",
			"severin, broken genius",
			"singularity's grasp",
			"snowclearer",
			"sovereign skies",
			"sparkline dancer",
			"sparkline harness",
			"spectacle of innovation",
			"steam daimyo's gauntlets",
			"steamcharged armor",
			"steamwork musicians",
			"stormcannon testing",
			"strike down the usurpers",
			"takumi's headquarters",
			"taste brilliance",
			"throne of the west",
			"tsubasa's redoubt",
			"union rail strikebreaker",
			"aeriform remnant",
			"alquyut mount",
			"ash-withered cloak",
			"back-alley vandal",
			"barren boneyard",
			"bearer of old growth",
			"beastback raider",
			"bitter wanderer",
			"blade of burning sand",
			"blighted dagger",
			"bloodboil harlequin",
			"buried by time",
			"calcified dunes",
			"churning rough-roller",
			"congruous simulacrum",
			"curio pavilion",
			"curious dais",
			"dancing mirrorblade",
			"dilapidate",
			"drift tracer",
			"effigy of creation",
			"effigy of destiny",
			"effigy of harvest",
			"effigy of morality",
			"effigy of wisdom",
			"egg of avarice",
			"el-mazar, wayward palace",
			"encrusted sahalia",
			"exemplar of disdain",
			"facsimile sculptor",
			"fanciful bloom",
			"flourishing dunes",
			"furnace golem",
			"gateway statues",
			"gemplate golem",
			"gilded wyvern",
			"globule of agony",
			"globule of intuition",
			"globule of sanctuary",
			"globule of turmoil",
			"globule of vigor",
			"granite plating",
			"gulch custodian",
			"helm of princes",
			"highland dunes",
			"idol of the dead god",
			"igneous pulverizer",
			"immolated grave",
			"kaleidostone",
			"laden bruiser",
			"liege of luxury",
			"macabre ruins",
			"meddling gargoyle",
			"painted bluffs",
			"palace gargoyle",
			"plumed carpet",
			"prismatic basilisk",
			"promenade banner",
			"proselytic shrine",
			"ravaged monument",
			"rubble scavenger",
			"runed servitor",
			"saber of defiled rites",
			"sandswept bazaar",
			"saturated dunes",
			"scabrous automaton",
			"secluded monument",
			"seismic colossus",
			"shrapnel golem",
			"silt conduit",
			"silt-trench brute",
			"siltsplitter",
			"skeletal oasis",
			"soul chalice",
			"stabilize",
			"strider harness",
			"strike down",
			"stygian dunes",
			"sunrazed ruins",
			"temple attendant",
			"tomb of great drakes",
			"trove tyrant",
			"volatile stonework",
			"zoetic tomb",
			"carven guardian",
			"dust barrens",
			"golden glade",
			"granite watchers",
			"hallowed fragment",
			"leija's greenblade",
			"ligos, shadow's source",
			"mind-mute",
			"remnants of divinity",
			"rius, temple of the grandfather",
			"singers' grove",
			"tea of augury",
			"the aurora's heart",
			"the court of angels",
			"vanquisher's banner",
			"aetherdrain",
			"arcane saxophone",
			"art studio",
			"artisan's fountain",
			"artisan's sorrow",
			"automated maestromancer",
			"blessed mausoleum",
			"bogchomper juggernaut",
			"bogsnatcher drake",
			"bogsworn club",
			"bouquet singer",
			"burning revelations",
			"cataclysmic preacher",
			"coat in petals",
			"damning flames",
			"dangerous territory",
			"determined evangelist",
			"eerie bayou",
			"elegant strike",
			"faradia, honored sovereign",
			"faradia's collector",
			"faradia's grace",
			"faradia's outrage",
			"festival rioters",
			"fleshcarver knife",
			"forlorn ruin",
			"glorious celebration",
			"helena's rebuff",
			"heroic crusader",
			"improvising automaton",
			"irrigation trawler",
			"lakeside park",
			"lazaire's altar",
			"lord's voyage",
			"lost in admiration",
			"lotus debutante",
			"lotus feaster",
			"marsh's veil",
			"mushroom lagoon",
			"occult tutor",
			"ontarachie dryad",
			"ornate incense",
			"parish's command",
			"passionate congregation",
			"prayer hall",
			"reclaim the devout",
			"rejoicing aristocrats",
			"ritzy parlor",
			"royal domain",
			"solemn offering",
			"soul of new alores",
			"storehouse collapse",
			"sudden conversion",
			"sunlit plaza",
			"tempted by lotuses",
			"unicorn of the vale",
			"vacated bar",
			"vibrant rapture",
			"vindictive abbot",
			"vivid march",
			"wade through",
			"wailing chorus",
			"woopip wanderer",
			"zoulev altar",
			"zoulev offering",
			"artist's vista",
			"charming marauder",
			"fate charm",
			"fateseeker's orb",
			"once abandoned",
			"over the horizon",
			"paradox rings",
			"poisoned tonic",
			"potion of inhibition",
			"seeking sword",
			"stark copse",
			"stark hinterlands",
			"stark horizon",
			"stark stream",
			"stark wildfire",
			"abandoned monument",
			"aether corsair",
			"aether crosser",
			"aether gateway",
			"aethercrafting",
			"alethea, syzygy captain",
			"arboreal runes",
			"autumn canopy",
			"blossoming expanse",
			"brine fleet bay",
			"chamber of reflections",
			"chronosphere sovereign",
			"cloudsteel summit",
			"cryptic sentinel",
			"cursed wastes",
			"dimensional reshaper",
			"dreamscape",
			"dustchoked outpost",
			"endless trove",
			"eternal reactor",
			"ethereal stone",
			"expedition post",
			"explorer's ascent",
			"fenhauler gang",
			"fractured reach",
			"fungal swathe",
			"gathering beacon",
			"ghostspore mire",
			"gilded gulch",
			"glacial shelf",
			"grove of embers",
			"heart of zhedina",
			"idravir, the last city",
			"intrepid",
			"kilnfire",
			"krismite shard",
			"krismite vault",
			"lotus lake",
			"mausoleum suffragan",
			"molten falls",
			"monument of queens",
			"morphic verge",
			"mutalithic golem",
			"nereba, sandchoked archives",
			"notorious smuggler",
			"othersea submersible",
			"otherworldly forest",
			"otherworldly island",
			"otherworldly mountain",
			"otherworldly plains",
			"otherworldly swamp",
			"paracosm",
			"polyp pools",
			"possibility engine",
			"possibility scope",
			"precursor sanctum",
			"promethean grotto",
			"rainsculpted gorge",
			"razione racecourse",
			"rippling curtain",
			"saddled scuttleback",
			"shadowcleft hideout",
			"shifting canyon",
			"shifting cascade",
			"shifting crag",
			"shifting grove",
			"shifting morass",
			"shuddering node",
			"skylight fortress",
			"smuggler's den",
			"soaring biome",
			"soaring rainforest",
			"soulblade",
			"starlight beacon",
			"steamlit peaks",
			"syzygy navigator",
			"syzygy privateer",
			"tears of tizuma",
			"telarine skychaser",
			"timeless shrine",
			"tomb of shifting sands",
			"transposition portal",
			"untethered spire",
			"voliv edgelands",
			"woven network",
			"zhargetan reclaimer",
			"zhedina bazaar",
			"zhedina confiscator",
			"zhedina exchange",
			"zhedina outskirts",
			"zhedina servitor",
			"zhelid, planar academy",
			"acin, the toymaker",
			"advanced powercell",
			"alia's enforcer",
			"align the astrolabe",
			"arcane chronometer",
			"arcane metalcrafter",
			"artificer's prowess",
			"artisan's genius",
			"artistic vision",
			"benevolent malach",
			"blessing of morning",
			"brilliant academy",
			"brilliant archives",
			"brilliant capital",
			"brilliant castle",
			"brilliant citadel",
			"brilliant cityscape",
			"brilliant hub",
			"brilliant mansion",
			"brilliant port",
			"brilliant workshop",
			"channeler of the veil",
			"city gate",
			"citywide automation",
			"claim for civilization",
			"colossal achievement",
			"cosmic chart",
			"dedicated weaponsmith",
			"disable",
			"eager observer",
			"eleventh hour breakthrough",
			"encampment blimp",
			"endless assembly",
			"facsimile of divinity",
			"flamboyant inventor",
			"forgemaster's charm",
			"gearcraft observer",
			"gilded gearhulk",
			"gilded spyglass",
			"harmony array",
			"hub of innovation",
			"iterative designer",
			"junktrawler",
			"lightblessed claymore",
			"mana rose",
			"manaflux battery",
			"matron of machines",
			"nina, master of arms",
			"observer of secret paths",
			"oldgrove nurturer",
			"perpetual motion machine",
			"petal-weaver alexa",
			"polgek artisan",
			"polgek restorationist",
			"powercell cultivator",
			"powercell engineer",
			"propagation blade",
			"reinvent",
			"renewal grove",
			"riftway to the other side",
			"runecrested valley",
			"sealed riftway",
			"self replication",
			"sword of tides and time",
			"telvim explorer",
			"telvim sculptor",
			"the clocktower project",
			"timeworn crags",
			"transplanted citadel",
			"unexplored regions",
			"unite the powergrid",
			"unity spheres",
			"vitin blastgear",
			"vitin forgemaster",
			"volta, construct consultant",
			"ancestor's skull",
			"antiquated firearm",
			"armament scavenger",
			"cobbled currency",
			"cobbled transport",
			"courier's misfortune",
			"determined to prevail",
			"drained shore",
			"drought-plagued slum",
			"excavator of the beyond",
			"experimental battle armor",
			"fluctuating locale",
			"forager's lore",
			"forsaken getaway",
			"grave of an old lord",
			"haunted fairground",
			"head of ulko",
			"hellwaste settlement",
			"hunger of old lovi",
			"imposing barricade",
			"left on the wayside",
			"medical mask",
			"memorial ground",
			"mennin jar",
			"pulsating mass",
			"realm tiller",
			"rebuild history",
			"reclamation project",
			"relic hoarder",
			"renegade servitor",
			"risti citadel",
			"risti salvager",
			"scavenger holdout",
			"scavengermobile",
			"secluded farmstead",
			"seductive seashell",
			"sepulchral seas",
			"servitor vanguard",
			"singer of calamities",
			"surveyor's rifle",
			"suspect concoctions",
			"the ark project",
			"the hidden truths resurface",
			"warped landscape",
			"windmill project",
			"aureate panorama",
			"ayala's effigy",
			"cinderblade",
			"frozen hinterlands",
			"hazy coppice",
			"kaor's tithe",
			"lowland vista",
			"spires of caulte",
			"sunlit fissure",
			"testament to heroism",
			"the whisperwoods",
			"towering boughs",
			"aether sculptor",
			"aetherspear",
			"ancient dominion",
			"bleak dominion",
			"bloodfell caves",
			"blossoming sands",
			"canid simulacrum",
			"coastal dominion",
			"desolate dominion",
			"dismal backwater",
			"esoteric egg",
			"felling vines",
			"gleaming river",
			"hembwe, the all-mother's hand",
			"jungle hollow",
			"majestic dominion",
			"murky peat",
			"ornery bloom",
			"primal dominion",
			"pristine dominion",
			"punja stick trap",
			"rugged dominion",
			"rugged highlands",
			"scoured barrens",
			"stalwart dominion",
			"sunwashed spires",
			"swiftwater cliffs",
			"thornwood falls",
			"tranquil cove",
			"tropical grove",
			"vast savannah",
			"verdant dominion",
			"wind-scarred crag",
			"wings of liberty",
			"11-a lionheart",
			"aose lab tech",
			"aose skydrone",
			"advanced schematics",
			"aldorus fin, vice president",
			"ancient artillery",
			"architect of the derezzed",
			"barren vista",
			"blooming vista",
			"bury the past",
			"c-25 juliet",
			"clash reactor",
			"combat technician",
			"convert to resources",
			"crucible of worlds",
			"defected android",
			"dreadtread rover",
			"essential override",
			"fo-2 radiation kid",
			"field technician",
			"fracking factory",
			"glacial vista",
			"glitch, galactic muse",
			"greedy insects",
			"green daywalker",
			"hall of random access memories",
			"hardened explorer",
			"heaven, presidential ship",
			"inquirer, roaming rover",
			"joyous explorer",
			"k-17 drone",
			"killdrone assembly works",
			"killdrone engineer",
			"living vista",
			"lower stratosphere destroyer",
			"marshy vista",
			"mineral retriever",
			"mining rover manager",
			"nebula of empty gold",
			"new divide",
			"operations manager",
			"pernicious primavore",
			"power drive",
			"precursor filtercruiser",
			"precursor sentinel",
			"prismatic cavern",
			"r-12 lone digger",
			"ravenous abomination",
			"ready to go",
			"repurposed killdrone",
			"robot herder",
			"s-19 long jacket",
			"scavenging pack",
			"senator christian winters",
			"servant of precursors",
			"slyten crystal motherlode",
			"source decay",
			"starborne hellkite",
			"sword of monsters and men",
			"tt-23 aegis",
			"tessellated orb",
			"the tomb of precursors",
			"trick mirror gui",
			"unending armies",
			"v-4 fixit",
			"arcane sanctum",
			"bigroot valley",
			"bleak shoreline",
			"caustic mangrove",
			"cesspool scrapper",
			"charred marsh",
			"cloudcover heights",
			"cloudheath sentinel",
			"cognition crucible",
			"crumbling necropolis",
			"dominator's diadem",
			"duneglass ascetic",
			"erupting territory",
			"esper command",
			"esper shardseeker",
			"etherium abrogator",
			"etherium leviathan",
			"etherium sculptor",
			"etherium staff",
			"ethersworn elite",
			"ethersworn indoctrination",
			"filigree drake",
			"filigree lotus",
			"font of nefarox",
			"forbidding isle",
			"gloomtide gulf",
			"hazy summits",
			"hegemon's cutthroat",
			"idyllic oasis",
			"jungle shrine",
			"kaleidoscape",
			"lichen's grasp",
			"lush coast",
			"macabre effigy",
			"meticulous mechanist",
			"nacatl skirmisher",
			"orlesia, first of the sen",
			"ostracizer orb",
			"peaceful passage",
			"recraft in steel",
			"retinue golem",
			"rings of new alara",
			"sanctum battlemage",
			"savage lands",
			"scrap spiral",
			"sculler's oar",
			"sculpted observatory",
			"seaside citadel",
			"sharuum, archmagocrat",
			"sharuum's council",
			"sigil of the skyward eye",
			"skygrid surveyor",
			"somber meadow",
			"sphinx paramount",
			"spire of bant",
			"spire of esper",
			"spire of grixis",
			"spire of jund",
			"spire of naya",
			"steel wind goliath",
			"steel wind strix",
			"steelfin manta",
			"supreme mechanothurge",
			"telemin architect",
			"terraformer's globe",
			"terramorphic expanse",
			"the riddle gate",
			"tidehollow lich",
			"twisting fissure",
			"vectis entrancer",
			"visitarium smuggler",
			"wayward sphinx",
			"adorned naga",
			"anku the primordial",
			"ankulith shard",
			"aven merchant",
			"aven supervisor",
			"behead",
			"bloodsoaked blades",
			"bordermakers",
			"breaker of cities",
			"center of culture",
			"collapse the pillars",
			"consult the scriptures",
			"crescent of possibilities",
			"crooked merchant",
			"crushclaw pulverizer",
			"currency",
			"death pits trophy",
			"dehmi's servitor",
			"divine chariot",
			"donkey jawbone",
			"edge of the empires",
			"edifice overseer",
			"ekebram's archive",
			"eli windsors, lone gun",
			"epic of jobiah",
			"epic of the lovers",
			"founding hero",
			"funerary barge",
			"gilded authority",
			"gilded blade",
			"gilded idol",
			"golden age",
			"hannaru's spear",
			"hard-working oxen",
			"harshapal banner",
			"hauling hippopotamus",
			"hefty tablet",
			"hirsute champion",
			"immortalize",
			"imperator namuzzar",
			"imperial achievement",
			"imperial brutality",
			"imperial claim",
			"imperial confidant",
			"imperial defenses",
			"imperial prosperity",
			"keeper of codices",
			"legacy warmask",
			"life's worth",
			"look to the future",
			"many-voiced tower",
			"manalith",
			"marble row healer",
			"master of marble row",
			"merchant of flesh",
			"mustering grounds",
			"nameless throng",
			"namuzzar's disciple",
			"namuzzar's iterator",
			"nibinem's hand",
			"obviate",
			"oppress the weak",
			"opulent ankulim",
			"paid in blood",
			"palace enforcer",
			"pound by pound",
			"rhudai overseer",
			"rod of marble row",
			"rupture spire",
			"ruthless advancement",
			"sannurian sentinel",
			"scavenger's wagon",
			"scion of sannuria",
			"serpent staff",
			"serve the empire",
			"sire of empires",
			"sling of the meek",
			"splinter of creation",
			"stonecut lammasu",
			"strongarm",
			"subjugator of empires",
			"tempered ankulim",
			"tiller's adze",
			"urn of heroes",
			"voyager's ark",
			"wealthy merchants",
			"wondrous bazaar",
			"amulet coin",
			"brutality",
			"caustic caterpillar",
			"cheerful generator",
			"chikyu league arena",
			"curious fossil",
			"ether",
			"expert belt",
			"focus sash",
			"forage",
			"forgotten temple",
			"gene pool",
			"healing center",
			"ice path",
			"lake of rage",
			"lucky egg",
			"maple's journal",
			"metal coat",
			"muggy mire",
			"old map",
			"paleontologist",
			"power plant",
			"practice range",
			"quick claw",
			"ruined lab",
			"ruined shrine",
			"sanaito, alone",
			"still waters",
			"titanic fossil",
			"treasure beach",
			"unburdened",
			"victory road",
			"wandering hamlet",
			"wicked fossil",
			"abandon ship",
			"adept fisherman",
			"admirable admiral",
			"adoroth, the baneful",
			"all that glitters",
			"alvarez of the huntsman",
			"arbiter of the demeter",
			"blacksteel loadout",
			"boarding party",
			"breakneck barque",
			"brig of the damned",
			"broadside raider",
			"brume leviathan",
			"calamitous wave",
			"cannonblast",
			"captain darlene filham",
			"captain's companion",
			"captain's orders",
			"chartered fleet",
			"civil discourse",
			"crackling agama",
			"crain's crew",
			"crain's crony",
			"crazed swashbuckler",
			"crewmaster gillo",
			"crosswind cutter",
			"crown of the speaker",
			"cruising schooner",
			"cryptozoologist",
			"culling blade",
			"dapper ragamuffin",
			"daybreak wayfarers",
			"dragonlord's shrine",
			"dusk lieutenant",
			"dwarven war hatchet",
			"eager voyager",
			"elaborate firecannon",
			"elder prophesier",
			"faithless deserter",
			"fated mariner",
			"fiery cannonade",
			"flaming point technique",
			"flintlock pistol",
			"fog at sea",
			"garth of the chimera",
			"ghost sloop",
			"greedy rapscallions",
			"grievous buccaneer",
			"grizzled cutthroat",
			"h.s.s. demeter",
			"harbinger of giradrus",
			"harriet of the pioneer",
			"heinous smuggler",
			"helicos aberration",
			"helmsman's chart",
			"holcomb of the peregrine",
			"hugo of the shadowstaff",
			"idyllic pegasus",
			"intrepid captain",
			"ironclad infantry",
			"keen seafarer",
			"last passage",
			"lava scutterer",
			"lofty dreamship",
			"mable of the sea's whimsy",
			"marisa of the gravehowl",
			"maritime thug",
			"master negotiator",
			"merchant galleon",
			"merciless bandit",
			"nimble caravel",
			"old salt",
			"perilous treaty",
			"pirate's cutlass",
			"pirate's hideout",
			"plucky pickpocket",
			"rattled bones",
			"raving brigand",
			"recruits of the demeter",
			"ruinous proselyte",
			"rum guzzler",
			"salty swab",
			"salvage wyvern",
			"searle of the tempest",
			"seasoned lookout",
			"seawise swain",
			"silent hunt",
			"sink",
			"siren's song",
			"skysail rigger",
			"slaughterkeg",
			"suitor of the sea",
			"sun-crowned flagship",
			"swift corsair",
			"tabia of the lionheart",
			"tankard of grog",
			"the winged steed",
			"three seas cartographer",
			"three seas squire",
			"trawl the wreckage",
			"treasure hauler",
			"twilight privateer",
			"two-faced marauder",
			"unruly cannoneer",
			"valencia of the concordant",
			"watchful navigator",
			"advent from above",
			"anemone cluster",
			"barnacled blade",
			"battle station",
			"bloodhollow bruiser",
			"brilliant runepearl",
			"brine duelist",
			"bygone wreck",
			"cannoncoil hermit",
			"conchhorn shinygrabber",
			"conchspear hunter",
			"coralcrown's banishment",
			"coralight castle",
			"coralight paladin",
			"crack open",
			"crushing grip",
			"cuxuri's corruption",
			"dawson's bouncer",
			"dawson's collector",
			"dawson's jetslicer",
			"dawson's loot",
			"dawson's marauder",
			"dawson's warden",
			"depthlight beacon",
			"depthlight brute",
			"depthlight captain",
			"depthlight frontliner",
			"depthlight salvager",
			"dredgeline colossus",
			"duke atrios xxiv",
			"dukedom outcast",
			"dukedom turncoat",
			"edina, coralight soothsayer",
			"enchanting palace",
			"fortune and glory",
			"frontline descender",
			"full salvo",
			"gilded merrow",
			"glittering narwhal",
			"goldtooth slasher",
			"greenscale bully",
			"grim's warchest",
			"grisly ruins",
			"harried submersible",
			"highbeam hulk",
			"ink seer",
			"lord rickard dawson",
			"lost empire's legacy",
			"mettalia, light from above",
			"mettalia's forward",
			"militant's standard",
			"minefield bomber",
			"molten basin",
			"myrmidon, coralight exile",
			"myrmidon's warhead",
			"mysterious lights",
			"oceanographer",
			"oil driller",
			"ominous helmet",
			"paradise reef",
			"patrol ship",
			"pay up",
			"rappel liner",
			"redeye commando",
			"redgill corsair",
			"reefcrown egg",
			"regal seasnake",
			"roving dreadnought",
			"rustshell crustacean",
			"salvage titan",
			"seabed delver",
			"seafloor cache",
			"seafloor casket",
			"seafloor shrine",
			"seafloor tomb",
			"seafloor wreckage",
			"searchlight drones",
			"shanty town",
			"shark slayer",
			"silt miner",
			"sledgesuit prospector",
			"spare supplies",
			"specimen collector",
			"stinging swordfish",
			"subnautical legionnaire",
			"tectonic chateau",
			"torpedo jetter",
			"tragic arrogance",
			"treasure haulers",
			"treasury master",
			"trenchbottom mariners",
			"trident of benediction",
			"typhoon caverns",
			"typhoon cruiser",
			"uncovered secrets",
			"vibrant sandbar",
			"volcanic hollow",
			"vyzer, the fallen despot",
			"wilt",
			"adam of the ironside",
			"animara, last of the fell",
			"brutal blow",
			"clockwork gaucho",
			"from peace and purpose",
			"galvan ranger",
			"hexplate companion",
			"iterative design",
			"plasma enforcer",
			"project head",
			"scrap, the second myr",
			"waxing angel",
			"adventuring gear",
			"ancient guardian",
			"arms merchant",
			"bag of holding",
			"coastal metropolis",
			"crowded tavern",
			"cunning mimic",
			"destructive storm",
			"dragon-forged armor",
			"exotic mask",
			"fertile steppe",
			"forceglow shield",
			"gold farmer",
			"haughty paladin",
			"healing potion",
			"hero's axe",
			"hoarding arachnid",
			"homeward amulet",
			"ildirin, the apex blade",
			"invoke the divine",
			"living hoard",
			"load-bearing behemoth",
			"mage's staff",
			"mana potion",
			"paladin's flail",
			"potion stockpile",
			"raid the dragon's lair",
			"ranger's bow",
			"relic corrosion",
			"rogue's passage",
			"seek the maker's egg",
			"spawning barrens",
			"thalassic borough",
			"the book of secrets",
			"thieves' dagger",
			"town elder",
			"tweak the settings",
			"uncanny investor",
			"village courier",
			"violent incursion",
			"waypoint stone",
			"wild peak",
			"world map",
			"admonish",
			"ageless wanderer",
			"allure of alratha",
			"alratha, pearl of the sand sea",
			"alrathan scholar",
			"alrathan vizier",
			"ancient tablet",
			"ancient tome",
			"archaeologist's discovery",
			"azure archaeologist",
			"bandit's blade",
			"blackhearted sphinx",
			"bloodstained altar",
			"calamity scholar",
			"cold shoulder",
			"collapsing ridges",
			"conto sika, ruined glory",
			"crest",
			"dark behemoth",
			"darna, dark overseer",
			"darna's grimoire",
			"desert's hearth",
			"drysand mole",
			"dthan's daggers",
			"ecological refuge",
			"elise, maktali prodigy",
			"giant's remains",
			"grave robbery",
			"guardian of mysteries",
			"inquisitive student",
			"kilani, awakened colossus",
			"living library",
			"love letters",
			"maktali visionary",
			"maktali, the great library",
			"marauder's broadsword",
			"merchant's outpost",
			"merchant's sidearm",
			"mindwave rod",
			"mystic khopesh",
			"oasiscrafting",
			"observer of aeons",
			"open the tomb",
			"palaisun, maktali's opus",
			"path of fire",
			"pillar of training",
			"prismite",
			"protect the treasure",
			"remnant of lost times",
			"restored automaton",
			"reytha's discovery",
			"riddle-eater",
			"riddlemaster's bane",
			"ruin guardian",
			"ruins' reward",
			"sand twister",
			"sandstone construct",
			"scholar of necromancy",
			"smashing brute",
			"stormcalling",
			"study",
			"sunken grave",
			"swaying sands",
			"tomb robber's grit",
			"verdant oasis",
			"wall of sand",
			"wayfarer's amulet",
			"worn study",
			"ancestor's bulwark",
			"elusive devout",
			"feral devout",
			"fervent devout",
			"fields of worship",
			"hail of blades",
			"inscrutable realms",
			"inviolable realms",
			"lustrous devout",
			"mortal deeds",
			"mortal realms",
			"perception pool",
			"poisoned devout",
			"settlement guardian",
			"shield of the unwavering",
			"sunderer of veils",
			"tempting realms",
			"void hilt",
			"weave etcher",
			"weeping lotus",
			"wild realms",
			"worn to nothing",
			"adventurer's amulet",
			"alchemist's kit",
			"ameret, pride of cyrukan",
			"ancestral guidance",
			"artificial wayfinder",
			"avalanche elemental",
			"avaricious ghul",
			"avaz banner",
			"avaz citadel",
			"avaz sanctuary",
			"avaz temple",
			"bulwark of tradition",
			"bustling bazaar",
			"conquerer's blade",
			"constructed jay",
			"cyrukan battleaxe",
			"cyrukan's crossblades",
			"cyrukan's devoted",
			"dagger of the lost ages",
			"danaj citadel",
			"danaj sanctuary",
			"danaj temple",
			"decanter of endless rivers",
			"dispute",
			"doomed alchemist",
			"dunesea captain",
			"efreetspeaker",
			"exquisite artisan",
			"flying throne",
			"furnished ghul",
			"gilded guardian",
			"greater masticore",
			"heartless army",
			"hidden cache",
			"hidden garden entrance",
			"ironhide hadhayosh",
			"kaneh citadel",
			"kaneh headdress",
			"kaneh sanctuary",
			"kaneh temple",
			"knife of sanctity",
			"maaru, tomb guardian",
			"mahara's command",
			"marketplace crossroads",
			"marketplace haggling",
			"mercantile satrapy",
			"muktann protectors",
			"neutral citystate",
			"nizev citadel",
			"nizev sanctuary",
			"nizev temple",
			"rahstahde truthseeker",
			"roaming city",
			"romantic rescue",
			"sahra poet-priest",
			"sahra's command",
			"serene thoughts",
			"shady deal",
			"shifting city",
			"shrine to those gone",
			"signet ring",
			"soli citadel",
			"soli sanctuary",
			"soli temple",
			"spear of truth",
			"supreme alchemist",
			"swindle the rapacious",
			"sword of fanaticism",
			"the blacksmith's banner",
			"threatening khopesh",
			"tomb-diving initiate",
			"treasure hoard",
			"truthseeker's blade",
			"unsustainable consumption",
			"venture into the muktann",
			"zenith of greed",
			"astral gateway",
			"cage of torment",
			"flawless counterfeit",
			"power gate",
			"rose of fretport",
			"scrapyard sovereign",
			"coveted heirloom",
			"geetha, glass-shaper",
			"iviana, speaker of fangs",
			"nightwatch rallier",
			"nova, skyship captain",
			"synchronous hellkite",
			"turn to gold",
			"wunderkind devising",
			"xenocrata's fleet",
			"call of the clocktower",
			"corecharge",
			"hannah, entelan prodigy",
			"lackeybot",
			"tricked-out hoverboard",
			"xolde, high king's castle",
			"bustling harbor",
			"dreary township",
			"glittering grove",
			"monsoon lagoon",
			"urban wastelands",
			"karaja hetegex",
			"starved oasis",
			"duplicated dismantler",
			"gitaxian reprocessor",
			"posey, of the seal cloak",
			"barten's journal",
			"cortex coil",
			"cosmic tendrils",
			"grand library of ormos",
			"s-40 wallbreaker",
			"snagged truck",
			"dustridden sepulcher",
			"risti workshop",
			"avatar of innovations",
			"all-blossom memorial",
			"dragonglass harp",
			"rampart ballista",
			"recon drone",
			"robocamel",
			"sandstone archivist",
			"scrap buggy",
			"steamquiver condor",
			"wayfarer's adornments",
			"flourishing lowlands",
			"forgotten monument",
			"pathway of lost sultans",
			"raintouched basin",
			"scoured mesa",
			"silent ridge",
			"windworn spires",
			"mechanomind researcher",
			"memorial of forgotten heroes",
			"sandstorm sentinel",
			"slicing steer",
			"steelscribed katana",
			"towering wickerman",
			"arcane oasis",
			"arid causeway",
			"bloodsand gulch",
			"blooming needles",
			"crumbling aqueduct",
			"desiccated trail",
			"dunesea expanse",
			"humble hamlet",
			"resurgent oasis",
			"rot-sand ruins",
			"sundappled scrub",
			"alchemos, efficiency engine",
			"astrina, tempered by glory",
			"the shadowstaff",
			"chigau market outskirts",
			"dha-bukan, jewel of the dunes",
			"eroded sanctuary",
			"k-83 sunshine walker",
			"telenian adornments",
			"fakadeh's anointed",
			"darutu's plow",
			"patent thief",
			"tempest stormcaster",
			"alrathan courier",
			"tutorial boss",
			"sky-torrent navigator",
			"kellythross's collector",
			"one person's trash",
			"kofe isolation",
			"reliya's scraphawk",
			"recruiter of irregulars",
			"dark seas of shiryen",
			"ethersketch blueprints",
			"infamous bilgecaptain",
			"encore of the drowned",
			"specimen suit",
			"nestled delta",
			"unshackled revolutionary",
			"helicos-drowned captain",
			"maaru's hoard",
			"manifest corruption",
			"tinbeard of the brine",
			"exultant oni",
			"beragnian blacksmith",
			"coral plunderers",
			"roggar's mastery",
			"profane flames",
			"harvesters gone haywire",
			"hookhand freebooter",
			"vitin slagshaper",
			"ironsmash drill-delver",
			"discoveries of akieva",
			"fretport market smuggler",
			"surviving ndengo",
			"ophorio scavenger",
			"octopus shiny-grabber",
			"da'lang's preyscenter",
			"out of fashion",
			"myrmidon's plunder",
			"death pits gladiator",
			"croakfolk marsh-baron",
			"chaos of the conflux",
			"steward of empire's cradle",
			"ontarachie curio",
			"sower of sabne's harvest",
			"press-gang recruiter",
			"lizaveth's surveyor",
			"amira, grand inventor",
			"erduk, settled nomad",
			"copperhide calf",
			"playful scalchopper",
			"relitian renegade",
			"glitch, cosmic dreamer",
			"blistering boneyard",
			"shrine of the world-shepherd",
			"stormforged guardian",
			"hitana's implements",
			"incubated energy",
			"consortium astrolabe",
			"phantom walker",
			"bar-room brawler",
			"siv katari, rebel technician",
			"soul of muetar",
			"farmyard",
			"pompous explorer",
			"deadly harpoon",
			"amateur munitionist",
			"gate of realms",
			"delve into karsus",
			"company cannibalization",
			"voidtouched nightblade",
			"no-good gunpointer",
			"scoundreleo",
			"metal munch",
			"olson's sky brigade",
			"changing seasons",
			"tinyvale treetops",
			"bleakrealm moor",
			"dawn hill outskirts",
			"fabled passage",
			"flamingo rock",
			"frondpond grotto",
			"gloomhollow woodlock",
			"highpoint shrine",
			"humble abode",
			"fang den jaws",
			"slipsand oasis",
			"supply hauler",
			"siltbottom freebooters",
			"exotic isle",
			"explorer's torch",
			"x marks the spot",
			"tinyvale trappings",
			"ancestral tapestry",
			"old-rune sentinel",
			"leafdown amulet",
			"weedy whackers",
			"hoof cliff horngrove",
			"captain fina redtail",
			"salty dog",
			"karoa, his roaring grace",
			"the grand conchport heist",
			"crossroads town",
			"northrime aurora",
			"take all you can carry",
			"tavern brokerage",
			"steadfast smite",
			"minstrel's armor",
			"northrime privateers",
			"olson's flockmaster",
			"blade of the valiant",
			"rugged expanse",
			"travel pouch",
			"eon campfire",
			"old-rune watcher",
			"olson's armada",
			"dawn hill raiment",
			"leafdown ambusher",
			"pieces of eight",
			"barx, interplanar mastermind",
			"tapestry of united onora",
			"shadowstep shawl",
			"suspicious gambler",
			"paw valley alpha",
			"onoran runeglyphs",
			"memorial to sir jasper",
			"breathtaking valley",
			"whiskered buccaneer",
			"sentinel's pike",
			"admiral olson stout",
			"siltbottom tax collectors",
]

		names
			.map{|n| db.cards[n]}
			.flat_map{|card| card ? card.printings : []}
			.to_set
	end

	def to_s
		"tinbeard"
	end
end