class ConditionIsAdventure < Condition
	def search(db)
		names = [
			"valdez, leafdown vagabond",
			"adventurer extraordinaire",
			"dawn hill bellringer",
			"safety expert",
			"wayfaring mentor",
			"tinyvale finch-corps",
			"nimblefoot",
			"tongue twister",
			"siltbottom friendfinder",
			"galetwister mage",
			"highpoint guru",
			"slipsand ritualist",
			"no-good gunpointer",
			"gloomhollow scalesage",
			"conchport crook",
			"scoundreleo",
			"leafdown sizzlemage",
			"fang den flunky",
			"wimbledon's herald",
			"kula's disciple",
			"fang den bouncer",
			"paw valley pathfinder",
			"mouseketeer",
			"tinyvale treetops",
			"bleakrealm moor",
			"dawn hill outskirts",
			"flamingo rock",
			"frondpond grotto",
			"gloomhollow woodlock",
			"highpoint shrine",
			"fang den jaws",
			"slipsand oasis",
			"burning hart",
			"fennek farstrider",
			"cobri, slipsand scoundrel",
			"gruff, karoa's right paw",
			"acolyte of azos",
			"scourge of the slipsands",
			"dawn hill patriots",
			"salty dog",
			"hoof cliff caretaker",
			"toxic miscreant",
			"frondpond errand-runner",
			"strict tutor",
			"leafdown hunk",
			"dawn hill forgemaster",
			"northrime aurora",
			"valdez, leafdown vagabond",
			"highpoint hymncaller",
			"swiftspear ambusher",
			"wrathful meditant",
			"siltbottom conductor",
			"valdez's strike leader",
			"paleolizard",
			"northrime privateers",
			"hoof cliff roughrider",
			"paw valley wildclaw",
			"sturdy oakclimber",
			"shifty fink",
			"aurora weaver",
			"sunwatcher aspirant",
			"blessed suncrusher",
			"fang den headhunter",
			"whiskered buccaneer",
			"sir roger wimbledon",
			"sentinel's pike",
			"critters' companion",
			"mikkino, realized greatness",
			"panya of lands unknown",
			"aegisul, the sunspear",
			"cloud swine",
			"hyle's gift",
			"inconspicuous platypus",
			"mother roo",
			"scrappy hatchling",
			"seaside skimmer",
			"slippery bunyip",
			"duwinda hunter",
			"second death",
			"shadowlurk",
			"token of tribulation",
			"trophy taker",
			"hand of the fallen",
			"blood constrictor",
			"cartographer's step",
			"charging cassowary",
			"duwinda sniper",
			"little pig",
			"the lonely hunter",
			"curious amalgam",
			"drop bear",
			"sluggish sage",
			"inconspicuous platypus",
			"irbek, crocodile hunter",
			"feathersword duelist",
			"the undercity amalgam",
			"aurora hydra",
			"ominous dragoncaller",
]

		names
			.map{|n| db.cards[n]}
			.flat_map{|card| card ? card.printings : []}
			.to_set
	end

	def to_s
		'is:adventure'
	end
end