class ConditionIsPlayable < Condition
	def search(db)
		names = [
			"wayfarer's shrine",
			"nebula of empty gold",
			"seal the tomb",
			"pith wilt",
			"stand unassailable",
			"duress",
			"flooded depths",
			"mysterious cataract",
			"magmatic torrent",
			"shifting glade",
			"crystal cavern",
			"murmuring falls",
			"grim bastion",
			"shardstone rift",
			"nomad's township",
			"crumbling precipice",
			"sedate tundra",
			"scorch",
			"amber hills",
			"lush oasis",
			"ocean monastery",
			"monument of queens",
			"timber range",
			"resplendent substratum",
			"flooded morass",
			"stolen secrets",
			"cursory glance",
			"fungal mire",
			"cosmic sinkhole",
			"event horizon",
			"arctic mine",
			"barren desolation",
			"rampant summit",
			"prying inquiry",
			"shal'draen's rage",
			"forgotten steppe",
			"sunlit highland",
			"out-of-body experience",
			"roggar's frenzy",
			"frostfire geysers",
			"lavatorn fields",
			"exeunt",
			"lumbering hillock",
			"pool of light",
			"memento mori",
			"sacrificial bull",
			"nereba, sandchoked archives",
			"recall forgotten eons",
			"portal fracture",
			"negate",
			"journey's end",
			"titan snare",
			"mana ascetic",
			"corpsebed",
			"soul gate",
			"descend on the helpless",
			"cane dancer",
			"gloomcover steppe",
			"voidflare",
			"still the pandemonium",
			"mirrorgate",
			"singularity's grasp",
			"spell pierce",
			"violent collapse",
			"oracle's vision",
			"shikai's redoubt",
			"wheat from chaff",
			"xanigan, the darkened cloud",
			"thought blossom",
			"heart of the glade",
			"flourishing crevasse",
			"guiding light",
			"solar flare",
			"whisperwoods exploration",
			"monkeyshines",
			"nature's claim",
			"mpumo, who stands alone",
			"sealed riftway",
			"spiraling canyon",
			"intrepid",
			"stormsurge",
			"many-voiced tower",
			"seek prophecy",
			"murky peat",
			"tsang jin, master of the jade sea",
			"dark bargain",
			"pay up",
			"bahum, the warden",
			"tenacious guide",
			"sigil of radiance",
			"bounty of the gardens",
			"anzen, beyond the sea",
			"inishtu, desert healer",
			"unceasing flames",
			"prodigious panya",
			"the high prairies",
			"polyp pools",
			"rage of the ravaged",
			"heart of zhedina",
			"tiny heroine totti",
			"forbidden treasure",
			"union rail strikebreaker",
			"northern express line",
			"rakkiri dissident",
			"basat charm",
			"banished companion",
			"gleaming river",
			"a planet far, far away",
			"children of the clouds",
			"aerie's pillar",
			"jade vault reclaimer",
			"villainy",
			"unjust sentence",
			"unraveling",
			"tropical grove",
			"chi lee of the underworld",
			"rousing rubble",
			"conjure realities",
			"brine fleet bay",
			"cradle of corruption",
			"valdez, leafdown vagabond",
			"shifting cascade",
			"lucien, the grifter",
			"leyran alpha",
			"antimagic",
			"sea of skies beyond",
			"jobiah, devoted farmer",
			"etherium abrogator",
			"vibrant rapture",
			"terraformer's globe",
			"profane emissary",
			"once abandoned",
			"neutralize",
			"hierarch ranger",
			"ostracizer orb",
			"endless helpless souls",
			"imperial siege",
			"veilborn meddler",
			"bessie's brood",
			"setting sun",
			"shugenja sanctuary",
			"ancestral council",
			"end of all things",
			"imperial claim",
			"tal, locus sentry",
			"shifting grove",
			"destructive ambition",
			"rot",
			"find happiness in misery",
			"unearth",
			"lumenbay flyer line",
			"sunwashed spires",
			"ignition ritual",
			"dovon, verdant experimenter",
			"departed evangel",
			"fractured reach",
			"ruin delver",
			"rock",
			"dreamsight well",
			"seto san, the dragonblade",
			"bloodriver",
			"brazen sacrilege",
			"volatile stonework",
			"verdant dominion",
			"fogspewer",
			"forked pillar",
			"temporary treason",
			"gift of the phoenix",
			"warded tome",
			"suitor of the sea",
			"heist headquarters",
			"face the dawn",
			"epic encounter",
			"chains of subdual",
			"stalwart dominion",
			"new divide",
			"bant command",
			"aiel tazan",
			"civilization's cost",
			"invalidate",
			"sea cache",
			"mindstorm's eye",
			"sights beyond",
			"shifting crag",
			"reveal eternities",
			"antithesis",
			"vast savannah",
			"opt",
			"idyllic odyssey",
			"precursor sanctum",
			"end of days",
			"fiery erasure",
			"admonish",
			"tamiyo, lunar arcanist",
			"tidehollow lich",
			"glistening chalice",
			"powder scatterer",
			"confirm hypothesis",
			"embodied soul",
			"thunder road",
			"earthbreaker behemoth",
			"social graces",
			"spirit script",
			"logger recluse",
			"unquenched greed",
			"kaur, end of lies",
			"channeling stone",
			"scion of torrents",
			"impden mother",
			"masahita, bloodtongue",
			"abscond",
			"mosecf, the sunseeker's path",
			"long forgotten",
			"kellythross' workshop",
			"sporeflow protector",
			"garth of the chimera",
			"shifting canyon",
			"chikyu champion",
			"lord rickard dawson",
			"performer of ambition",
			"self replication",
			"rift splicing",
			"grim slums",
			"reconsider",
			"galvan coal line",
			"tendrilsnare",
			"strike from the shadows",
			"diffuse",
			"blood jade prophet",
			"mabil fardancer",
			"brutal blow",
			"corrupted memory",
			"once shunned",
			"stormshaper adept",
			"crystal wave",
			"kati evalin, world wanderer",
			"dead man's party",
			"theocracy",
			"fair trial",
			"hugo of the shadowstaff",
			"sunken ambitions",
			"deform sanity",
			"tyrant of tributes",
			"mystery of the crashed craft",
			"plasma addict",
			"tend to the grove",
			"infectious ego",
			"crossing the fog",
			"shifting morass",
			"monument to the fallen man",
			"nightwatch rallier",
			"dispel",
			"stay determined",
			"leija's greenblade",
			"redtail fencer",
			"flaming point technique",
			"crewmaster gillo",
			"zaukar of the ancient ways",
			"roggar's gambit",
			"the flames approach",
			"dawson's loot",
			"avatar of basat",
			"glitch, galactic muse",
			"coralight champion",
			"noxious upwelling",
			"shadowband consul",
			"what lurks beyond",
			"distant thunder",
			"beneath the zhedina",
			"bottled lightning",
			"farseek",
			"velir the sunderer",
			"kaalia's abomination",
			"sorcerous spyglass",
			"caulte axeslinger",
			"silent hypnotist",
			"emissary of antiquity",
			"seedshrine",
			"hellion devastator",
			"kinken, the dragon's breath",
			"autumnal watch",
			"beckon of the wild",
			"herald of oblivion",
			"primal ruffian",
			"answer midnight's call",
			"stalked healer",
			"canyon creek",
			"fiery burst",
			"cleared vault",
			"helene trant",
			"parrot pools",
			"explore",
			"ignition point",
			"ancient dominion",
			"priestess of simplicity",
			"ceaseless stalker",
			"sabne's autumn",
			"twilight ambush",
			"avatar of the natural",
			"ever-gnawing rat",
			"rapacious rattler",
			"mysterious coffer",
			"seabreen nullmage",
			"fellor charm",
			"ninhasir's march",
			"whiterun ordainer",
			"budding companion",
			"nacatl skirmisher",
			"explorer's fate",
			"lord rokai",
			"tether of simplicity",
			"vaultkeeper",
			"gaze deeper",
			"soaring canyon",
			"ria-demian charm",
			"anointed cursebreaker",
			"archive guardian",
			"bearer of the lantern",
			"ruinous naga",
			"academic's claymore",
			"scuttling gnat",
			"brushcover elf",
			"martial maestro",
			"silent wanderer",
			"ambitious necromancer",
			"veteran lifeforger",
			"temporal resuscitation",
			"endless discoveries",
			"calamitous crash",
			"promethean grotto",
			"lord ellison crain",
			"mastery of the veil",
			"azun, sheriff of daisite",
			"palace of reflections",
			"the afterlife takes its due",
			"resonating force",
			"pristine dominion",
			"bitter duckling",
			"jara champion",
			"azamir, wayward titan",
			"staff of equilibrium",
			"abandoned monument",
			"replicator mage",
			"curse of bleeding",
			"parish paragon",
			"desolate dominion",
			"corvid heretic",
			"iviana, speaker of fangs",
			"all-enduring mafua",
			"oppress the weak",
			"danithra muckbruiser",
			"relic corrosion",
			"harm's way",
			"obscoriate",
			"crack open the cache",
			"egg of avarice",
			"backstage rooms",
			"ethereal armor",
			"siesa tremund",
			"seismic colossus",
			"no rest",
			"smoldering pages",
			"clockwork gaucho",
			"qililia, the saboteur",
			"zhelid, planar academy",
			"alratha, pearl of the sand sea",
			"seto san, the sacred hand",
			"kalemn weller",
			"enter mephisto's gate",
			"scion of flourishing",
			"putrid lurker",
			"redo",
			"curse of the drow",
			"tempered ankulim",
			"meteor volley",
			"hungering cult",
			"metal munch",
			"cognitive fumigator",
			"starlit raze",
			"irika, wielder of secrets",
			"perilous passage",
			"confining priest",
			"mystic arts",
			"wave of decay",
			"helena, the awakener",
			"idravir, the last city",
			"one with the world",
			"turi of hollow depths",
			"reflected moment",
			"soul warden",
			"plaxolotl pyari",
			"gilded gearhulk",
			"eli windsors, lone gun",
			"coastal dominion",
			"titanic fossil",
			"lilyreed triton",
			"forbidden burial",
			"verdant bluff",
			"golden touch",
			"fateful journey",
			"conspiracy of ravens",
			"arpechian champion",
			"anomalion",
			"forgotten pit",
			"cumulus horizon",
			"fey grove",
			"lt. daisy saxon",
			"renewal grove",
			"facsimile of divinity",
			"lhosei of the ghost peak",
			"forest fellowship",
			"infuse the apparatus",
			"fiery temper",
			"frailty",
			"soul leak",
			"worlds away",
			"devised companions",
			"noble's hedonism",
			"ardy's invocation",
			"babyscale bruiser",
			"void portal",
			"imagine",
			"sevid, the lookout",
			"fireshaper adept",
			"miyoga firebird",
			"crystal garden",
			"flare blitz",
			"starjump",
			"moment of tranquility",
			"sedraxis trepanator",
			"flesh to rot",
			"dark rite cultist",
			"a journey begins",
			"mausoleum suffragan",
			"scion of fecundity",
			"elrayin, the manaroot",
			"ravaged monument",
			"chratteri restoration",
			"barren boneyard",
			"arcane chronometer",
			"amelie mayn",
			"waxing angel",
			"hazy moorland",
			"mable of the sea's whimsy",
			"unassuming swineherd",
			"suzume oshiruko",
			"convert to resources",
			"reinvent",
			"unlikeliest heroes",
			"currency",
			"primal dominion",
			"tidal spite",
			"heraldry",
			"crystal conjuration",
			"caylin whirlwind",
			"bind the mind",
			"possibility engine",
			"chikami castle",
			"scion of desolation",
			"krismite vault",
			"squid pro quo",
			"will of a fickle lord",
			"oshin, keeper of the shoal",
			"finish off",
			"find nothing",
			"sear flesh",
			"tenuous existence",
			"shadowed slums",
			"forbidden brew",
			"servant of armageddon",
			"rain of ruin",
			"paragon of honor",
			"petal-weaver alexa",
			"unforget",
			"keeper of the sanctum",
			"tinkerer's tools",
			"shining crusader",
			"head of ulko",
			"watch from above",
			"xirix, the usurper",
			"adam of the ironside",
			"seek the lost child",
			"consult ancient knowledge",
			"dockyard swindling",
			"truth unveiled",
			"rain zai, spiritscale",
			"consult the dewdrops",
			"into waridi valley",
			"lone survivor",
			"emerabi's disciple",
			"xiong mao, the intrepid",
			"bal's descent",
			"legitimate establishment",
			"fulmen, aether prodigy",
			"tabia of the lionheart",
			"iken troubleshooter",
			"rippling curtain",
			"forgemaster's altar",
			"conjuring of locusts",
			"gallord's ascension",
			"aguri, shadow of doubt",
			"scion of storms",
			"warhound shuja",
			"soliloquy",
			"the last sacred gate",
			"buy time",
			"last stop",
			"helene, steel of the exiled",
			"dusk lieutenant",
			"sunrise river",
			"master of tranquility",
			"rune-scribe's apprentice",
			"tear loose",
			"aethermancer's familiar",
			"kantra of old majik",
			"pitchpyre curse",
			"profound introspection",
			"dead-set duo",
			"cinderblade",
			"founding hero",
			"ema, the traveler",
			"sun-sigil ordainer",
			"monsoon lagoon",
			"jak, daring vanguard",
			"crystal grotto",
			"unlit alley",
			"path of fire",
			"timestream sentinel",
			"by the sea",
			"zhedina envoys",
			"ardy, youthful geomancer",
			"banish",
			"shinrei of the ghosting way",
			"witch's invocation",
			"orichi of the cold mist",
			"slaffield workgate",
			"hall of random access memories",
			"far wandering guardian",
			"marisa of the gravehowl",
			"nightmares unseen",
			"blessed spellroot",
			"death pits hawker",
			"frigid thicket",
			"haunted boughs",
			"sworn cohort",
			"a flawless world",
			"journey to the otherworlds",
			"danuri charm",
			"anguished unmaking",
			"rei's reinforcements",
			"the moon rises",
			"sadistic indulgence",
			"croakfolk troubadour",
			"into the unknown",
			"tt-23 aegis",
			"once scarred",
			"source decay",
			"adiran distractor",
			"overgrowth guardian",
			"rugged dominion",
			"fox of the orange orchard",
			"sunrise prairie",
			"forgotten lessons",
			"ruined precipice",
			"sarrutu flamebinder",
			"power plant",
			"emperor's retainer",
			"rustshell crustacean",
			"soulbreaker of mautakesh",
			"sofia, fortune's fated",
			"performer of desire",
			"aquilifer axelius",
			"warfield excavator",
			"imperial port",
			"gyreon pickpocket",
			"anarchy storm",
			"lodestone golem",
			"caller of hunger",
			"charming marauder",
			"worried vulpine",
			"imagination unleashed",
			"imperial coins",
			"echoing knowledge",
			"willow spirit",
			"hesediel, the reborn",
			"rahstahde's command",
			"underpass sentinel",
			"soul release",
			"seeker of mysteries",
			"hemley eggfeather",
			"council's will",
			"recoil",
			"earthfeeder worm",
			"timely reinforcements",
			"ayala's concord",
			"xira, scatterer of seeds",
			"hub of innovation",
			"legendweaving",
			"all or nothing",
			"left on the wayside",
			"summit guardian",
			"cranial violation",
			"nidohagane warfans",
			"oil driller",
			"jade temple",
			"fierce combatant",
			"breach the lilies",
			"dawn hill forgemaster",
			"ready for anything",
			"stormchaser mage",
			"felice, adira's salvation",
			"forgotten shrine",
			"hunter's hideout",
			"blundering clocktower",
			"persevere",
			"resign to madness",
			"angel of succor",
			"cosmic war",
			"unexplored regions",
			"blossoming defense",
			"master negotiator",
			"rod of marble row",
			"transplanted citadel",
			"needless atrocities",
			"secrets of coralight court",
			"zhedina valiant",
			"bogborn charger",
			"guardian's revocation",
			"liliana at the brink",
			"shimmering dragon",
			"anuran encounters",
			"sera of coppercove",
			"exploring the mirrorworlds",
			"serene prayer",
			"champion of scales",
			"sun yun, master of self",
			"cadre hawk",
			"qilan wanderer",
			"hannaru's courage",
			"soul's attendant",
			"minister of madness",
			"daisy, the heart of chasmek",
			"untouched wilds",
			"seeker lizaveth",
			"wayfaring pilgrim",
			"impish delights",
			"ethereal fervor",
			"sunrazed ruins",
			"stormwake",
			"camouflaged sprareos",
			"shengin renegade",
			"paracosm",
			"the witch queens",
			"soul pierce",
			"fae-blessed attendant",
			"holcomb of the peregrine",
			"deflecting strike",
			"intrepid captain",
			"cosmic coalescing",
			"tunu, ancient shaper",
			"ameret, hope of night",
			"hatsuo's maneuver",
			"arcane metalcrafter",
			"lazaire's conjuring",
			"madcap mercenary",
			"howling shieldbreaker",
			"heart of the deadwood",
			"ajani resolute",
			"rootwarper",
			"bygone guardian",
			"skycaster's aura",
			"transnaturalist",
			"witch of spring's promise",
			"artificer's gift",
			"crest",
			"basalt ritualist",
			"rini, sundial archcleric",
			"roggar the furious",
			"thriving budling",
			"critters' companion",
			"fidelity of the pure",
			"judge's decree",
			"primal resurgence",
			"blood ritual",
			"publicly disgraced",
			"shinrin spellhunter",
			"remembrance of light",
			"deadwood terror",
			"death in reverse",
			"glymna blackrune",
			"aerial adept",
			"seeker of untouched beauty",
			"slashing pangolin",
			"caustic caterpillar",
			"all that glitters",
			"observer of aeons",
			"rawthlin market line",
			"bleak dominion",
			"shionoshio, ocean's vow",
			"trial recruitment",
			"realms overturning",
			"beckon the pack",
			"fade",
			"helene, bound by might",
			"mattia, hero of tinyvale",
			"cyone, expedition captain",
			"festival of winter's night",
			"carnival yatiri",
			"worlds colliding",
			"reconstruct",
			"young necromancer",
			"purging watchkeeper",
			"gateblessed explorer",
			"vivid mirage",
			"essential override",
			"molten falls",
			"conflux ravager",
			"thievery",
			"mark of dark opulence",
			"reweave reality",
			"flourishing dunes",
			"phantasmal owl",
			"bearer of tormented truths",
			"mourn no more",
			"weeping lotus",
			"enraptured countess",
			"tahli's council",
			"bustling marketplace",
			"loresprout",
			"lost in smoke",
			"dreadfire tyrant",
			"edith waunt",
			"champion of the fae",
			"fulfill twisted dreams",
			"wealth of the underbrush",
			"ainok lout",
			"ainok caretaker",
			"ainok alpha",
			"ainok hunter",
			"art of evasion",
			"featherfall ascetic",
			"flora acolyte",
			"sewer pack",
			"spellbane adept",
			"paragon of purity",
			"rend",
			"slaughterkeg",
			"stormcaller sentinel",
			"protective memory",
			"othersea submersible",
			"raid the forgotten tomb",
			"warden of silence",
			"turin's study",
			"mindwave rod",
			"byron's gambit",
			"academy renegade",
			"vengeful messenger",
			"hexfang ascetic",
			"greypelt initiate",
			"bourasan highguard",
			"zegarra, the rival",
			"imperial silks",
			"decree of bias",
			"overgrown refuge",
			"earthchannel apprentice",
			"resurging rhino",
			"darklands charm",
			"edarna the everforge",
			"collapse the pillars",
			"bogborn exorcist",
			"hanabira, kogane's legacy",
			"merrow legendmaker",
			"skypath pilgrimage",
			"valencia of the concordant",
			"first general of the wards",
			"experimental battle armor",
			"culling blade",
			"brutality",
			"marshy marauder",
			"clean-up crew",
			"evaldi's muse",
			"seedy bar",
			"highland dunes",
			"rahstahde, word of truth",
			"shift the sands",
			"the mind falters",
			"aiko, tranquil fury",
			"el, humble apprentice",
			"vir of the starskipper",
			"miner's barracks",
			"coppergild mercenary",
			"rabid thrill",
			"advocate of the hunt",
			"mukhif the grim",
			"merciful yuroda",
			"moonlight sanctum",
			"zhedina bazaar",
			"chantwood channeler",
			"ethereal spellmaster",
			"dreamsteel paladin",
			"sealed mausoleum",
			"maghbri oracle",
			"merchant of false lives",
			"pyremage's knack",
			"mountain bighorn",
			"burning revelations",
			"blazing volley",
			"herald of wisdom",
			"reckless festivities",
			"salva tore",
			"vasille rioters",
			"ivenge, false god",
			"burning up",
			"suburban runebrawler",
			"searing grace",
			"fiery truthseeker",
			"brothers' reunion",
			"kinjiru assailant",
			"bahum's penance",
			"grove's respite",
			"mossy companion",
			"zoulev offering",
			"volcanic pounce",
			"astute prophet",
			"demolitionist deviser",
			"junktrawler",
			"soulblade",
			"recurring abomination",
			"flatboat artisan",
			"champion of destinies",
			"accursed by unborn fates",
			"vicious slasher",
			"plasma blader",
			"rest",
			"duskwood vanguard",
			"clutch of the coil",
			"starlight beacon",
			"zhedina outskirts",
			"osk, the maker's pet",
			"unburdened rage",
			"zareen, the second shah",
			"posey, of the seal cloak",
			"burning hart",
			"chigau, the red market",
			"fireheart channeler",
			"relic heist",
			"extravagant flair",
			"grove of embers",
			"chart the vast",
			"jejun, dark hunter",
			"from ancient tomes",
			"vanish",
			"tomb steward",
			"root dancer",
			"unity spheres",
			"memories reignited",
			"forbidden truths",
			"false vitality",
			"sanaito, alone",
			"lucien's trail",
			"cloud rock",
			"supreme stampede",
			"find greater purpose",
			"krismite purveyor",
			"royal domain",
			"imposition",
			"titan's palace",
			"the court of angels",
			"myrmidon, coralight exile",
			"channel the mirror",
			"coralight paladin",
			"death pits trophy",
			"ophidian oracle",
			"world made anew",
			"barx, interplanar mastermind",
			"justiciar overseer",
			"pineblight caribou",
			"kaone of the golden sonata",
			"seasons of war",
			"veil's recovery",
			"farmer's repose",
			"ardy's study",
			"withering husk",
			"pocket aces",
			"volta, construct consultant",
			"ring of souls",
			"spectral skycruiser",
			"border guardian",
			"mystic's mantle",
			"choking despair",
			"ghastly ferry",
			"gilded gulch",
			"great sable stag",
			"master of elements",
			"illusionary steed",
			"hymn of fury",
			"ruinous proselyte",
			"myrmidon's warhead",
			"mina, jeweled minnow",
			"coercive methods",
			"rainy night lovers",
			"duskwood thicket",
			"stormwing raven",
			"apprentice summoner",
			"burning heels",
			"blade of the serpent",
			"thin the veil",
			"hegemony monarch",
			"chattering parrot",
			"faerie infiltration",
			"commanding princess",
			"shawlbinder",
			"epoch warden",
			"mercantile accords",
			"dedicated weaponsmith",
			"adiran scryers",
			"once denied",
			"wicked blow",
			"shrine of the six pillars",
			"legends remembered",
			"essence inversion",
			"rujan, the great pumpkin",
			"interan skycaster",
			"vedalken machinist",
			"tear through",
			"untethered disciple",
			"chemical grenade",
			"erollin, eccentric collector",
			"headwind glider",
			"rejoicing aristocrats",
			"sword of tides and time",
			"meteor harbinger",
			"stabilize",
			"entrail elemental",
			"guard of cuirassiers",
			"inoshi the wild boar",
			"master of masks",
			"ill fated travels",
			"vythraktos, master necromancer",
			"kazimir's ban",
			"powercell engineer",
			"wisdom in reflection",
			"mettalia, light from above",
			"culminating despair",
			"legacy warmask",
			"eye of the beholder",
			"favorable winds",
			"idyll",
			"warden of time",
			"return to form",
			"speaker of the iris",
			"armadillo cloak",
			"voiceless assailant",
			"magister of impotence",
			"sharuum, archmagocrat",
			"student of the coil",
			"scion of scales",
			"fang of mautakesh",
			"serpent's grasp",
			"down with the ship",
			"timeworn crags",
			"overwhelming armies",
			"patient optimizer",
			"wailing chorus",
			"paygan archer",
			"muktann protectors",
			"queen andarli, the fierce",
			"pensive songwriter",
			"karaja hetegex",
			"pronouncer of preserves",
			"grave tutor",
			"voliv ritualist",
			"instant of brilliance",
			"sword",
			"fardancer liege",
			"expedition post",
			"arcane duelist",
			"reclamation grovesculptor",
			"prismatic leyline",
			"fatal edict",
			"spitfireling",
			"starbane elemental",
			"onyx ritualist",
			"vibrant flames",
			"threshing sundew",
			"raiun bay admiral",
			"dust barrens",
			"razione racecourse",
			"nightmare riders",
			"fanciful bloom",
			"dragoncalling",
			"reforge",
			"chiu of the wild realm",
			"invoking the name",
			"wild lifescale",
			"corecharge",
			"coralight mystic",
			"offerings to the deathless",
			"possibility scope",
			"bustling harbor",
			"one bad night",
			"dragongate",
			"selvar's defiance",
			"alvarez of the huntsman",
			"propagation plant",
			"amber reserves",
			"strongarm",
			"sankataar scourge",
			"searle of the tempest",
			"salvage titan",
			"amongst the flames",
			"wish to see",
			"nip at the heel",
			"glimpse in the static",
			"cosmonaut pioneer",
			"no-good gunpointer",
			"swarming midden",
			"reflect on serenity",
			"arboreal runes",
			"frilled drakeling",
			"shroud of hinasa",
			"syzygy navigator",
			"careless violence",
			"immortalize in stone",
			"barricade patrol",
			"gyreon smuggling",
			"manifest memories",
			"rejuvenation",
			"golden glade",
			"iron warden",
			"planeswalker's insight",
			"brilliant academy",
			"diasune immolator",
			"forgemaster's charm",
			"xing, the lucky charm",
			"through the ashen gate",
			"the aetherite saloon",
			"supreme mechanothurge",
			"awaken to the skies",
			"boundless evolution",
			"rafiq the magnanimous",
			"naya command",
			"insurgent ballads",
			"adoroth, the baneful",
			"aureate panorama",
			"helm of the infinite",
			"dawson's collector",
			"iron signet",
			"sunrise orchard",
			"lucien, the ravenous",
			"fungal swathe",
			"tower of long shadows",
			"confront the riddlemaster",
			"rampant growth",
			"burgeoning blooms",
			"whirling thoughts",
			"equanimity",
			"offworld surveyors",
			"seek guidance",
			"servant of precursors",
			"edge of the world",
			"greypelt brute",
			"reduce to naught",
			"flotsam",
			"creed's desperado",
			"unhappy ending",
			"three cheers",
			"sihari, fury of the dunes",
			"eroded sanctuary",
			"dha-bukan, jewel of the dunes",
			"performance of a lifetime",
			"chevalier's lance",
			"azos, tyrant of bleakrealm",
			"sevenfold summoner",
			"sentinel of latter days",
			"fallback plan",
			"dragon's ire",
			"wightlight",
			"pyramid lord",
			"glimmer",
			"photon barricade",
			"kagetsu, chronicler of jidai",
			"crimson hellmaw",
			"between life and death",
			"kantra of bounty",
			"wellspring of creation",
			"blissful lull",
			"foulweather effigy",
			"edge of the water",
			"pyroclastic maw",
			"reclamation sage",
			"crystal cauldron",
			"duelist's forms",
			"unstable footing",
			"culminating wisdom",
			"shigurei, the floodbringer",
			"stickup",
			"paleontologist",
			"weaver of mists",
			"zhedina confiscator",
			"helping hand",
			"animorph",
			"unified theory",
			"heirloom",
			"house of forgotten whispers",
			"iterative design",
			"mind-mute",
			"duskwood revolutionary",
			"exiled necromancer",
			"sungrace meadows",
			"militant youth",
			"entrancing light",
			"spring renewal",
			"endless expedition",
			"njel crocodile",
			"seeds of new life",
			"helena's rebuff",
			"channeler of the veil",
			"immolated grave",
			"reflect upon the past",
			"chew the scenery",
			"flash of inspiration",
			"right to rule",
			"oracle's ploy",
			"hostile atmosphere",
			"stonewood sanctuary",
			"glorybound chorister",
			"shemesh, nomad chieftain",
			"zadyk resourcefulness",
			"heaven, presidential ship",
			"spirit pendant",
			"procedural genesis",
			"volcano tyrant",
			"pull away",
			"call of the huma",
			"recreator of myths",
			"deadly harpoon",
			"graide, voice of autumn",
			"ecological refuge",
			"blooming needles",
			"impromptu escapade",
			"selective breeding",
			"rhysta of the roses",
			"griffin country",
			"tyrant's breath",
			"unrelenting",
			"prismatic champion",
			"soul jar",
			"dead man's hand",
			"caronas, eon wanderer",
			"adoration",
			"guardian's resolve",
			"seek the future",
			"calamity dragon",
			"haunted fairground",
			"roads untraveled",
			"disassociate",
			"harriet, liberated wildborn",
			"stolen cache",
			"elegant strike",
			"tinkering swarm",
			"syrina, the dragon queen",
			"antali archdruid",
			"ironeyes desperado",
			"sinister pact",
			"thallid cultivator",
			"bloodbraid ritualist",
			"sprout thought",
			"shatter the mask",
			"whirlpool ride",
			"enlightenment",
			"spotless mind",
			"the whisperwoods",
			"bahum, penitent",
			"takeda taro",
			"ketsueki, kiyomi's legacy",
			"sylvan scrying",
			"hasty intervention",
			"kevthra's command",
			"fortune charm",
			"miyoga dragonsoul",
			"voidlife orbs",
			"bewitching vapors",
			"shroud the world in doom",
			"joyous explorer",
			"awaken the nav",
			"golden company tactics",
			"time in a bottle",
			"emissary of dark tides",
			"touch of the coil",
			"recruits of the demeter",
			"broadside raider",
			"mieng, who dances with dragons",
			"elemental of surprise",
			"trident of benediction",
			"ralora, unforgiving depths",
			"descend upon the tomb",
			"sunset monastery",
			"nadei the wavecaller",
			"glimpse beyond",
			"derelict amphitheatre",
			"into the woods",
			"hidden garden entrance",
			"trade route bandit",
			"parasitic rebirth",
			"beckon the damned",
			"subdue false idols",
			"dovon's masterwork",
			"convoy's companion",
			"buzzard barrens",
			"efflorescence",
			"merciless shieldbreaker",
			"margyd's celebrant",
			"vorganisaath's flamewaker",
			"inexorable epidemic",
			"secluded courtyard",
			"cloudpeak spires",
			"mei's collection",
			"realmwalker domovoi",
			"colossal achievement",
			"wild lightning",
			"nomadic patriarch",
			"asharo's handmaiden",
			"rhys, keeper of scriptures",
			"wisdom of the leylines",
			"imperial artisan",
			"phyrexian arcforger",
			"phasmopillar",
			"commune with kantra",
			"weeping soul",
			"hao'tai, the ancient one",
			"shared reminiscence",
			"resounding relief",
			"brilliant citadel",
			"autumn canopy",
			"guardian of the divergent",
			"abandoned laboratory",
			"interan soothsayer",
			"mobilize the heavenly",
			"master of imports",
			"reenter orbit",
			"rocket admin",
			"maelstrom elemental",
			"bittersweet reunion",
			"ancient counsel",
			"puppeteering",
			"ruchi, the effervescent",
			"radiant bonds",
			"behemoth channeler",
			"from peace and purpose",
			"madelon, merchant's heir",
			"masquerading bohemian",
			"scion of calamities",
			"bearer of fables",
			"appeal to the ancestors",
			"phantom threader",
			"phantasmal possession",
			"risen looter",
			"selene the cruel",
			"miraculous genesis",
			"tomb of shifting sands",
			"fathom diver",
			"mountain runt",
			"rylei wakebreaker",
			"fleeting memory",
			"mele, the onemother",
			"godwatcher",
			"dark behemoth",
			"lofty denial",
			"fine craftsmanship",
			"brilliant mansion",
			"ghulish unearthing",
			"malefic portal",
			"working together",
			"wanderer of endless paths",
			"fleeting moments",
			"sweep the leg",
			"dustridden sepulcher",
			"delve for treasures",
			"dazzling dreamspinner",
			"mawdryk's harrier",
			"lorilyf, home-tree",
			"hookhand freebooter",
			"olson's flockmaster",
			"karoa's downfall",
			"astralhorn familiar",
			"brimstone oration",
			"korrinary warcaller",
			"serene chapel",
			"irbek, crocodile hunter",
			"calcified dunes",
			"imperial proclaimer",
			"fashionable heiress",
			"oracle's disciple",
			"high chancellor kazimir",
			"amulet of loyalties",
			"kiri, cloudwalker",
			"one",
			"ravaging tyrant",
			"disallow",
			"gathering the gang",
			"wandering souls",
			"planar eviction",
			"kaor awoken",
			"festival of fading lights",
			"foreseen denial",
			"the frontier beckons",
			"equilibrium paladin",
			"rilken forcefield keeper",
			"claimed by the veil",
			"hembwe, the all-mother's hand",
			"rainbow phoenix",
			"festival of roaring dragons",
			"war-pride champion",
			"calming dromoryx",
			"arcanist's reaver",
			"morose harpist",
			"cloudbank",
			"blossom-sower witch",
			"temporal insight",
			"brilliant capital",
			"abandoned meadow",
			"twin lis of the divine realm",
			"wayward afflicted",
			"grim armory",
			"ascension",
			"fateful eruption",
			"rokai's vassal",
			"vengeant precursor",
			"lava plume",
			"trace the leylines",
			"synapstorm",
			"spilling secrets",
			"archaelogical experience",
			"once betrayed",
			"awakening the dragon",
			"sporeflow mantle",
			"opulent proprietor",
			"scourge of the skies",
			"rewrite fate",
			"meddling gargoyle",
			"seedcall",
			"curator of cures",
			"villains: the musical",
			"derevi's adjutant",
			"cursed scroll",
			"cast out",
			"derail",
			"giradrus, ashen master",
			"scramble the scouts",
			"day of the emperor",
			"tranquil repose",
			"ambition's crown",
			"gift of eternity",
			"heathen rise",
			"aether road caravan",
			"brilliant castle",
			"knight of valimir",
			"guardian of mysteries",
			"blurring mists",
			"surge of the leylines",
			"cadalon outfitter",
			"hallowed moon sentinel",
			"risti workshop",
			"black hole musings",
			"fang of anaz",
			"x marks the spot",
			"scoundreleo",
			"studies in scientific theory",
			"dunecrest pariah",
			"territorial camaar",
			"darksand acolyte",
			"fluffpuff whisperer",
			"heists most daring",
			"paragon of noon",
			"martoob beastkeeper",
			"disciple of faradia",
			"marianne, the heartstopper",
			"taiyohata's dominion",
			"soul of iscathia",
			"mortality keeper",
			"ontarachie emissary",
			"fade into mists",
			"buoyant thoughts",
			"vitality unbridled",
			"sleight of hand",
			"chronofracture",
			"vedlinn ross",
			"only memories remain",
			"fleeting thoughts",
			"citadel of denial",
			"spectacle of innovation",
			"sandswept bazaar",
			"performer of growth",
			"cloudcover heights",
			"bond of battle",
			"strike down the usurpers",
			"conscription",
			"callow survivors",
			"final reckoning",
			"buried by time",
			"rush of wonder",
			"hannaru's spear",
			"festering waif",
			"lizhao, lord of the yaogu",
			"globule of sanctuary",
			"kaor's tithe",
			"vitality maestro",
			"keystone conjurer",
			"unzari ruins",
			"blessing of morning",
			"heavy moneybag",
			"gyr, awoken world",
			"seek refuge",
			"crossroad bard",
			"the lost titan",
			"breaker of secrets",
			"light within shadow",
			"sporegraft",
			"wardbane mystic",
			"heartwalker",
			"ferocious desert-hunter",
			"meteor fall",
			"propagation blade",
			"dylso charmer",
			"glintwing replica",
			"el-mazar, wayward palace",
			"xinan skycharter",
			"cypress, the wayfarer",
			"gilded spyglass",
			"sword of monsters and men",
			"fo-2 radiation kid",
			"nel toth shaman",
			"acorn assault",
			"demanding idol",
			"mennin reclamation",
			"bile of the world",
			"forgotten homelands",
			"elaborate transportation",
			"chiheisen, terrace of serenity",
			"collector of histories",
			"shoalshine",
			"coralight lifebloom",
			"bvala, queen of the swarm",
			"collect rotting remains",
			"eccentric gardener",
			"edina, coralight soothsayer",
			"ildirin, the apex blade",
			"curious disturbances",
			"perpetual motion machine",
			"secrets of the tower",
			"grin, scourge of goresand",
			"revela, star-touched",
			"verdict of the council",
			"venture into the muktann",
			"mirror reality",
			"fortune dealer",
			"steamlit peaks",
			"autumn moon",
			"sinslither",
			"dawson's negotiations",
			"explorer's torch",
			"pawsitive vibes",
			"raise the alarm",
			"rally the railguard",
			"duelist's poise",
			"maddened inferno",
			"pupil of lightning",
			"out of fashion",
			"sacrifice to setar",
			"lysandra, leyline trickster",
			"lysene, aravant spymaster",
			"getaway rider",
			"hellfire titan",
			"the roseblade",
			"stonevault blademaster",
			"fretport market smuggler",
			"restore",
			"champion of the provinces",
			"glimmerbark treant",
			"devotee of winds",
			"slippery bunyip",
			"dreams come true",
			"rahit's study",
			"backwoods cultivator",
			"dryad of the grove",
			"deserted trail",
			"thriving hydra",
			"refuse trawler",
			"moranai survivalist",
			"fate transfer",
			"inquirer, roaming rover",
			"torch the city",
			"ligos, shadow's source",
			"abandoned cairn",
			"sudden decompression",
			"vithian arcanist",
			"rallios' return",
			"mortal pilgrimage",
			"bleak shoreline",
			"taiyohata champion",
			"prophet of pacifism",
			"ice path",
			"magdel, caller of souls",
			"prismatic cavern",
			"clever rejoinder",
			"vibrant sandbar",
			"xenocrata, reality breaker",
			"ancient ossuary",
			"orphan of the nav",
			"charting the cosmos",
			"chamber of splendor",
			"kurayami shrine",
			"opportunistic raiders",
			"kimar, lightforger",
			"aether leak",
			"raloran tidecaller",
			"ill-fated profit",
			"kamu-tribe outfitter",
			"giltwork legacy",
			"saishuteki castle",
			"sword of silver and gold",
			"raidragos' avenger",
			"brilliant port",
			"battlesuit prototyping",
			"journey through kareki",
			"the warrior within",
			"tea of augury",
			"shizen, the thousand steps",
			"hashiro's devoted",
			"reverent flame",
			"expedition map",
			"virtual terrain",
			"sandstreamer",
			"aether pull",
			"ambitious dreams",
			"ifram, god of chaos",
			"yrodu, the lotus ablaze",
			"arbiter of the scales",
			"skeigr, skhorvall flagship",
			"kin of the rainforest",
			"herald of the departed",
			"the dominomicon",
			"thunderhoof mammoth",
			"high sovereign thura",
			"lumbering egil",
			"secret stash",
			"berylscale alaj",
			"riko, the paragon",
			"abandoned preserve",
			"acin, the toymaker",
			"vitality of blossoms",
			"nirami, ema's keeper",
			"dream of greatness",
			"experienced mentor",
			"lelin, the wise",
			"verdant cloak",
			"hollow wanderer",
			"bind the great evil",
			"searing insult",
			"bind in jade",
			"ferrofy",
			"mage's command",
			"across the threshold",
			"fatestitcher",
			"succumb to dreams",
			"eternal duneborn",
			"ancient gleam",
			"envious geist",
			"book return",
			"ire of ancient tomes",
			"the grand simurgh",
			"young forager",
			"hoof cliff horngrove",
			"brilliant workshop",
			"culminating chaos",
			"flamecaller's command",
			"tongue twister",
			"calmed battleground",
			"anthus's accomplice",
			"yaran's curfew",
			"asamund, queen of yroncaster",
			"humble abode",
			"esmerie, skysworn general",
			"bloodbriar archdruid",
			"candlegift",
			"shae, master evoker",
			"abrupt duplication",
			"macabre effigy",
			"breach the mind",
			"ashe of the winged steed",
			"creativity",
			"condescend",
			"creative salvage",
			"miss margaret barton",
			"wavebreaker",
			"twisted masterwork",
			"become immersed",
			"legacy foundations",
			"shock blast",
			"refracted thoughts",
			"feed to the pigs",
			"soaring dreams",
			"favor of the emperor",
			"disciple of the buried glade",
			"dregs of order",
			"moonlit hunter",
			"slightly mad",
			"sleeping dryads",
			"sowing spring",
			"turn to gold",
			"flourishing waterways",
			"choked estuary",
			"thunder wave",
			"autumn fae",
			"sign in blood",
			"curse-blood morrigan",
			"evigian noble",
			"nightcloak ritualist",
			"unorthodox methods",
			"aurora, soulweaver",
			"emperor azuma hashiro",
			"carrionpult",
			"twisted archangel",
			"blood harvest",
			"woopip bruiser",
			"lightless hedron",
			"champion of the red dawn",
			"golden age",
			"scorned figurant",
			"dregscape chant",
			"avid researcher",
			"shina taiyohata",
			"enemies of my enemy",
			"idyllic oasis",
			"fatresya, protector of the people",
			"shuddering node",
			"shambling morass",
			"light knight",
			"solar flair",
			"rangewalker pyromancer",
			"splitting phantasm",
			"twinned slasher",
			"crystallized moment",
			"mirrorstorm",
			"glorysinger",
			"hunt the monstrous",
			"snuff out the light",
			"reckless pyremage",
			"cosmostorm rider",
			"scraps of memory",
			"repent's champion",
			"sunstage",
			"turela, defiant angel",
			"trailbloomer",
			"theurgist of the depths",
			"through the mists",
			"hate-driven arsonist",
			"way of the dragon",
			"supplanter of realities",
			"mask of shikai",
			"beckon darkness",
			"endless assembly",
			"bleak condor",
			"adiran survivors",
			"sphinx of ill omens",
			"requiem of the fallen",
			"cathartic reunion",
			"slaughter",
			"journeying giftbearer",
			"runeclad seeker",
			"raven's standard",
			"shushing usher",
			"grab bag",
			"dignity",
			"greenheart squirrel",
			"price of wisdom",
			"evoke the maelstrom",
			"the sun also rises",
			"archlegislator",
			"risen raven",
			"gorbes index",
			"destabilizing the rifts",
			"raiding gnoll-band",
			"ephemeral support",
			"crossing the rifts",
			"iken company nightwalker",
			"pakka, the shadowcloak",
			"scuripi lookout",
			"enjoy the silence",
			"united force",
			"arcor diamond",
			"abandoned memorial",
			"sticky fingers",
			"shokan captain",
			"fallen ideal",
			"beckoner of horrors",
			"demystifying tide",
			"mirror image",
			"borsuppa scavenger",
			"the future is now",
			"foretold strength",
			"eradicating flames",
			"paincaller",
			"aleryn, trapseeker",
			"tidepool turtle",
			"highspire informant",
			"bessie",
			"rogg, chaos treader",
			"lerithan rebel",
			"ascendant's murmur",
			"journey to the zhedina",
			"depthlight captain",
			"idol of the dead god",
			"blood bond",
			"tsolmon, the huntress",
			"dominik's shack",
			"pillar of flame",
			"heart's desire",
			"rehearse",
			"kenleigh, liege of redemption",
			"vivid march",
			"deadland scavenger",
			"dreary township",
			"determined hero",
			"guided sniper",
			"contagious deathspore",
			"slayer of the famed",
			"improbable aim",
			"raid the cursed temple",
			"seek the buried relic",
			"hunting experience",
			"thailen, heir to daeland",
			"fleeting discoveries",
			"ghostway",
			"glorious celebration",
			"insipid metamorph",
			"crash through",
			"maw of a thousand worlds",
			"rush of thought",
			"dire predictions",
			"the book of secrets",
			"kunal, dragonclaw's legacy",
			"walker of the final path",
			"unravel shattered worlds",
			"clock of seasons",
			"senator christian winters",
			"darna's confluence",
			"the shadowstaff",
			"cursed wastes",
			"leafdown sizzlemage",
			"absolve",
			"the magistrate",
			"herald of suns",
			"asamund's gambit",
			"ravik, still-smoke seer",
			"meren, bane of the cairns",
			"frontier trackers",
			"gladesworn ranger-captain",
			"vaeldan's liberator",
			"ryleth, vengeful shadow",
			"lost in the roses",
			"grave robbery",
			"ancient tablet",
			"asabeth of the intrepid",
			"director amitai eliahu",
			"coveted heirloom",
			"blessing of roya",
			"words of eternity",
			"scarhide, arsenal crafter",
			"adventurous impulse",
			"deathwind detonator",
			"springcaller",
			"tempus fugit",
			"vantage point",
			"tranquil path",
			"goddess' whimsy",
			"maaru's hoard",
			"resource management",
			"poisoned tonic",
			"echoing sunder",
			"verdant renewal",
			"erika's purge",
			"petrify",
			"globule of intuition",
			"hermit's travels",
			"searing pulse",
			"bloodboil harlequin",
			"in tragedy",
			"inferno lash",
			"dazzling display",
			"game trail",
			"novaheart guardian",
			"coward's compulsion",
			"glowspore grove",
			"seal of approval",
			"from beyond the grave",
			"oslyd dreamer",
			"terror of the tides",
			"reality reversal",
			"evavin duelist",
			"jund command",
			"egg bomb",
			"silt lurker",
			"fuhai-no-oni",
			"little kibo",
			"himitsu, shigure's legacy",
			"antimagic formula",
			"quell mutiny",
			"abandoned skyroad",
			"decide boundaries",
			"rugged fields",
			"imperial barracks",
			"tectonic chateau",
			"risti inquisitor",
			"fragment mind",
			"severin, broken genius",
			"curio pavilion",
			"relitian sentry",
			"kor skyknight",
			"indomitable duo",
			"spark new life",
			"enlightened lizard",
			"stonefall golem",
			"soulcarver",
			"irrigation trawler",
			"fungal whomper",
			"highlands champion",
			"masked impersonator",
			"cutthroat deceiver",
			"storm of shadows",
			"reflected grandeur",
			"youthful savior",
			"saber of defiled rites",
			"skybreaker hook",
			"sword of truth and lies",
			"bretala of redsky",
			"window shopping",
			"mua, seishin ascendant",
			"one with seishin",
			"seishin's edge",
			"warrior's discipline",
			"natural recycling",
			"oldgrove nurturer",
			"dictate of the evil one",
			"ediam, the inside man",
			"bow or burn",
			"imaginary flames",
			"silkweaver matron",
			"court beastmaster",
			"fate tracer",
			"formidable bulkvine",
			"haruna, master architect",
			"battlewise strategist",
			"buttress formation",
			"raving rover",
			"jara incarnation",
			"spirit of autumn",
			"butcher of shallow graves",
			"march of the gray",
			"stratospheric bombardment",
			"khalizors' last stand",
			"heretical summons",
			"animus vox",
			"alive and on top",
			"great and small",
			"painwield explorer",
			"architect of the derezzed",
			"search for inspiration",
			"midnight's pale moon",
			"gate to the nav",
			"aetherdrain",
			"caress the fleets",
			"xoqal, world eater",
			"archangel of bliss",
			"sculler's oar",
			"starlight seraph",
			"in the face of divinity",
			"elvish songseeker",
			"ontarachie hunter",
			"awaken to the new world",
			"vectis entrancer",
			"mindbreak artisan",
			"killdrone assembly works",
			"cranial archive",
			"fiery embrace",
			"mercurial chameleon",
			"time after time",
			"depth charger",
			"iaijutsu",
			"prepare for trouble",
			"masaru, aspiring champion",
			"charming nereid",
			"conchspear hunter",
			"pitchwater singer",
			"schoolstrider",
			"feeding time",
			"seadrake rider",
			"pristine duelist",
			"imperial defenses",
			"ridge warden",
			"the banishment of seh'a",
			"consult the scriptures",
			"under cover of dark",
			"mystic mackerel",
			"organic corrosion",
			"epic of jobiah",
			"aelinn, serpent's voice",
			"siraj, interplanar thief",
			"abandoned wilderness",
			"otherworldly forest",
			"project head",
			"stinging hunter",
			"woven network",
			"phantasmal stalker",
			"sand scorpion",
			"winter's whelp",
			"fourth eye assassin",
			"ingredient scroungers",
			"shedding of the coils",
			"depthlight salvager",
			"thornweald archer",
			"avoid fate",
			"martyr of the work",
			"fretport mob",
			"precursor filtercruiser",
			"seek the maker's egg",
			"kotis, promised general",
			"reyhsia, truth chaser",
			"reflected worldwalker",
			"wild dogs of the night",
			"tara, duneblessed",
			"honey wagon",
			"ruptured grove",
			"kowareta scrounger",
			"suzume's envoy",
			"ser wayver, the broken hour",
			"hand of the harvest",
			"crimson knight",
			"adept necromancer",
			"blazing fox",
			"firemane fox",
			"uncovered secrets",
			"alenian warhammer",
			"duan, the fabled rider",
			"lonesome traveler",
			"ochre knight",
			"eve's spiritstalker",
			"runescale brawler",
			"surmise reality's limits",
			"amateur auteur",
			"roland, philosopher king",
			"div of bonded souls",
			"silver-dawn radiant",
			"armament upgrade",
			"sway the naive",
			"grisly feast",
			"carnival daredevil",
			"nizev enforcer",
			"spellshatter",
			"nurturing knowledge",
			"scathing review",
			"power drive",
			"sever",
			"monstrous guise",
			"emerabi and sunnula",
			"ameret, pride of cyrukan",
			"boxue and ma'long",
			"orodu's consumption",
			"canopy dancer",
			"aldrane's masterpiece",
			"serafina, the traitor amongst",
			"highwild survivalist",
			"borsuppa roughrider",
			"sandstorm sentinel",
			"flourishing lowlands",
			"windworn spires",
			"helar ritualist",
			"lady ilyrana jhalach",
			"greenwood outrider",
			"singers' grove",
			"salty swab",
			"infamous bilgecaptain",
			"masha, hero of pelastrov",
			"abital, hesediel's fawn",
			"sunder history",
			"wildbond aspirant",
			"knight-academic",
			"spymaster's consignment",
			"qilan seer",
			"cosmic tendrils",
			"backup forces",
			"nekomi, the thought police",
			"hellkite's decree",
			"high priest of kahroba",
			"cyril, volaris captain",
			"heavenly radiance",
			"elspeth's intervention",
			"arid causeway",
			"enigma mystic",
			"hadak, end of progress",
			"legion angel",
			"lightning ripple",
			"bloodvenge berserker",
			"owl of the seven stars",
			"leyline invoker",
			"undead banneret",
			"prophet of reclamation",
			"pestilent scavenger",
			"gate of realms",
			"power jam",
			"master of three paths",
			"leafdown hunk",
			"sculptor of the ruby sands",
			"fang den jaws",
			"sandstone construct",
			"fallen celestial",
			"celestial principality",
			"gold retriever",
			"senn, the haunting gaze",
]

		names
			.map{|n| db.cards[n]}
			.flat_map{|card| card ? card.printings : []}
			.to_set
	end

	def to_s
		'is:playable'
	end
end