class ConditionIsStaple < Condition
    def search(db)
        names = [
            "wayfarer's shrine",
            "nebula of empty gold",
            "seal the tomb",
            "pith wilt",
            "mysterious cataract",
            "stand unassailable",
            "magmatic torrent",
            "crumbling precipice",
            "shardstone rift",
            "flooded depths",
            "event horizon",
            "crystal cavern",
            "duress",
            "shifting glade",
            "murmuring falls",
            "grim bastion",
            "lush oasis",
            "stolen secrets",
            "lavatorn fields",
            "flooded morass",
            "scorch",
            "amber hills",
            "nomad's township",
            "lumbering hillock",
            "sedate tundra",
            "fungal mire",
            "sacrificial bull",
            "timber range",
            "cosmic sinkhole",
            "corpsebed",
            "monument of queens",
            "frostfire geysers",
            "titan snare",
            "ocean monastery",
            "soul gate",
            "prying inquiry",
            "shal'draen's rage",
            "out-of-body experience",
            "shikai's redoubt",
            "barren desolation",
            "rampant summit",
            "arctic mine",
            "mana ascetic",
            "memento mori",
            "descend on the helpless",
            "exeunt",
            "gloomcover steppe",
            "roggar's frenzy",
            "sunlit highland",
            "wheat from chaff",
            "flourishing crevasse",
            "pool of light",
            "oracle's vision",
            "recall forgotten eons",
            "voidflare",
            "heart of the glade",
            "cursory glance",
            "spell pierce",
            "whisperwoods exploration",
            "hierarch ranger",
            "still the pandemonium",
            "thought blossom",
            "cane dancer",
            "mana confluence",
            "portal fracture",
            "the high prairies",
            "stormsurge",
            "rage of the ravaged",
            "forgotten steppe",
            "tamiyo, lunar arcanist",
            "solar flare",
            "banished companion",
            "violent collapse",
            "negate",
            "etherium abrogator",
            "reveal eternities",
            "suitor of the sea",
            "chi lee of the underworld",
            "basat charm",
            "nature's claim",
            "tropical grove",
            "bahum, the warden",
            "cradle of corruption",
            "mpumo, who stands alone",
            "pay up",
            "seto san, the dragonblade",
            "tiny heroine totti",
            "epic encounter",
            "mirrorgate",
            "bounty of the gardens",
            "imperial claim",
            "murky peat",
            "fair trial",
            "tenacious guide",
            "impden mother",
            "xanigan, the darkened cloud",
            "chikyu champion",
            "prodigious panya",
            "shugenja sanctuary",
            "last passage",
            "veilborn meddler",
            "hugo of the shadowstaff",
            "polyp pools",
            "departed evangel",
            "rot",
            "unceasing flames",
            "unjust sentence",
            "unquenched greed",
            "villainy",
            "inishtu, desert healer",
            "unearth",
            "ostracizer orb",
            "once abandoned",
            "seek prophecy",
            "idyllic odyssey",
            "singularity's grasp",
            "fogspewer",
            "profane emissary",
            "face the dawn",
            "volatile stonework",
            "long forgotten",
            "fractured reach",
            "endless helpless souls",
            "rakkiri dissident",
            "northern express line",
            "tidehollow lich",
            "stalwart dominion",
            "grim slums",
            "sights beyond",
            "brushcover elf",
            "bloodriver",
            "seedshrine",
            "jobiah, devoted farmer",
            "dreamsight well",
            "ever-gnawing rat",
            "temporary treason",
            "aiel tazan",
            "destructive ambition",
            "budding companion",
            "kati evalin, world wanderer",
            "find happiness in misery",
            "theocracy",
            "flaming point technique",
            "corvid heretic",
            "dovon, verdant experimenter",
            "tsang jin, master of the jade sea",
            "tyrant of tributes",
            "warded tome",
            "autumnal watch",
            "end of all things",
            "ancestral council",
            "terraformer's globe",
            "kaur, end of lies",
            "earthbreaker behemoth",
            "scuttling gnat",
            "avatar of the natural",
            "distant thunder",
            "dark bargain",
            "ignition point",
            "danithra muckbruiser",
            "guiding light",
            "primal ruffian",
            "rousing rubble",
            "thunder road",
            "union rail strikebreaker",
            "nacatl skirmisher",
            "mindstorm's eye",
            "bessie's brood",
            "gift of the phoenix",
            "leija's greenblade",
            "twilight ambush",
            "dead man's party",
            "sunken ambitions",
            "vibrant rapture",
            "marisa of the gravehowl",
            "dawson's loot",
            "conjure realities",
            "forked pillar",
            "heist headquarters",
            "smoldering pages",
            "redtail fencer",
            "velir the sunderer",
            "lord ellison crain",
            "invalidate",
            "stalked healer",
            "turi of hollow depths",
            "canyon creek",
            "sigil of radiance",
            "mosecf, the sunseeker's path",
            "performer of ambition",
            "tend to the grove",
            "lumenbay flyer line",
            "verdant bluff",
            "beneath the zhedina",
            "rock",
            "staff of equilibrium",
            "academic's claymore",
            "farseek",
            "diffuse",
            "herald of oblivion",
            "new divide",
            "palace of reflections",
            "sea cache",
            "deform sanity",
            "bitter duckling",
            "caulte axeslinger",
            "brazen sacrilege",
            "verdant dominion",
            "shadowband consul",
            "curse of bleeding",
            "neutralize",
            "crystal wave",
            "eli windsors, lone gun",
            "mausoleum suffragan",
            "cognitive fumigator",
            "vaultkeeper",
            "egg of avarice",
            "martial maestro",
            "waxing angel",
            "powder scatterer",
            "pitchpyre curse",
            "dead-set duo",
            "sabne's autumn",
            "emerabi's disciple",
            "answer midnight's call",
            "imagination unleashed",
            "rain of ruin",
            "self replication",
            "rift splicing",
            "silent hypnotist",
            "avatar of basat",
            "meteor volley",
            "crewmaster gillo",
            "lord rickard dawson",
            "roggar's gambit",
            "sporeflow protector",
            "garth of the chimera",
            "chains of subdual",
            "channeling stone",
            "masahita, bloodtongue",
            "sedraxis trepanator",
            "priestess of simplicity",
            "slashing pangolin",
            "gleaming river",
            "ayala's concord",
            "plaxolotl pyari",
            "veteran lifeforger",
            "ruin delver",
            "earthfeeder worm",
            "anomalion",
            "silent wanderer",
            "sun-sigil ordainer",
            "mark of dark opulence",
            "shifting cascade",
            "cumulus horizon",
            "holcomb of the peregrine",
            "civilization's cost",
            "oil driller",
            "jara champion",
            "setting sun",
            "timestream sentinel",
            "lhosei of the ghost peak",
            "reckless festivities",
            "cosmic war",
            "ambitious necromancer",
            "abandoned monument",
            "all or nothing",
            "buy time",
            "blessed spellroot",
            "xirix, the usurper",
            "hazy moorland",
            "bogborn charger",
            "lord rokai",
            "forgotten shrine",
            "forbidden brew",
            "seismic colossus",
            "charming marauder",
            "blood jade prophet",
            "resign to madness",
            "hellion devastator",
            "no rest",
            "gaze deeper",
            "soul release",
            "fiery burst",
]

        names
            .map{|n| db.cards[n]}
            .flat_map{|card| card ? card.printings : []}
            .to_set
    end

    def to_s
        "is:staple"
    end
end