class ConditionIsStaple < Condition
	def search(db)
		names = [
			"wayfarer's shrine",
			"nebula of empty gold",
			"seal the tomb",
			"pith wilt",
			"magmatic torrent",
			"mysterious cataract",
			"spell pierce",
			"stand unassailable",
			"crystal cavern",
			"shifting glade",
			"event horizon",
			"stolen secrets",
			"cosmic sinkhole",
			"shardstone rift",
			"flooded depths",
			"sedate tundra",
			"grim bastion",
			"scorch",
			"murmuring falls",
			"crumbling precipice",
			"ocean monastery",
			"lush oasis",
			"corpsebed",
			"flooded morass",
			"frostfire geysers",
			"shal'draen's rage",
			"duress",
			"prying inquiry",
			"sunlit highland",
			"nomad's township",
			"cursory glance",
			"fungal mire",
			"timber range",
			"amber hills",
			"portal fracture",
			"lumbering hillock",
			"out-of-body experience",
			"pool of light",
			"lavatorn fields",
			"shikai's redoubt",
			"roggar's frenzy",
			"solar flare",
			"soul gate",
			"cane dancer",
			"reveal eternities",
			"mana confluence",
			"resplendent substratum",
			"voidflare",
			"sacrificial bull",
			"thought blossom",
			"still the pandemonium",
			"forgotten steppe",
			"rampant summit",
			"negate",
			"recall forgotten eons",
			"the high prairies",
			"monkeyshines",
			"bounty of the gardens",
			"nature's claim",
			"end of all things",
			"endless helpless souls",
			"prodigious panya",
			"heart of the glade",
			"etherium abrogator",
			"fractured reach",
			"violent collapse",
			"ostracizer orb",
			"mystery of the crashed craft",
			"forked pillar",
			"embodied soul",
			"suitor of the sea",
			"mirrorgate",
			"banished companion",
			"idyllic odyssey",
			"spiraling canyon",
			"stormsurge",
			"rousing rubble",
			"hierarch ranger",
			"seek prophecy",
			"cradle of corruption",
			"veilborn meddler",
			"once abandoned",
			"inishtu, desert healer",
			"unceasing flames",
			"rage of the ravaged",
			"rift splicing",
			"northern express line",
			"wheat from chaff",
			"dreamsight well",
			"singularity's grasp",
			"basat charm",
			"powder scatterer",
			"sigil of radiance",
			"mana ascetic",
			"antimagic",
			"conjure realities",
			"garth of the chimera",
			"ria-demian charm",
			"hugo of the shadowstaff",
			"admonish",
			"polyp pools",
			"shugenja sanctuary",
			"lumenbay flyer line",
			"tiny heroine totti",
			"grim slums",
			"corrupted memory",
			"new divide",
			"last passage",
			"bant command",
			"gaze deeper",
			"volatile stonework",
			"caulte axeslinger",
			"sealed riftway",
			"union rail strikebreaker",
			"impden mother",
			"flaming point technique",
			"terraformer's globe",
			"profane emissary",
			"palace of reflections",
			"ancestral council",
			"dovon, verdant experimenter",
			"self replication",
			"tenacious guide",
			"aerie's pillar",
			"silent hypnotist",
			"verdant bluff",
			"nacatl skirmisher",
			"aiel tazan",
			"unjust sentence",
			"canyon creek",
			"rot",
			"departed evangel",
			"shifting grove",
			"waxing angel",
			"spirit script",
			"destructive ambition",
			"guiding light",
			"clockwork gaucho",
			"death pits hawker",
			"ignition point",
			"sunken ambitions",
			"seto san, the dragonblade",
			"verdant dominion",
			"cognitive fumigator",
			"crystal conjuration",
			"tidehollow lich",
			"seismic colossus",
			"thunder road",
			"shifting cascade",
			"fiery burst",
			"hazy moorland",
			"neutralize",
			"tamiyo, lunar arcanist",
			"herald of oblivion",
			"forbidden treasure",
			"nightwatch rallier",
			"veteran lifeforger",
			"heist headquarters",
			"rakkiri dissident",
			"brutal blow",
			"theocracy",
			"roggar's gambit",
			"mindstorm's eye",
			"xirix, the usurper",
			"autumnal watch",
			"corvid heretic",
			"fogspewer",
			"danithra muckbruiser",
			"unearth",
			"source decay",
			"cumulus horizon",
			"void portal",
			"monsoon lagoon",
			"sights beyond",
			"shadowband consul",
			"lord rickard dawson",
			"ruin delver",
			"warded tome",
			"sun-sigil ordainer",
			"stalked healer",
			"masahita, bloodtongue",
			"chains of subdual",
			"oppress the weak",
			"farseek",
			"kaur, end of lies",
			"mausoleum suffragan",
			"dawson's loot",
			"holcomb of the peregrine",
			"fey grove",
			"soaring canyon",
			"one with the world",
			"shifting canyon",
			"leyran alpha",
			"nightmares unseen",
			"tether of simplicity",
			"cleared vault",
			"coralight champion",
			"path of fire",
]

		names
			.map{|n| db.cards[n]}
			.flat_map{|card| card ? card.printings : []}
			.to_set
	end

	def to_s
		"is:staple"
	end
end