class ConditionIsPerfecthandunderdog < Condition
	def search(db)
		names = [
			"abandoned memorial",
			"abandoned skyroad",
			"absorb the soul",
			"ace trainer",
			"adam of the ironside",
			"adoroth, the baneful",
			"aerida, envious chronomancer",
			"aerie's pillar",
			"aethercrafting",
			"ageless wanderer",
			"ahl's study",
			"alia, bearer of morning",
			"alin and meva, warqueens",
			"alpha scout",
			"amelie mayn",
			"angelfire",
			"angeltouched cavern",
			"anku the primordial",
			"annihilate aggressor",
			"anomalion",
			"arcane genesis",
			"arcane rebound",
			"archaeomancer",
			"archon of the accord",
			"ardy's invocation",
			"arrogant entrant",
			"astralhorn familiar",
			"atychiphobia",
			"aurora's whisper",
			"autointerment",
			"avatar of basat",
			"avatar of plume de val",
			"avatar of the natural",
			"awaken the source",
			"azun, sheriff of daisite",
			"banish",
			"barren boneyard",
			"bashful drake",
			"battlefield catastrophe",
			"bessie, the muscle",
			"bewitching vapors",
			"bile of the world",
			"blade of the long night",
			"blade of the serpent",
			"blessing of morning",
			"bloated keystone",
			"bloodrune patron",
			"bloomcrawler",
			"bogborn exorcist",
			"bogsworn club",
			"brazen sacrilege",
			"breach the mind",
			"brilliant mansion",
			"burning sulfur",
			"calamitous crash",
			"calamity rose",
			"cannoncoil hermit",
			"caravan sumpter",
			"carving secrets",
			"cascade failure",
			"cauldish banneret",
			"celestial army",
			"channel the mirror",
			"charming marauder",
			"chiu of the wild realm",
			"chromeleon",
			"citywide automation",
			"cloudshaper",
			"commanding princess",
			"confining priest",
			"coppergild mercenary",
			"coralight lifebloom",
			"cragbound crusher",
			"crain's crony",
			"craving secrets",
			"crush the hull",
			"crystal wave",
			"curious cubs",
			"cyone, expedition captain",
			"dancing flames",
			"dawson's collector",
			"dawson's marauder",
			"dawson’s collector",
			"dead man's hand",
			"deadwood grove",
			"deathwind detonator",
			"deem unworthy",
			"demanding idol",
			"departed evangel",
			"desert wurms",
			"deus ex machina",
			"dignitary's rickshaw",
			"discordant bell",
			"dismal backwater",
			"dispel",
			"distant lover",
			"divide and slaughter",
			"doomed fate",
			"dragon queen's disciple",
			"dredgeline colossus",
			"eager hatchling",
			"earthfeeder worm",
			"edarna the everforge",
			"ediam, the inside man",
			"eli’s defiance",
			"embodied soul",
			"emerabi's disciple",
			"enchanting palace",
			"end of all things",
			"enigma of seventy scrolls",
			"enshrine",
			"epic of inishtu",
			"eradicating flames",
			"erika, mourning soul",
			"erollin, eccentric collector",
			"esper command",
			"eternal reactor",
			"ethereal armor",
			"ethereal fervor",
			"etherium abrogator",
			"etlan high priest",
			"event horizon",
			"ever-gnawing rat",
			"everember phoenix",
			"expedition post",
			"extremespeed",
			"eye of dismay",
			"fade",
			"fair trial",
			"fallacy's sanctifier",
			"fang of mautakesh",
			"faradia, honored sovereign",
			"fated mariner",
			"fatresya's command",
			"feed into aether",
			"fiery embrace",
			"final fate",
			"fireheart channeler",
			"firehearth halls",
			"flintlock pioneer",
			"forbidden treasure",
			"forebear of hibernation",
			"forgotten pit",
			"fortune dealer",
			"fox of a glistening glen",
			"fox of a radiant meadow",
			"fox of the orange orchard",
			"frenzied watchkeeper",
			"frontier hunter",
			"frostbreath dragon",
			"gambler’s tournament",
			"gao’wu, master soothsayer",
			"gate to the nav",
			"ghostly flicker",
			"gilded lotus",
			"gleaming mirrorweaver",
			"glimmering staff",
			"glint-glyph oracle",
			"glitch, cosmic dreamer",
			"glorybound chorister",
			"golden age",
			"grand expeditions",
			"grand stand at danaj",
			"great sable stag",
			"grixis twin",
			"gruff smith",
			"guardian of the eclipse",
			"harrier's falcon",
			"harriet, liberated wildborn",
			"hateful gaze",
			"hayuan, the misjudged",
			"head of ulko",
			"heavens held waiting",
			"heinous acts",
			"helena, the awakener",
			"hembwe, the all-mother's hand",
			"herald of the humble",
			"heraldry",
			"hirukari, daughter of the sun",
			"holy war",
			"horrific progenitor",
			"hostile takeover",
			"howl of the hunted",
			"howling shieldbreaker",
			"hugo of the shadowstaff",
			"hunter of the moon-serpent",
			"huntsman's guile",
			"idravir, the last city",
			"idyllic odyssey",
			"ifram, god of chaos",
			"ill-fated seer",
			"illusionary steed",
			"imisti, elven insurgent",
			"impden mother",
			"imperial titan",
			"implant greenhouse",
			"ing'wei, the surging tide",
			"invalidate",
			"iroshi, blade of the old ways",
			"isochron wand",
			"jachsechep, god's wife",
			"japan declares war",
			"jarl's brutalizer",
			"judge's decree",
			"judge’s decree",
			"junan venomtongue",
			"just business",
			"kaalia's abomination",
			"kai'oro, grave betrayer",
			"kalemn, bound by violence",
			"kaneh citadel",
			"kazimir’s ban",
			"killdrone assembly works",
			"law enforcement",
			"lay low",
			"legends remembered",
			"leviathan of isles",
			"lodestone golem",
			"lord ellison crain",
			"lord of the bubbledome",
			"losing my religion",
			"lost among the stars",
			"lotus studies",
			"lt. daisy saxon",
			"luminescent feathrets",
			"magnificent raid",
			"maktali archivist",
			"mana ascetic",
			"marin polgek, academy heiress",
			"mattia, hero of tinyvale",
			"mei liva, the exfiltrator",
			"mei, the inflitrator",
			"memory hole",
			"mercantile accords",
			"meren, bane of cairns",
			"meren, bane of the cairns",
			"mindlock field",
			"miner's barracks",
			"mirai, spring's promise",
			"misery keeps company",
			"moment of tranquility",
			"momentous charge",
			"moonlight sanctum",
			"mortal pilgrimage",
			"mounting up",
			"mulchborn behemoth",
			"myrmidon, coralight exile",
			"nacatl skirmisher",
			"nataila, raven's repented",
			"ninhasir's march",
			"ninja wolves",
			"niu mo wang, ashen absolution",
			"northern express line",
			"oathbreaker orc",
			"obscoriate",
			"observer of aeons",
			"oceanographer",
			"ochiji, serpent of seven heads",
			"ominous presence",
			"orodu, the onyx wave",
			"ostentatious octopus",
			"ostracizer orb",
			"overwhelming armies",
			"painful reminiscence",
			"pakka, the shadowcloak",
			"peer into the cosmos",
			"perfect distraction",
			"performer of growth",
			"perilous treaty",
			"perish song",
			"phantasmal owl",
			"phantasmal stalker",
			"pierce the storm",
			"plasma enforcer",
			"plaxolotl pyari",
			"portal fracture",
			"posey of the seal cloak",
			"posey, of the seal cloak",
			"powder scatterer",
			"precursor sanctum",
			"prepare for the onslaught",
			"pristine prison",
			"prodigious panya",
			"profane emissary",
			"prohibit",
			"propaganda division",
			"psywave",
			"qililia, the saboteur",
			"quillback of gloomhollow",
			"rahit, immaculate architect",
			"rakkiri initiate",
			"ravaged monument",
			"razing throng",
			"reclaim relics",
			"reconsider",
			"remnant of the hunt",
			"rhysta of the roses",
			"riftkeeper entity",
			"rugged endurance",
			"ruinous proselyte",
			"rujan, the great pumpkin",
			"rune of rejuvenation",
			"sadistic indulgence",
			"salvation engine",
			"sanaito, alone",
			"sanitarium skeleton",
			"scintillate",
			"scorch",
			"scrapyard sovereign",
			"sea’s allure",
			"seal of approval",
			"seal the tomb",
			"seasons of war",
			"seila, the lost one",
			"seismic colossus",
			"self-replication",
			"senator christian winters",
			"sera of coppercove",
			"serafina, the traitor amongst",
			"serene prayer",
			"serpentdancer kantra",
			"sesillius, chosen speaker",
			"set the stage",
			"shabil's absolute triumph",
			"shared reminiscence",
			"sharuum, archmagocrat",
			"shifting cascade",
			"shifting crag",
			"shigurei, the floodbringer",
			"shikai’s redoubt",
			"shining crusader",
			"shroud the world in doom",
			"siaveed, commander of armies",
			"sihari, fury of the dunes",
			"silent wanderer",
			"silent wayfarer",
			"sinister heir",
			"siraj, interplanar thief",
			"skycaster’s aura",
			"slippery assassin",
			"slyten crystal motherlode",
			"soul of iscathia",
			"speaker of deliverance",
			"spectral chains",
			"spectral skycruiser",
			"spell pierce",
			"stall fate",
			"steward of silence",
			"stolen cache",
			"subdue false idols",
			"submergence",
			"suborn humanity's work",
			"succumb to dreams",
			"suitor of the sea",
			"sukhar, consort to the dark",
			"sunrise woods",
			"supplanter of realities",
			"syrina, the dragon queen",
			"tahli's council",
			"tal, locus sentry",
			"tarraka-no-oni",
			"temporal blink",
			"temporal resucitation",
			"temporal resuscitation",
			"tempted by lotuses",
			"tenacious guide",
			"terror of the ontarachie",
			"the issbarrens",
			"the mistake",
			"the moon rises",
			"the stranger’s play",
			"the sun also rises",
			"theatre of cruelty",
			"third legion general",
			"threshing sundew",
			"thunder road",
			"tidehollow lich",
			"timestream sentinel",
			"timeworn crags",
			"titan's palace",
			"touch of the uncanny",
			"tranquil moment",
			"trial recruitment",
			"tyrant's breath",
			"tzelin, cabal liturgist",
			"unearth",
			"unhappy ending",
			"unlikeliest heroes",
			"voliv edgelands",
			"vulpine verse",
			"wandering dragonfly",
			"wastes scrambler",
			"waxing angel",
			"weeping lotus",
			"whatever it takes",
			"whispering halls",
			"whistling blades",
			"wicked fossil",
			"wild encounter",
			"wild festivities",
			"worried vulpine",
			"xie'e amphitheatre",
			"xifang hu, light within",
			"xing, the lucky charm",
			"xiong mao, survivalist",
			"zhedina envoys",
			"zoetic tomb",
		]

		names
			.map{|n| db.cards[n]}
			.flat_map{|card| card ? card.printings : []}
			.to_set
	end

	def to_s
		'is:perfecthandunderdog'
	end
end