# frozen_string_literal: true

class ConditionIsSearle < Condition
	def search(db)
		names = [
			"academy renegade",
			"afterlife heist",
			"against the waves",
			"antimagic formula",
			"apex's oath",
			"autumn's farewell",
			"calamitous crash",
			"chronofracture",
			"crystal garden",
			"emperor tzhai",
			"epic score",
			"finale of cinders",
			"glorysinger",
			"glymna blackrune",
			"hunter's hideout",
			"just business",
			"legacy's malediction",
			"leyline alignment field",
			"lost to the ages",
			"meadow's melody",
			"memento mori",
			"meteor fall",
			"mirrorgate",
			"ol' sycamore",
			"outsmart",
			"overclock",
			"overloaded aethergate",
			"puppeteering",
			"rend the mind",
			"sinister heir",
			"terror of palta gorge",
			"the start of something",
			"tidal spite",
			"titan's palace",
			"unceasing flames",
			"vengeful messenger",
			"villainy",
			"welcome return",
			"abhorrent exhumer",
			"abolishers of sin",
			"allagras, tidal master",
			"arcane dexterity",
			"arcane rebound",
			"arcanist's dispersal",
			"assault on prosania",
			"bane of sanity",
			"barbarian hoarders",
			"barbaric dexterity",
			"beragnian blizzard",
			"beragnian brawlmaster",
			"beragnian intimidator",
			"blade of reolem",
			"bloodchill risen",
			"bloodrite fiend",
			"bone saw",
			"budding echomage",
			"burn with rage",
			"cannon fodder",
			"cease conflict",
			"close escape",
			"collapsing ground",
			"continental collapse",
			"corpse exploiter",
			"counteroffense",
			"cranial archive",
			"curse of the drow",
			"danuri banisher",
			"distort reality",
			"drow ritualist",
			"duskwood marshal",
			"fellor ironborn",
			"forest",
			"furious betrayal",
			"griptide",
			"groundswell",
			"guilty execution",
			"hapless chronomancer",
			"humanity's hope",
			"imminent collision",
			"infuse vitality",
			"instinctual savagery",
			"island",
			"khalizors' last stand",
			"koth, one true hero",
			"koth's retaliation",
			"landbound connoisseur",
			"magus of memories",
			"majestic garrison",
			"master echomage",
			"mawdryk, endrison warden",
			"mawdryk's accusation",
			"mawdryk's haven",
			"mental supremacist",
			"merkurio's rebuttal",
			"mountain",
			"mulchborn behemoth",
			"necrobite",
			"offer to nature",
			"one with nature",
			"pandora's antagonism",
			"pandora's eviction",
			"plains",
			"prosanian warden",
			"purging reolem",
			"purifying light",
			"pyromancer's fury",
			"rallios' demise",
			"rallios' return",
			"reality check",
			"ripping wilds",
			"roggar's frenzy",
			"roggar's gambit",
			"ruin salvager",
			"savrios' cohort",
			"sentinel's longbow",
			"sinful past",
			"soulstone commander",
			"soulstone redeemer",
			"stay on edge",
			"strength of the phalanx",
			"surge of depravity",
			"survive the wreckage",
			"swallowed by the earth",
			"swamp",
			"temporal resuscitation",
			"temporary treason",
			"tharyen's sadism",
			"the high prairies",
			"tideshift elemental",
			"time to depart",
			"timecrafter lafterii",
			"unstable footing",
			"unstable magmaling",
			"until the last breath",
			"vampiric appetite",
			"vaporizing blast",
			"wailing spirit",
			"weaponize",
			"abandoned sanctuary",
			"allure of the dark grove",
			"an and en, destined souls",
			"anointed general",
			"apothecary's remedy",
			"artful coercion",
			"barterer of passage",
			"bathophobia",
			"breath of fresh air",
			"breath of hao'tai",
			"brothers in arms",
			"brutal descent",
			"call to attention",
			"charmer of the folded fan",
			"chian, augury adept",
			"chords of order",
			"come crashing down",
			"consuming flame",
			"contort reality",
			"courageous charge",
			"crane legionnaire",
			"crimson hellmaw",
			"da'lang, forest guardian",
			"deep in thought",
			"demystifying tide",
			"dragon grip",
			"empowering chant",
			"engulfing incubus",
			"fell the beast",
			"ferocity of hao'tai",
			"firebelly toad",
			"for glory",
			"form of the demon",
			"gaze of the golden fox",
			"guawu the untamed",
			"heping, master arbitrator",
			"ing'wei of the flood realm",
			"inspiring effigy",
			"inundated sanctuary",
			"isle conservator",
			"jiayin, the harmonious",
			"keeper of blue incense",
			"kicking crane technique",
			"kiora, empress of the flood",
			"kiss of the dryad",
			"kugoja, perished conduit",
			"lizhao, lord of the yaogu",
			"lost among the lilies",
			"magnificent liturgy",
			"maiden of the daffodils",
			"mastery of the silken strand",
			"mother of owls",
			"negate",
			"neutralize",
			"nightcloak ritualist",
			"overzealous tutor",
			"pay respects",
			"pon, twister of forms",
			"put to rest",
			"radiant maleficence",
			"recalibrate",
			"resurrection plea",
			"reverent flame",
			"ruinous glutton",
			"rummage through remains",
			"sacred sanctuary",
			"sanguine oracle",
			"savage sanctuary",
			"shadow infestation",
			"shigurei, the floodbringer",
			"shock blast",
			"shojiro, the wavewaker",
			"skeletal shredwing",
			"soulless decree",
			"spidery grasp",
			"spire sanctuary",
			"spitfire",
			"succumb",
			"sun yun, master of self",
			"superiority complex",
			"surging stream",
			"technique of hao'tai",
			"the charmer's curse",
			"the dragon's madness",
			"the mad sage's scroll",
			"undead archivist",
			"unsettled rivalry",
			"unyielding presence",
			"vanishing memory",
			"vial of dragonfire",
			"wander ashore",
			"way of kindred mind",
			"wild germination",
			"wretched sanctuary",
			"xiong mao, survivalist",
			"xiusheng's teachings",
			"yawning crane",
			"aghavaan's corrupter",
			"aghavaan's wound",
			"ancient ossuary",
			"asharo's handmaiden",
			"asharo's yoroi",
			"ayashi, winter poet",
			"clutch of the coil",
			"council's will",
			"cursed scroll",
			"discorporate",
			"dragon's ire",
			"dragon's wake",
			"dragonwall samurai",
			"drown in sand",
			"festival of fading lights",
			"festival of roaring dragons",
			"festival of spring blossoms",
			"festival of winter's night",
			"final rest",
			"fireheart channeler",
			"flash of steel",
			"flow of the river",
			"heavenly temple",
			"hone the blade",
			"imperial ricefields",
			"imperial strategist",
			"imperial taxes",
			"kenshiro's yoroi",
			"kiyomi's disciple",
			"kiyomi's yoroi",
			"legends remembered",
			"masked impersonator",
			"masked stalker",
			"mautakesh strangler",
			"oshiruko cleansing",
			"pierce the storm",
			"reversal of fates",
			"sankataar assailant",
			"sankataar nightbringer",
			"sankataar scourge",
			"sasori ronin",
			"scorch",
			"searing script",
			"serpent's grasp",
			"shroud of hinasa",
			"shugenja sanctuary",
			"silk crane adept",
			"snake cult initiation",
			"soul leak",
			"stonesculpting",
			"storm of shadows",
			"sudden seism",
			"sunrise orchard",
			"swirling dragonfire",
			"touch of the coil",
			"tranquil ascetic",
			"unhallowed graves",
			"violent repercussions",
			"vizier of mautakesh",
			"voice of sheraku",
			"wayfarer's shrine",
			"wild lightning",
			"windwielder",
			"adaptive terrains",
			"ankryss' staff",
			"arcane might",
			"archaeomancer",
			"armament upgrade",
			"armor of vines",
			"beastly dispute",
			"berserker's axe",
			"blessing from above",
			"bloodstained knife",
			"brew of undeath",
			"brutal murder",
			"cancel",
			"cast away",
			"chaotic will",
			"confining priest",
			"crafted wings",
			"crafter's mistake",
			"cuff down",
			"cunning infiltrator",
			"dark desire",
			"daughter of malextros",
			"derrivan brawnmage",
			"deserter's disdain",
			"disassemble",
			"distressing reality",
			"divine verdict",
			"erudition of the lafterii",
			"explosive implant",
			"faint memory",
			"fervent assault",
			"fierce instinct",
			"flooded morass",
			"flourishing crevasse",
			"forced idleness",
			"gift of undeath",
			"goblin arsonist",
			"goblin stormcaller",
			"hate-driven arsonist",
			"heart of the glade",
			"hunger for battle",
			"impulsive action",
			"infected flesh",
			"infiltrator's appeal",
			"insatiable thirst",
			"knightly valor",
			"kragnoss, rebellion commander",
			"kragnoss' arsenal",
			"kragnoss' assault",
			"lavatorn fields",
			"led by fury",
			"logayr, lafterii magistrate",
			"logayr's tome",
			"magus of the sands",
			"malextros, deathlord",
			"mental dislocation",
			"mind's intruder",
			"monolith of ages",
			"moreena's banner",
			"natural growth",
			"natural recycling",
			"necromancer's talent",
			"pennon blade",
			"pillar of flame",
			"planar alignment",
			"pool of light",
			"prophetic flames",
			"rageborn phoenix",
			"raidragos, the vindictive",
			"ravenous rats",
			"reclamation sage",
			"repressed potential",
			"rush of strength",
			"seluriel, danuri leader",
			"shoot down",
			"sign in blood",
			"sorcerer's staff",
			"soul pierce",
			"soul of iscathia",
			"spreading disease",
			"springjack pasture",
			"spur of the moment",
			"suicidal impulse",
			"summoner's bane",
			"surprise strike",
			"swiftfoot elk",
			"tortured psyche",
			"toxic lurker",
			"vaertris, mindmelder",
			"vampire's curse",
			"vanguard's assault",
			"viper's fangs",
			"vythraktos, master necromancer",
			"vythraktos' dagger",
			"war golem forge",
			"ward shatter",
			"abrupt volley",
			"adamant healer",
			"amber hills",
			"arcane harvesters",
			"arcanomancer",
			"barbarian battle rage",
			"barbarian intimidator",
			"barbaric ambusher",
			"battle the evil one",
			"blessing of might",
			"blighted reckoning",
			"blighting ooze",
			"boiling ridge",
			"bravery",
			"bring down",
			"chain of command",
			"clever diversion",
			"coercive methods",
			"contemptuous teacher",
			"controlled decisions",
			"crippling illness",
			"cutthroat deceiver",
			"darklands charm",
			"deadly infection",
			"deadly manipulation",
			"decay",
			"deception",
			"dementia's clutch",
			"denied attempt",
			"dictate of rallios",
			"dictate of the evil one",
			"disentomb",
			"duskwood thicket",
			"dusty record",
			"elementalize",
			"elspeth, protector of the meek",
			"elspeth's intervention",
			"elusive illusionist",
			"empty the tombs",
			"erudite's tome",
			"ethereal savior",
			"evil one's mind tricks",
			"exodus of the khalizors",
			"expel from reality",
			"fading memories",
			"fatestitcher",
			"fellor charm",
			"flame jolt",
			"flooded depths",
			"forced loyalty",
			"general's presence",
			"goblin experimenter",
			"grim bastion",
			"grim recruitment",
			"hazy moorland",
			"helm of the anointer",
			"impulsive spirit",
			"inscrutable elixir",
			"intelligence",
			"intrepid shooter",
			"kill shot",
			"lafterii charm",
			"lafterii trickery",
			"lavaspark igniter",
			"magmatic torrent",
			"memories reignited",
			"menacing stance",
			"merkurio zellurys",
			"merkurio's prowess",
			"mirror image",
			"monument of war",
			"naturalize",
			"obliterating blast",
			"painstriker",
			"pandora's mending",
			"peaceful intentions",
			"piling corpses",
			"poisonblade elite",
			"poisonous shot",
			"polluted servant",
			"power of unity",
			"punish aggression",
			"reader of fates",
			"reconstruct",
			"rehison charm",
			"rugged fields",
			"runewing's feathers",
			"ruthless bash",
			"scar shed",
			"sealed mausoleum",
			"searing pulse",
			"shield's rebuttal",
			"shifting frontiers",
			"silencing curse",
			"spellgorger elemental",
			"spellmaster's dominance",
			"strangle to death",
			"strategic retreat",
			"strike from above",
			"sungrace meadows",
			"sunlit highland",
			"temporal loophole",
			"terrenal might",
			"the shield",
			"unbound researchers",
			"undead harbinger",
			"unknown shores",
			"venomous grasp",
			"veteran's plate",
			"wardbane mystic",
			"warden of rehis-dorahn",
			"warrior's blade",
			"weapon smash",
			"windrider elemental",
			"wretched spawn",
			"admonish the unruly",
			"altar of adversity",
			"altar of chaos",
			"altar of creation",
			"altar of destruction",
			"altar of order",
			"angelbane spider",
			"angelic destiny",
			"angeltouched cavern",
			"angeltouched crag",
			"angeltouched garden",
			"angeltouched marsh",
			"angeltouched saltflat",
			"archlegislator",
			"armorer of the soul",
			"assertive inaction",
			"bahet's wink",
			"bahum, penitent",
			"bane of identity",
			"beastwaker of gusma",
			"binding judgment",
			"blazeblade sergeant",
			"born from the flock",
			"chemical grenade",
			"chiara the enchantress",
			"combatant conflagration",
			"cosmostorm rider",
			"crisis of body",
			"curator of cures",
			"damnation of gluttons",
			"dark night cleansing",
			"dauntless qith",
			"death in reverse",
			"descended delta",
			"descended marsh",
			"descended meadow",
			"descended mortuary",
			"descended towers",
			"devilish undoer",
			"di'ala, ominous seraph",
			"dissolve",
			"divine detention",
			"divine lockdown",
			"dutiful counselor",
			"end of the road",
			"enforce the cycle",
			"essence of thought",
			"eternal path",
			"eternal recurrence",
			"ethereal fervor",
			"excise from existence",
			"false savior",
			"formed anew",
			"fury swipes",
			"heedless adversary",
			"hestia, doubtful archon",
			"ifram, god of chaos",
			"inspiring mantle",
			"instability elemental",
			"ishim of genesis",
			"ishim of oblivion",
			"ishim of punishment",
			"lifetwist",
			"lightning chorus",
			"masqued cleansers",
			"meditant's halo",
			"mindstorm's eye",
			"oracle of edicts",
			"peel from reality",
			"pierce the unruly",
			"qith maneuver",
			"recombobulate",
			"release from death",
			"repel the unruly",
			"return of the fallen",
			"return to ash",
			"righteous bolt",
			"saghira, divinity's usurper",
			"scrivener of sha'iv",
			"searing blasphemy",
			"sha'iv cagemage",
			"sha'iv, god of order",
			"sha'iv's scout",
			"silence of the guilty",
			"starlight seraph",
			"strength from chaos",
			"strength in imagining",
			"summer's approach",
			"tammil and sulei, the guides",
			"temple stalker",
			"test of fear",
			"thought police",
			"through new eyes",
			"tides of chaos",
			"tiller of potential",
			"unpredictable bloodshed",
			"wayfaring swindler",
			"whim of ifram",
			"wings of reckoning",
			"zaidha, seraph of calamity",
			"zealous enforcers",
			"ada, the free",
			"ada's mischief",
			"aetherial ascent",
			"ahl's study",
			"aleud grace",
			"aleud scorn",
			"alyss, lawweaver",
			"annihilate aggressor",
			"arisen haploc",
			"arroyo, the bound",
			"augment authority",
			"aurora, soulweaver",
			"blighted haploc",
			"bogclaw sniper",
			"brilliant griffin",
			"carrier pigeon",
			"carrionpult",
			"clipped seer",
			"confront death",
			"crafted coast",
			"crusher claw",
			"crystallizer",
			"culling claw",
			"dawn chord",
			"deathlink",
			"delirious landscape",
			"dire dive",
			"disgrace of kin",
			"dispel delusions",
			"earthen armor",
			"edge of the world",
			"elven war paint",
			"enduring memory",
			"enlightened lizard",
			"fading prison",
			"fallen fateweaver",
			"fateweaving",
			"ferrofy",
			"firing blind",
			"flare extensions",
			"foreign affliction",
			"foreseen denial",
			"foreseen failure",
			"foretold strength",
			"frenzied fervor",
			"gleamhorn elk",
			"gleaming mirrorweaver",
			"glintwing replica",
			"guerrilla strike",
			"halls of renown",
			"haploc assembly",
			"haploc striker",
			"haunted estate",
			"helm of the infinite",
			"hour of honor",
			"ichor fling",
			"intents",
			"kalak bridge",
			"lightbolt archer",
			"live",
			"lush outcrop",
			"lusterform",
			"lusterwing owl",
			"memory martyr",
			"might of the dylso",
			"mirrorwalk",
			"moonsight",
			"nullify naysayer",
			"proclaimed cure",
			"quadmired",
			"rain of ruin",
			"recast destiny",
			"reckless ride",
			"reclaim relics",
			"reins of influence",
			"reweave reality",
			"rite of fangs",
			"rooted hooter",
			"scaled mindreaver",
			"scaled thundercaller",
			"scattering light",
			"search",
			"searing insult",
			"shield of the lha",
			"sodden sorrow",
			"spired canopy",
			"stolen strain",
			"sweltering storm",
			"sword of memories",
			"tempt fate",
			"the blight beyond",
			"tormented echo",
			"treasurer of thought",
			"twisted elixir",
			"vicar of victory",
			"vicious slasher",
			"wait",
			"walk the seas",
			"wightlight",
			"above",
			"avoid fate",
			"bazaar guardian",
			"blazing mirage",
			"blood lashing",
			"chain of decimation",
			"channel the mirror",
			"clinging mire",
			"colpah charmer",
			"controlled burn",
			"cranial violation",
			"carving secrets",
			"deepcaller cultist",
			"delude",
			"dissipator mage",
			"divert attention",
			"draw and quarter",
			"dreamfire",
			"dredge the graves",
			"duela alchemist",
			"dusk chord",
			"dwarven twinslinger",
			"echo cleric",
			"echo striker",
			"echoing determination",
			"echoing rites",
			"echoing silence",
			"echoing sunder",
			"echoing thunder",
			"energize",
			"ensouler of blades",
			"exploit fear",
			"faded sacrifice",
			"false shimmer",
			"feed into aether",
			"fine craftsmanship",
			"flames of the forge",
			"flinging invoker",
			"forge trick",
			"forgotten fall",
			"frozen halo",
			"fueled flame",
			"ghastly castle",
			"gleaming veldt",
			"grisly marsh",
			"heat of the moment",
			"high",
			"hired kalak",
			"infiltrate memory",
			"intangible company",
			"learn from mistakes",
			"lha sha'rador",
			"lift off",
			"manifest memories",
			"market caster",
			"mei liva, the forsaken",
			"melt down",
			"memory deterioration",
			"mental meltdown",
			"might of the oslyd",
			"mightlight",
			"mindrip",
			"mirage adept",
			"mirage caster",
			"mirage keeper",
			"mirrorform",
			"mirrorfuse angel",
			"mirrorstalk",
			"mirrorstorm",
			"ore tunneler",
			"portent of doom",
			"reforged relic",
			"refract",
			"retrace histories",
			"revoke",
			"safe",
			"sandstrider",
			"sever existence",
			"shard flower",
			"sigil of echoes",
			"slightly mad",
			"spellwoven monster",
			"spiritual colpah",
			"sunken cavern",
			"sunny dunes",
			"surging kalak",
			"sword",
			"toggle",
			"trade blows",
			"trench breaker",
			"unveil",
			"vampiric rise",
			"vigil invoker",
			"adept necromancer",
			"amosis charm",
			"avatar of amosis",
			"awestruck",
			"basat charm",
			"brute force",
			"caravan sumpter",
			"crippling spirit",
			"dance for the heavens",
			"dawn silhouette",
			"desert temple",
			"despise",
			"divine denial",
			"divine protection",
			"doomed journey",
			"double arming",
			"dune peregrination",
			"eternal banishment",
			"expulse to the desert",
			"fire from above",
			"gates to the afterlife",
			"giant dromad",
			"gruesome transport",
			"high-priestess nebti",
			"imaginary flames",
			"jachsechep, god's wife",
			"judge unworthy",
			"kalro, desert outpost",
			"kill the competition",
			"life-giving waters",
			"menes, the great pyramid",
			"menhet charm",
			"mesmerizing shimmer",
			"mounted marksman",
			"mummy's grin",
			"njel crocodile",
			"peaceful sunbath",
			"preserving cloak",
			"pyramid lord",
			"rockpounding saurian",
			"sandborn mage",
			"sanding",
			"sandmouth dragon",
			"scaled lurker",
			"spell dilution",
			"sprawled arming",
			"stream of light",
			"streaming waters",
			"sudden drought",
			"survive",
			"tendrils of corruption",
			"terrifying ankh",
			"wachet charm",
			"winged envoy",
			"zarchepet, master of sands",
			"alenian boom squad",
			"annihilate the enemy",
			"arina's defiance",
			"auramancer's appraisal",
			"awaken to the skies",
			"bird call",
			"break hold",
			"counteredge blade",
			"deathfeeder",
			"deathwind expanse",
			"deathwind survivor",
			"deathwind's grasp",
			"defiant bristles",
			"deform sanity",
			"despair scavenger",
			"devastating impact",
			"duel of intellect",
			"earthfeeder worm",
			"elancean regrowth",
			"electrokinetic's bolt",
			"encrypted dagger",
			"esiara, skycaster's infiltrator",
			"essence scatter",
			"firewall trap",
			"flamerider",
			"forest whale",
			"fulmen, eldritch channeler",
			"gryla canyon",
			"hidden prowess",
			"icilica's icestrider",
			"infested goblin",
			"inspiration of war",
			"interan skycaster",
			"interan soothsayer",
			"jonah of the spellbane",
			"last parley",
			"lavahurler",
			"lerithan rebel",
			"lightbringer's touch",
			"moonshadow abyss",
			"morning's rise",
			"notion retrieval",
			"paralysis field",
			"perfect aim",
			"photon barricade",
			"plasma arc",
			"priest's altar",
			"pyre trap",
			"reliya's construct",
			"remove from existence",
			"renili, telenian weaponist",
			"shadowfeeder",
			"simplified life",
			"skycaster's aura",
			"spellbane's strike",
			"steelcharm obliterator",
			"stormcaster's tower",
			"supreme judge",
			"syncopate",
			"sythian enrichment",
			"sythian interference",
			"sythian scripture",
			"tether of simplicity",
			"touch of corruption",
			"trapcatcher's form",
			"treecrawler elemental",
			"triline hunter",
			"vampiric defenses",
			"abrupt explosion",
			"acabo, the fabled falcon",
			"akimbo slash",
			"ancestral shrine",
			"aquatic refuge",
			"arbalest barrage",
			"ascendant's murmur",
			"attuned ancient",
			"blazing beam",
			"cai lan, the chained",
			"child of the pack",
			"citadel of denial",
			"concentrated blast",
			"contentious yak",
			"crane's way",
			"crippling fear",
			"dazzling display",
			"decipher the dark tome",
			"deep temptation",
			"deluge crab",
			"dessication ritual",
			"dimensional plunge",
			"divine dispersion",
			"essence rehabilitator",
			"fierce howl",
			"fox of the molten dawn",
			"foxflame",
			"graveyard shift",
			"harrowing infusion",
			"haunting illusion",
			"heated dispute",
			"heping's armistice chains",
			"heyu, immortal hunter",
			"hui zhou, the dark visage",
			"hunter's instinct",
			"hypnotic halo",
			"illustrious lantern",
			"ing'wei, the surging tide",
			"kan'gi, the reverent",
			"liao, seto's shield",
			"lifeblood leecher",
			"malignant afflicted",
			"mamei, benevolent tyrant",
			"melodious musician",
			"monumental siege",
			"no-man's land",
			"noble fall",
			"once more with style",
			"organic corrosion",
			"orichi of the cold mist",
			"paralysis specialist",
			"parrying scholar",
			"perimeter siege",
			"perplexing turmoil",
			"prairie monastery",
			"rhythmic distraction",
			"robe of shadows",
			"scorched copse",
			"sea wall",
			"shimmering veil",
			"siphoning slash",
			"skirmish scars",
			"slippery salamander",
			"staggering brilliance",
			"stand tall",
			"stitch sinew",
			"strike out",
			"sunless ridge",
			"sunspear surge",
			"sustaining meditation",
			"swift savior",
			"temple of brilliance",
			"til death",
			"toxic spring",
			"vial of ice",
			"vigorous dryad",
			"vindictive pyromancer",
			"wash away",
			"woken wave",
			"xiong's gambit",
			"abinna, humanity's herald",
			"abinna's consecration",
			"akrianos, redeemed avenger",
			"akrianos' command",
			"althestran oathsworn",
			"ammbradu parasite",
			"arsenal curator",
			"artful diversion",
			"artificer's persuasion",
			"auramancer",
			"battlemage's disruption",
			"battlewise aptitude",
			"bioenhancement",
			"black cat",
			"blessing of plenty",
			"blissful lull",
			"blood-tithe harpy",
			"bloodcrazed instigator",
			"blow to pieces",
			"bomb juggler",
			"bonds of quicksilver",
			"brace for battle",
			"branding shackles",
			"burglar's mischief",
			"burn with demonfire",
			"butcher's fervor",
			"callous renegade",
			"celestian crusader",
			"centipede engine",
			"consuming doom",
			"contempt for the unnatural",
			"dazzling voidmage",
			"delirious fervor",
			"deranged arsonist",
			"earthenlore blessing",
			"earthenlore disciple",
			"enduring vestige",
			"erika, mourning soul",
			"erika's purge",
			"escape hatch",
			"ethereal armor",
			"evasive maneuver",
			"fallen ideal",
			"fatresya, protector of the people",
			"fatresya's ankh",
			"fatresya's command",
			"form of the phoenix",
			"foundryborn ingester",
			"frontline commander",
			"frostfire geysers",
			"fungal mire",
			"general merthilios",
			"gloomcover steppe",
			"glorious revival",
			"goblin sniper",
			"goblin tunneler",
			"gorandu's majesty",
			"goriana battlechief",
			"goriana earthshaker",
			"goriana naturalist",
			"goriana tactician",
			"griffin skycaller",
			"guiltless brutality",
			"harmonical weaver",
			"harpoon launching",
			"heartstabber mosquito",
			"igniting lavaling",
			"imposing bulkvine",
			"incapacitated",
			"infiltrate celestia",
			"infiltrate nimunot",
			"infiltrate rammaneth",
			"insurgent's blade",
			"jeska, neolition leader",
			"jeska's command",
			"kellythross' workshop",
			"kevthra's command",
			"knight's daring",
			"loot hoarder dragon",
			"loxodon battlepriest",
			"lush oasis",
			"mark of mutiny",
			"merkurio, volatile elementalist",
			"merkurio's command",
			"merthilios' escort",
			"meticulous dissector",
			"mold shambler",
			"molten ritual",
			"moment of madness",
			"network sabotage",
			"nightchill grasp",
			"novice pyromancer",
			"nroxi beastmaster",
			"pestilent renewal",
			"pinpoint accuracy",
			"prohibit",
			"purging priestess",
			"purging strike",
			"ragantiar, maurassi overlord",
			"ragantiar's hoarding",
			"ralezza, weaver of okthuros",
			"rammanethi hydroshaper",
			"rammanethi sandshaper",
			"rampaging tremorwurm",
			"reengineer",
			"reorganized thoughts",
			"replicator mage",
			"runic soulthief",
			"sagewood animist",
			"sanctuary invocation",
			"scrapgear contraption",
			"scrapyard aberration",
			"seismic strike",
			"sense of loss",
			"seven deadly sins",
			"shrine of the six pillars",
			"skyblind duo",
			"smoldering blade",
			"soul of misery",
			"spellbound gauntlet",
			"spinegraft disabler",
			"spiraling canyon",
			"sporesowed disease",
			"stampede instigator",
			"steelhoof battlechief",
			"stunning jolt",
			"terror of the tides",
			"total recall",
			"unpredictable blizzard",
			"unstable orb",
			"valtrian cavalier",
			"vanquish the obsolete",
			"vedalken reshaper",
			"vengeful ferocity",
			"vestige of skithiryx",
			"vile weavers",
			"violent offensive",
			"volatimancer",
			"wingcrafter's legacy",
			"absence of the unmaker",
			"arcor windfall",
			"arrive unseen",
			"arrogant training",
			"bend the knee",
			"beneath the lilies",
			"bustling docks",
			"change of fortunes",
			"choked estuary",
			"cloak of the exiled",
			"commoners' justice",
			"coward's compulsion",
			"curiosity",
			"dance of grace",
			"dead man's armor",
			"death's door",
			"derelict amphitheatre",
			"distracting handmaiden",
			"drunken night",
			"duress",
			"exile's vanguard",
			"fall of whiterun harbor",
			"fall of the axe",
			"farmer's repose",
			"feathered dancer",
			"femourri archer",
			"forbidden knowledge",
			"foreboding ruins",
			"forgo the past",
			"fortified village",
			"game trail",
			"generous offer",
			"grand tourney",
			"hasty intervention",
			"hermit's travels",
			"hypersomnia",
			"ill-advised tactics",
			"inner dogmatism",
			"interlocked waterways",
			"isolated cloister",
			"jailer's manacles",
			"left for carrion",
			"lone heroics",
			"melting point",
			"merchant's bane",
			"messenger's haste",
			"minor melee",
			"misleading doubts",
			"moment of glory",
			"moment of tranquility",
			"morning mists",
			"mutual destruction",
			"old grudges",
			"pacifism",
			"plunge through the heart",
			"port town",
			"price of power",
			"publicly disgraced",
			"punish the bold",
			"pursued paranoia",
			"ranger's guile",
			"reckless cultivator",
			"reflect upon the past",
			"reverence seeker",
			"roads twice traveled",
			"royal summons",
			"sage's foresight",
			"sails of commerce",
			"seal the tomb",
			"seek glory",
			"sera of coppercove",
			"shadowed slums",
			"shatter",
			"social graces",
			"splitshaft deadeye",
			"spur to action",
			"sturdy belligerent",
			"sunken ambitions",
			"surge of duty",
			"sway the naive",
			"take for ransom",
			"tearful reunion",
			"tectonic wound",
			"tenacious guide",
			"thailen's reprisal",
			"three blade boon",
			"till the fields",
			"tranquil endeavors",
			"trapped in the tower",
			"trystasp coating",
			"twilight raid",
			"under cover of dark",
			"vial of arcor",
			"visiting dignitary",
			"voyage's end",
			"weaken defenses",
			"weary steward",
			"weaver of tales",
			"whiterun gates",
			"whiterun harbor",
			"wildborn lancer",
			"wildborn swindler",
			"withering agony",
			"youthful dreams",
			"yvette, the golden gull",
			"abandoned battlefield",
			"abandoned cairn",
			"abandoned meadow",
			"abandoned skyroad",
			"abandoned wilderness",
			"academy wastes",
			"alpine meadow",
			"barren desolation",
			"calmed battleground",
			"charbroiled core",
			"chiseled cliffside",
			"cleared vault",
			"cliffside entrance",
			"command tower",
			"dawnlit battlefield",
			"deadwood grove",
			"deeplife cavern",
			"deserted steppe",
			"deserted trail",
			"desolate barrens",
			"exotic xenoreef",
			"fiery chasm",
			"flourishing waterways",
			"forgotten cryovault",
			"forgotten shrine",
			"frigid highlands",
			"frontier base",
			"gleaming hot springs",
			"gnarled henge",
			"grim slums",
			"grove of reversal",
			"haughty chateau",
			"haunted woodlock",
			"highland vale",
			"horizon of origins",
			"imperial barracks",
			"jagged crag",
			"legacy foundations",
			"lush outskirts",
			"mossy shrine",
			"mysterious cataract",
			"ocean monastery",
			"ominous lair",
			"ornamented evergreen",
			"overgrown refuge",
			"quintok station",
			"rainforest spring",
			"roaring cascade",
			"secluded cascade",
			"shardstone rift",
			"shrouded rooftops",
			"sky-high spires",
			"sodden cavern",
			"somber marsh",
			"spires of telenia",
			"stormcharged pyre",
			"strange harbor",
			"sunlit ruins",
			"timber range",
			"tirenan market",
			"torrid geysers",
			"toxic jungle",
			"tranquil stream",
			"unlit alley",
			"wastes",
			"weathered fortress",
			"wildrune thicket",
			"abandoned forge",
			"abandoned hideout",
			"abandoned laboratory",
			"abandoned preserve",
			"abandoned shores",
			"anguished unmaking",
			"bestial mob",
			"blood frenzy",
			"breaking news",
			"choking despair",
			"cloudsnatch",
			"courier eagle",
			"creeping terror",
			"danawan wanderer",
			"dancing flames",
			"descent of the stars",
			"distant thunder",
			"doctored trail",
			"emberling",
			"ephemeral support",
			"essence of nurture",
			"evanescier greypelt",
			"flickercloak",
			"foul drifter",
			"guardian's resolve",
			"hollow hooligan",
			"insightful blow",
			"living antimagic",
			"lost in fugue",
			"mass pandemonium",
			"miede-district enforcer",
			"moonshadow remnant",
			"mystic's mantle",
			"paralyzing ennui",
			"rakdos drakeswarm",
			"revenge of the disfigured",
			"rheila rachy",
			"solar wisp",
			"split-second decision",
			"still the pandemonium",
			"the midwife",
			"thomar's sowing",
			"absolve",
			"abura-no-oni",
			"anzen, beyond the sea",
			"awoken nightmares",
			"betrayal of steel",
			"chikami castle",
			"chochin the silent moth",
			"commander hyctaleon",
			"disciple of flames",
			"dragonwall gates",
			"emblem of aghavaan",
			"emperor azuma hashiro",
			"faceless animist",
			"finishing touches",
			"fires of seishin",
			"fleeting thoughts",
			"forbidden brew",
			"forgotten homelands",
			"hanabira, kogane's legacy",
			"heirloom",
			"hirukari, daughter of the sun",
			"hisana-no-oni",
			"house of forgotten whispers",
			"iaijutsu",
			"imako, ninefingers",
			"imperator valtasius",
			"imperial port",
			"imperial siege",
			"imposition",
			"inner peace",
			"inner purity",
			"inoshi the wild boar",
			"kami's greed",
			"kamu-tribe outfitter",
			"kamu-tribe runt",
			"kareki heretic",
			"kasoha, keeper of truths",
			"keeper of dark shadows",
			"kemono-no-oni",
			"ketsueki, kiyomi's legacy",
			"konoe the traitor's hand",
			"kuma strike",
			"kurayami butcher",
			"kurayami shrine",
			"kuryu swordsman",
			"legacy's end",
			"lesson in discipline",
			"lord rokai",
			"mana corruption",
			"memorial of the fallen",
			"midnight keep",
			"mua, seishin ascendant",
			"mystic arts",
			"only memories remain",
			"perilous passage",
			"phasmophobia",
			"prayer of drifting lights",
			"raiun bay scourge",
			"ronin of broken vows",
			"saishuteki castle",
			"sanctify",
			"scions of old jidai",
			"sea hunter",
			"seishin dojo",
			"serene form",
			"sever limbs",
			"shikai's redoubt",
			"shizura, keeper of traditions",
			"snake tattoo",
			"soulbreaker of mautakesh",
			"spectral kitsune",
			"spirit reflections",
			"student of the coil",
			"sunset monastery",
			"takaki's kihei",
			"temple of falling leaves",
			"the last sacred gate",
			"thousand cuts",
			"tower of long shadows",
			"treacherous ways",
			"tsang jin, master of the jade sea",
			"unhallow",
			"unleash the dragon",
			"unzari ruins",
			"whisper of the winds",
			"worthy of the name",
			"yamisaran bladedancer",
			"aiel tazan",
			"anurafication",
			"arcanum owl",
			"aspect of rage",
			"assassinate",
			"bloodstone halls",
			"brain static",
			"caustic lurker",
			"channel enmity",
			"copse watcher",
			"corrupted strength",
			"crumbling vestige",
			"daril, agent of time",
			"daril's timewalker",
			"death strike",
			"depths of solitude",
			"divine ascension",
			"dominion crown",
			"dracosoul",
			"due judgement",
			"edge of madness",
			"elegant fireslinger",
			"ember salvo",
			"ensnaring vines",
			"erase from existence",
			"exclude",
			"forced sprouting",
			"galeforce ",
			"gavis the stalwart",
			"gavis's dragoons",
			"goblin cutpurses",
			"goldhill enforcer",
			"goldhill guardian",
			"gossamer veil",
			"grave revenant",
			"harm's way",
			"harvest moon",
			"hav'za, itavan warchief",
			"healer's knack",
			"heavens above",
			"hill of souls",
			"illusionary steed",
			"in arms",
			"infernal invocation",
			"inferno forerunner",
			"ironsmash wrecker",
			"kalime charger",
			"kusore, essence spinner",
			"leech soul",
			"life's harbinger",
			"life's will",
			"lightning strike",
			"lord of swarms",
			"maelstrom griffin",
			"magmatic ravager",
			"mavisa, wayfinder",
			"meteorain",
			"mighty swing",
			"mind crash",
			"monstrous guise",
			"moonlit shore",
			"morbid plunder",
			"move unseen",
			"murderous rampage",
			"nimbus fae",
			"northwind master",
			"ophelia's neophyte",
			"planar processor",
			"prey upon",
			"pull the strings",
			"pummel",
			"puppetize",
			"pyrostorm",
			"recall to mind",
			"redo",
			"rise from the grave",
			"rouse from below",
			"rule of nature",
			"sagi's revenant",
			"sanctum",
			"sanguine mortifier",
			"scourge of the skies",
			"seabreen nullmage",
			"searshot dragon",
			"seismic spike",
			"shieldmaster's blessing",
			"sink into despair",
			"skavi behemoth",
			"soul flame",
			"spell shackle",
			"spirit drain",
			"steeled resolve",
			"stillness",
			"stoneskin",
			"sunwright scion",
			"surging charge",
			"swordmaster's blessing",
			"tactical maneuvers",
			"tainted grounds",
			"thought siphon",
			"trail of rebirth",
			"travian archsage",
			"valley falls",
			"vampiric thirst",
			"vanishing stroke",
			"vengeant souls",
			"verdant sanctum",
			"verendas spiritwalker",
			"waketide serpent",
			"wayfarer's lantern",
			"wellspring of life",
			"wild fervor",
			"wild ravine",
			"zephyr rider",
			"aether tradewinds",
			"blessing of bliss",
			"blight seed",
			"blood ritual",
			"bloodriver",
			"blossoming defense",
			"breathgiving roots",
			"brush off",
			"buzzing flitter",
			"captivate",
			"child's play",
			"cloudbank",
			"cloudchaser kestrel",
			"cloudfisher",
			"cloudwing",
			"corpsebed",
			"corrupted dancer",
			"corrupted warlord",
			"corruption's hold",
			"crackling seaform",
			"cradle of corruption",
			"crash down",
			"dawnsong",
			"dazzle",
			"deadeye drowner",
			"deathmask initiation",
			"devious naiad",
			"devoted dancer",
			"dodgy infant",
			"don the deathmasks",
			"drown",
			"drowned weaver",
			"eldritch undoing",
			"elrayin, the manaroot",
			"embrace the curse",
			"envious nereid",
			"even death may die",
			"eye of a moment",
			"fallweather dancer",
			"giant growth",
			"gifted grace",
			"gone with the wind",
			"gorran hunter",
			"gorru deathmask",
			"gravelocked seeker",
			"grip of the deadwood",
			"haunted sunseeker",
			"heart of the deadwood",
			"heat of day",
			"honorwing",
			"horned spy",
			"koisoul diver",
			"lapidify",
			"liquefaction",
			"lurking in the reeds",
			"mistcharm",
			"monkey trinket",
			"moonlace",
			"mosecf, the sunseeker's path",
			"mother night",
			"nymph's greed",
			"oppressive rays",
			"orria mirrorpelt",
			"overflowing knowledge",
			"overkill",
			"path to mortality",
			"pitchwater singer",
			"planar eviction",
			"pond tenders",
			"predator's hunger",
			"primal resurgence",
			"prismweaver",
			"quickchange",
			"ralora, unforgiving depths",
			"raloran adept",
			"reconsider",
			"relinquish",
			"return to light",
			"revert to dust",
			"ride the waves",
			"river's wrath",
			"rotting sunseeker",
			"runes of ralora",
			"rylei wakebreaker",
			"school the fish",
			"sea of skies beyond",
			"seafoam charmer",
			"seedshrine",
			"seeker sword",
			"seeker's end",
			"sever",
			"shifting terrain",
			"shimmerhold",
			"slippery capuchin",
			"sneaking capuchin",
			"spark of faith",
			"spiteful growth",
			"springcaller",
			"starglare",
			"striptide",
			"suncatcher",
			"sunlight dancer",
			"sunstage",
			"swirling sylph",
			"tempest core",
			"thicketwalker",
			"thunder wave",
			"twilight walker",
			"undine coven",
			"vaporize",
			"veiled charmer",
			"venomous gorran",
			"voice of ambition",
			"whispers of the dark",
			"yrodu, the lotus ablaze",
			"arcor-staff adherent",
			"arctic mine",
			"assassin's warning",
			"awash in despair",
			"boneweary warrior",
			"callow survivors",
			"carve a path",
			"chapel warden",
			"comfort the fallen",
			"conspiracy of ravens",
			"crumbling precipice",
			"crystal cavern",
			"crystal puncture",
			"cull the citizenry",
			"daunting skyline",
			"days of decay",
			"debt dignitary",
			"decrepit crags",
			"disassociate",
			"dockyard stalker",
			"dockyard swindling",
			"dregs of order",
			"drown in nightmares",
			"evade the authorities",
			"exhaustive toil",
			"failing port",
			"false-cure smuggler",
			"fate transfer",
			"fervent arbiter",
			"flee the city",
			"forgotten consequences",
			"forgotten sins",
			"forgotten steppe",
			"fretport anarchists",
			"fretport gravetender",
			"fretport's lament",
			"grace of the trinity",
			"grim courtyard",
			"harriet, liberated wildborn",
			"hateful gaze",
			"hazy lagoon",
			"heedless lovers",
			"honor's refuge",
			"invalidate",
			"iron warden",
			"judge's decree",
			"kalemn weller",
			"kasienka, raven's regarded",
			"let loose",
			"loss of focus",
			"lurking terrors",
			"martyr's sacrifice",
			"master of disorientation",
			"mental fracture",
			"merchant's district",
			"morning passages",
			"mourn the lost",
			"murmuring falls",
			"nomad's township",
			"pale flotsam",
			"phosphorescent ravine",
			"political opportunist",
			"prayers of defiance",
			"prayers of release",
			"precarious ledgers",
			"purge the harbor",
			"purging watchkeeper",
			"rampant summit",
			"raven's standard",
			"resource management",
			"resplendent bearing",
			"resplendent substratum",
			"rickety guildhall",
			"right to challenge",
			"rising riots",
			"ruined citadel",
			"scatter riches",
			"sedate tundra",
			"selective prophecies",
			"serene trail",
			"shared reminiscence",
			"shifting glade",
			"sickening madness",
			"stalwart physicker",
			"strength of the devout",
			"the raven queen of fretport",
			"thespian's finale",
			"to say farewell",
			"track prey",
			"traumatic memories",
			"unbeholden to death",
			"unjust sentence",
			"untested recruit",
			"valor of the desperate",
			"vibrant rainforest",
			"wary watchkeeper",
			"watchkeeper's prerogative",
			"watchkeeper's retort",
			"weathered veteran",
			"weight of sin",
			"whiplash",
			"wildborn courtesan",
			"wisdom in reflection",
			"withering beggar",
			"aether recoverer",
			"aetherite shackles",
			"aetherite slugs",
			"aetherite vein",
			"aetherwhirl",
			"arcane heist",
			"arrest",
			"atop their high horses",
			"axom, the drifter",
			"azun, sheriff of daisite",
			"azun's play",
			"bearidge charmer",
			"bearidge marshall",
			"bearidge preacher",
			"blind soulcaller",
			"bloodleaf warcry",
			"bounty collector",
			"brush sniper",
			"cage the mind",
			"campfire stories",
			"cardsharp drifter",
			"collapsed mine",
			"dead man's hand",
			"derelict town",
			"diligent deputy",
			"disallow",
			"dispel",
			"down barrel",
			"drifting warden",
			"dual wield",
			"dusk rider",
			"elven wanderer",
			"embed",
			"feed to the pigs",
			"fool's gold",
			"forgotten haunt",
			"ghastly character",
			"ghostly flicker",
			"gift of shadows",
			"gifts of ancient ulek",
			"gleaming rider",
			"graygulch drifter",
			"graygulch lurker",
			"graygulch turncoat",
			"gulchdrinker serpent",
			"gun fight",
			"haide bankbuster",
			"hair-trigger marshall",
			"hardened soul",
			"harsh wastes",
			"haunting bard",
			"head in the clouds",
			"high noon",
			"high spirits",
			"howler sellout",
			"howler sheriff",
			"injustice",
			"judges' shield",
			"land grab",
			"lead the charge",
			"lonely return",
			"make an entrance",
			"march of the gray",
			"midnight fright",
			"mighty totem",
			"mudslinging",
			"murder",
			"needle doll",
			"nightrail forger",
			"nightrail kingpin",
			"nightrail printer",
			"old-world forgotten",
			"old-world walker",
			"one with the herd",
			"pains of the drunk",
			"penny dreadful",
			"public hanging",
			"qilan wanderer",
			"quelling tavern",
			"ravenous chupacabra",
			"recoil",
			"reforge",
			"refund",
			"ride into the sunset",
			"roxite of nightrail",
			"roxite's revenge",
			"sandbluff assailant",
			"sandbluff confiscator",
			"sandbluff enforcers",
			"sandbluff slinger",
			"sareng, the dealer",
			"scoundrel's aetherlock",
			"silence of the drifter",
			"slighted spirit",
			"slinger's showdown",
			"songs of the howlers",
			"sparkling jackalope",
			"spectral slinger",
			"spirit guidance",
			"spirit of infamy",
			"stand your ground",
			"stickup",
			"stolen cache",
			"street urchin",
			"sunrise bluffs",
			"sunrise prairie",
			"sunrise river",
			"sunrise ruins",
			"sunrise woods",
			"sunset cliffs lawman",
			"sunset cliffs patron",
			"take aim",
			"tavern brawl",
			"the aetherite saloon",
			"the wicker lord",
			"threaten",
			"vengeful agent",
			"victims of graygulch",
			"wanted",
			"warning shot",
			"wave of goblins",
			"wild bounties",
			"winning hand",
			"wu, the shackled",
			"abscond",
			"aguri, shadow of doubt",
			"aokara commander",
			"ashspeaker",
			"backburner",
			"bitter lies",
			"bond of battle",
			"chamber of splendor",
			"chimei scourge",
			"daughter of suisei",
			"diffuse",
			"dragon's eye descendant",
			"dragonfly shrine",
			"dragonmaw wurm",
			"dragonsoul disciple",
			"dreams of tomorrow",
			"elemental power",
			"enemies of my enemy",
			"enshrine",
			"fiery embrace",
			"fire and ashes",
			"fireshaper adept",
			"flash of blades",
			"garrote",
			"grasp of water",
			"hand of the governor",
			"heartcleaver",
			"horizon treader",
			"jade temple",
			"jade vault reclaimer",
			"kareki stormshooter",
			"kemuri saboteur",
			"kinjiru sandshaper",
			"kodaichi bladedancer",
			"kuno aokara, ivory crane",
			"lives redeemed",
			"mirai, spring's promise",
			"mortal will",
			"night ambush",
			"nightmarish fears",
			"odaya magistrate",
			"old soeji",
			"oshiruko operative",
			"oshiruko silencer",
			"palace of reflections",
			"path of shadows",
			"profaner of souls",
			"red flower assassin",
			"ride as one",
			"rippling water shugenja",
			"rising tides",
			"searing grace",
			"seikatsu warleader",
			"shengin heartland",
			"shengin scoundrel",
			"shengin tactician",
			"smoldering pages",
			"soul jar",
			"stolen breath",
			"stolen secrets",
			"strike from the shadows",
			"sundering sage",
			"takara flameblade",
			"throwing stones",
			"thunder from above",
			"toil the fields",
			"torrent of wind",
			"vanish",
			"venerable purist",
			"windshaper",
			"yamamai invoker",
			"aerie's pillar",
			"aether ascendant",
			"almgrove sentinel",
			"archive guardian",
			"ardy, youthful geomancer",
			"arpechian tiger",
			"artisan of marrow",
			"blessing of valor",
			"bloated keystone",
			"bygone guardian",
			"ceaseless valiant",
			"channeling stone",
			"clockwork spellwork",
			"compulsion's voice",
			"confirm hypothesis",
			"crystal conjuration",
			"entrancing virtuoso",
			"false vitality",
			"forgotten pit",
			"gruff smith",
			"ironwood elemental",
			"keystone conjurer",
			"lodestone convergence",
			"lumbering hillock",
			"paternal pride",
			"prismatic leyline",
			"rahit's prodigy",
			"rousing rubble",
			"runic depths",
			"salva tore's vexation",
			"salva tore",
			"shatter facade",
			"stall fate",
			"stormsurge",
			"submergence",
			"thought blossom",
			"thunderous charge",
			"visceral offering",
			"whistling blades",
			"abandoned den",
			"aegis expertise",
			"ascetic of imbalance",
			"aspect of focus",
			"astrid, disgruntled princess",
			"awoken soul",
			"bear necessities",
			"bear in mind",
			"beat down",
			"bereave",
			"bestial harmony",
			"bjarndyr militant",
			"bjarndyr outfitter",
			"blood hunter's spear",
			"bloodhunter orca",
			"bloodshed devotee",
			"bloodsworn provoker",
			"blow away",
			"brain feeding",
			"breathless gasp",
			"byway bruiser",
			"cane dancer",
			"casualty of war",
			"cinder arrows",
			"cogent recruiter",
			"conviction",
			"crippling apparition",
			"cryptic ritual",
			"culi-sae exonerator",
			"culi-sae mesmer",
			"culi-sae partisan",
			"culi-sae transfigurer",
			"dark harvester",
			"dawn siege",
			"demand submission",
			"demolish",
			"devastating blow",
			"dire betrayal",
			"dragon queen's den",
			"efface",
			"engrave",
			"ephemeral visions",
			"equanimity",
			"fiery reckoning",
			"flailing terror",
			"frost walker",
			"frosted adder",
			"furor of the bitten",
			"greenheart den",
			"grizzly matriarch",
			"hat trick",
			"heartless host",
			"hemley eggfeather",
			"hibernation den",
			"howl of the hunted",
			"ice over",
			"icy manipulator",
			"inborn instincts",
			"intrepid shieldmate",
			"invocation circle",
			"issbarren warden",
			"issbarrens banishment",
			"join the pack",
			"last dusk",
			"light a fire",
			"lose composure",
			"lumbering egil",
			"marked scent",
			"model of perfection",
			"mortal resurrection",
			"mountain bighorn",
			"murderlust",
			"nature's claim",
			"phantasmal possession",
			"pinion peaks",
			"play the coward",
			"raider's den",
			"recover",
			"rend asunder",
			"reticent possessor",
			"rimecraft owl",
			"ruthless conscript",
			"saffrisa, heir apparent",
			"saffrisa's touch",
			"sanctifier spirit",
			"scornful flames",
			"seismic passage",
			"seto san, forlorn savior",
			"shambling gutless",
			"shipway whale",
			"shorecrash octopus",
			"shredding blizzard",
			"sinful burial",
			"sinner's purge",
			"skeigr, skhorvall flagship",
			"skhorvall raider",
			"soul release",
			"soul stroke",
			"splintering hail",
			"staff of equilibrium",
			"starlit raze",
			"steelcrusher viking",
			"steward of the code",
			"student's pilgrimage",
			"sullen bonecrusher",
			"syrina, the dragon queen",
			"tear loose",
			"temple instructor",
			"the issbarrens",
			"third legion rider",
			"thoughtless malice",
			"to the hunt",
			"touch of shadow",
			"transcendent arts",
			"treacherous conditions",
			"turbulent journey",
			"twilight delirium",
			"unburdened rage",
			"unending voracity",
			"viking greataxe",
			"viork woods butcher",
			"vitality reclaimer",
			"wake of the beast",
			"wanton cleave",
			"war-torn tundra",
			"warfield excavator",
			"warring ways",
			"wave of ice",
			"weirding wings",
			"winter widow",
			"a whisper's touch",
			"amateur pilfering",
			"autumn moon",
			"bellani mystic",
			"benign whisper",
			"blundering clocktower",
			"borderland garrison",
			"bout of boredom",
			"buoyant thoughts",
			"cackling jack",
			"canyon creek",
			"charitable wisdom",
			"charm canary",
			"chef's apprentice",
			"cloud rock",
			"clouded mind",
			"concord of ravens",
			"crinster innocents",
			"crinster stitcher",
			"crystal grotto",
			"cumulus horizon",
			"dance of fire",
			"desraen, serpent's will",
			"driven to distraction",
			"edith waunt",
			"embergourd scarecrow",
			"evolving wilds",
			"fate of the brave",
			"fate of the devout",
			"fate of the generous",
			"fate of the wayward",
			"fate of the weary",
			"feed the eager",
			"fey grove",
			"frailty",
			"frigid thicket",
			"furtive witch",
			"gorgon's gaze",
			"grinning fox",
			"haunted boughs",
			"hint of exuberance",
			"humored outlaw",
			"incarcerate",
			"intoxicate",
			"inviting feast",
			"lady heiffyd",
			"latent potential",
			"legend of the brave",
			"legend of the devout",
			"legend of the generous",
			"legend of the wayward",
			"legend of the weary",
			"lord's handmaiden",
			"midnight stalking",
			"moon of the encroaching night",
			"moon of the final dawn",
			"moon of the frozen dusk",
			"moon of the lingering day",
			"moon of the promised day",
			"moonlit hunter",
			"radiant bonds",
			"reflect on serenity",
			"ruined precipice",
			"soaring canyon",
			"steady reminiscence",
			"the witch queens",
			"thunder shrike",
			"touch of witchcraft",
			"verdant bluff",
			"whisper witch",
			"accursed by unborn fates",
			"aethermage's chains",
			"ancient cairns",
			"antimagic",
			"arcane duelist",
			"archivist's torment",
			"ashen host",
			"aura of leadership",
			"barricade patrol",
			"blood cult covenant",
			"bloodspawn",
			"cackling tormentor",
			"chroma, the faerie circle",
			"cloud runner",
			"confront",
			"crack open the cache",
			"curse of unraveling",
			"deem incomplete",
			"demonqueller mage",
			"dimensional dodge",
			"dimensional isolation",
			"dispersive volley",
			"duelist's forms",
			"duelist's wings",
			"elemental of vengeance",
			"enter the labyrinth",
			"exiled necromancer",
			"fae-blessed attendant",
			"field of obelisks",
			"finish the job",
			"force back",
			"from ancient tomes",
			"gate to the nav",
			"gift of fire",
			"grip of paranoia",
			"guardian of the eclipse",
			"guardian's revocation",
			"high chancellor kazimir",
			"immortalize in stone",
			"intertwined fates",
			"ion field",
			"kazimir's inquisition",
			"keep at bay",
			"kindle the cursed",
			"king of bones",
			"lodestone sword",
			"masha's lightbound",
			"merchant of false lives",
			"mirror cipher",
			"mischievous sprite",
			"moss dweller",
			"nature's defiance",
			"noxious garden",
			"overgrown ruins",
			"pact of martyrs",
			"paincaller",
			"paranoid archivist",
			"patient aethermage",
			"pelaski valiant",
			"prying inquiry",
			"pyremage's knack",
			"realmwalker domovoi",
			"return to earth",
			"rune-scribe's apprentice",
			"runebreaker mage",
			"sadistic indulgence",
			"scholar of reflections",
			"serafina, the traitor amongst",
			"serafina's gift",
			"sever flesh",
			"skymount reinforcements",
			"slaffield workgate",
			"sower of dreamless sleep",
			"sphinx of ill omens",
			"stonefall golem",
			"student of lightning",
			"tear through",
			"thunderstep ved",
			"titan of lake vasil",
			"touch of the uncanny",
			"traitor's execution",
			"trespasser of the gallows",
			"under untamed skies",
			"unmasker of fate's design",
			"vanguard of the barricade",
			"wanderer's sky",
			"warden of the archives",
			"wave of decay",
			"wither",
			"wreath of crows",
			"yuroda's blessing",
			"zadyk assassin",
			"zadyk resourcefulness",
			"acorn assault",
			"aerial watch",
			"alley hunter",
			"amateur auteur",
			"arisen troops",
			"ascendant's gate",
			"awestone",
			"babbling experiment",
			"backalley silencer",
			"backstage rooms",
			"bahum, the warden",
			"bessie, the muscle",
			"bessie's brood",
			"blood artist",
			"bounty crusher",
			"break a leg",
			"brilliance overbearing",
			"cadalon chemist",
			"cadalon inspector",
			"clock of seasons",
			"compulsive accuser",
			"control discourse",
			"coral hunter",
			"cornrose, the mighty",
			"corpsing",
			"crux pinnacle",
			"cursory glance",
			"defying gravity",
			"diasune immolator",
			"diasune tracker",
			"distracting performer",
			"dying breath",
			"ediam, the inside man",
			"eldritch egg",
			"elsewhere mirror",
			"elven guard",
			"encore",
			"epic confrontation",
			"exit, pursued by a bear",
			"first blood",
			"flameblade",
			"flawless heist",
			"forsaken bloodletter",
			"gentleman thief",
			"ghost light",
			"gilded cipher",
			"golden touch",
			"grab bag",
			"grieved outburst",
			"growing pains",
			"heddwyn, the law",
			"heist headquarters",
			"her ascension",
			"hidden hollow",
			"impatient busker",
			"lantern tender",
			"legitimate establishment",
			"lost memories",
			"lost in smoke",
			"lucien, the grifter",
			"malign growth",
			"mei, the infiltrator",
			"mei's collector",
			"miscast",
			"moonlit charmer",
			"oracle of flames",
			"pilfered process",
			"poisoned wine",
			"questionable methods",
			"queue bouncer",
			"rehearse",
			"rei's awakening",
			"reprising bard",
			"restoration",
			"reversal medic",
			"rewriting loyalties",
			"ruined theater",
			"ruptured citadel",
			"ruptured expanse",
			"ruptured falls",
			"ruptured flats",
			"ruptured grotto",
			"ruptured grove",
			"ruptured meadow",
			"ruptured morass",
			"ruptured square",
			"ruptured trail",
			"ruststep centipede",
			"saia, the mastermind",
			"saia's price",
			"saia's protege",
			"scathing review",
			"scenery chewing",
			"scuripi blessing",
			"scuripi collector",
			"scuripi lookout",
			"seedy bar",
			"send away",
			"shoreline temptress",
			"skeleton keyring",
			"soliloquy",
			"soul gate",
			"squid pro quo",
			"stage dressing",
			"stage fright",
			"street stalker",
			"sword of redemption",
			"talent pool",
			"talent scout",
			"thunderous applause",
			"tower prowler",
			"treasury keyper",
			"tyrant's reckoning",
			"uncovered idol",
			"undercity diplomat",
			"unmoving usher",
			"unraveling",
			"unwilling accomplice",
			"vampiric hunger",
			"vivian, the detective",
			"voices overwhelming",
			"war's sorrow",
			"zegarra, the rival",
			"absorb the soul",
			"aetheric disarm",
			"bank job",
			"blind sharpshooter",
			"brazen blackguard",
			"catalina's turf",
			"clutch shot",
			"consign to oblivion",
			"corporate war",
			"custom armaments",
			"dawn of the final day",
			"dead man's ambush",
			"demolitionist deviser",
			"derail",
			"determined slayer",
			"deviser's cunning",
			"devour memories",
			"dominik's shack",
			"doom defied",
			"douse in flame",
			"evening report",
			"failing defenses",
			"flamearrow partisan",
			"forgotten doorway",
			"fortunate exorcist",
			"ganzorig's domain",
			"grifter's diversion",
			"guns akimbo",
			"hiroto's refuge",
			"hostile takeover",
			"impeccable aim",
			"imperial titan",
			"keep the peace",
			"laconic deputy",
			"last stop",
			"lie dreaming not dead",
			"lightning draw",
			"lumenbay jailer",
			"lurk at vision's edge",
			"mari, dawn resurgent",
			"mei liva, the exfiltrator",
			"mountain-western inventor",
			"neblus' legacy",
			"pained ascension",
			"raven-cursed dominik",
			"reckless research",
			"reclaim the world",
			"riga's workshop",
			"riko's academy",
			"rise from the harbor",
			"rising temper",
			"riv's safehouse",
			"saboteur's panic",
			"savvy saboteur",
			"scrapyard raiders",
			"secret-hoarder",
			"shadow of izumito",
			"shatter mortal conveyances",
			"shroud the world in doom",
			"spark new life",
			"sparkline harness",
			"specialist saboteur",
			"stay on guard",
			"steelclad investigator",
			"stormcannon testing",
			"strike down the usurpers",
			"suborn humanity's works",
			"takumi's headquarters",
			"tenne, thief of destiny",
			"tentacled grip",
			"the long road north",
			"throne of the west",
			"thuggish detective",
			"thunderwhirl dancer",
			"tracing leylines",
			"treacherous toss",
			"tsolmon, the huntress",
			"tsubasa's redoubt",
			"unorthodox methods",
			"watch from above",
			"wrassle",
			"xiong mao, the protector",
			"xiu's escape",
			"apt countermeasure",
			"ash-withered cloak",
			"atrophy",
			"barren boneyard",
			"bearer of old growth",
			"beetleback forager",
			"bewitching vapors",
			"blade of burning sand",
			"bloodboil harlequin",
			"brazen sacrilege",
			"brittle bequest",
			"buried by time",
			"calcified dunes",
			"chosen of bal",
			"colossal camouflage",
			"crested crustacean",
			"deathless siege",
			"decree of bias",
			"dilapidate",
			"dissipate",
			"djinni imprisonment",
			"dromedary packbeast",
			"due judgment",
			"dutiful camel",
			"el-mazar, wayward palace",
			"encrusted sahalia",
			"exemplar of disdain",
			"facsimile sculptor",
			"fierce contempt",
			"flourishing dunes",
			"follow the light",
			"furnace golem",
			"gateway statues",
			"gaunt abnormality",
			"gemplate golem",
			"globule of agony",
			"globule of turmoil",
			"globule of vigor",
			"granite plating",
			"hafiq the wise",
			"hajir soothsayer",
			"hand of dominion",
			"harsh erosion",
			"heat ray",
			"highland dunes",
			"hostile atmosphere",
			"igneous pulverizer",
			"immolated grave",
			"impish delights",
			"judicious djinni",
			"liege of luxury",
			"macabre ruins",
			"meat puppet",
			"meddling gargoyle",
			"menna al-mejjat",
			"morrow probe",
			"mortal pilgrimage",
			"mukhif the grim",
			"ninhasir's march",
			"obscuring sandstorm",
			"one with the wind",
			"outflank",
			"painted bluffs",
			"palace dancer",
			"patron of asham",
			"petal scatterer",
			"princely mettle",
			"raise a ruckus",
			"rapacious rattler",
			"ravaged monument",
			"ridge warden",
			"roving chaplains",
			"rubble scavenger",
			"rush of adrenaline",
			"ruthless vagrant",
			"sandstreamer",
			"sandswept bazaar",
			"saturated dunes",
			"scaleback steed",
			"scimitar techniques",
			"sensory gouger",
			"seraph of renewal",
			"seto san, summer blossom",
			"shawlbinder",
			"shrapnel golem",
			"sink into the floor",
			"skeletal oasis",
			"skin from bone",
			"slum scrounger",
			"soul chalice",
			"stabilize",
			"stasis snare",
			"sticky fingers",
			"strangulate",
			"strider harness",
			"strike down",
			"stygian dunes",
			"sultan's strength",
			"sunrazed ruins",
			"suraj militant",
			"tip the scales",
			"tomb of great drakes",
			"unfettered atrocity",
			"venerable judgment",
			"venom infusion",
			"verdant haven",
			"visceral assault",
			"volatile stonework",
			"warrior's discipline",
			"zoetic tomb",
			"amelie mayn",
			"ancient gift",
			"angelfire",
			"armadillo cloak",
			"aurora's whisper",
			"beckon the shadows",
			"binding stones",
			"blinded avenger",
			"breach the mind",
			"conjured shade",
			"diabolic designs",
			"divine in blood",
			"dryad of the grove",
			"dust barrens",
			"fade into mists",
			"ferocity of the redeemed",
			"golden glade",
			"granite watchers",
			"great sable stag",
			"heartless pact",
			"hexfang ascetic",
			"leija's greenblade",
			"ligos, shadow's source",
			"moonlit pursuit",
			"pyresong aspirant",
			"rain zai, spiritscale",
			"reaping mask",
			"rebellious streak",
			"reckless rage",
			"remembrance of light",
			"remnants of divinity",
			"rend",
			"resolution of stone",
			"rimebreath tyrant",
			"rite of the dark harvest",
			"rius, temple of the grandfather",
			"selene the cruel",
			"silent musing",
			"singers' grove",
			"sleeping dryads",
			"smoke's whispers",
			"snowline ascetic",
			"soulcarver",
			"spotless mind",
			"stag of the moon",
			"the aurora's heart",
			"the court of angels",
			"verdant cloak",
			"verse of fire",
			"warband lieutenant",
			"wastewolf",
			"young hieromancer",
			"acclaimed leadership",
			"aetherdrain",
			"ancestor's calling",
			"antonin lazaire",
			"arcane saxophone",
			"art studio",
			"artisan's sorrow",
			"aven acoustimancer",
			"banish",
			"belittle",
			"bewildering sight",
			"bite down",
			"blessed mausoleum",
			"bog rebirth",
			"bogborn exorcist",
			"bogsworn club",
			"bokor's recruitment",
			"book return",
			"brash hunter",
			"captivating jester",
			"cataclysmic preacher",
			"chilling musician",
			"coat in petals",
			"coordinated commotion",
			"creeping pianist",
			"crown of spores",
			"curse of bleeding",
			"curse of encroaching waters",
			"curse of haunting",
			"curse of impotence",
			"curse of tracking",
			"curse of uncertainty",
			"curse of vulnerability",
			"curse of waning wealth",
			"curse of the petrified",
			"damning flames",
			"dangerous territory",
			"disrupting storms",
			"eerie bayou",
			"elaborate transportation",
			"elegant strike",
			"exciting band",
			"explorer's fate",
			"faradia's outrage",
			"fervent strike",
			"fool's errand",
			"forlorn ruin",
			"glamorous aerialist",
			"grisly hunger",
			"helena, the awakener",
			"helena's exaltation",
			"hunter's mark",
			"improvising automaton",
			"inspiring band",
			"kantra of avarice",
			"kantra of old majik",
			"lakeside park",
			"lazaire's altar",
			"lost in admiration",
			"mark of the scaleblight",
			"marsh's veil",
			"marshcroaker drake",
			"murmurs of the bayou",
			"mushroom lagoon",
			"new alores charmer",
			"oracle's ploy",
			"overgrowth instigator",
			"overwhelming guilt",
			"parish's command",
			"portside smuggler",
			"prayer hall",
			"pretentious performer",
			"proselytize",
			"radiant outburst",
			"ranidaphobia",
			"reclaim the devout",
			"rejoicing aristocrats",
			"ritzy parlor",
			"riverboat assault",
			"riverguide harpist",
			"royal domain",
			"scuttling bogbuster",
			"shaman of the first pact",
			"shock and awe",
			"smite the monstrous",
			"solemn offering",
			"soul trapper",
			"soul of new alores",
			"splendid leap",
			"sporeflow mantle",
			"sporeflow protector",
			"sporeflow repulsion",
			"sporegraft",
			"storehouse collapse",
			"stratusform seraph",
			"streetside entertainer",
			"sudden conversion",
			"sunlit plaza",
			"tear to shreds",
			"tempted by lotuses",
			"trufflefrog",
			"vacated bar",
			"vindictive abbot",
			"vivid march",
			"wild instincts",
			"woopip bruiser",
			"zealous scaleblight",
			"zoulev rebuff",
			"act of repentance",
			"adiran distractor",
			"algrin's legacy",
			"almgrove ambassador",
			"anarchy storm",
			"appeal to the ancestors",
			"artist's vista",
			"champion of the red dawn",
			"charming marauder",
			"cognitive fumigator",
			"consuming symbiosis",
			"contemplate obscurity",
			"crystal wave",
			"culminating conspiracy",
			"culminating despair",
			"fallacy's channeler",
			"fallacy's sanctifier",
			"felice's defiance",
			"in tragedy",
			"mirrorplate exemplar",
			"once abandoned",
			"once betrayed",
			"once denied",
			"once scarred",
			"once shunned",
			"over the horizon",
			"recalculation",
			"refracted thoughts",
			"repent, daughter of fallacy",
			"spectrum archmage",
			"stark copse",
			"stark hinterlands",
			"stark horizon",
			"stark stream",
			"stark wildfire",
			"theurgist of the depths",
			"wicked blow",
			"abandoned monument",
			"across the threshold",
			"aether crosser",
			"aether gateway",
			"aether road caravan",
			"aethercrafting",
			"aethermancer's familiar",
			"ageless weaver",
			"akkrixian ambassador",
			"alethea, syzygy captain",
			"autumn canopy",
			"basalt ritualist",
			"beneath the zhedina",
			"benthic thaumaturge",
			"blossoming expanse",
			"brine fleet bay",
			"brinechum",
			"caldera crawlers",
			"chronosphere sovereign",
			"cloudshaper pilgrim",
			"cloudsteel summit",
			"contested discovery",
			"crater burst",
			"cryptic sentinel",
			"cursed wastes",
			"dimensional reshaper",
			"dreadfire tyrant",
			"dreamscape",
			"dustchoked outpost",
			"endless trove",
			"entropic harvest",
			"epoch warden",
			"eternal reactor",
			"exhilarating journey",
			"explorer's ascent",
			"far-realm guardian",
			"farwander guide",
			"fearless realmwalker",
			"fenhauler gang",
			"filch",
			"forgotten remains",
			"fractured reach",
			"gathering beacon",
			"ghostspore mire",
			"gilded gulch",
			"glacial shelf",
			"glimmer",
			"grove of embers",
			"guided by the weave",
			"gyreon pickpocket",
			"gyreon smuggling",
			"harrowing experience",
			"heart of zhedina",
			"honored spellthreader",
			"hot streak",
			"hunting experience",
			"idravir, the last city",
			"incense stoker",
			"interplanar raid",
			"isolated",
			"journey's end",
			"journeying giftbearer",
			"kilnfire",
			"krismite shard",
			"krismite vault",
			"lotus lake",
			"mausoleum suffragan",
			"molten falls",
			"monument of queens",
			"morphic verge",
			"nereba, sandchoked archives",
			"notorious smuggler",
			"offworld surveyors",
			"otherworldly forest",
			"otherworldly island",
			"otherworldly mountain",
			"otherworldly plains",
			"otherworldly swamp",
			"paracosm",
			"pathshaper mage",
			"phantom threader",
			"planar eulogist",
			"planeshift",
			"polyp pools",
			"portal fracture",
			"portal inhibitor",
			"possibility scope",
			"precursor sanctum",
			"prismatic champion",
			"prodigious telemancer",
			"promethean grotto",
			"pyroclastic maw",
			"quandary seer",
			"quickmire",
			"rainsculpted gorge",
			"razione racecourse",
			"razorshell marauder",
			"reborn from the ashes",
			"relentless pathcutter",
			"rift splicing",
			"rippling curtain",
			"roguish instincts",
			"rootbound awakener",
			"saddlesaur guide",
			"scion of desolation",
			"scion of torrents",
			"seeds of new life",
			"shadowcleft hideout",
			"shifting canyon",
			"shifting cascade",
			"shifting crag",
			"shifting grove",
			"shifting morass",
			"shifting spaces",
			"shuddering node",
			"silkweaver matron",
			"skylight fortress",
			"smuggler's den",
			"soaring rainforest",
			"soulblade",
			"sowing spring",
			"spellweaver aureate",
			"sphinx of supremacy",
			"spoils of the undermarket",
			"starlight beacon",
			"steamlit peaks",
			"stormtide sovereign",
			"survival experience",
			"syzygy navigator",
			"syzygy privateer",
			"tears of tizuma",
			"telarine runecarver",
			"temporal rift",
			"thievery",
			"timeless shrine",
			"tomb of shifting sands",
			"transnaturalist",
			"undermarket favors",
			"untethered spire",
			"vedlinn ross",
			"verdant renewal",
			"vivid mirage",
			"voidflare",
			"voliv edgelands",
			"wayfinding",
			"whisper in the rift",
			"woven network",
			"zephyr gliders",
			"zhedina confiscator",
			"zhedina exchange",
			"zhedina outskirts",
			"zhedina valiant",
			"zhelid, planar academy",
			"alia, bearer of morning",
			"ambitious necromancer",
			"artisan of brutality",
			"artistic vision",
			"atychiphobia",
			"backwoods cultivator",
			"beckon darkness",
			"bottled lightning",
			"brilliant academy",
			"brilliant archives",
			"brilliant capital",
			"brilliant castle",
			"brilliant citadel",
			"brilliant cityscape",
			"brilliant hub",
			"brilliant mansion",
			"brilliant port",
			"brilliant workshop",
			"city gate",
			"claimed by the veil",
			"dawnwisp vents",
			"deliver from dilapidation",
			"disable",
			"disqualify",
			"dovon, verdant experimenter",
			"embrace the veil",
			"extravagant flair",
			"facsimile of divinity",
			"final symphony",
			"flare blitz",
			"forgemaster's charm",
			"gearcraft observer",
			"gilded gearhulk",
			"glimpse the veil",
			"harmony array",
			"herald of wisdom",
			"hunt the monstrous",
			"iken troubleshooter",
			"inevitable future",
			"instant of brilliance",
			"jessica turin, battlemage",
			"kati evalin, world wanderer",
			"lightblessed claymore",
			"malicious growth",
			"mana confluence",
			"marin polgek, academy heiress",
			"matron of machines",
			"meteor harbinger",
			"mirrorcast battlemage",
			"monstrous hunter",
			"morning's warden",
			"nina, master of arms",
			"omegalomania",
			"open the secret paths",
			"perpetual motion machine",
			"petal-weaver alexa",
			"polgek restorationist",
			"polgek songcrafter",
			"purging light",
			"pyromantic expertise",
			"reclamation grovesculptor",
			"renewal grove",
			"resonating force",
			"riftway to the other side",
			"rilken forcefield keeper",
			"rilken preserver",
			"runecrested valley",
			"sealed riftway",
			"secret thief",
			"seek perfection",
			"sesilius, chosen speaker",
			"siraj, interplanar thief",
			"slay the unkillable",
			"speedreading",
			"surmise reality's limits",
			"sword of tides and time",
			"telvim sculptor",
			"terraformer's globe",
			"timeworn crags",
			"transplanted citadel",
			"twisted speaker",
			"unexplored regions",
			"veil's recovery",
			"veilborn meddler",
			"veilcrossed twins",
			"vitin forgemaster",
			"volta, construct consultant",
			"watch time slip away",
			"acid sewage",
			"ancestor's skull",
			"approach of old lovi",
			"bloodrune patron",
			"bravery's reward",
			"courier's misfortune",
			"cower in denial",
			"crossroads harrier",
			"determined to prevail",
			"dogged pioneer",
			"drained shore",
			"drought-plagued slum",
			"eerie armament",
			"false god's downfall",
			"favoured firebrand",
			"fertile flesh",
			"fluctuating locale",
			"forager's lore",
			"foreboding calm",
			"forsaken getaway",
			"grave of an old lord",
			"haunted fairground",
			"head of ulko",
			"heir to the old bonds",
			"hellwaste settlement",
			"hollow wanderer",
			"hone strategy",
			"hunger of old lovi",
			"imperious nixie",
			"imposing barricade",
			"ineffable patronage",
			"ivenge, false god",
			"kaur, end of lies",
			"keen reflexes",
			"kielie, risti strike leader",
			"leery sortie",
			"left on the wayside",
			"life remembers its roots",
			"lone hunter",
			"make or break",
			"medical mask",
			"memorial ground",
			"mennin jar",
			"mennin reclamation",
			"moved by instinct",
			"neo-alchemist's mastery",
			"neo-alchemist",
			"nixie's edict",
			"open the cryo-chambers",
			"privilege's sway",
			"pulsating mass",
			"reality reversal",
			"reason rots, rage remains",
			"reclamation project",
			"resign to madness",
			"risti citadel",
			"risti inquisitor",
			"risti operative",
			"risti strategist",
			"risti suppression",
			"scavenger holdout",
			"scavenger hunt",
			"secluded farmstead",
			"seductive seashell",
			"sepulchral seas",
			"singer of calamities",
			"sudden fatigue",
			"suspect concoctions",
			"swarm of the dispossessed",
			"the ark project",
			"the flesh becomes soil",
			"the mist thirsts for silence",
			"tip of the tongue",
			"trail off",
			"true shot",
			"underhanded employ",
			"warped landscape",
			"warped recluse",
			"wind-blessed guardian",
			"windmill project",
			"agonizing punishment",
			"aureate panorama",
			"banish the intruders",
			"brushcover elf",
			"descend on the helpless",
			"earthform pachyderm",
			"endless discoveries",
			"escape death",
			"eternal rage",
			"frostbreath dragon",
			"frostfire hulk",
			"frozen hinterlands",
			"hazy coppice",
			"hell's verdict",
			"icepeak phantasm",
			"inferno lash",
			"jaws of the sea",
			"jenn, the rising dawn",
			"lowland vista",
			"see the sunrise",
			"shatter the mask",
			"show of dominance",
			"solitary guardian",
			"spellshatter",
			"spires of caulte",
			"sunlit fissure",
			"surge of darkness",
			"testament to heroism",
			"the flames approach",
			"the whisperwoods",
			"towering boughs",
			"vali, planar researcher",
			"veiled by the blizzard",
			"verdict of the council",
			"whisperwoods reclaimer",
			"a grave sentence",
			"aether runes",
			"agrestal decay",
			"all-enduring mafua",
			"ancient dominion",
			"animorph",
			"arcane refusal",
			"artful chari",
			"aspirant of legend",
			"babyscale bruiser",
			"battle for msuji highlands",
			"beyond the boneyard",
			"blackmoat bully",
			"bleak dominion",
			"blind blackguard",
			"blisterbug",
			"bloodfell caves",
			"blossoming sands",
			"bogfume pact",
			"bone splinters",
			"brushfire",
			"calamity of yore",
			"canine acumen",
			"coastal dominion",
			"coldblood bender",
			"desert storm",
			"desolate dominion",
			"dismal backwater",
			"elegant agility",
			"eternal deliverance",
			"feline furor",
			"felling vines",
			"fractured illusion",
			"frontier savior",
			"fume whisperer",
			"gleaming river",
			"golden gust",
			"grace of timber",
			"greypelt emissary",
			"hembwe, the all-mother's hand",
			"herd matron",
			"hero slayer",
			"homestead",
			"indomitable rage",
			"infestation",
			"iron hide",
			"join the colony",
			"joyful deviant",
			"jungle hollow",
			"kafyabari patrol",
			"kambiro, the untrue king",
			"kiana, the unyielding",
			"lava spill",
			"lunar emissary",
			"lupine ferocity",
			"majestic dominion",
			"malnourish",
			"msuji sureshot",
			"murky peat",
			"murmuring typhoon",
			"mythos scribe",
			"nest matriarch",
			"netherform",
			"neural contagion",
			"nip at the heel",
			"olde king koswe",
			"on marvelous wings",
			"oozing adder",
			"pact of dark power",
			"paint over",
			"pangoling",
			"pestilent vermin",
			"petrify",
			"pith wilt",
			"plaxolotl pyari",
			"primal dominion",
			"primation",
			"pristine dominion",
			"provincial loyalty",
			"punja stick trap",
			"quill sniper",
			"rapacious instinct",
			"resting wildehound",
			"rip to shreds",
			"ruchi, the effervescent",
			"rugged dominion",
			"rugged ferocity",
			"rugged highlands",
			"rumble in the jungle",
			"sage of storms",
			"sandblast",
			"savannah huntsman",
			"scavenger's feast",
			"scoured barrens",
			"serenity of youth",
			"serum smoker",
			"shrieking gnoll",
			"siamang minstrel",
			"silthway scuttler",
			"sirif of the lord's legion",
			"spirit transfusion",
			"stalwart dominion",
			"sunwashed spires",
			"swiftwater cliffs",
			"t'nege, skyguard",
			"tanager typhoon",
			"the banishment of seh'a",
			"the harnessing of fire",
			"thornwood falls",
			"threshing sundew",
			"tranquil cove",
			"trials of ndengo",
			"tropical grove",
			"turf war",
			"twilight ambush",
			"twinklewings",
			"umala, the reverent",
			"unbracing rain",
			"vast savannah",
			"verdant dominion",
			"vibrant flames",
			"will of a fickle lord",
			"wind ward",
			"wind-scarred crag",
			"wisdom beyond age",
			"xiong mao, restless waif",
			"abandon life and hope",
			"abomination emissary",
			"adapted explorer",
			"advanced schematics",
			"alive and on top",
			"ancient artillery",
			"architect of the derezzed",
			"atrocity of flesh",
			"barren vista",
			"between life and death",
			"big enough",
			"biocrystal augmentation",
			"bloody business",
			"blooming vista",
			"bulletproof will",
			"burning up",
			"bury the past",
			"call of the abyss",
			"collapsing star viper",
			"come out and play",
			"comfortably numb",
			"convert to resources",
			"cosmic sinkhole",
			"counting stars",
			"covert reinforcement",
			"dead end adventurer",
			"dead on arrival",
			"destructive ambition",
			"embrace the abominable",
			"enter mephisto's gate",
			"exergetic chains",
			"extrastellar larceny",
			"far too young to die",
			"fiery erasure",
			"find happiness in misery",
			"first wave explorer",
			"galactic detonation",
			"glacial vista",
			"glitch, galactic muse",
			"greedy insects",
			"green daywalker",
			"ground bound",
			"growing up",
			"guardian of lost truths",
			"hall of random access memories",
			"hardened explorer",
			"head on collision",
			"hero's downfall",
			"hold me down",
			"hot to the touch",
			"human frailty",
			"i'll be gone",
			"ignition point",
			"in control",
			"jacque, crystal-touched",
			"killdrone assembly works",
			"let it burn",
			"living vista",
			"lost among the stars",
			"lost without you",
			"lt. daisy saxon",
			"malignant reaver",
			"marshy vista",
			"mentalist guardian",
			"nebula of empty gold",
			"nebula's majesty",
			"new divide",
			"no rest",
			"novaheart guardian",
			"on display",
			"one bad night",
			"out-of-body experience",
			"painwield explorer",
			"pernicious primavore",
			"persevere",
			"planetary reconnoiterer",
			"power drive",
			"precursor sentinel",
			"predatory psion",
			"prismatic cavern",
			"prismatic scyphozoa",
			"prosthetic repairs",
			"r-12 lone digger",
			"rage-fueled adventurer",
			"recurring abomination",
			"remember for centuries",
			"repurposed killdrone",
			"scarlet mist",
			"scavenging pack",
			"silencing guardian",
			"skyward ambition",
			"slyten crystal motherlode",
			"space oddity",
			"spaceship invader",
			"speck of dust",
			"speed of darkness",
			"starborne hellkite",
			"strange discovery",
			"stratospheric bombardment",
			"sudden decompression",
			"sword of monsters and men",
			"take a walk",
			"terrasculpt mantas",
			"the flenser of singularities",
			"the tomb of precursors",
			"thunder road",
			"uncover the truth",
			"v-4 fixit",
			"wandering megaflora",
			"whatever it takes",
			"whimsy",
			"wild dogs of the night",
			"winged guardian",
			"aether pull",
			"agonizing syphon",
			"ajani resolute",
			"akrasan sentry",
			"ambush gharial",
			"antali archdruid",
			"arcane sanctum",
			"aven strategist",
			"bant command",
			"behemoth channeler",
			"bigroot valley",
			"bleak shoreline",
			"blessed radiance",
			"blessed vanquisher",
			"brutal struggle",
			"calamitous rampage",
			"canopy assault",
			"caustic mangrove",
			"charred marsh",
			"citadel battlemage",
			"cloud's roar avenger",
			"cloudcover heights",
			"cloudheath sentinel",
			"cognition crucible",
			"conflux ravager",
			"crumbling necropolis",
			"disperse",
			"dissident's vortex",
			"dominator's diadem",
			"dregscape chant",
			"duneglass ascetic",
			"earthbreaker behemoth",
			"edarna the everforge",
			"entrail elemental",
			"eos beseecher",
			"erupting territory",
			"esper command",
			"essence erasure",
			"etherium leviathan",
			"ethersworn indoctrination",
			"exenterate",
			"fearful flooding",
			"flarespore mycoid",
			"fletcher's precision",
			"forbidding isle",
			"giltspire exemplar",
			"gleamhorn gargantuan",
			"gloomtide gulf",
			"grixis command",
			"hallucinate",
			"hazy summits",
			"heart of spores",
			"hellion devastator",
			"hellkite omnivore",
			"hellkite's decree",
			"hellspark prankster",
			"herald of the white orchid",
			"hierarch ranger",
			"hostile barbfly",
			"idyllic oasis",
			"incantation demon",
			"infernal flames",
			"influence of progenitus",
			"jenara's favor",
			"jund command",
			"jungle battlemage",
			"jungle shrine",
			"kaalia, sky's end",
			"kaalia's abomination",
			"kaleidoscape",
			"kess the necromaster",
			"leotau rider",
			"lichen's grasp",
			"lush coast",
			"maelstromancy",
			"mage's warding",
			"magma spray",
			"magmatic violator",
			"make way",
			"meren, bane of the cairns",
			"mortal finish",
			"nacatl skirmisher",
			"naya command",
			"necropolis battlemage",
			"nefarox, strifelord",
			"obscene recitation",
			"omen of nefarox",
			"ominous lightning",
			"ostracizer orb",
			"paladin's attendant",
			"peaceful passage",
			"pledge of peace",
			"radiant resolve",
			"rafiq the magnanimous",
			"ragemist",
			"ravenous tarwurm",
			"recraft in steel",
			"sanctum battlemage",
			"savage lands",
			"scatter what remains",
			"scrap spiral",
			"sculler's oar",
			"sculpted observatory",
			"seaside citadel",
			"sedraxis scourge",
			"sedraxis trepanator",
			"serul cove escort",
			"shining revival",
			"sigil of fortitude",
			"somber meadow",
			"sphinx's scrutiny",
			"spinebreak",
			"subduing serum",
			"sunstrike",
			"supreme mechanothurge",
			"telemin architect",
			"tendrilsnare",
			"terramorphic expanse",
			"tharrsus, tyrant's scion",
			"topan curemaster",
			"tremor seer",
			"twisting fissure",
			"unbeholden navigator",
			"unearth",
			"varakna wurm",
			"vectis entrancer",
			"velir the sunderer",
			"veteran horncaptain",
			"vibrant expulsion",
			"volcano elemental",
			"war-pride champion",
			"ziggurat behemoth",
			"act of treason",
			"anatomy",
			"ankulithic armaments",
			"ashen persecutor",
			"azutahn hydromancer",
			"behead",
			"blazing offerings",
			"bloodstained ziggurat",
			"burning sulfur",
			"center of culture",
			"choking dunes",
			"churning sandwurms",
			"collapse the pillars",
			"consult the scriptures",
			"cradle of civilization",
			"crescent of possibilities",
			"crushclaw pulverizer",
			"death pits trophy",
			"dehmi, origin seeker",
			"dehydrate",
			"delugic surger",
			"despoiler of civilization",
			"eli windsors, lone gun",
			"eli's grit",
			"embers of prophecy",
			"emissary of dark tides",
			"endak death pits",
			"endak savagery",
			"epic of anku",
			"epic of ekebram",
			"epic of hannaru",
			"epic of inishtu",
			"epic of jobiah",
			"epic of the lovers",
			"fall in line",
			"gilded blade",
			"gilded idol",
			"glimpse of fate",
			"godchosen valor",
			"halls of worship",
			"hannaru's courage",
			"heartland's protection",
			"hila emergence",
			"immortalize",
			"imperial claim",
			"into the lion's den",
			"irrigation channels",
			"kanaan wardriver",
			"keeper of codices",
			"legacy warmask",
			"lhosei of the ghost peak",
			"life's worth",
			"lisseria, general of kanaa",
			"long journey",
			"lush delta",
			"medicine",
			"metallurgy",
			"monstrous hila",
			"mustering grounds",
			"obviate",
			"oppress the weak",
			"paid in blood",
			"parted waters",
			"pierce the sky",
			"piercing blow",
			"pound by pound",
			"queen hannaru",
			"rod of marble row",
			"rupture spire",
			"sacrificial bull",
			"sandburst",
			"sannurian storyteller",
			"sarrutu flamebinder",
			"savage takedown",
			"scavenging hilakites",
			"scorpid sniper",
			"seeker amalgam",
			"selezzar, tyrant of endak",
			"serve the empire",
			"shala na, urshadi apostate",
			"shepherd's companion",
			"shock",
			"solemn judgment",
			"sorrowful memories",
			"spell pierce",
			"spirit of the harvest",
			"stolen innovations",
			"strongarm",
			"suffocating sands",
			"sure strike",
			"sustaining crops",
			"test of strength",
			"theocracy",
			"torrent of ankuliths",
			"trace the oasis",
			"trenchcutter beetle",
			"turn to salt",
			"voyager's ark",
			"wondrous bazaar",
			"aeroblast",
			"aggressive instinct",
			"attract",
			"barrier",
			"brutality",
			"call back",
			"caustic caterpillar",
			"chikyu league arena",
			"confusion",
			"depth charger",
			"dreamnapper",
			"driven mad",
			"duplicate",
			"ema, the traveler",
			"event horizon",
			"extremespeed",
			"familiar's ruse",
			"farewell",
			"fierce lunge",
			"flamethrower",
			"forgotten temple",
			"full belly",
			"gene pool",
			"ghastly tether",
			"grinding",
			"gruff clutch",
			"healing center",
			"helping hand",
			"hex maniac",
			"hidden sprout",
			"hyper beam",
			"hypnosis",
			"i choose you",
			"ice path",
			"jovial martyr",
			"karina's training",
			"lake of rage",
			"lakeside trickster",
			"lava plume",
			"leech seed",
			"lucien, the ravenous",
			"lucien's trail",
			"lunar vigil",
			"mighty beetle",
			"moonlight",
			"mountain runt",
			"muggy mire",
			"natural cure",
			"night shade",
			"nurse trainee",
			"ominous wind",
			"onigori, ema's shield",
			"overheat",
			"paralycker",
			"poison point",
			"power plant",
			"power of love",
			"practice range",
			"prepare for trouble",
			"psychic assault",
			"psywave",
			"quiet retreat",
			"rest",
			"rocket admin",
			"ruined lab",
			"ruined shrine",
			"run away",
			"safe from harm",
			"sanaito, alone",
			"sanaito's blessing",
			"sandslinger",
			"scary face",
			"seal of approval",
			"secret stash",
			"shadow ball",
			"shadow sneak",
			"sharp-eyed wingmate",
			"slashing sneak",
			"sludge drudger",
			"smokescreen",
			"sporecrowned scavenger",
			"spotted slugger",
			"sprout tender",
			"still waters",
			"stingsower",
			"sucker punch",
			"swords dance",
			"tangle up",
			"the rocket gang strikes!",
			"thundermane fox",
			"tidesweeper gharial",
			"time stands still",
			"treasure beach",
			"twinning psionic",
			"tyrant of tributes",
			"unburdened",
			"veil of flames",
			"victory road",
			"volt vermin",
			"waking pollution",
			"wandering hamlet",
			"whirling winds",
			"wicked fossil",
			"wild encounter",
			"wondering oaf",
			"work up",
			"zipping zapper",
			"adept fisherman",
			"adoroth, the baneful",
			"aerie watch",
			"all that glitters",
			"all for one",
			"alvarez of the huntsman",
			"autointerment",
			"blighted branch-beast",
			"bramble armor",
			"brig of the damned",
			"bushwhack",
			"calamitous wave",
			"cannonblast",
			"children of gos",
			"civil discourse",
			"claustrophobia",
			"cleansing cleric",
			"crazed swashbuckler",
			"cryptozoologist",
			"daybreak wayfarers",
			"deathless conscription",
			"down with the ship",
			"dragonlord's shrine",
			"dwarven war hatchet",
			"eager voyager",
			"elaborate firecannon",
			"empyrean griffin",
			"expunge the terrors",
			"fair trial",
			"fiery temper",
			"fight song",
			"flaming point technique",
			"fog at sea",
			"forged alliance",
			"forsaken shores",
			"gaze of the grave",
			"glisterhorn",
			"good night's sleep",
			"grasp of hollows",
			"grave wrangler",
			"grievous buccaneer",
			"grizzled cutthroat",
			"helmsman's chart",
			"inexorable epidemic",
			"infernal fury",
			"keelhaul",
			"keen seafarer",
			"kelp garden",
			"knotweald ambassador",
			"lava scutterer",
			"law enforcement",
			"light the fuse",
			"long forgotten",
			"lord ellison crain",
			"lost knowledge",
			"malignant rise",
			"marisa of the gravehowl",
			"mark of dark opulence",
			"maroon",
			"master negotiator",
			"mephitic fumes",
			"opaline drake",
			"osseous augur",
			"pale courier",
			"pathless shallows",
			"pay the right price",
			"pelagic hydra",
			"perennial unrest",
			"perilous treaty",
			"petty dispute",
			"pick up the pieces",
			"pilfer",
			"pirate's cutlass",
			"pirate's hideout",
			"plucky pickpocket",
			"plummet",
			"radiant elegance",
			"raving brigand",
			"revivification",
			"revoke privileges",
			"roll the dice",
			"rootshaper",
			"ruinous proselyte",
			"run through",
			"sail the open sea",
			"salvage wyvern",
			"searle of the tempest",
			"seasoned lookout",
			"seto san, the dragonblade",
			"shipwrecked",
			"shrouded spoils",
			"silent hunt",
			"sink",
			"skulduggery",
			"skysail rigger",
			"slaughterkeg",
			"sleepless vigil",
			"smoldering husk",
			"song of the sea",
			"strange tides",
			"stygian leviathan",
			"sudden storm",
			"swift corsair",
			"tabia of the lionheart",
			"tamiyo, lunar arcanist",
			"tankard of grog",
			"thalassophobia",
			"thicket mimicry",
			"three seas squire",
			"trawl the wreckage",
			"twilight privateer",
			"two-faced marauder",
			"up in arms",
			"visions of oblivion",
			"wakeborne kraken",
			"advent from above",
			"anemone cluster",
			"aquatic might",
			"bank skimmer",
			"blood in the water",
			"bloodthirsty jaws",
			"bonetooth darter",
			"bubbledome chorister",
			"cannoncoil hermit",
			"cast out",
			"chitinborn sentry",
			"conchspear hunter",
			"coral bruiser",
			"coral guidance",
			"coralcrown's banishment",
			"coralight castle",
			"coralight champion",
			"coralight choir",
			"coralight lifebloom",
			"coralight mystic",
			"coralight sentinel",
			"crush the hull",
			"crushing grip",
			"curious adventure",
			"cuxuri beckoner",
			"cuxuri's corruption",
			"danithra inquisitor",
			"danithra muckbruiser",
			"danithra oracle",
			"death sentence",
			"doom and gloom",
			"drag beneath",
			"drawn to the light",
			"dualglaive acolyte",
			"dukedom outcast",
			"emerge from the reeds",
			"encapsulate",
			"enchanting palace",
			"entrancing light",
			"face of the abyss",
			"final struggle",
			"finish off",
			"foregone ancestries",
			"glowskate channeler",
			"gobble up",
			"grim, dawson's vassal",
			"grim's warchest",
			"grisly ruins",
			"guppyfin duelist",
			"harmonic attunement",
			"harried submersible",
			"hila okunos",
			"horrors' reach",
			"idyllic odyssey",
			"into cuxuri trench",
			"into waiting jaws",
			"jetskate",
			"jumbo shrimp",
			"keep in line",
			"krill-clan guardian",
			"lilyreed triton",
			"lionfrill hunter",
			"lord rickard dawson",
			"lord of the bubbledome",
			"lost empire's legacy",
			"majestic hippocamp",
			"minefield bomber",
			"molten basin",
			"mysterious lights",
			"mystic mackerel",
			"noble birthright",
			"odelia's attendant",
			"oryxyth, doom of elmare",
			"ostentatious octopus",
			"paradise reef",
			"pay up",
			"pensive muse",
			"plasma blader",
			"rappel liner",
			"regal coralhorn",
			"restless predation",
			"riptide mystic",
			"ruin dive",
			"seafloor casket",
			"seafloor tomb",
			"shanty town",
			"shark slayer",
			"shine a light",
			"shoalshine",
			"smell blood",
			"snuff out the light",
			"speaker of open waters",
			"subnautical legionnaire",
			"tectonic chateau",
			"tentacle lash",
			"tide crasher",
			"turi of hollow depths",
			"typhoon caverns",
			"typhoon cruiser",
			"unsuspecting victim",
			"vibrant sandbar",
			"volcanic catastrophe",
			"volcanic hollow",
			"vyzer, the fallen despot",
			"wave spinner",
			"way of the danithra",
			"weight of oceans",
			"wilt",
			"alonzo, departed detective",
			"brutal blow",
			"bustling harbor",
			"camahueto calf",
			"channel the song",
			"ciel, the raider king",
			"dreary township",
			"end of all things",
			"eye of dismay",
			"forbidden burial",
			"forked pillar",
			"fulmen, aether prodigy",
			"ghislain, cryptbreaker",
			"glimpse in the static",
			"glittering grove",
			"griamoor, deathless warrior",
			"grin, scourge of goresand",
			"hop of life",
			"inescapable fate",
			"iroshi, blade of the old ways",
			"lay low",
			"monsoon lagoon",
			"night of the unliving",
			"pixie procurer",
			"powder scatterer",
			"ria-demian charm",
			"sear flesh",
			"solar flare",
			"urban wastelands",
			"vulture valleys",
			"warfaring epunamun",
			"waxing angel",
			"willow spirit",
			"xirix, the usurper",
			"zarad, the final adversary",
			"abrupt duplication",
			"ancient wurm",
			"awaken the source",
			"backstab",
			"bind the great evil",
			"blessing of immunity",
			"boiling tensions",
			"champion's steed",
			"coastal metropolis",
			"corrupted memory",
			"critical strike",
			"crowded tavern",
			"devour essence",
			"doom cultist",
			"eccentric gardener",
			"engulf in flames",
			"essence manipulator",
			"expel from the dungeon",
			"fast travel",
			"fertile steppe",
			"final form",
			"foretold cataclysm",
			"fragment mind",
			"freeze in place",
			"gambler's tournament",
			"gather the ingredients",
			"godmother ilthiss",
			"hero's henchman",
			"heroic return",
			"hunt the elusive titans",
			"hurl from existence",
			"improbable aim",
			"ingredient scroungers",
			"invoke the divine",
			"kleptomania",
			"lag spike",
			"load-bearing behemoth",
			"long shot",
			"lost progress",
			"loyal squire",
			"magma bolt",
			"malaise",
			"mending valkyrie",
			"might of the modrans",
			"momentous blow",
			"no way out",
			"overfull inventory",
			"pacifist run",
			"palette swap",
			"polymorphist's gift",
			"predictable pattern",
			"raid the cursed temple",
			"raid the infested woods",
			"ravenous grue",
			"relic corrosion",
			"rogue's passage",
			"romantic interlude",
			"save the village",
			"scale factor",
			"scour forgotten archives",
			"seek the maker's egg",
			"selvar's defiance",
			"shedding of the coils",
			"smash and grab",
			"smelting breath",
			"spawning barrens",
			"stampede shepherd",
			"student of winds",
			"sudden absence",
			"taran joy, cruel huntress",
			"thalassic borough",
			"thornweald cavalier",
			"time fissure",
			"town elder",
			"twitchy pyromancer",
			"unlikely recruitment",
			"unravel",
			"unsummon",
			"viscous webbing",
			"walk through walls",
			"warped glitchmage",
			"watchful ancestor",
			"waypoint stone",
			"wild peak",
			"xenocrata, reality breaker",
			"admonish",
			"aeren hellfire",
			"alratha, pearl of the sand sea",
			"alrathan outcast",
			"ancestral facsimile",
			"ancient tablet",
			"archaeologist's discovery",
			"bloodstained calamity",
			"calamity apparition",
			"calamity harbinger",
			"charging brute",
			"ciel's cavalry",
			"cold shoulder",
			"collapsing ridges",
			"confront the riddle master",
			"conto sika, ruined glory",
			"crest",
			"daring escape",
			"dark behemoth",
			"daunt",
			"death rites",
			"decisive arcanist",
			"descend upon the tomb",
			"desert marauder",
			"desert's hearth",
			"dismissive pyromancer",
			"drysand mole",
			"dthan's confluence",
			"dthan's daggers",
			"duel amongst dunes",
			"dunetreader tortoise",
			"ecological refuge",
			"elise, maktali prodigy",
			"enraged fangwurm",
			"enroll",
			"eve, the mastermind",
			"eve's spiritstalker",
			"exhaust",
			"ferocity of the sands",
			"fiery burst",
			"ghostly hounds",
			"harmonic charm",
			"harsh trek",
			"heatwave",
			"heavy sandstorm",
			"heinous acts",
			"herald of flame",
			"herald of shadow",
			"honorable mentor",
			"huntsman's guile",
			"imposing sphinx",
			"inescapable blaze",
			"leave for dead",
			"library infiltrator",
			"lofty denial",
			"lonesome traveler",
			"lost and alone",
			"mage's command",
			"masked lancer",
			"master of ancient ways",
			"mindwave rod",
			"naiala, the informant",
			"nature charm",
			"nimble sandstorm",
			"open the tomb",
			"outpost merchant",
			"palaisun, maktali's opus",
			"path of fire",
			"pillar of training",
			"plague calamity",
			"prowling beastmaster",
			"puzzlemaster's priest",
			"regrow anew",
			"relentless sphinx",
			"restore",
			"restored automaton",
			"riddlemaster's bane",
			"road to alratha",
			"roaming spirit",
			"roland, philosopher king",
			"roland's confluence",
			"ruinshell crab",
			"sand twister",
			"sandstorm charm",
			"sandwurm's command",
			"sandwurm's might",
			"search the archives",
			"searing sandwurm",
			"secrets of the orrery",
			"secrets of the tower",
			"seeker of ruins",
			"seeking horizons",
			"settle down",
			"sinister charm",
			"sink beneath the sands",
			"skelephant",
			"smashing brute",
			"spectral wings",
			"sphinx's advice",
			"sphinx's sight",
			"spirit of the sands",
			"spirits' descent",
			"spiritual charm",
			"splitting image",
			"spoiled oracle",
			"stormcalling",
			"swaying sands",
			"tara, duneblessed",
			"tara's confluence",
			"the sun rises",
			"tomb robber's grit",
			"tormenter of graves",
			"trail of bones",
			"traveling scholar",
			"tribal guard",
			"turn up",
			"unlikely growth",
			"unnerving assistant",
			"verdant oasis",
			"way of the warrior",
			"ylda, the wild soul",
			"ylda's confluence",
			"bile of the world",
			"crystal wave",
			"entelan deep storage",
			"fickle songstress",
			"master of minds",
			"mpumo, who stands alone",
			"penny and pete",
			"rain zai, spiritscale",
			"restore life",
			"spectrum archmage",
			"spike wall trap",
			"stormwing ultrateryx",
			"taken away",
			"bow or burn",
			"breach titan",
			"geetha, glass-shaper",
			"liliana at the brink",
			"plasma addict",
			"turn to gold",
			"xanigan, the darkened cloud",
			"call of the clocktower",
			"corecharge",
			"eternal blessings",
			"forbidden treasure",
			"mortal whims falter",
			"pitchpyre curse",
			"skypath pilgrimage",
			"suburban runebrawler",
			"weaver of mists",
			"wish to see",
]

		names
			.map{|n| db.cards[n]}
			.flat_map{|card| card ? card.printings : []}
			.to_set
	end

	def to_s
		"searle"
	end
end