class ConditionHugo < Condition
	def search(db)
		names = [
			"academy renegade",
			"afterlife heist",
			"against the waves",
			"apex's oath",
			"aquilifer axelius",
			"arpechian champion",
			"backwood rangers",
			"captain mattias ochre",
			"charting the cosmos",
			"crystal garden",
			"curse-blood morrigan",
			"daisy, the heart of chasmek",
			"daring skythief",
			"edge of the water",
			"elder's wisdom",
			"embrace madness",
			"finale of cinders",
			"glymna blackrune",
			"golden company tactics",
			"hunter's hideout",
			"jara champion",
			"just business",
			"legacy's malediction",
			"leyline alignment field",
			"lost to the ages",
			"magdel, caller of souls",
			"meadow songstress",
			"mirrorgate",
			"overloaded aethergate",
			"puppeteering",
			"right to rule",
			"spring renewal",
			"start anew",
			"the aether lens",
			"the start of something",
			"tidal spite",
			"titan's palace",
			"unceasing flames",
			"vengeful messenger",
			"villainy",
			"wandering souls",
			"xinan skycharter",
			"abhorrent exhumer",
			"barbarian hoarders",
			"barbaric dexterity",
			"beragnian savage",
			"bone saw",
			"cease conflict",
			"chillwhisper witch",
			"chronomancer's bauble",
			"chronowing phoenix",
			"clashborn stormling",
			"close escape",
			"collapsing ground",
			"curse of the drow",
			"danuri custodian",
			"deadland mongrel",
			"diligent protector",
			"duskwood vanguard",
			"duskwood wildcaller",
			"echoing knowledge",
			"expand your options",
			"fellor armorsmith",
			"feral cleaver",
			"fickleflame summon",
			"ficklewing elemental",
			"final revelation",
			"flamewaker's staff",
			"forest",
			"forgeborn barbarian",
			"formidable bulkvine",
			"furious betrayal",
			"groundswell",
			"hapless chronomancer",
			"haunter of the deadlands",
			"ill-fated profit",
			"imminent collision",
			"imposing bastion",
			"instinctual savagery",
			"irisglow dryad",
			"island",
			"landbound connoisseur",
			"lavacore elemental",
			"mawdryk's haven",
			"merkurio's rebuttal",
			"meteor volley",
			"mountain",
			"necrobite",
			"one with nature",
			"pandora's antagonism",
			"plains",
			"prepare for confrontation",
			"purifying light",
			"rallios' return",
			"rallying banner",
			"ready for the odyssey",
			"reality check",
			"ripping wilds",
			"risen looter",
			"roggar's gambit",
			"savrios' masterpiece",
			"scourge of the deadlands",
			"shrapnelcrafter",
			"sigil of destruction",
			"sigil of duty",
			"sigil of savagery",
			"sinful past",
			"soulstone servant",
			"soulstone shard",
			"steelborn apprentice",
			"strength of the phalanx",
			"stronghold recruit",
			"subturgian bloodhunter",
			"subturgian proliferator",
			"swamp",
			"swiftstep cliffdweller",
			"temporal resuscitation",
			"tharyen's sadism",
			"the high prairies",
			"threats from the outskirts",
			"tinkerer's tools",
			"treetop defense",
			"unstable footing",
			"vampiric appetite",
			"vaporizing blast",
			"vestige of evil",
			"voice of the wild",
			"wanderer's talisman",
			"waning behemoth",
			"warmonger contraption",
			"weaponize",
			"abandoned sanctuary",
			"achieve greatness",
			"admirer of the lost",
			"an and en, destined souls",
			"ancient crab",
			"anointed general",
			"assassin's shuriken",
			"bane of the folded fan",
			"barterer of passage",
			"bathophobia",
			"beckon from the depths",
			"blades of the many",
			"brass dragon",
			"brazen chimera",
			"brutal descent",
			"call to attention",
			"chords of order",
			"coax under",
			"collared kugsha",
			"come crashing down",
			"deep in thought",
			"demystifying tide",
			"deranged apothecary",
			"descend into insanity",
			"diseased prophet",
			"draconic bulwark",
			"dragon grip",
			"empowering chant",
			"engulfing incubus",
			"ethereal guidance",
			"fallen forest wolf",
			"ferocity of hao'tai",
			"fetid nibbler",
			"firebelly toad",
			"flame ascetic",
			"fleshwrithe ghoul",
			"foraging chipmunk",
			"form of the demon",
			"fox of the fallen forest",
			"frilled drakeling",
			"general of the folded fan",
			"guawu the untamed",
			"hostile hermit",
			"ing'wei of the flood realm",
			"inundated sanctuary",
			"jiayin, the harmonious",
			"kicking crane technique",
			"kiri, cloudwalker",
			"kugoja, perished conduit",
			"leafmantle dryad",
			"lei, yak herder",
			"lurking hippo",
			"maiden of the daffodils",
			"merciless xun huang",
			"mieng, who dances with dragons",
			"mother of owls",
			"mull over",
			"neutralize",
			"obscure apostle",
			"oshin, keeper of the shoal",
			"pan, honored sergeant",
			"pay respects",
			"peddler of commonwares",
			"pious flutist",
			"plodding moose",
			"pon, twister of forms",
			"put to rest",
			"read the bones",
			"recalibrate",
			"resurrection plea",
			"reverent flame",
			"roaring dracowyrm",
			"rummage through remains",
			"sacred sanctuary",
			"sanguine oracle",
			"savage sanctuary",
			"shock blast",
			"shredskin sky horror",
			"skeletal shredwing",
			"slicing legion",
			"spear of the folded fan",
			"spidery grasp",
			"spire sanctuary",
			"statuary forge",
			"temperate gazebo",
			"temple cranes",
			"test the winds",
			"the dragon's madness",
			"the mad sage's scroll",
			"tomb scavenger",
			"twin lis of the divine realm",
			"tzelin of the demon realm",
			"wander ashore",
			"warrior of the folded fan",
			"warrior's perspective",
			"way of kindred mind",
			"wicked rites",
			"wisdom of hao'tai",
			"wretched sanctuary",
			"young dragonheart",
			"zhehan, the mediator",
			"aghavaan's corrupter",
			"aghavaan's wound",
			"ancient ossuary",
			"asharo's yoroi",
			"bind in jade",
			"blade of the serpent",
			"celestial o-yoroi",
			"chalkira duelist",
			"clutch of the coil",
			"council's will",
			"cursed scroll",
			"discorporate",
			"dragon's ire",
			"dragon's wake",
			"dragonwall fragment",
			"dragonwall samurai",
			"elemental loremaster",
			"emperor kenshiro",
			"emperor's retainer",
			"empress kogane",
			"exemplar of honor",
			"fang of mautakesh",
			"festival of fading lights",
			"festival of roaring dragons",
			"festival of spring blossoms",
			"festival of winter's night",
			"final rest",
			"flow of the river",
			"hashiro's infiltrator",
			"heavenly temple",
			"imperial kensai",
			"imperial ricefields",
			"imperial strategist",
			"inner thoughts",
			"kenshiro's yoroi",
			"kiyomi's yoroi",
			"kogane's yoroi",
			"lady kiyomi",
			"masamori ranger",
			"masked stalker",
			"masterwork artisan",
			"mautakesh strangler",
			"miyoga dragonsoul",
			"miyoga firebird",
			"mokuteki ambusher",
			"pierce the storm",
			"protector of the gates",
			"sage's ashes",
			"sankataar ambushers",
			"sasori ronin",
			"scorch",
			"searing script",
			"seeker of mysteries",
			"servant of the white hand",
			"sheraku elite",
			"shigure's yoroi",
			"shinrin blademaster",
			"shinrin sage",
			"shinrin spellhunter",
			"shugenja sanctuary",
			"silk crane adept",
			"soaring dreams",
			"stonesculpting",
			"storm of shadows",
			"student of shigure",
			"sudden seism",
			"sunrise orchard",
			"taiyohata champion",
			"teikoku cavalry",
			"teikoku daimyo",
			"tranquil ascetic",
			"valor in battle",
			"violent repercussions",
			"voice of sheraku",
			"void sculptor",
			"wayfarer's shrine",
			"will of the emperor",
			"wizened calligrapher",
			"yamisaran guard",
			"adaptive terrains",
			"ankryss' staff",
			"aqueous treader",
			"armament upgrade",
			"armor of vines",
			"artificer's workshop",
			"battle fervor",
			"beastly dispute",
			"berserker's axe",
			"bonereader",
			"boundless evolution",
			"brainless ghoul",
			"brew of undeath",
			"cancel",
			"crafter's mistake",
			"derrivan beast tracker",
			"deserter's disdain",
			"disassemble",
			"divination",
			"divine presence",
			"earthchannel apprentice",
			"eradicating flames",
			"erudition of the lafterii",
			"evergrowing hydra",
			"faithful acolyte",
			"feed the horde",
			"fervent assault",
			"fierce instinct",
			"flooded morass",
			"flourishing crevasse",
			"gift of undeath",
			"goblin arsonist",
			"goblin roughrider",
			"heart of the glade",
			"heaven's champion",
			"hollowflesh ghoul",
			"infected flesh",
			"ingenious trickster",
			"inspiring personality",
			"insurgent racketeer",
			"knight's attendant",
			"kragnoss' arsenal",
			"kragnoss' battlecharger",
			"lafterii savant",
			"laia's intervention",
			"lavatorn fields",
			"lay to rest",
			"led by fury",
			"logayr's tome",
			"magus of the lantern",
			"magus of the sands",
			"mental dislocation",
			"mind's intruder",
			"mindblaze pyromancer",
			"moreena's banner",
			"natural growth",
			"newborn dragon",
			"pennon blade",
			"pillar of flame",
			"plan ahead",
			"planar alignment",
			"pool of light",
			"pyromancer apprentice",
			"rageborn phoenix",
			"reclamation sage",
			"repressed potential",
			"scholar's captivation",
			"sentient contraption",
			"shoot down",
			"skieryg menace",
			"sorcerer's staff",
			"soul pierce",
			"soul warden",
			"sprareos yearling",
			"spreading disease",
			"springjack pasture",
			"spur of the moment",
			"surprise strike",
			"syurrai traitor",
			"tainted remedy",
			"tortured psyche",
			"trained warhawk",
			"vampire nighthawk",
			"vampire's curse",
			"vinecreeper",
			"vorreia, farseer",
			"vythraktos, master necromancer",
			"vythraktos' dagger",
			"wall of hope",
			"war golem forge",
			"warden of the fronds",
			"wizard's insight",
			"amber hills",
			"arcane harvesters",
			"barbarian axe flinger",
			"barbarian intimidator",
			"barbarian rager",
			"boiling ridge",
			"brainless wanderers",
			"clairvoyant mage",
			"clever infiltrator",
			"coercive methods",
			"controlled decisions",
			"danuri eaglerider",
			"danuri warcaller",
			"deadly manipulation",
			"dictate of rallios",
			"disentomb",
			"distracted researcher",
			"duskwood thicket",
			"dusty record",
			"elspeth, protector of the meek",
			"elspeth's intervention",
			"elusive illusionist",
			"empty the tombs",
			"erudite aspirant",
			"erudite's tome",
			"exodus of the khalizors",
			"fearsome army",
			"fellor grunt",
			"fellor raider",
			"flame jolt",
			"flooded depths",
			"forestborn acolyte",
			"general's presence",
			"grave reaper",
			"grim bastion",
			"hazy moorland",
			"heartless warleader",
			"helm of the anointer",
			"herald of oblivion",
			"hindered research",
			"impulsive spirit",
			"intrepid shooter",
			"kill shot",
			"landmender",
			"last crusade",
			"lumi orthodox",
			"magmatic torrent",
			"menacing stance",
			"merkurio zellurys",
			"merkurio's prowess",
			"mirror image",
			"order's anointer",
			"peaceful intentions",
			"poisonblade trainee",
			"poisonous shot",
			"possibility grinder",
			"power of unity",
			"primitive berserker",
			"purger of blights",
			"quiet meditation",
			"reconstruct",
			"rehis-dorahn plowbeast",
			"resounding battlecry",
			"rugged fields",
			"saboteur's amulet",
			"scar shed",
			"sealed mausoleum",
			"search for inspiration",
			"searing pulse",
			"shifting frontiers",
			"sigil of brutality",
			"sigil of growth",
			"sigil of ingenuity",
			"sigil of malice",
			"sigil of unity",
			"strangle to death",
			"sudden changes",
			"sungrace meadows",
			"sunlit highland",
			"sureshot recruit",
			"the shield",
			"undying mobilizer",
			"unearthed legion",
			"unknown shores",
			"unstable experiment",
			"unstable impersonator",
			"verdant expanse",
			"warm blood chaser",
			"youthful recruiter",
			"admonish the unruly",
			"adverse reunion",
			"altar of adversity",
			"altar of chaos",
			"altar of creation",
			"altar of destruction",
			"altar of devotion",
			"altar of order",
			"angeltouched cavern",
			"angeltouched crag",
			"angeltouched garden",
			"angeltouched marsh",
			"angeltouched saltflat",
			"armorer of the soul",
			"augury hydra",
			"bahet's emissary",
			"bahum, penitent",
			"bahum's penance",
			"beastwaker of gusma",
			"beckon the scribes",
			"binding judgment",
			"born from the flock",
			"chaos tradewinder",
			"chiara the enchantress",
			"coercive cardinal",
			"combatant conflagration",
			"consult the ashes",
			"counsel of bahet",
			"crisis of body",
			"curator of cures",
			"dark night cleansing",
			"dauntless qith",
			"death in reverse",
			"descended delta",
			"descended marsh",
			"descended meadow",
			"descended mortuary",
			"descended towers",
			"descent of the cherubim",
			"devilish undoer",
			"dismantle the established",
			"dissolve",
			"duchess of life",
			"duke of death",
			"embrace the id",
			"end of the road",
			"enforce the cycle",
			"eternal path",
			"eternal recurrence",
			"evoke the maelstrom",
			"fanatic revival",
			"fatal edict",
			"fury swipes",
			"gusma's artisan",
			"gusma's emissary",
			"hand of genesis",
			"ifram, god of chaos",
			"ifram's cavalier",
			"ifram's emissary",
			"immortal terror",
			"in the face of divinity",
			"inspired trialmaker",
			"ishim of punishment",
			"ishim of tempest",
			"lesser virtue",
			"marzen, answer seeker",
			"marzen's sorrow",
			"masqued cleansers",
			"mindstorm's eye",
			"ni'ama, god of adversity",
			"ni'ama's emissary",
			"pierce the unruly",
			"proclamation of the tides",
			"qith maneuver",
			"release from death",
			"rework the canvas",
			"scrivener of sha'iv",
			"search for precedent",
			"searing blasphemy",
			"seraph's remnant",
			"sha'iv, god of order",
			"sha'iv's emissary",
			"sha'iv's scout",
			"shrine to the shrouded",
			"soul cajoler",
			"souls of the jury",
			"strength from chaos",
			"strength in imagining",
			"taker of tithes",
			"tammil and sulei, the guides",
			"temple stalker",
			"test of fear",
			"test of forsaking",
			"treacherous devil",
			"unorthodox tutelage",
			"unwavering questant",
			"war priest of bahet",
			"wayfaring swindler",
			"wellspring of creation",
			"whim of ifram",
			"wings of reckoning",
			"worldly lore",
			"accelerate fate",
			"aetherial ascent",
			"ahl's study",
			"airam, packleader",
			"aleud beastmaster",
			"aleud grace",
			"ancient gleam",
			"annihilate aggressor",
			"arroyo's servant",
			"augment authority",
			"bogclaw sniper",
			"bogclaw swarm",
			"chainslinger",
			"clipped seer",
			"contagious host",
			"contorted reflection",
			"crafted coast",
			"crystallizer",
			"deathlink",
			"dire dive",
			"dylso charmer",
			"earthen armor",
			"edge of the world",
			"exploring the mirrorworlds",
			"fallen fateweaver",
			"ferrofy",
			"flare extensions",
			"follower of fortune",
			"foreign affliction",
			"forgotten lessons",
			"frenzied fervor",
			"gleamhorn elk",
			"glow of grandeur",
			"halls of renown",
			"haploc blooddrinker",
			"haunted estate",
			"haunting haploc",
			"helm of the infinite",
			"hopeful healer",
			"ichor fling",
			"kalak culler",
			"lavamind elemental",
			"light knight",
			"lush outcrop",
			"lusterform",
			"lusterwing owl",
			"mark of majesty",
			"martyr's bounty",
			"memory martyr",
			"moonsight",
			"moonwing watcher",
			"ophorion refugee",
			"poisoned aleud",
			"proclaimed cure",
			"promised seeker",
			"promising visage",
			"prophetic blade",
			"reweave reality",
			"rooted hooter",
			"sacrificial pit",
			"scattering light",
			"searing insult",
			"seek prophecy",
			"sharpened claw",
			"show of supremacy",
			"singer of songs",
			"skulking claw",
			"sneak a peek",
			"solar flair",
			"spark inspiration",
			"spired canopy",
			"stalk the dylso",
			"steward of silence",
			"stolen strain",
			"tempt fate",
			"the blight beyond",
			"the sun's last setting",
			"vicar of victory",
			"vicious slasher",
			"wait",
			"weaver of lore",
			"wightlight",
			"wild haploc",
			"abandoned hermit",
			"adamant cultist",
			"alita dawnstrike",
			"avoid fate",
			"bird with the word",
			"blazing mirage",
			"blessed spellroot",
			"blind spellfeeder",
			"chain of decimation",
			"channel the mirror",
			"chantwood channeler",
			"clinging mire",
			"colpah charmer",
			"controlled burn",
			"cranial violation",
			"carving secrets",
			"crystallized moment",
			"devouring spellroot",
			"divert attention",
			"duela duelist",
			"duela marshall",
			"duela science kit",
			"dwarven fireslinger",
			"echoing determination",
			"echoing rites",
			"echoing silence",
			"echoing sunder",
			"echoing thunder",
			"endless reverie",
			"excavation engine",
			"fallen fanatic",
			"fatethief",
			"feed into aether",
			"fine craftsmanship",
			"flotsam",
			"forge trick",
			"forging blade",
			"fueled flame",
			"ghastly castle",
			"gleaming dream",
			"gleaming veldt",
			"gravantee",
			"grisly marsh",
			"intangible company",
			"lha maria",
			"market caster",
			"memory collector",
			"mental meltdown",
			"mightlight",
			"mindrip",
			"mirage adept",
			"mirage bracers",
			"mirror mirage",
			"mirrorform",
			"mirrorstorm",
			"obliterate flesh",
			"oslyd dreamer",
			"oslyd heretic",
			"poisoned pupil",
			"portent of doom",
			"power jam",
			"preparation",
			"purestrike rebel",
			"raving student",
			"relentless researcher",
			"ritesinger shaman",
			"safe",
			"scout the chantwoods",
			"spilling secrets",
			"splintering scuttler",
			"sunken cavern",
			"sunny dunes",
			"surging kalak",
			"sweep stakes",
			"the warrior within",
			"tunnel map",
			"twin trifles",
			"twisted echo",
			"twisted legacy",
			"unhallowed singers",
			"untouched wilds",
			"adept necromancer",
			"amosis charm",
			"avatar of basat",
			"basat charm",
			"blurring mists",
			"brute force",
			"crippling spirit",
			"dawn silhouette",
			"depraved disciple",
			"desert slaughterer",
			"desert temple",
			"desert warriors",
			"despise",
			"divine protection",
			"dune peregrination",
			"essence dehydration",
			"excellent architecture",
			"fire from above",
			"gates to the afterlife",
			"giant dromad",
			"haggard jackal",
			"haughty priest",
			"haze raptor",
			"high-priestess nebti",
			"lasis persecutor",
			"menhet charm",
			"mounted marksman",
			"mummification",
			"savannah scout",
			"scaled lurker",
			"sharp eyed sentinel",
			"spell dilution",
			"stream of light",
			"suntail hawk",
			"survive",
			"wachet charm",
			"wall of fog",
			"warrior's pride",
			"alenian boom squad",
			"alenian cruel-star",
			"alenian warcaller",
			"alenian warhammer",
			"annihilate the enemy",
			"artificer's gift",
			"awaken to the skies",
			"blood bairn",
			"circus firebreather",
			"counteredge blade",
			"deathfeeder",
			"deathwind expanse",
			"deathwind survivor",
			"defiant bristles",
			"deform sanity",
			"devastating impact",
			"drakon nightshade",
			"duel of intellect",
			"earthfeeder worm",
			"elemental envelopment",
			"elementalist's blade",
			"enhance armor",
			"entali aeromancer",
			"entelan erasure",
			"firefish assault",
			"flamewhip",
			"forestheart elemental",
			"forgemaster's altar",
			"fulmen, eldritch channeler",
			"goblin exploration team",
			"goblin rocktosser",
			"gryla canyon",
			"icilica's icestrider",
			"infested goblin",
			"infinite suspension",
			"interan resistance",
			"kor skyknight",
			"lerithan rebel",
			"lightbringer's touch",
			"lightsteel enforcer",
			"lighttoxin arcrunner",
			"master chef",
			"mental thievery",
			"miroran skycatcher",
			"miroran waterbinder",
			"moonshadow abyss",
			"notion retrieval",
			"opt",
			"phiresan lifemage",
			"phyrexian snapjaw",
			"playful surveyor",
			"priest's altar",
			"pyre trap",
			"relitian sentry",
			"reliya's construct",
			"revela, entelan darkcaster",
			"roilmaster",
			"rose defender",
			"savings broker",
			"sea gate crawler",
			"shadowfeeder",
			"shaidostan cryoforger",
			"skycaster's aura",
			"stormcaster's tower",
			"supreme judge",
			"syncopate",
			"sythian interference",
			"sythian scripture",
			"tether of simplicity",
			"touch of corruption",
			"trace the leylines",
			"trapcatcher's form",
			"trauma surgeon",
			"triline hunter",
			"veteran lifeforger",
			"warden of the moonshadow",
			"zephyrglider",
			"anima interrogator",
			"aquatic refuge",
			"arbalest barrage",
			"ascendant's murmur",
			"barreling chariot",
			"blazing beam",
			"canopy ratstalker",
			"canyon agamid",
			"child of the pack",
			"citadel of denial",
			"commander of the folded fan",
			"conduit of rage",
			"crane's way",
			"cunning cephalomancer",
			"dark rite cultist",
			"dazzling display",
			"deathcoil cobra",
			"deep temptation",
			"depraved imp",
			"dessication ritual",
			"divine dispersion",
			"doombringer dragon",
			"draconic aspirant",
			"enduring rockshell",
			"essence rehabilitator",
			"fall from glory",
			"fennec fostress",
			"fierce howl",
			"golden grizzly",
			"harmonious meditation",
			"harness the wild",
			"hasty assault",
			"haunting illusion",
			"hayuan, the misjudged",
			"heated dispute",
			"hypnotic halo",
			"inciting blade",
			"ing'wei's crystal top",
			"lightning ox",
			"majestic monitor",
			"malefic portal",
			"melodious musician",
			"morose harpist",
			"no-man's land",
			"noble fall",
			"ocean spray",
			"pietistic performance",
			"plagued skull",
			"prairie monastery",
			"scorched copse",
			"sea wall",
			"shimmering veil",
			"siphoning slash",
			"spined tarantula",
			"stand tall",
			"sunless ridge",
			"sustaining meditation",
			"swift savior",
			"temple of brilliance",
			"the way of the fan",
			"toxic spring",
			"vial of ice",
			"vigorous dryad",
			"wadepool frog",
			"wanderer of the wilds",
			"warpath ghoul",
			"whitepeak lookout",
			"wind drake",
			"worshipper whelp",
			"xiong's gambit",
			"xira, scatterer of seeds",
			"akrianos' command",
			"ammbradu parasite",
			"ardor of the masses",
			"auramancer",
			"aven ranger",
			"battlemage's disruption",
			"birthing elemental",
			"blessing of plenty",
			"blood-tithe harpy",
			"bloodblade mercenary",
			"bloodfury warlord",
			"bomb juggler",
			"branding shackles",
			"coalition relic",
			"contempt for the unnatural",
			"delirious fervor",
			"deranged arsonist",
			"drownyard scavenger",
			"earthenlore blessing",
			"enduring vestige",
			"ethereal armor",
			"evasive maneuver",
			"fallen ideal",
			"fatresya, protector of the people",
			"fearless recruit",
			"flesh hoarder ghoul",
			"frontline commander",
			"frostfire geysers",
			"fungal mire",
			"glitched carcass",
			"gloomcover steppe",
			"goblin sniper",
			"grafted physician",
			"harmonical weaver",
			"infiltrate althestra",
			"infiltrate celestia",
			"infiltrate demmurya",
			"infiltrate nimunot",
			"infiltrate rammaneth",
			"kellythross' workshop",
			"kevthra's will",
			"knight's daring",
			"korrinary warcaller",
			"lush oasis",
			"mark of mutiny",
			"merkurio's opus",
			"mobilize the heavenly",
			"moment of madness",
			"mossvine lurker",
			"mountain victor",
			"muster for battle",
			"naturebound druid",
			"novice pyromancer",
			"phyrexian scraphandler",
			"pinpoint accuracy",
			"poignant hydra",
			"poisonheart undead",
			"psychic grid",
			"ragantiar's hoarding",
			"ralezza, weaver of okthuros",
			"ralezza's disciple",
			"rammanethi sandshaper",
			"reengineer",
			"reorganized thoughts",
			"replicator mage",
			"runic soulthief",
			"scorchland vandal",
			"scrapgear contraption",
			"seismic strike",
			"sense of loss",
			"seven deadly sins",
			"shrine of the six pillars",
			"smoldering blade",
			"soulsorrow shade",
			"spiraling canyon",
			"sporesowed disease",
			"steelhoof battlechief",
			"stunning jolt",
			"symbiotic sprout",
			"tidemaster's loyalist",
			"tidetwister mage",
			"timely reinforcements",
			"total recall",
			"vaultkeeper",
			"vedalken machinist",
			"vedalken wingcrafter",
			"vigorous tracker",
			"voice of revolution",
			"walking platform",
			"watchful skyguardian",
			"absence of the unmaker",
			"ambition's crown",
			"amongst the flames",
			"ancestral zweihander",
			"arrogant fencer",
			"arrogant training",
			"attended knight",
			"beneath the lilies",
			"bloodied twinblade",
			"bustling docks",
			"captain of the exiled",
			"captain of the militia",
			"catch unawares",
			"cauldish banneret",
			"cauldish cavalier",
			"choked estuary",
			"cloak of the exiled",
			"commoners' favored",
			"confident cavalier",
			"coven adherent",
			"coward's compulsion",
			"crossroad bard",
			"curiosity",
			"daelish messenger",
			"declan, wayward squire",
			"decorated duelist",
			"deflecting strike",
			"derelict amphitheatre",
			"distracting handmaiden",
			"drunken night",
			"duress",
			"earnest labourer",
			"escort recruiter",
			"exiled warband",
			"ferris, the sapphire storm",
			"forbidden knowledge",
			"foreboding ruins",
			"fortified village",
			"game trail",
			"gild-cloak strider",
			"hedge knight",
			"highborn meditant",
			"hound of glory",
			"interlocked waterways",
			"isolated cloister",
			"knight of the hawk",
			"knight of the raven",
			"knight of the staff",
			"knight of the stag",
			"knight of the verdigris",
			"left for carrion",
			"lone heroics",
			"lord jared, the griffin knight",
			"measured contemplation",
			"melting point",
			"moment of glory",
			"moment of tranquility",
			"old grudges",
			"painful reminiscence",
			"peace of the glade",
			"perish in harmony",
			"plated valiant",
			"port town",
			"price of power",
			"publicly disgraced",
			"pursued paranoia",
			"rally the volunteers",
			"ranger's guile",
			"red pelt hart",
			"reflect upon the past",
			"requiem of the fallen",
			"reverence seeker",
			"sage's foresight",
			"satisfied gleaner",
			"scraps of memory",
			"seal the tomb",
			"seek glory",
			"ser joffrey, plague of nines",
			"shadowed slums",
			"shrouded cackler",
			"slayer of the famed",
			"splitshaft deadeye",
			"spur to action",
			"sunken ambitions",
			"sunpiercing bow",
			"surge of duty",
			"tactical deployment",
			"take for ransom",
			"talks in hidden hollows",
			"thailen, heir to daeland",
			"thailen's guard",
			"thief's harness",
			"till the fields",
			"tranquil endeavors",
			"trapped in the tower",
			"trusted comrade",
			"trystasp coating",
			"twilight raid",
			"under cover of dark",
			"untested commander",
			"visserine's royal guard",
			"voyaging devout",
			"waifish squire",
			"wayfaring ordealist",
			"weald sentry",
			"weary steward",
			"weaver of tales",
			"whiterun gates",
			"whiterun harbor",
			"withering agony",
			"youthful dreams",
			"youthful savior",
			"abandoned battlefield",
			"abandoned cairn",
			"abandoned meadow",
			"abandoned skyroad",
			"abandoned wilderness",
			"academy wastes",
			"alpine meadow",
			"barren desolation",
			"calmed battleground",
			"charbroiled core",
			"chiseled cliffside",
			"cleared vault",
			"cliffside entrance",
			"command tower",
			"dawnlit battlefield",
			"deadwood grove",
			"deeplife cavern",
			"deserted steppe",
			"deserted trail",
			"desolate barrens",
			"exotic xenoreef",
			"fiery chasm",
			"flourishing waterways",
			"forgotten cryovault",
			"forgotten shrine",
			"frigid highlands",
			"frontier base",
			"gleaming hot springs",
			"gnarled henge",
			"grim slums",
			"grove of reversal",
			"haughty chateau",
			"haunted woodlock",
			"highland vale",
			"horizon of origins",
			"imperial barracks",
			"jagged crag",
			"legacy foundations",
			"lush outskirts",
			"mossy shrine",
			"mysterious cataract",
			"ocean monastery",
			"ominous lair",
			"ornamented evergreen",
			"overgrown refuge",
			"quintok station",
			"rainforest spring",
			"roaring cascade",
			"secluded cascade",
			"shardstone rift",
			"shrouded rooftops",
			"sigil of creation",
			"sigil of martyrdom",
			"sky-high spires",
			"sodden cavern",
			"somber marsh",
			"spires of telenia",
			"stormcharged pyre",
			"strange harbor",
			"sunlit ruins",
			"timber range",
			"tirenan market",
			"torrid geysers",
			"toxic jungle",
			"tranquil stream",
			"unlit alley",
			"wastes",
			"weathered fortress",
			"wildrune thicket",
			"abandoned forge",
			"abandoned hideout",
			"abandoned laboratory",
			"abandoned preserve",
			"abandoned shores",
			"agent of vitu-ghazi",
			"anguished unmaking",
			"border guardian",
			"choking despair",
			"chronic traitor",
			"courier eagle",
			"creeping terror",
			"dancing flames",
			"deformed vagrant",
			"distant thunder",
			"doctored trail",
			"emberling",
			"embrace samang",
			"fertile soil",
			"fleeting memory",
			"gnuge-district hoarder",
			"grete-district hermit",
			"guardian's resolve",
			"highspire informant",
			"hold fast",
			"horizon gazer",
			"leyline tracer",
			"looking glass",
			"loresprout",
			"lost in fugue",
			"miede-district alchemist",
			"moonshadow remnant",
			"patient ascetic",
			"reclusive mermaid",
			"solar wisp",
			"stalked healer",
			"stay determined",
			"strive for the heavens",
			"thomar, fearbringer",
			"vitality unbridled",
			"wheat from chaff",
			"absolve",
			"anzen, beyond the sea",
			"aokara devoted",
			"aokara duelists",
			"asahi yoroi",
			"awoken nightmares",
			"betrayal of steel",
			"blade of mautakesh",
			"bladed warfan",
			"chikami castle",
			"chochin the silent moth",
			"dragonwall gates",
			"envenomed shuriken",
			"eternal inheritance",
			"faceless animist",
			"favor of the emperor",
			"finishing touches",
			"fires of seishin",
			"fleeting thoughts",
			"forbidden brew",
			"fortune charm",
			"gifts of the oshiruko",
			"haruna, master architect",
			"hashiro's vanguard",
			"heirloom",
			"hinasa historian",
			"hinasa lorebinder",
			"house of forgotten whispers",
			"imperial artisan",
			"imperial mox",
			"imperial port",
			"imposition",
			"inner peace",
			"inner purity",
			"inoshi the wild boar",
			"inscribed histories",
			"jaakuna betrayer",
			"jaakuna bloodsworn",
			"kameno yoroi",
			"kamu-tribe outfitter",
			"kamu-tribe rager",
			"kamu-tribe runt",
			"kamu-tribe warlord",
			"kareki heretic",
			"kemono-no-oni",
			"kizoku valiant",
			"kogane the crimson consort",
			"konoe's lieutenant",
			"kurayami butcher",
			"kurayami shrine",
			"kuryu swordsman",
			"legacy's end",
			"lesson in discipline",
			"light within shadow",
			"little kibo",
			"lord rokai",
			"mana ascetic",
			"master of balance",
			"memorial of the fallen",
			"midnight keep",
			"moranai paragon",
			"mua, seishin ascendant",
			"mystic arts",
			"nidohagane warfans",
			"one with the world",
			"oshiruko purifier",
			"path of the waters",
			"perilous passage",
			"prayer of drifting lights",
			"rokai's vassal",
			"ronin of broken vows",
			"saishuteki castle",
			"saki of the sea and sky",
			"sasori nightrunner",
			"seishin dojo",
			"seishin rageshaper",
			"seishin smokeshaper",
			"seishin tidekeeper",
			"seishin's edge",
			"sekitsui yoroi",
			"serene form",
			"shadow lantern",
			"shadowstrider",
			"shaping dragonsteel",
			"shikai revenant",
			"shikai's redoubt",
			"shionoshio, ocean's vow",
			"shugenja's journal",
			"silent wanderer",
			"snake tattoo",
			"soulstone",
			"spirit reflections",
			"stormshaper adept",
			"strident retainer",
			"student of the coil",
			"sunset monastery",
			"sword of silver and gold",
			"tales of old jidai",
			"teikoku songcrafter",
			"temple of falling leaves",
			"the last sacred gate",
			"tower of long shadows",
			"tsang jin, master of the jade sea",
			"unearthly grace",
			"unhallow",
			"unzari ruins",
			"whisper of the winds",
			"white petal ronin",
			"yamisaran bladedancer",
			"yuso, light of jidai",
			"adaptive servitor",
			"adept of waves",
			"aegis champion",
			"aeon's hand cutthroat",
			"aiel tazan",
			"aiel's fury",
			"ancient statue",
			"anurafication",
			"arden, mirrormage",
			"assassinate",
			"backup forces",
			"blade of the many",
			"bladesinger",
			"blood fiend",
			"bloodrage gladiator",
			"bloodstone halls",
			"carved dagger",
			"caustic lurker",
			"commune with nature",
			"concenter",
			"consort of blood",
			"corrupted strength",
			"crude tablet",
			"crumbling vestige",
			"dark bargain",
			"dauntless piker",
			"divine ascension",
			"edge of madness",
			"elegant fireslinger",
			"ember salvo",
			"ensnaring vines",
			"exclude",
			"fates foretold",
			"ferverent sergeant",
			"focus thoughts",
			"goblin squire",
			"harm's way",
			"harrier's falcon",
			"harvest moon",
			"heavens above",
			"hill of souls",
			"illusionary steed",
			"in arms",
			"mana prism",
			"mavisa's familar",
			"mighty swing",
			"mindwinder",
			"mistwake hydra",
			"monstrous guise",
			"moonlit shore",
			"morbid plunder",
			"move unseen",
			"nimbus fae",
			"northwind master",
			"ophelia's neophyte",
			"oracle crab",
			"paladin's blade",
			"prey upon",
			"prophetic flame",
			"pummel",
			"rejuvenation",
			"revenant shade",
			"runic wall",
			"sanctum",
			"shieldmaster's blessing",
			"shredding gale",
			"skeleton shield",
			"sleight of hand",
			"soul flame",
			"spirit drain",
			"steeled resolve",
			"stillness",
			"stoneskin",
			"swordmaster's blessing",
			"thought grifter",
			"valley falls",
			"valley mists",
			"vampiric thirst",
			"verdant sanctum",
			"verendas spiritwalker",
			"voracious ghoul",
			"wailing soul",
			"whispernight assassin",
			"whitetail sparrow",
			"wild ravine",
			"wildwood keeper",
			"zephyr rider",
			"acolyte of night",
			"aerolius",
			"aether tradewinds",
			"ancestral revision",
			"blight seed",
			"blood ritual",
			"blood tide",
			"bloodriver",
			"blossoming defense",
			"breeze sylph",
			"brush off",
			"charging nymph",
			"charming nereid",
			"child's play",
			"cloudbank",
			"cloudchaser kestrel",
			"cloudstep capuchin",
			"coralkeeper",
			"corpsebed",
			"corrupted warlord",
			"cradle of corruption",
			"crash down",
			"dawnsong",
			"daybreak",
			"dazzle",
			"deadeye drowner",
			"deathmask dancer",
			"deathmask initiation",
			"deceitful soul",
			"devious naiad",
			"devoted dancer",
			"dodgy infant",
			"drown",
			"drowned rusalka",
			"drowned weaver",
			"eldritch undoing",
			"elrayin, the manaroot",
			"elusive monkey",
			"eye of a moment",
			"feathered warden",
			"feeding time",
			"forsaken sunseeker",
			"giant growth",
			"gifted grace",
			"glimpse of beyond",
			"glimpse the sun",
			"gorran totem",
			"gorru recluse",
			"gorru tracker",
			"gorru wolftender",
			"haunted sunseeker",
			"heat of day",
			"honorwing",
			"idyllic tutor",
			"lapidify",
			"lightseeker nymph",
			"lightwrencher",
			"lotus acolyte",
			"lunar boon",
			"monkey trinket",
			"monkeyshines",
			"moonlace",
			"mosecf, the sunseeker's path",
			"mother's disciples",
			"nightshade slayer",
			"nymph's greed",
			"oppressive rays",
			"overgrown siren",
			"painted watcher",
			"path to mortality",
			"pelt mystic",
			"petaldiver",
			"planar eviction",
			"pond tenders",
			"predator's hunger",
			"pride of thorns",
			"primal resurgence",
			"primeval expansion",
			"pureheart naiad",
			"ralora, unforgiving depths",
			"raloran adept",
			"redeemed daughter",
			"reinvigorate",
			"schoolstrider",
			"sea of skies beyond",
			"seafoam charmer",
			"seedshrine",
			"seeker sword",
			"sever",
			"shield warden",
			"slippery capuchin",
			"spiteful growth",
			"starglare",
			"stinging hunter",
			"striptide",
			"sun's own",
			"suncatcher",
			"sunken outcast",
			"sunlight dancer",
			"sunlit diver",
			"sunstage",
			"sunwing",
			"swirling sylph",
			"sylph spawning",
			"sylvan explorer",
			"synapstorm",
			"tempest core",
			"thicketkeeper",
			"thorn, keeper of the wilds",
			"thunder wave",
			"united fervor",
			"whispers of the dark",
			"windcaller capuchin",
			"all who wander",
			"arcor-staff adherent",
			"arctic mine",
			"assassin's warning",
			"awash in despair",
			"balanced blade",
			"battered steel",
			"bearer of the lantern",
			"belligerent's augur",
			"blade of the long night",
			"boneweary warrior",
			"chained wildborn",
			"chapel defendant",
			"comfort the fallen",
			"compelling pariah",
			"conspiracy of ravens",
			"crumbling precipice",
			"crystal cavern",
			"crystal puncture",
			"cult of trinity's fall",
			"dashing rogue",
			"daunting skyline",
			"debt dignitary",
			"decrepit crags",
			"delusional noble",
			"dockyard stalker",
			"dwindling peace",
			"dwindling stores",
			"elixir of immortality",
			"exquisite heist",
			"failing port",
			"fearful observer",
			"feverish noble",
			"figures in the mist",
			"flintlock pioneer",
			"flush with arcor",
			"forgotten consequences",
			"forgotten sins",
			"forgotten steppe",
			"fretport anarchists",
			"fretport gravetender",
			"fretport mob",
			"fretport warden",
			"fretport's fade",
			"fretport's heedless",
			"fretport's lament",
			"gabryel's devout",
			"grim courtyard",
			"haphazard militia",
			"hateful gaze",
			"hazy lagoon",
			"hide from horrors",
			"hired blades",
			"inciting bard",
			"inkwell daggers",
			"invalidate",
			"judge's decree",
			"kalemn weller",
			"kasienka, raven's regarded",
			"martyr's sacrifice",
			"merchant's district",
			"morning passages",
			"morose bohemian",
			"murmuring falls",
			"nomad's township",
			"phosphorescent ravine",
			"plague mask",
			"postulate",
			"prayers of defiance",
			"prayers of judgement",
			"precarious ledgers",
			"purge the harbor",
			"rallying horn",
			"rampant summit",
			"raven's standard",
			"resplendent substratum",
			"rickety guildhall",
			"riot queller",
			"rising riots",
			"ruined citadel",
			"sedate tundra",
			"serene prayer",
			"serene trail",
			"shifting glade",
			"silence dissent",
			"steadfast heart",
			"sycophantic aristocrat",
			"thespian's finale",
			"unjust sentence",
			"unquenched greed",
			"untested recruit",
			"untouched duelist",
			"valeriya, watchkeeper veteran",
			"valor of the desperate",
			"vibrant rainforest",
			"watchkeeper deserter",
			"watchkeeper's retort",
			"wayward afflicted",
			"weary watchkeeper",
			"weathered veteran",
			"whiplash",
			"whisper collector",
			"wisdom in reflection",
			"withering beggar",
			"zealous bloodletter",
			"aetherite shackles",
			"arcane heist",
			"arrest",
			"azun, sheriff of daisite",
			"azun's play",
			"bearidge charmer",
			"bloodleaf tracker",
			"bloodshot berserker",
			"brazen drifter",
			"burning-tree shaman",
			"campfire stories",
			"canopy ambush",
			"cardsharp",
			"crossfire",
			"daisite express",
			"dead man's hand",
			"deputy gibem",
			"derelict town",
			"disallow",
			"dispel",
			"dusk rider",
			"eternal scout",
			"expedition leader",
			"exposed ghoul",
			"fireheart centaur",
			"fog",
			"fool's gold",
			"forgotten haunt",
			"foulweather effigy",
			"frontier meditation",
			"frontier outrider",
			"frontier scouts",
			"gambler's dice",
			"ghostly flicker",
			"ghostway",
			"gift of shadows",
			"gifts of ancient ulek",
			"graygulch drifter",
			"graygulch howler",
			"graygulch lurker",
			"graygulch revenant",
			"hard knocks",
			"haunting bard",
			"haunting horseman",
			"heavy moneybag",
			"high noon",
			"high spirits",
			"howler sellout",
			"injustice",
			"ironeyes desperado",
			"judges' shield",
			"lone stranger",
			"make an entrance",
			"maligned scavenger",
			"march of the gray",
			"mentor of the mighty",
			"mighty totem",
			"miner's barracks",
			"moonlit lurker",
			"murder",
			"mysteries of the ulek",
			"nameless drifter",
			"needle doll",
			"nightrail fence",
			"nightrail forger",
			"nightrail kingpin",
			"open road",
			"pains of the drunk",
			"penny dreadful",
			"pickpocket",
			"pioneer of wild places",
			"pocket aces",
			"qilan archer",
			"qilan raiders",
			"qilan wanderer",
			"reach for the sky",
			"recoil",
			"refund",
			"ride into the sunset",
			"sandbluff barflies",
			"sandbluff confiscator",
			"sandbluff duelist",
			"sandbluff slinger",
			"sareng, the dealer",
			"scout ahead",
			"shredding sword",
			"solemn deputy",
			"stand your ground",
			"stealer of secrets",
			"stickup",
			"street urchin",
			"sunrise bluffs",
			"sunrise prairie",
			"sunrise river",
			"sunrise ruins",
			"sunrise woods",
			"sunset cliffs hunter",
			"take aim",
			"the aetherite saloon",
			"threaten",
			"tracker of wild places",
			"tumblewalker",
			"ulek wayfinder",
			"ulek windrider",
			"vengeful agent",
			"vivid hallucination",
			"walking with ancients",
			"wanted",
			"wardens of the ulek",
			"warning shot",
			"whirling thoughts",
			"wild bounties",
			"abscond",
			"aguri, shadow of doubt",
			"akaima rager",
			"ancestral council",
			"aokara commander",
			"arcane strategist",
			"ashspeaker",
			"backburner",
			"bitter lies",
			"bond of battle",
			"chamber of splendor",
			"chimei scourge",
			"daughter of suisei",
			"dragon's eye descendant",
			"dragon's eye spiritualist",
			"dragonfly shrine",
			"dragonsoul disciple",
			"dreams of tomorrow",
			"enlightenment",
			"fate in flames",
			"fire and ashes",
			"flash of blades",
			"garrote",
			"general of kinjiru castle",
			"hirukari's immortal",
			"honored retinue",
			"horizon treader",
			"imperial coins",
			"imperial diplomats",
			"imperial proclaimer",
			"indomitable duo",
			"jade temple",
			"jade vault reclaimer",
			"kagetsu, chronicler of jidai",
			"kareki retainer",
			"kareki vanguard",
			"kareki warmaster",
			"kinjiru assailant",
			"kuno aokara, ivory crane",
			"lives redeemed",
			"masamori initiate",
			"miyoga flameweaver",
			"moeru thunderers",
			"moranai tracker",
			"mortal will",
			"nightfall infiltrator",
			"nightmare riders",
			"palace of reflections",
			"perfect distraction",
			"phantasmal stalker",
			"proffered heirloom",
			"raikai raider",
			"reserve troops",
			"ride as one",
			"rippling water shugenja",
			"rising tides",
			"scales of seishin",
			"searing grace",
			"seek guidance",
			"seikatsu recruits",
			"shadow courier",
			"shengin heartland",
			"shengin renegade",
			"shengin scoundrel",
			"shina taiyohata",
			"soul jar",
			"spirit keeper",
			"stolen secrets",
			"stonework infantry",
			"swift spearmaster",
			"throwing stones",
			"toil the fields",
			"torrent of wind",
			"traitor's touch",
			"uwaito envoy",
			"windshaper",
			"yasei, heart of jidai",
			"zen ascendant",
			"aerie's pillar",
			"aether ascendant",
			"almgrove champion",
			"almgrove sentinel",
			"bloated keystone",
			"breaker of secrets",
			"bygone guardian",
			"cavorting beauty",
			"ceaseless valiant",
			"channeling stone",
			"entrancing virtuoso",
			"exhaustive research",
			"exhilarating prescience",
			"forgotten pit",
			"giltwork legacy",
			"headwind glider",
			"ignition ritual",
			"jara jadefist",
			"lumbering hillock",
			"mechanized ideal",
			"possibility matrix",
			"rahit, immaculate architect",
			"rahit's prodigy",
			"rahit's study",
			"rousing rubble",
			"runic depths",
			"salva tore's study",
			"salva tore's vexation",
			"shatter facade",
			"spellslinger's gauntlet",
			"stormsurge",
			"surge of the leylines",
			"thunderous charge",
			"warded tome",
			"abandoned den",
			"aegis expertise",
			"astrid, disgruntled princess",
			"bjarndyr militant",
			"bloodguard's hand",
			"blow away",
			"brain feeding",
			"bristled wolverine",
			"casualty of war",
			"chains of subdual",
			"crash of hooves",
			"cryptic ritual",
			"culi-sae exonerator",
			"culi-sae mesmer",
			"curio connoisseur",
			"deathless ghoul",
			"departed evangel",
			"dire betrayal",
			"dissenting vikings",
			"dragon queen's den",
			"dragon queen's pupil",
			"efface",
			"engrave",
			"ephemeral visions",
			"fiery reckoning",
			"fleecy lynx",
			"flesh shredder",
			"forgotten experiment",
			"frosted adder",
			"furor of the bitten",
			"gale murmurer",
			"ghastly ferry",
			"greenheart den",
			"greenheart squirrel",
			"hat trick",
			"hearty karv",
			"hibernation den",
			"howl of the hunted",
			"humble fieldhand",
			"icefang wurm",
			"intrepid shieldmate",
			"issbarrens banishment",
			"lose composure",
			"lumbering egil",
			"mammoth crab",
			"mirin, held by the heavens",
			"model of perfection",
			"mortal resurrection",
			"nature's claim",
			"neckbreaker viking",
			"oaken longbow",
			"phantasmal possession",
			"pillager's sloop",
			"pinion peaks",
			"play the coward",
			"powdercoat leopard",
			"primal caribou",
			"raider's den",
			"rakkiri archer",
			"rakkiri initiate",
			"rakkiri piker",
			"recover",
			"rend asunder",
			"reticent possessor",
			"rimecraft owl",
			"ripclaw drake",
			"ruthless conscript",
			"sanitarium skeleton",
			"seek haven",
			"sentinel of the highlands",
			"shambling gutless",
			"short sword",
			"skhorvall eternal",
			"sly snow-fox",
			"steelcrusher viking",
			"student's pilgrimage",
			"tawny lemmings",
			"temple instructor",
			"temple recluse",
			"the issbarrens",
			"third legion general",
			"thoughtless malice",
			"to the hunt",
			"touch of shadow",
			"treacherous conditions",
			"unending voracity",
			"viking greataxe",
			"viork woods savage",
			"wanton cleave",
			"war-torn tundra",
			"warring ways",
			"weeping soul",
			"weirding wings",
			"whispered wishes",
			"windwhip",
			"a whisper's touch",
			"ainok brushwacker",
			"ainok lout",
			"autumn moon",
			"autumnal watch",
			"bauble collector",
			"bellani mystic",
			"benign whisper",
			"blundering clocktower",
			"borderland garrison",
			"braenid nomad",
			"canyon creek",
			"clever rejoinder",
			"climber's gear",
			"cloud rock",
			"conjuring minstrel",
			"crinster stitcher",
			"crinster tattooist",
			"crop warden",
			"crystal grotto",
			"cumulus horizon",
			"driven to distraction",
			"edith waunt",
			"evolving wilds",
			"expedition map",
			"eyes of the maghbri",
			"familial matriarch",
			"feed the eager",
			"fertile fields",
			"fey grove",
			"forced offering",
			"frailty",
			"frigid thicket",
			"furtive witch",
			"glacial buttress",
			"grayce blaen",
			"haunted boughs",
			"intoxicate",
			"lady heiffyd",
			"latent potential",
			"lord's handmaiden",
			"maghbri hunter",
			"maghbri whisper",
			"marked coin",
			"moon of the encroaching night",
			"moon of the final dawn",
			"moon of the frozen dusk",
			"moon of the lingering day",
			"moon of the promised day",
			"playful child",
			"roads untraveled",
			"rolling homestead",
			"rotwood whisper",
			"ruined precipice",
			"scion of the wild",
			"small luxuries",
			"soaring canyon",
			"spirit of autumn",
			"the last hunt",
			"tinkering swarm",
			"touch of witchcraft",
			"trae, serpent's grasp",
			"trinkets and charms",
			"verdant bluff",
			"vestiges of autumn",
			"vibrant balloon",
			"witch of spring's promise",
			"witch's abode",
			"witch's apprentice",
			"aethermage's chains",
			"ancient cairns",
			"ancient maze",
			"arcblade enforcers",
			"archivist heretic",
			"archivist's torment",
			"ashen host",
			"barricade patrol",
			"barricade watch",
			"beyond the forest's edge",
			"blightroot",
			"bloodspawn",
			"blossom-ash trance",
			"brutish champion",
			"buried glade historian",
			"catalog the possibilities",
			"chained ravager",
			"champion of the fae",
			"channel the spirits",
			"choir of the lost",
			"chroma, the faerie circle",
			"clockwork astrolarium",
			"confront",
			"cryptic fragment",
			"darken the skies",
			"deem incomplete",
			"demonqueller mage",
			"devouring flame",
			"dimensional isolation",
			"dispersive volley",
			"district of artisans",
			"dreamcast relic",
			"enigma of seventy scrolls",
			"evoker of the ancient form",
			"exiled necromancer",
			"fae-blessed attendant",
			"fae-blessed hunter",
			"featherfall ascetic",
			"field of obelisks",
			"finish the job",
			"fleshcrawler",
			"force back",
			"from ancient tomes",
			"gate to the nav",
			"gift of fire",
			"hall of lost histories",
			"halskrow street gallows",
			"halskrow street scavenger",
			"hand of the chroma",
			"harbinger of inversion",
			"herald of desolations",
			"immortalize in stone",
			"infernal barrier",
			"ion field",
			"keen-eyed gemcutter",
			"keep at bay",
			"key to the nexus",
			"kindle the cursed",
			"knight of the orchards",
			"leapweb lurker",
			"marketplace brawl",
			"masha, hero of pelastrov",
			"masha's vanguard",
			"merciful yuroda",
			"mirror cipher",
			"mischievous sprite",
			"moonlight sanctum",
			"mortal's conundrum",
			"mysterious absence",
			"nature's defiance",
			"nexus of possibilities",
			"noxious garden",
			"oracle's omission",
			"oracle's vision",
			"orb of undoing",
			"orphan of the nav",
			"outland alchemist",
			"overgrown ruins",
			"paincaller",
			"paradox sculptor",
			"paranoid archivist",
			"parliament's courtyard",
			"patient aethermage",
			"pelaski valiant",
			"public gardens",
			"putrid lurker",
			"reckless pyremage",
			"relearn history",
			"riddle of entropy",
			"river's end falls",
			"rune of rejuvenation",
			"rune-scribe's apprentice",
			"seeker taras",
			"sentry of kollis gate",
			"serafina, the traitor amongst",
			"serafina's gift",
			"sift through false leads",
			"skymount reinforcements",
			"slaffield workgate",
			"tear through",
			"tesseract conjecture",
			"the barricade strikes",
			"the frontier beckons",
			"through the ashen gate",
			"tinkerer's assistant",
			"touch of the uncanny",
			"tracer sigil",
			"traitor's gambit",
			"twist the threads",
			"unmasker of fate's design",
			"vanguard of the barricade",
			"vidal, rune thief",
			"wanderer's sky",
			"wandering domovoi",
			"wave of decay",
			"zadyk assassin",
			"zadyk ritualist",
			"acorn assault",
			"adoration",
			"amulet of loyalties",
			"ascendant's gate",
			"aspiring recluse",
			"awestone",
			"backstage banter",
			"backstage manager",
			"backstage rooms",
			"bessie's brood",
			"bit player",
			"blood overruling",
			"break a leg",
			"brilliance overbearing",
			"cadalon experimenter",
			"cadalon inspector",
			"changing room",
			"chromatic lantern",
			"chronovore clock",
			"compulsive accuser",
			"crystal cauldron",
			"cut short",
			"defying gravity",
			"diasune warleader",
			"divinity",
			"dragonfire blade",
			"duelist's choice",
			"eldritch egg",
			"elven guard",
			"enlightened sigil",
			"eternity pendant",
			"evigian noble",
			"exeunt",
			"forsaken bloodletter",
			"gentleman thief",
			"ghost light",
			"gilded cipher",
			"grab bag",
			"grieved outburst",
			"growing pains",
			"heist headquarters",
			"her ascension",
			"hidden hollow",
			"joyous chromatelk",
			"kiku, the gadgeteer",
			"lantern tender",
			"legitimate establishment",
			"living script",
			"lost memories",
			"mei, the infiltrator",
			"mei's collector",
			"mei's understudy",
			"merfolk vandal",
			"mirrored mask",
			"miscast",
			"moonlit charmer",
			"multipurpose mannequin",
			"performer of ambition",
			"performer of enlightenment",
			"pilfered process",
			"power overflowing",
			"prismatic panes",
			"pristine frame",
			"questionable methods",
			"realms overturning",
			"rehearse",
			"rei's awakening",
			"rei's ranger",
			"rei's watch",
			"ring of souls",
			"ruined theater",
			"ruptured citadel",
			"ruptured expanse",
			"ruptured falls",
			"ruptured flats",
			"ruptured grotto",
			"ruptured grove",
			"ruptured meadow",
			"ruptured morass",
			"ruptured square",
			"ruptured trail",
			"ruststep centipede",
			"saia's price",
			"saia's protege",
			"sartha's studies",
			"scathing review",
			"scramble the scouts",
			"scuripi collector",
			"seedy bar",
			"seer's sphere",
			"send away",
			"seven-year step",
			"shared trove",
			"shifty squirrel",
			"shining crusader",
			"skeleton keyring",
			"skitterthorns",
			"slay them in the aisles",
			"soliloquy",
			"soulless backstabber",
			"stage dressing",
			"steamquiver strix",
			"storm servant",
			"stormcannon gauntlet",
			"street busker",
			"street stalker",
			"sword of truth and lies",
			"taken for granite",
			"talent pool",
			"talent scout",
			"theater guard",
			"trap door",
			"turned watcher",
			"uncovered idol",
			"unmoving usher",
			"unraveling",
			"unwilling accomplice",
			"vault sentinel",
			"vile infiltrator",
			"villains: the musical",
			"voices overwhelming",
			"wayfaring realmstitcher",
			"whispering halls",
			"wild pyromancer",
			"zegarra, the rival",
			"absorb the soul",
			"ancestral warlord",
			"armored transports",
			"battlesuit prototyping",
			"brazen blackguard",
			"catalina's turf",
			"caylin whirlwind",
			"clutch shot",
			"consign to oblivion",
			"custom armaments",
			"derail",
			"determined slayer",
			"devised battlesuit",
			"deviser's cunning",
			"dominik's shack",
			"elderbane rifle",
			"elections tampering",
			"emmerich, the negotiator",
			"fashionable heiress",
			"forgotten doorway",
			"forsaken gunfighter",
			"ganzorig's domain",
			"gathering the gang",
			"gleeful deviser",
			"guiying's gambit",
			"guns blazing",
			"hiroto's refuge",
			"hostile takeover",
			"jin yahui, sage of war",
			"laconic deputy",
			"last stop",
			"lightning draw",
			"lurk at vision's edge",
			"marshal jin guiying",
			"modular mercenary",
			"neblus' legacy",
			"prophet of reclamation",
			"ravensgulch contractor",
			"recall forgotten eons",
			"reckless research",
			"riga's workshop",
			"riko, the paragon",
			"riko's academy",
			"rise from the harbor",
			"riv's safehouse",
			"savvy saboteur",
			"scrapyard raiders",
			"shadow of izumito",
			"shroud the world in doom",
			"snowclearer",
			"sparkline dancer",
			"specialist saboteur",
			"spectacle of innovation",
			"stay on guard",
			"steam daimyo's gauntlets",
			"strike down the usurpers",
			"takumi's headquarters",
			"tesqua cohort",
			"the long road north",
			"thuggish detective",
			"traveling marshal",
			"truth unveiled",
			"tsubasa's redoubt",
			"twelve thousand eyes",
			"unforget",
			"unorthodox methods",
			"wandering doyen",
			"watch from above",
			"xiong mao, the protector",
			"young falconer",
			"alquyut mount",
			"ash-withered cloak",
			"atrophy",
			"barren boneyard",
			"bashful drake",
			"bazaar informant",
			"bewitching vapors",
			"bitter wanderer",
			"bleak gorge convoy",
			"blighted dagger",
			"blood jade prophet",
			"brittle bequest",
			"broadened horizons",
			"calcified dunes",
			"carpet racers",
			"chart the stars",
			"colossal camouflage",
			"cruel consultation",
			"curious dais",
			"deathless siege",
			"dissipate",
			"drift tracer",
			"dune wraith",
			"effigy of creation",
			"effigy of destiny",
			"effigy of harvest",
			"effigy of morality",
			"effigy of wisdom",
			"el-mazar, wayward palace",
			"emerald warcaller",
			"emissary of antiquity",
			"encrusted sahalia",
			"ephemeral soultender",
			"flourishing dunes",
			"gateway statues",
			"gaunt abnormality",
			"gentry infiltrator",
			"gilded wyvern",
			"granite plating",
			"hafiq the wise",
			"hajir allegiant",
			"hajir soothsayer",
			"hand of fidelity",
			"hand of fury",
			"harsh erosion",
			"heat ray",
			"herald of the humble",
			"highland dunes",
			"highland hermit",
			"hostile atmosphere",
			"iekin's portal",
			"immolated grave",
			"impish delights",
			"keeper of holy lands",
			"loose threads",
			"madcap mercenary",
			"magnific wilderkin",
			"meddling gargoyle",
			"memoria thief",
			"menna al-mejjat",
			"mercantile accords",
			"morrow probe",
			"mortal pilgrimage",
			"mukhif the grim",
			"ninhasir's march",
			"outflank",
			"painted bluffs",
			"patron of asham",
			"petal scatterer",
			"plumed carpet",
			"princely mettle",
			"pristine duelist",
			"raise a ruckus",
			"rapacious rattler",
			"ravaged monument",
			"raving rover",
			"roving chaplains",
			"rush of adrenaline",
			"ruthless vagrant",
			"saber of defiled rites",
			"sandswept bazaar",
			"saturated dunes",
			"scabrous automaton",
			"scimitar techniques",
			"scorned figurant",
			"secluded monument",
			"shadow ambusher",
			"shadowband consul",
			"shrapnel golem",
			"sights beyond",
			"sink into the floor",
			"skeletal oasis",
			"skyline tracer",
			"soul chalice",
			"sower of wishes",
			"stabilize",
			"stasis snare",
			"strider harness",
			"strike down",
			"stygian dunes",
			"sunrazed ruins",
			"suraj militant",
			"tomb steward",
			"tomb of great drakes",
			"twisted gladiator",
			"venerable judgment",
			"venom infusion",
			"verdant haven",
			"violent collapse",
			"volatile stonework",
			"ancient counsel",
			"angelfire",
			"armadillo cloak",
			"aryam the dreamer",
			"aurora's whisper",
			"beckon the shadows",
			"blinded avenger",
			"children of the clouds",
			"conjured shade",
			"consuming knowledge",
			"dryad outrider",
			"dust barrens",
			"fade into mists",
			"fidelity of the pure",
			"glorybound chorister",
			"golden glade",
			"granite watchers",
			"great sable stag",
			"grove's respite",
			"hallowed fragment",
			"heart's desire",
			"heartless pact",
			"hesediel, the reborn",
			"hexfang ascetic",
			"hymn of fury",
			"invoking the name",
			"lavamancer adept",
			"ligos, shadow's source",
			"magmatic cache",
			"onyx ritualist",
			"pyresong ranger",
			"rain zai, spiritscale",
			"reaping mask",
			"rebellious streak",
			"reckless rage",
			"remembrance of light",
			"rend",
			"rius, temple of the grandfather",
			"sage of the aurora",
			"scion of fecundity",
			"silent griffin",
			"silent musing",
			"singers' grove",
			"smokeweaver initiate",
			"stag of the moon",
			"streamlash",
			"tea of augury",
			"the aurora's heart",
			"the court of angels",
			"tranquil moment",
			"upon the altar",
			"verdant cloak",
			"vindictive regent",
			"volcanic pounce",
			"waking mists",
			"warband commander",
			"warband lieutenant",
			"windwise courier",
			"windwise mentor",
			"acclaimed leadership",
			"ancestor's calling",
			"art studio",
			"aven traveller",
			"band of irregulars",
			"banish",
			"bayou courier",
			"belittle",
			"bewildering sight",
			"bite down",
			"blazing volley",
			"blessed mausoleum",
			"blessings of the parish",
			"bog rebirth",
			"boghex witch",
			"bogsnatcher drake",
			"bogsworn club",
			"bouquet singer",
			"captivating jester",
			"commune with kantra",
			"coordinated commotion",
			"creeping pianist",
			"crown of spores",
			"curse of encroaching waters",
			"dangerous territory",
			"determined evangelist",
			"eerie bayou",
			"elaborate transportation",
			"elegant strike",
			"encore of the phoenix",
			"enthralling actor",
			"explorer's fate",
			"faradia, honored sovereign",
			"faradia's favored",
			"faradia's grace",
			"faradia's outrage",
			"fervent strike",
			"festival rioters",
			"festival songstress",
			"fool's errand",
			"forlorn ruin",
			"gift of the phoenix",
			"helena, the awakener",
			"helena's exaltation",
			"heroic crusader",
			"inspiring band",
			"lakeside park",
			"lonely devil",
			"lotus debutante",
			"lotus feaster",
			"mark of the scaleblight",
			"marsh's veil",
			"mushroom lagoon",
			"new alores fiddler",
			"nimbus glider",
			"ontarachie dryad",
			"ontarachie forager",
			"ontarachie hunter",
			"oracle's ploy",
			"ornate incense",
			"overgrowth guardian",
			"parish custodian",
			"parish's command",
			"passionate congregation",
			"prayer hall",
			"ranidaphobia",
			"rejoicing aristocrats",
			"ritzy parlor",
			"river dabbler",
			"royal domain",
			"sensational festivities",
			"shelled muckdweller",
			"solemn offering",
			"sporeflow mantle",
			"sporeflow propagator",
			"stinghopper",
			"storehouse collapse",
			"streetside entertainer",
			"sudden conversion",
			"sunlit plaza",
			"tear to shreds",
			"tenacious brawler",
			"tomb keeper",
			"turtleback guide",
			"unicorn of the vale",
			"vacated bar",
			"vindictive abbot",
			"vivid march",
			"wanderspore terrapin",
			"whispers of the ontarachie",
			"woopip sproutling",
			"zoulev rebuff",
			"zoulev rites",
			"zoulev ritualist",
			"act of repentance",
			"adiran scryers",
			"adiran survivors",
			"aerida, envious chronomancer",
			"aerida's study",
			"anarchy storm",
			"artist's vista",
			"burgeoning blooms",
			"chance at redemption",
			"charming marauder",
			"consuming symbiosis",
			"contemplate obscurity",
			"crystal wave",
			"culminating chaos",
			"culminating conspiracy",
			"culminating despair",
			"culminating salvation",
			"culminating wisdom",
			"fallacy's channeler",
			"fallacy's sanctifier",
			"heraldry",
			"inspire actuality",
			"litany of renewal",
			"master of masks",
			"mirrorplate exemplar",
			"mystic of many winds",
			"once abandoned",
			"once shunned",
			"over the horizon",
			"paradox rings",
			"root dancer",
			"seek refuge",
			"shroud in paranoia",
			"stark copse",
			"stark hinterlands",
			"stark horizon",
			"stark stream",
			"stark wildfire",
			"starvation",
			"abandoned monument",
			"aether gateway",
			"akkrixian assailants",
			"alethea, syzygy captain",
			"amber reserves",
			"arboreal runes",
			"ardent explorers",
			"autumn canopy",
			"benthic thaumaturge",
			"blossoming expanse",
			"brine fleet bay",
			"brinechum",
			"caronas, eon wanderer",
			"cloudsteel summit",
			"contested discovery",
			"crossing the rifts",
			"crossworld wanderer",
			"cursed wastes",
			"cyone, expedition captain",
			"dimensional reshaper",
			"dreamscape",
			"dustchoked outpost",
			"endless trove",
			"epoch warden",
			"eternal reactor",
			"explorer's ascent",
			"farwander guide",
			"fearless realmwalker",
			"feral ornithax",
			"filch",
			"forgotten remains",
			"fractured reach",
			"gathering beacon",
			"ghostspore mire",
			"gilded gulch",
			"glacial shelf",
			"gloam gullet",
			"grand expeditions",
			"grove of embers",
			"gyr, awoken world",
			"harrowing experience",
			"heart of zhedina",
			"honored spellthreader",
			"hot streak",
			"idravir, the last city",
			"incense stoker",
			"intrepid",
			"jadycian empath",
			"journeying giftbearer",
			"krismite purveyor",
			"krismite shard",
			"krismite vault",
			"lotus lake",
			"marrow raptor",
			"molten falls",
			"monument of queens",
			"morphic verge",
			"mutalithic golem",
			"nereba, sandchoked archives",
			"offworld surveyors",
			"opulent proprietor",
			"otherworldly forest",
			"otherworldly island",
			"otherworldly mountain",
			"otherworldly plains",
			"otherworldly swamp",
			"outlander patrol",
			"paracosm",
			"pathshaper mage",
			"phantom threader",
			"phasmopillar",
			"planar eulogist",
			"planeshift",
			"polyp pools",
			"possibility engine",
			"precursor sanctum",
			"promethean grotto",
			"quandary seer",
			"rainsculpted gorge",
			"razione racecourse",
			"razorshell marauder",
			"reborn from the ashes",
			"research experience",
			"rift splicing",
			"rippling curtain",
			"rogg, chaos treader",
			"saddled scuttleback",
			"shadowcleft hideout",
			"shambling morass",
			"shifting canyon",
			"shifting cascade",
			"shifting crag",
			"shifting grove",
			"shifting morass",
			"shiftscale drake",
			"shuddering node",
			"skylight fortress",
			"smuggler's den",
			"soaring rainforest",
			"spoils of the undermarket",
			"starlight beacon",
			"steamlit peaks",
			"stormtide renegade",
			"sunchaser mantas",
			"syzygy privateer",
			"tears of tizuma",
			"telarine ascendant",
			"temporal rift",
			"thermal surger",
			"thievery",
			"timeless shrine",
			"tomb of shifting sands",
			"undermarket hawker",
			"untethered spire",
			"verdant renewal",
			"vivid mirage",
			"voidflare",
			"voliv edgelands",
			"wayfinding",
			"worldshaper adept",
			"woven network",
			"xoqal, world eater",
			"zhargetan reclaimer",
			"zhedina bazaar",
			"zhedina exchange",
			"zhedina outskirts",
			"zhelid, planar academy",
			"acin, the toymaker",
			"alia's enforcer",
			"ambitious necromancer",
			"arcane chronometer",
			"arcane metalcrafter",
			"beckon darkness",
			"beckoner of horrors",
			"brilliant academy",
			"brilliant archives",
			"brilliant capital",
			"brilliant castle",
			"brilliant citadel",
			"brilliant cityscape",
			"brilliant hub",
			"brilliant mansion",
			"brilliant port",
			"brilliant workshop",
			"city gate",
			"claim for civilization",
			"consort of morning",
			"cosmic chart",
			"dawnwisp vents",
			"disable",
			"dovon, verdant experimenter",
			"eager observer",
			"embrace the veil",
			"evavin duelist",
			"extravagant flair",
			"fallback plan",
			"flamecloaked artisan",
			"flare blitz",
			"gate to the beyond",
			"hunt the monstrous",
			"iken troubleshooter",
			"imagine",
			"imitator of drakes",
			"iterative designer",
			"jessica turin, battlemage",
			"kati evalin, world wanderer",
			"lightblessed claymore",
			"lockdown",
			"mana confluence",
			"mana rose",
			"maniacal elementalist",
			"marin polgek, academy heiress",
			"martial maestro",
			"matron of machines",
			"mirrorcast battlemage",
			"nina, master of arms",
			"oldgrove nurturer",
			"open the secret paths",
			"philosophy of fire",
			"polgek restorationist",
			"powercell cultivator",
			"primal ruffian",
			"ravenous hydra",
			"renewal grove",
			"riftway to the other side",
			"runecrested valley",
			"sealed riftway",
			"seeker of untouched beauty",
			"self replication",
			"slay the unkillable",
			"speedreading",
			"sword of tides and time",
			"the clocktower project",
			"timeworn crags",
			"transplanted citadel",
			"twisted speaker",
			"unexplored regions",
			"veilborn hunter",
			"veilcrossed twins",
			"vitin forgemaster",
			"volta, construct consultant",
			"ancestor's skull",
			"antiquated firearm",
			"bright-eyed adventurer",
			"broken deathbringer",
			"cantrip collector",
			"cobbled currency",
			"cobbled transport",
			"courier's misfortune",
			"dead-set duo",
			"desperate forsaken",
			"determined to prevail",
			"discover survivors",
			"drained shore",
			"drought-plagued slum",
			"drove of the lost",
			"eerie armament",
			"excavator of the beyond",
			"expand the perimeter",
			"experimental battle armor",
			"false god's downfall",
			"farmland settlers",
			"fate tracer",
			"favoured firebrand",
			"fluctuating locale",
			"forager's lore",
			"forsaken getaway",
			"grave of an old lord",
			"hand of the murder",
			"haunted fairground",
			"hellwaste settlement",
			"herald of the departed",
			"hermit of the taiga",
			"hone strategy",
			"hunger of old lovi",
			"imperious nixie",
			"ineffable patronage",
			"infiltrator of the anomalous",
			"keen reflexes",
			"kielie, risti strike leader",
			"life remembers its roots",
			"logger recluse",
			"medical mask",
			"memorial ground",
			"mennin jar",
			"mennin pack",
			"moved by instinct",
			"neo-alchemist",
			"neophyte of the old gods",
			"privilege's sway",
			"pulsating mass",
			"ravenous forsaken",
			"reunite with nature",
			"reyhsia, truth chaser",
			"risti citadel",
			"risti operative",
			"risti strategist",
			"risti watchkeeper",
			"runeclad seeker",
			"savage stalker",
			"scavenger holdout",
			"scavengermobile",
			"secluded farmstead",
			"seductive seashell",
			"sepulchral seas",
			"singer of calamities",
			"suspect concoctions",
			"swarm of the dispossessed",
			"the ancestors pass judgment",
			"the bliss of ignorance dies",
			"the flesh becomes soil",
			"the mist thirsts for silence",
			"the songs of gods echo",
			"traversing the hellwastes",
			"true shot",
			"warped landscape",
			"warped recluse",
			"windmill project",
			"worn peacekeeper",
			"ascension",
			"aureate panorama",
			"banish the intruders",
			"banished companion",
			"bloodlash caravan",
			"brushcover elf",
			"caulte axeslinger",
			"cinderblade",
			"corvid heretic",
			"descend on the helpless",
			"endless discoveries",
			"eternal rage",
			"fleeting discoveries",
			"frozen hinterlands",
			"hazy coppice",
			"heartripper zombie",
			"highpeak rider",
			"icepeak phantasm",
			"lowland vista",
			"militant youth",
			"molten incubation",
			"ochre knight",
			"offerings to the deathless",
			"phantasmal reflection",
			"poisonheart druid",
			"reaper of the fields",
			"scarletblood hound",
			"skystream mantas",
			"spellshatter",
			"spires of caulte",
			"stonewood sanctuary",
			"strix of dark omens",
			"sunlit fissure",
			"testament to heroism",
			"the whisperwoods",
			"towering boughs",
			"vali, planar researcher",
			"veiled by the blizzard",
			"verdict of the council",
			"whisperwoods phoenix",
			"worldly travels",
			"aether runes",
			"aetherspear",
			"ancient dominion",
			"artful chari",
			"aspirant of legend",
			"azure caterwauler",
			"back-alley gnoll",
			"barbed cocoon",
			"berylscale alaj",
			"blackmoat bully",
			"bleak dominion",
			"blind blackguard",
			"blisterbug",
			"bloodfell caves",
			"blossoming sands",
			"bogfume pact",
			"bone splinters",
			"canine acumen",
			"coastal dominion",
			"colony soldier",
			"croak tales",
			"desolate dominion",
			"devious paladin",
			"disciple of the all-mother",
			"dismal backwater",
			"distorted reflection",
			"elegant agility",
			"elken grovetender",
			"esoteric egg",
			"felling vines",
			"fierce combatant",
			"fractured illusion",
			"fuel the arcflame",
			"fume whisperer",
			"gentle giraffe",
			"gleaming river",
			"glinthide hero",
			"grace of timber",
			"great migration",
			"greypelt brute",
			"greypelt emissary",
			"greypelt initiate",
			"greypelt trooper",
			"homestead",
			"iron hide",
			"join the colony",
			"joyful deviant",
			"jungle hollow",
			"lumbering ox",
			"lunar emissary",
			"maddening thoughts",
			"majestic dominion",
			"msuji operative",
			"murky peat",
			"mythos scribe",
			"nip at the heel",
			"on marvelous wings",
			"oozing adder",
			"ornery bloom",
			"ox of blood bend",
			"pact of dark power",
			"paint over",
			"pangoling",
			"pestilent vermin",
			"petrify",
			"plaxolotl pyari",
			"primal dominion",
			"pristine dominion",
			"prodigious panya",
			"provincial loyalty",
			"pungent beetle",
			"punja stick trap",
			"quill sniper",
			"rage of the ravaged",
			"rapacious instinct",
			"resting wildehound",
			"reticulate chemist",
			"royal bloodhound",
			"ruchi, the effervescent",
			"rugged dominion",
			"rugged highlands",
			"ruinous naga",
			"runescale brawler",
			"ruthless mastiff",
			"sable hoopoe",
			"samaki school",
			"sandblast",
			"scale-crown archer",
			"scoured barrens",
			"serum smoker",
			"shadow stalker",
			"speckled outcast",
			"spirit transfusion",
			"squall serpent",
			"stalwart dominion",
			"student of the scroll",
			"stupefied piper",
			"sunwashed spires",
			"swiftwater cliffs",
			"the banishment of seh'a",
			"theurgic flock",
			"thornwood falls",
			"threshing sundew",
			"tranquil cove",
			"tropical grove",
			"twilight ambush",
			"unlikeliest heroes",
			"vast savannah",
			"verdant dominion",
			"vibrant flames",
			"virtuorangutan",
			"warhound shuja",
			"wind-scarred crag",
			"windwatch eagle",
			"wisdom beyond age",
			"aose field researcher",
			"abomination sculptor",
			"accompanied adventurer",
			"aldorus fin, vice president",
			"ancient artillery",
			"architect of calamity",
			"barren vista",
			"beyond humanity",
			"big enough",
			"biocrystal augmentation",
			"blooming vista",
			"call of the abyss",
			"combat technician",
			"cosmic sinkhole",
			"counting stars",
			"crucible of worlds",
			"cultivate",
			"daring adventurer",
			"dead end adventurer",
			"dead on arrival",
			"deepbrush operative",
			"defected android",
			"exergetic chains",
			"field technician",
			"fiery erasure",
			"fracking factory",
			"glacial vista",
			"glowspore grove",
			"green daywalker",
			"growing up",
			"guardian of lost truths",
			"hall of random access memories",
			"hardened explorer",
			"head on collision",
			"heaven knows",
			"hero's downfall",
			"hold me down",
			"hostile habitat",
			"hot to the touch",
			"human frailty",
			"i'll be gone",
			"jacque, crystal-touched",
			"k-17 drone",
			"killdrone engineer",
			"lay claim to nature",
			"living vista",
			"lone survivor",
			"lost without you",
			"lt. daisy saxon",
			"marshy vista",
			"mineral retriever",
			"nebula of empty gold",
			"nebula's call",
			"new divide",
			"nimble explorer",
			"olten survivalist",
			"on the shoulders of giants",
			"out-of-body experience",
			"painwield explorer",
			"paired pathfinders",
			"planetary reconnoiterer",
			"precursor filtercruiser",
			"predatory psion",
			"prismatic cavern",
			"prosthetic repairs",
			"rage-fueled adventurer",
			"recurring abomination",
			"reenter orbit",
			"repurposed killdrone",
			"rethia cultivator",
			"returned explorer",
			"sage of wilds",
			"scarlet mist",
			"scavenging pack",
			"silencing guardian",
			"slyten crystal motherlode",
			"slyten ignitor",
			"space jelly swarm",
			"strange discovery",
			"sword of monsters and men",
			"the tomb of precursors",
			"thorn-touch abomination",
			"thunder road",
			"trick mirror gui",
			"wandering precursor",
			"watch the world fade",
			"whatever it takes",
			"when the stars align",
			"whimsy",
			"wild dogs of the night",
			"xenoflora expert",
			"aether pull",
			"ajani's advocate",
			"akrasan sentry",
			"antali archdruid",
			"arcane sanctum",
			"arcanist's reaver",
			"bant shardseeker",
			"behemoth channeler",
			"bigroot valley",
			"bleak shoreline",
			"blessed radiance",
			"brackwater scuttler",
			"brutal struggle",
			"caustic mangrove",
			"cesspool scrapper",
			"charred marsh",
			"chromeleon",
			"cling to undeath",
			"cloudcover heights",
			"cognition crucible",
			"crumbling necropolis",
			"dagger-thrash marauders",
			"dire predictions",
			"disturb the riddle gate",
			"duneglass ascetic",
			"edarna's augurling",
			"empyrial reverence",
			"entrail elemental",
			"erupting territory",
			"esper shardseeker",
			"etlan high priest",
			"exuberant hunter",
			"fathom the forbidden",
			"flesheater vine",
			"font of nefarox",
			"forbidding isle",
			"frenzied nacatl",
			"fungal flourishing",
			"gloomtide gulf",
			"grixis shardseeker",
			"hazy summits",
			"hellkite's decree",
			"herald of the white orchid",
			"hierarch ranger",
			"idyllic oasis",
			"infernal flames",
			"jhessian cavalier",
			"jund shardseeker",
			"jungle shrine",
			"kaleidoscape",
			"kederekt seawitch",
			"leotau rider",
			"lush coast",
			"macabre effigy",
			"maelstromancy",
			"mage's warding",
			"magma spray",
			"meren, bane of the cairns",
			"meticulous mechanist",
			"nacatl skirmisher",
			"naya shardseeker",
			"nel toth shaman",
			"omen of nefarox",
			"orlesia, first of the sen",
			"paladin's attendant",
			"peaceful passage",
			"pledge of peace",
			"radiant resolve",
			"rafiq the magnanimous",
			"ragemist",
			"reliquary rhox",
			"savage lands",
			"sculler's oar",
			"sculpted observatory",
			"seaside citadel",
			"sedraxis trepanator",
			"sighted-caste knight",
			"sigil of the many",
			"somber meadow",
			"sphinx's scrutiny",
			"spire of bant",
			"spire of esper",
			"spire of grixis",
			"spire of jund",
			"spire of naya",
			"steel wind strix",
			"subduing serum",
			"sun-dappled paragon",
			"telemin architect",
			"terraformer's globe",
			"terramorphic expanse",
			"thallid cultivator",
			"thrinax sporemother",
			"thunderscorn",
			"tidehollow lich",
			"torchlight tormentor",
			"tranquil repose",
			"twisting fissure",
			"unbeholden navigator",
			"unearth",
			"vectis entrancer",
			"vigor from the vein",
			"vitalhydra",
			"vithian arcanist",
			"war-pride champion",
			"worldheart nexus",
			"act of treason",
			"agriculture",
			"aridland camaar",
			"battlescarred predator",
			"bloodsoaked blades",
			"borsuppa outrider",
			"borsuppa scavenger",
			"center of culture",
			"collapse the pillars",
			"consult the scriptures",
			"court sponsor",
			"cradle of civilization",
			"crescent of possibilities",
			"day of rest",
			"death pits trophy",
			"dehmi, origin seeker",
			"dehmi's servitor",
			"dehydrate",
			"despoiler of civilization",
			"donkey jawbone",
			"ekebram the scholar",
			"eli windsors, lone gun",
			"emissary of dark tides",
			"endak city slavedriver",
			"epic of anku",
			"epic of ekebram",
			"epic of jobiah",
			"founding hero",
			"funerary barge",
			"gilded idol",
			"godchosen valor",
			"hannaru's courage",
			"hard-working oxen",
			"harrow",
			"heartland's protection",
			"hefty tablet",
			"hirsute champion",
			"imperial achievement",
			"imperial brutality",
			"imperial claim",
			"kanaan wardriver",
			"keeper of codices",
			"lammasu roost",
			"life's worth",
			"lisseria, general of kanaa",
			"long journey",
			"lush delta",
			"manalith",
			"mangrove fisher",
			"marble row healer",
			"marrow cruncher",
			"medicine",
			"multiculturalism",
			"mustering grounds",
			"nibinem's hand",
			"opulent ankulim",
			"paid in blood",
			"palace enforcer",
			"parted waters",
			"piercing blow",
			"pound by pound",
			"primordial manifestation",
			"queen hannaru",
			"rhudai fieldtiller",
			"rhudai pathfinder",
			"rod of marble row",
			"rottenfruit coiler",
			"rupture spire",
			"sarrutu flamebinder",
			"scavenger's wagon",
			"scorpid sniper",
			"seeker amalgam",
			"serpent staff",
			"serve the empire",
			"shemesh, nomad chieftain",
			"shepherd's companion",
			"shock",
			"sire of empires",
			"sling of the meek",
			"sorrowful memories",
			"spawn of the guardian",
			"spell pierce",
			"splinter of anku",
			"strongarm",
			"suffocating sands",
			"sunblessed orator",
			"sunnula's firebird",
			"theocracy",
			"trace the oasis",
			"trusty camaar",
			"under the gun",
			"urn of heroes",
			"wandering warden",
			"wealthy merchants",
			"wondrous bazaar",
			"writing",
			"a journey begins",
			"aeroblast",
			"aspiring trainer",
			"attract",
			"barrier",
			"bee hive",
			"bridled growth",
			"brutality",
			"bug catcher",
			"canopy darter",
			"caustic caterpillar",
			"chikyu league arena",
			"citadel bagworm",
			"compulsive patrol",
			"confusion",
			"cruel fledgling",
			"curious fossil",
			"duplicate",
			"eager hatchling",
			"eerie cocoons",
			"elemental of surprise",
			"ema, the traveler",
			"enduring charge",
			"ever-gnawing rat",
			"extremespeed",
			"fierce lunge",
			"firemane fox",
			"focus sash",
			"forgotten temple",
			"from a seed",
			"full belly",
			"gene pool",
			"ghastly tether",
			"grinding",
			"healing center",
			"hellhound alpha",
			"hidden sprout",
			"ice path",
			"improvised guardian",
			"jovial martyr",
			"lake of rage",
			"lakeside trickster",
			"lava plume",
			"leech seed",
			"lunar vigil",
			"maternal monster",
			"metal coat",
			"monstrous champion",
			"moon-rune fox",
			"moonlight",
			"mountain runt",
			"mournful newborn",
			"muggy mire",
			"natural cure",
			"nirami, ema's keeper",
			"paleontologist",
			"perish song",
			"petal dancer",
			"poised koi",
			"poison point",
			"power plant",
			"practice range",
			"preying mantis",
			"psychic assault",
			"psywave",
			"quiet retreat",
			"rapid rodent",
			"rocket admin",
			"ruined lab",
			"ruined shrine",
			"run away",
			"ruthless brawler",
			"sanaito, alone",
			"sandslinger",
			"scary face",
			"scuttling gnat",
			"shadow ball",
			"shadow sneak",
			"shocking ewe",
			"skill link",
			"slashing pangolin",
			"sludge-gill fox",
			"smokescreen",
			"snatch",
			"sprout tender",
			"still waters",
			"tangling vines",
			"thundermane fox",
			"toxic larva",
			"trainee karina oblay",
			"treasure beach",
			"unburdened",
			"unstoppable weed",
			"victory road",
			"viper ambush",
			"wandering hamlet",
			"warning birds",
			"wishing star",
			"wistful fox",
			"working together",
			"worried vulpine",
			"zipping zapper",
			"adept fisherman",
			"all for one",
			"alvarez of the huntsman",
			"another day in paradise",
			"armored valiant",
			"bramble armor",
			"bushwhack",
			"captain darlene filham",
			"captain's companion",
			"cascade drake",
			"children of gos",
			"civil discourse",
			"claustrophobia",
			"crain's crony",
			"crazed swashbuckler",
			"crown of the speaker",
			"cruising schooner",
			"down with the ship",
			"dusk lieutenant",
			"dwarven war hatchet",
			"east ward forgetender",
			"expunge the terrors",
			"fated mariner",
			"fen glutton",
			"fiery cannonade",
			"fiery temper",
			"fight song",
			"find greater purpose",
			"flaming point technique",
			"flintlock pistol",
			"fog at sea",
			"forged alliance",
			"gale mediator",
			"garth of the chimera",
			"gaze of the grave",
			"glisterhorn",
			"grasp of hollows",
			"grave wrangler",
			"greedy rapscallions",
			"grievous buccaneer",
			"griffling",
			"grisly reaper",
			"harbinger of giradrus",
			"harriet of the pioneer",
			"holcomb of the peregrine",
			"infernal fury",
			"intrepid captain",
			"ironclad infantry",
			"keen seafarer",
			"law enforcement",
			"legion of giradrus",
			"light the fuse",
			"lost knowledge",
			"mable of the sea's whimsy",
			"malignant rise",
			"maritime thug",
			"master negotiator",
			"mephitic fumes",
			"oaken sentry",
			"old salt",
			"pathless shallows",
			"perennial unrest",
			"perilous treaty",
			"pirate's cutlass",
			"pirate's hideout",
			"prowling agamid",
			"rattled bones",
			"recruits of the demeter",
			"revoke privileges",
			"rising terrain",
			"rootshaper",
			"ruinous proselyte",
			"seto san, the dragonblade",
			"shipwrecked",
			"shrieking nightwing",
			"silent hunt",
			"skulduggery",
			"sleepless vigil",
			"song of the sea",
			"staunch constrictor",
			"strange tides",
			"suitor of the sea",
			"swift corsair",
			"swooping razorbeak",
			"tamiyo, lunar arcanist",
			"tankard of grog",
			"tender warden",
			"thicket mimicry",
			"three seas cartographer",
			"treasure hauler",
			"twilight privateer",
			"two-faced marauder",
			"valencia of the concordant",
			"verdurous herald",
			"visions of oblivion",
			"watchful navigator",
			"anemone cluster",
			"aquatic might",
			"battle station",
			"blood in the water",
			"bloodthirsty jaws",
			"bonetooth darter",
			"brilliant runepearl",
			"bubbledome keeper",
			"bubbledome waveblade",
			"buried at sea",
			"bygone wreck",
			"cannoncoil hermit",
			"conchspear hunter",
			"coral guidance",
			"coralblade cohort",
			"coralight castle",
			"coralight communer",
			"coralight mystic",
			"crush the hull",
			"curious disturbances",
			"current surfer",
			"cuxuri's corruption",
			"danithra oracle",
			"darting guppy",
			"dawson's bouncer",
			"dawson's collector",
			"dawson's loot",
			"dawson's warden",
			"depthcalling",
			"depthlight captain",
			"drag beneath",
			"dukedom outcast",
			"edina's soulsinger",
			"emerge from the reeds",
			"enchanting palace",
			"eye of the beholder",
			"fabulous find",
			"face of the abyss",
			"finish off",
			"frontline descender",
			"glittering narwhal",
			"glum oarfish",
			"goldtooth slasher",
			"grisly ruins",
			"guppyfin duelist",
			"harried submersible",
			"hila okunos",
			"hopesinker",
			"horrors' reach",
			"idyllic odyssey",
			"ink seer",
			"krill-clan guardian",
			"lie in wait",
			"lilyreed triton",
			"live in harmony",
			"lord rickard dawson",
			"mandibled mass",
			"master of the abyss",
			"megalodon rush",
			"merrow legendmaker",
			"mina, jeweled minnow",
			"minefield bomber",
			"molten basin",
			"myrmidon's warhead",
			"mysterious lights",
			"mystic mackerel",
			"narwhalrus",
			"oceanographer",
			"odelia's attendant",
			"oil driller",
			"ominous helmet",
			"palace servant",
			"paradise reef",
			"pay up",
			"prismscale piranhas",
			"redgill corsair",
			"reefcrown egg",
			"regal coralhorn",
			"restless predation",
			"roving dreadnought",
			"ruin dive",
			"ruin shark",
			"rustshell crustacean",
			"schoolmaster",
			"seadrake rider",
			"seafoam slasher",
			"searchlight drones",
			"shanty town",
			"silent doom",
			"specimen collector",
			"storm the seafloor",
			"tectonic chateau",
			"tide crasher",
			"tideflow wardings",
			"torpedo jetter",
			"trenchbottom mariners",
			"trident of benediction",
			"twenty thousand leagues",
			"typhoon caverns",
			"typhoon cruiser",
			"uncovered secrets",
			"unsuspecting victim",
			"vibrant sandbar",
			"volcanic catastrophe",
			"volcanic hollow",
			"way of the danithra",
			"adam of the ironside",
			"brutal blow",
			"bustling harbor",
			"camahueto calf",
			"channel the song",
			"ciel, the raider king",
			"clean-up crew",
			"dazzling dreamspinner",
			"diviner of blood",
			"dreary township",
			"end of all things",
			"endless helpless souls",
			"eye of dismay",
			"forbidden burial",
			"forest dragon telo",
			"forked pillar",
			"fulmen, aether prodigy",
			"galvan ranger",
			"glimpse in the static",
			"glittering grove",
			"grin, scourge of goresand",
			"hop of life",
			"idyll",
			"invent the future",
			"kenleigh, liege of redemption",
			"lay low",
			"lorilyf, home-tree",
			"monsoon lagoon",
			"mystery of the crashed craft",
			"noxious upwelling",
			"plasma enforcer",
			"powder scatterer",
			"rainy night lovers",
			"ria-demian charm",
			"scrap, the second myr",
			"sear flesh",
			"soul's attendant",
			"urban wastelands",
			"void portal",
			"vulture valleys",
			"waxing angel",
			"willow spirit",
			"abrupt duplication",
			"adaptive troll",
			"adventuring gear",
			"affluent cetanthrope",
			"arms merchant",
			"backstab",
			"bag of holding",
			"bind the great evil",
			"blessing of immunity",
			"cascade failure",
			"centaur courser",
			"chained greatwolf",
			"champion's steed",
			"coastal metropolis",
			"corrupted memory",
			"critical strike",
			"crowded tavern",
			"cut causality",
			"destructive storm",
			"devour essence",
			"doom cultist",
			"doomed traveler",
			"eldritch invitation",
			"embodied soul",
			"essence manipulator",
			"fast travel",
			"fertile steppe",
			"flooding magma",
			"folsen, king of valimir",
			"forceglow shield",
			"frantic researcher",
			"gambler's tournament",
			"gifted swordsman",
			"gifted warmage",
			"glimpse beyond",
			"godmother ilthiss",
			"guided hunter",
			"guided medic",
			"guided occultist",
			"hero's axe",
			"hero's henchman",
			"homeward amulet",
			"immortal child",
			"invisible communion",
			"invoke the divine",
			"itinerant stalker",
			"juddering mishap",
			"kindly pilgrim",
			"knight of valimir",
			"lag spike",
			"malaise",
			"mana potion",
			"map all creation",
			"missing manifestation",
			"momentous blow",
			"mukal desecrator",
			"mukal forerunner",
			"mukal pillager",
			"mukal rager",
			"mukal reaper",
			"mukal warleader",
			"mysterious stranger",
			"null entity",
			"osk, the maker's pet",
			"patient optimizer",
			"predictable pattern",
			"prepare for the onslaught",
			"procedural genesis",
			"puzzling stratagem",
			"raid the cursed temple",
			"raid the dragon's lair",
			"raid the forgotten tomb",
			"raid the infested woods",
			"ranger's bow",
			"relic corrosion",
			"renowned healer",
			"resurrection priest",
			"revela, star-touched",
			"rogue's passage",
			"savage companion",
			"scale factor",
			"scavenging alchemist",
			"scour forgotten archives",
			"seek the buried relic",
			"seek the lost child",
			"silent suppression",
			"smash and grab",
			"spawning barrens",
			"student of winds",
			"swift-fingered sneak",
			"thalassic borough",
			"thieves' dagger",
			"thornweald cavalier",
			"twisted hospitality",
			"twitchy pyromancer",
			"uncanny investor",
			"unending slime",
			"unsummon",
			"urak, voice of the horde",
			"walk through walls",
			"warden of urilath",
			"warped glitchmage",
			"wild peak",
			"world map",
			"zarad's executioner",
			"ageless wanderer",
			"alratha, pearl of the sand sea",
			"alrathan outcast",
			"ancient tablet",
			"archaeologist's discovery",
			"azure archaeologist",
			"calamity apparition",
			"cave spider",
			"cold shoulder",
			"collapsing ridges",
			"consult ancient knowledge",
			"conto sika, ruined glory",
			"dafiqi falconer",
			"darna's grimoire",
			"daunt",
			"descend upon the tomb",
			"desert's hearth",
			"disgruntled student",
			"drysand mole",
			"dthan, who bloodies the sands",
			"dthan's daggers",
			"ecological refuge",
			"eternal duneborn",
			"eve's scheme",
			"faithful priest",
			"fiery burst",
			"flamecaller's command",
			"freeborn healer",
			"giant's remains",
			"guardian of mysteries",
			"harsh trek",
			"heatwave",
			"heavy sandstorm",
			"heinous acts",
			"hero of aer",
			"illuminated firebird",
			"into the scorpion den",
			"living library",
			"lonesome traveler",
			"love letters",
			"mage's command",
			"maktali, the great library",
			"masked lancer",
			"master of ancient ways",
			"merchant's outpost",
			"mystic khopesh",
			"oasis' grandeur",
			"outpost merchant",
			"painful rites",
			"palaisun, maktali's opus",
			"path of fire",
			"peacemaker dove",
			"phantasmal owl",
			"pilgrim's packbeast",
			"pious relicseekers",
			"protect the treasure",
			"prowling beastmaster",
			"puzzlemaster's priest",
			"qalami barbarian",
			"reckless dunerider",
			"remnant of lost times",
			"restored automaton",
			"reytha, the sandstorm",
			"reytha's discovery",
			"roaming spirit",
			"royal falconer",
			"ruin guardian",
			"ruin wanderer",
			"ruins' reward",
			"sand scorpion",
			"sand twister",
			"scholar's assistant",
			"secrets of the orrery",
			"secrets of the tower",
			"shifting sands",
			"silent wayfarer",
			"smashing brute",
			"sparkmage prodigy",
			"spectral wings",
			"sphinx's advice",
			"sphinx's authority",
			"sphinx's sight",
			"spiny lizard",
			"spirit of the mountains",
			"spirit of the sands",
			"spirits' descent",
			"stargazing",
			"summoned skeleton",
			"swaying sands",
			"tara, duneblessed",
			"tara's confluence",
			"tara's lament",
			"telani scammer",
			"thief's command",
			"tomb robber's grit",
			"trail of bones",
			"trial recruitment",
			"turn up",
			"verdant oasis",
			"vicious stinger",
			"voidbringer",
			"warrior of far-off sands",
			"wayfarer's amulet",
			"winged stinger",
			"ylda, the wild soul",
			"astral gateway",
			"beckon of the wild",
			"bile of the world",
			"civilization's cost",
			"crossing the fog",
			"crystal wave",
			"dreamsteel paladin",
			"master of minds",
			"mpumo, who stands alone",
			"rain zai, spiritscale",
			"rose of fretport",
			"taken away",
			"voidcaller's ambition",
			"wisdom of the leylines",
			"ammbradu goliath",
			"bow or burn",
			"carnival yatiri",
			"champion of destinies",
			"coveted heirloom",
			"liliana at the brink",
			"minister of madness",
			"nightwatch rallier",
			"nova, skyship captain",
			"oshiruko conspirator",
			"soul's attendant",
			"twisting memories",
			"xenocrata's fleet",
			"abhorrent academic",
			"alien visitor",
			"endless expedition",
			"face of all",
			"grim botanist",
			"guard of cuirassiers",
			"lackeybot",
			"mortal whims falter",
			"paragon of noon",
			"ruffler of feathers",
			"shrine razer",
			"sigiled bulwark",
			"tend to the grove",
			"tiny heroine totti",
			"weaver of mists",
			"wild lifescale",
			"xolde, high king's castle",
			"acin, the toymaker avatar",
			"big presents",
			"massive surprises",
			"small gifts",
			"playtest card a10",
			"playtest card a11",
			"playtest card a12",
			"playtest card a13",
			"playtest card a14",
			"playtest card a15",
			"playtest card a1",
			"playtest card a2",
			"playtest card a3",
			"playtest card a4",
			"playtest card a5",
			"playtest card a6",
			"playtest card a7",
			"playtest card a8",
			"playtest card a9",
			"playtest card b10",
			"playtest card b11",
			"playtest card b12",
			"playtest card b13",
			"playtest card b14",
			"playtest card b15",
			"playtest card b1",
			"playtest card b2",
			"playtest card b3",
			"playtest card b4",
			"playtest card b5",
			"playtest card b6",
			"playtest card b7",
			"playtest card b8",
			"playtest card b9",
]

		names
			.map{|n| db.cards[n]}
			.flat_map{|card| card ? card.printings : []}
			.to_set
	end

	def to_s
		"hugo"
	end
end