class ConditionIsMarisa < Condition
	def search(db)
		names = [
			"afterlife heist",
			"against the waves",
			"apex's oath",
			"berbarus unsealed",
			"calamitous crash",
			"chratteri restoration",
			"crystal garden",
			"curse-blood morrigan",
			"edge of the water",
			"epic score",
			"final reckoning",
			"finale of cinders",
			"glorysinger",
			"glymna blackrune",
			"gorbes index",
			"hunter's hideout",
			"in memoriam",
			"leyline alignment field",
			"memento mori",
			"mirrorgate",
			"ol' sycamore",
			"overloaded aethergate",
			"puppeteering",
			"seventh circle cultist",
			"sinister heir",
			"start anew",
			"titan's palace",
			"unceasing flames",
			"villainy",
			"voidlife orbs",
			"wandering souls",
			"warden of the dead",
			"welcome return",
			"words of eternity",
			"abhorrent exhumer",
			"accursed existence",
			"accursed phantasm",
			"allagras, tidal master",
			"allagras' vanguard",
			"arcanist's dispersal",
			"bane of sanity",
			"beragnian blizzard",
			"blade of reolem",
			"blood servant",
			"bloodchill risen",
			"chillwhisper witch",
			"chronowing phoenix",
			"collapsing ground",
			"continental collapse",
			"corpse exploiter",
			"cranial archive",
			"curse of the deadlands",
			"deadland mongrel",
			"deadland scavenger",
			"deadland summoner",
			"doomed fate",
			"dulling necromancer",
			"echoing knowledge",
			"elemental clash",
			"endrison familiar",
			"endrison nourisher",
			"fellor ironborn",
			"final revelation",
			"fleshgraft aberration",
			"forest",
			"graveborn usurper",
			"guilty execution",
			"hapless chronomancer",
			"imminent collision",
			"island",
			"koth's retaliation",
			"lafterii augur",
			"lafterii ingenuity",
			"landbound ritualist",
			"magus of memories",
			"master echomage",
			"mawdryk, endrison warden",
			"mawdryk's accusation",
			"memories of the past",
			"merkurio's insight",
			"merkurio's rebuttal",
			"meteor volley",
			"mountain",
			"mulchborn behemoth",
			"offer to nature",
			"plains",
			"priest of forbiddance",
			"punishing catastrophe",
			"purging reolem",
			"pyromancer's fury",
			"rallios' demise",
			"rallios' return",
			"ripping wilds",
			"rise from death",
			"risen looter",
			"roggar's frenzy",
			"roggar's gambit",
			"ruin salvager",
			"savrios' timeshifter",
			"scourge of the deadlands",
			"shape the tides",
			"sinful past",
			"soulstone commander",
			"soulstone redeemer",
			"subturgian legionnaire",
			"subturgian proliferator",
			"surge of depravity",
			"survive the wreckage",
			"swallowed by the earth",
			"swamp",
			"temporal resuscitation",
			"tharyen, lord of subturgia",
			"tharyen's sadism",
			"the high prairies",
			"traversing bulkvine",
			"undying terror",
			"unhallowed legion",
			"unstable footing",
			"until the last breath",
			"vestige of evil",
			"whimsical elemental",
			"winds of toxicity",
			"abandoned sanctuary",
			"admirer of the lost",
			"bone pit raptor",
			"come crashing down",
			"crimson hellmaw",
			"desecrate antiquities",
			"diseased prophet",
			"disinter",
			"emissary of the wicked",
			"endangered rhino",
			"fell the beast",
			"flame ascetic",
			"fleshwrithe ghoul",
			"foolhardy huo",
			"forlorn murklurker",
			"infuse the apparatus",
			"inundated sanctuary",
			"kai'jun, the annihilator",
			"kai'long, dark immolator",
			"kai'shi, anguished one",
			"keeper of blue incense",
			"kugoja, perished conduit",
			"lizhao, lord of the yaogu",
			"maiden of the daffodils",
			"mother of owls",
			"mull over",
			"nightcloak ritualist",
			"qiyan, serpent of seven heads",
			"quell mutiny",
			"rabid rodent",
			"ravaging ghoul",
			"resurrection plea",
			"rise from the depths",
			"ruinous glutton",
			"sacred sanctuary",
			"savage sanctuary",
			"shock blast",
			"shredskin sky horror",
			"sightless blight",
			"skeletal shredwing",
			"soulless decree",
			"spire sanctuary",
			"succumb",
			"the first idol",
			"the mad sage's scroll",
			"tomb scavenger",
			"twisted mist",
			"tzelin of the demon realm",
			"undead archivist",
			"undeath comes",
			"warrior of the folded fan",
			"wretched sanctuary",
			"xiong mao, survivalist",
			"aghavaan's corrupter",
			"aghavaan's wound",
			"ancient ossuary",
			"azuma hashiro, the thronebreaker",
			"bind in jade",
			"clutch of the coil",
			"discorporate",
			"elemental loremaster",
			"festival of fading lights",
			"festival of roaring dragons",
			"fireheart channeler",
			"heavenly temple",
			"imperial ricefields",
			"kiyomi's disciple",
			"kiyomi's yoroi",
			"lady kiyomi",
			"legends remembered",
			"miyoga firebird",
			"sage's ashes",
			"sankataar nightbringer",
			"sankataar scourge",
			"serpent's grasp",
			"shugenja sanctuary",
			"soul leak",
			"stonesculpting",
			"sunrise orchard",
			"swirling dragonfire",
			"the moon rises",
			"unhallowed graves",
			"wayfarer's shrine",
			"windwielder",
			"adaptive terrains",
			"arcane might",
			"archaeomancer",
			"bonereader",
			"brainless ghoul",
			"brew of undeath",
			"brutal murder",
			"carrion gourmet",
			"cunning infiltrator",
			"daughter of malextros",
			"divine verdict",
			"erudition of the lafterii",
			"evergrowing hydra",
			"fateful hour",
			"fleshmonger",
			"flooded morass",
			"flourishing crevasse",
			"gift of undeath",
			"goblin arsonist",
			"hate-driven arsonist",
			"heart of the glade",
			"hollowflesh ghoul",
			"hunted sprareos",
			"insurgent racketeer",
			"kragnoss' assault",
			"lavatorn fields",
			"lay to rest",
			"magus of the sands",
			"malextros, deathlord",
			"mental dislocation",
			"mind's intruder",
			"mindscreech drake",
			"monolith of ages",
			"natural growth",
			"natural recycling",
			"necromancer's talent",
			"night screecher",
			"pillar of flame",
			"planar alignment",
			"pool of light",
			"rageborn phoenix",
			"reclamation sage",
			"sorcerer's staff",
			"soul of iscathia",
			"spreading disease",
			"springjack pasture",
			"suicidal impulse",
			"vaertris, mindmelder",
			"vampire nighthawk",
			"venomsilk recluse",
			"vexing riddlemage",
			"vollta patrician",
			"vythraktos, master necromancer",
			"war golem forge",
			"ward shatter",
			"abrupt volley",
			"amber hills",
			"arcane harvesters",
			"arcanomancer",
			"battle the evil one",
			"blightbringer",
			"boiling ridge",
			"bravery",
			"bring down",
			"chain of command",
			"darklands charm",
			"deadly infection",
			"deadly manipulation",
			"decay",
			"deception",
			"dictate of the evil one",
			"disentomb",
			"dredging aberration",
			"driver of hordes",
			"duskwood thicket",
			"dusty record",
			"empty the tombs",
			"ethereal savior",
			"evil one's mind tricks",
			"fading memories",
			"faith",
			"fatestitcher",
			"flooded depths",
			"forbidden resource",
			"forced loyalty",
			"goblin experimenter",
			"grave reaper",
			"grave tutor",
			"grim bastion",
			"hand of the evil one",
			"harvester of secrets",
			"hazy moorland",
			"hindered research",
			"intelligence",
			"kill shot",
			"magmatic torrent",
			"memories reignited",
			"merkurio's familiar",
			"naturalize",
			"obliterating blast",
			"piling corpses",
			"plundered graves",
			"rallios unleashed",
			"reader of fates",
			"reconstruct",
			"rugged fields",
			"runewing's feathers",
			"sealed mausoleum",
			"search for inspiration",
			"shifting frontiers",
			"silencing curse",
			"sungrace meadows",
			"sunlit highland",
			"the evil one awakens",
			"the high prairies burn",
			"thoughtgrinder",
			"tombstone looter",
			"undead harbinger",
			"undying mobilizer",
			"unearthed legion",
			"unknown shores",
			"venomous grasp",
			"wardbane mystic",
			"warden of rehis-dorahn",
			"weapon smash",
			"wretched spawn",
			"altar of adversity",
			"altar of chaos",
			"altar of creation",
			"altar of destruction",
			"altar of order",
			"angelbane spider",
			"angelic destiny",
			"angeltouched cavern",
			"angeltouched crag",
			"angeltouched garden",
			"angeltouched marsh",
			"angeltouched saltflat",
			"bahet's sacrament",
			"bahet's wink",
			"bahum, penitent",
			"bahum's penance",
			"bane of identity",
			"born from the flock",
			"branching antlers",
			"chaosphere ravager",
			"chiara the enchantress",
			"chimera graft",
			"combatant conflagration",
			"cosmostorm rider",
			"council of the immortals",
			"counsel of bahet",
			"dark night cleansing",
			"deathless hunter",
			"descended delta",
			"descended marsh",
			"descended meadow",
			"descended mortuary",
			"descended towers",
			"devilish undoer",
			"end of the road",
			"enforce the cycle",
			"eternal recurrence",
			"evershedder",
			"excise from existence",
			"fanatic revival",
			"fatal edict",
			"fearless charger",
			"final verdict",
			"formed anew",
			"ifram's greenfur",
			"inherited rite",
			"ishim of genesis",
			"ishim of oblivion",
			"journey to atonement",
			"lifetwist",
			"manifest dead",
			"martyr of the work",
			"masqued cleansers",
			"naberas' wisdom",
			"ophan titan",
			"pinnacle seraph",
			"potential beetle",
			"progenitor of rebirth",
			"purgator of storms",
			"qith maneuver",
			"rampant giantling",
			"razing throng",
			"reincarnation savant",
			"resounding relief",
			"return of the fallen",
			"return to ash",
			"rework the canvas",
			"saghira, divinity's usurper",
			"splitflame phoenix",
			"tammil and sulei, the guides",
			"thornweald archer",
			"thorough cleansing",
			"thoughts reborn",
			"trifold chaos",
			"tusked consumer",
			"unorthodox tutelage",
			"unpredictable bloodshed",
			"unwavering questant",
			"verdant trauma",
			"war priest of bahet",
			"wayfaring swindler",
			"weaver of ifram",
			"wellspring of creation",
			"wild gravetender",
			"wilting waif",
			"zaidha, seraph of calamity",
			"ahl's study",
			"aleud scorn",
			"arisen haploc",
			"aurora, soulweaver",
			"blood bounty",
			"burned bounty",
			"carrionpult",
			"contagious host",
			"crafted coast",
			"destiny forgotten",
			"dinah, lifeweaver",
			"dire dive",
			"edge of the world",
			"enduring memory",
			"ferrofy",
			"gleamhorn elk",
			"halls of renown",
			"haploc striker",
			"haunted estate",
			"infectious corpse",
			"kalak culler",
			"lha reckoner",
			"lifebreather",
			"lunar defractor",
			"lush outcrop",
			"martyr's bounty",
			"memory martyr",
			"might of the dylso",
			"recast destiny",
			"reclaim relics",
			"reclaimed kalak",
			"refractors gaze",
			"rite of fangs",
			"sodden sorrow",
			"spired canopy",
			"stargaze spirit",
			"summoner's call",
			"sword of memories",
			"tale of two sisters",
			"the erased",
			"vicar of victory",
			"wings of the moon",
			"above",
			"adamant cultist",
			"bazaar trickster",
			"bleak cultist",
			"blessed spellroot",
			"chantwood channeler",
			"chantwood cultist",
			"clawing shaman",
			"controlled burn",
			"cranial violation",
			"cultist's dagger",
			"draw and quarter",
			"dredge the graves",
			"echoing sunder",
			"endless reverie",
			"ensouler of blades",
			"eternal nightwalker",
			"excavation engine",
			"fallow grave",
			"fatethief",
			"fatetwist shaman",
			"fertile grave",
			"flotsam",
			"ghastly castle",
			"gleaming veldt",
			"grisly marsh",
			"hired kalak",
			"last-thought feeder",
			"manifest memories",
			"melt down",
			"memory collector",
			"memory deterioration",
			"mental meltdown",
			"might of the oslyd",
			"obliterate flesh",
			"one",
			"ravencaller",
			"reforged relic",
			"revived colpah",
			"revoke",
			"ritesinger shaman",
			"rotted kalak",
			"shattered mirrorwalker",
			"slightly mad",
			"spilling secrets",
			"spiritual colpah",
			"sunken cavern",
			"sunny dunes",
			"sweep stakes",
			"tale of two sons",
			"twisted echo",
			"untouched wilds",
			"vaneir, necromaster",
			"wild hermit",
			"adept necromancer",
			"ancestral memories",
			"avatar of amosis",
			"cunning chanter",
			"dance for the heavens",
			"depraved disciple",
			"desert slaughterer",
			"desert temple",
			"desert wurms",
			"divine denial",
			"giant dromad",
			"giant scarab",
			"kalro, desert outpost",
			"kill the competition",
			"menes, the great pyramid",
			"menhet's edict",
			"mummification",
			"mummy's grin",
			"rockpounding saurian",
			"sandborn mage",
			"sanding",
			"slaughter",
			"sudden drought",
			"survive",
			"wachet charm",
			"zarchepet, master of sands",
			"abyssal nightcaster",
			"arina's defiance",
			"auramancer's appraisal",
			"awaken to the skies",
			"break hold",
			"deathfeeder",
			"deathwind detonator",
			"deathwind expanse",
			"deathwind's grasp",
			"defiant bristles",
			"devastating impact",
			"drakon nightshade",
			"duel of intellect",
			"earthfeeder worm",
			"elancean regrowth",
			"electrokinetic's bolt",
			"enchanter's resolution",
			"encrypted dagger",
			"enhance armor",
			"entelan erasure",
			"firewall trap",
			"forest whale",
			"fortune hoarder",
			"fulmen, eldritch channeler",
			"gryla canyon",
			"hidden prowess",
			"infested goblin",
			"jonah of the spellbane",
			"kimar, lightforger",
			"lightbringer's touch",
			"moonshadow abyss",
			"notion retrieval",
			"perfect aim",
			"plasma arc",
			"priest's altar",
			"pyre trap",
			"reliya's construct",
			"revert to moonlight",
			"shadow sky",
			"shaidostan cryoforger",
			"simplified life",
			"spellbane's strike",
			"stormcaster's tower",
			"sudden suspension",
			"syncopate",
			"touch of corruption",
			"trace the leylines",
			"trapcatcher's form",
			"vampiric defenses",
			"ancestral shrine",
			"aquatic refuge",
			"beast hunt",
			"citadel of denial",
			"deep temptation",
			"deluge crab",
			"essence rehabilitator",
			"fox of the molten dawn",
			"graveyard shift",
			"ha'eng, figure of greed",
			"hayuan, the misjudged",
			"hui zhou, the dark visage",
			"ing'wei, the surging tide",
			"kai'wej, the desolate",
			"malefic portal",
			"malignant afflicted",
			"mausoleum rite",
			"monumental siege",
			"mystical dowsing",
			"no-man's land",
			"organic corrosion",
			"pack familiar",
			"prairie monastery",
			"scorched copse",
			"seto san, the sacred hand",
			"staggering brilliance",
			"stoic observation",
			"sunless ridge",
			"sustaining meditation",
			"temple of brilliance",
			"toxic spring",
			"woken wave",
			"xing, the lucky charm",
			"all-consuming fire",
			"auramancer",
			"birthing elemental",
			"black cat",
			"bloodfury warlord",
			"blow to pieces",
			"burn with demonfire",
			"callous renegade",
			"consuming doom",
			"contempt for the unnatural",
			"death's sentry",
			"drownyard scavenger",
			"earthenlore disciple",
			"enduring vestige",
			"erika, mourning soul",
			"fallen ideal",
			"fatresya's command",
			"fearless recruit",
			"flesh hoarder ghoul",
			"form of the phoenix",
			"foundryborn ingester",
			"frostfire geysers",
			"fungal mire",
			"glintfeather sage",
			"gloomcover steppe",
			"glorious revival",
			"goblin sniper",
			"heartstabber mosquito",
			"ill winds blow",
			"infiltrate nimunot",
			"insidious terror",
			"ishtari, oasis warden",
			"kellythross' workshop",
			"kevthra's will",
			"lush oasis",
			"mechanical masterpiece",
			"miraculous genesis",
			"mold shambler",
			"molten ritual",
			"mulch harvest",
			"necrosavant's staff",
			"norn's ultimatum",
			"pestilent renewal",
			"phyrexian scraphandler",
			"poisonheart undead",
			"purging priestess",
			"purging strike",
			"ragantiar, maurassi overlord",
			"ragantiar's hoarding",
			"ralezza, weaver of okthuros",
			"scrapgear contraption",
			"sense of loss",
			"seven deadly sins",
			"shrine of the six pillars",
			"spiraling canyon",
			"symbiotic sprout",
			"total recall",
			"vanquish the obsolete",
			"vaultkeeper",
			"vedalken reshaper",
			"bend the knee",
			"beneath the lilies",
			"bloodied twinblade",
			"bustling docks",
			"choked estuary",
			"commoners' justice",
			"daelish arbalest",
			"death's door",
			"declare, the mother bear",
			"derelict amphitheatre",
			"exiled warband",
			"farmer's repose",
			"ferris, the sapphire storm",
			"foreboding ruins",
			"forgo the past",
			"fortified village",
			"game trail",
			"inexperienced martyr",
			"interlocked waterways",
			"isolated cloister",
			"mutual destruction",
			"perish in harmony",
			"plunge through the heart",
			"port town",
			"price of power",
			"punish the bold",
			"requiem of the fallen",
			"reverence seeker",
			"roads twice traveled",
			"scraps of memory",
			"seal the tomb",
			"shadowed slums",
			"shatter",
			"shrouded cackler",
			"tearful reunion",
			"tectonic wound",
			"thailen's guard",
			"tranquil endeavors",
			"trystasp coating",
			"weald sentry",
			"whiterun gates",
			"whiterun harbor",
			"wildborn lancer",
			"withering agony",
			"abandoned battlefield",
			"abandoned cairn",
			"abandoned meadow",
			"abandoned skyroad",
			"abandoned wilderness",
			"academy wastes",
			"alpine meadow",
			"barren desolation",
			"calmed battleground",
			"charbroiled core",
			"chiseled cliffside",
			"cleared vault",
			"cliffside entrance",
			"command tower",
			"dawnlit battlefield",
			"deadwood grove",
			"deeplife cavern",
			"deserted steppe",
			"deserted trail",
			"desolate barrens",
			"exotic xenoreef",
			"fiery chasm",
			"flourishing waterways",
			"forgotten cryovault",
			"forgotten shrine",
			"frigid highlands",
			"frontier base",
			"gleaming hot springs",
			"gnarled henge",
			"grim slums",
			"grove of reversal",
			"haughty chateau",
			"haunted woodlock",
			"highland vale",
			"horizon of origins",
			"imperial barracks",
			"jagged crag",
			"legacy foundations",
			"lush outskirts",
			"mossy shrine",
			"mysterious cataract",
			"ocean monastery",
			"ominous lair",
			"ornamented evergreen",
			"overgrown refuge",
			"quintok station",
			"rainforest spring",
			"roaring cascade",
			"secluded cascade",
			"shardstone rift",
			"shrouded rooftops",
			"sky-high spires",
			"sodden cavern",
			"somber marsh",
			"spires of telenia",
			"stormcharged pyre",
			"strange harbor",
			"sunlit ruins",
			"timber range",
			"tirenan market",
			"torrid geysers",
			"toxic jungle",
			"tranquil stream",
			"unlit alley",
			"wastes",
			"weathered fortress",
			"wildrune thicket",
			"abandoned forge",
			"abandoned hideout",
			"abandoned laboratory",
			"abandoned preserve",
			"abandoned shores",
			"bestial mob",
			"blood frenzy",
			"boneforged arms",
			"callous ritualist",
			"cloudsnatch",
			"creeping terror",
			"dancing flames",
			"dead of night",
			"descent of the stars",
			"doctored trail",
			"emberling",
			"fertile soil",
			"flickercloak",
			"horizon gazer",
			"lifeshell crab",
			"liguno, who transcends all",
			"looking glass",
			"moonshadow remnant",
			"past unresolved",
			"revenge of the disfigured",
			"rheila rachy",
			"secrets unearthed",
			"stay determined",
			"thomar's sowing",
			"vitality unbridled",
			"abura-no-oni",
			"anzen, beyond the sea",
			"chikami castle",
			"commander hyctaleon",
			"curse of kurayami",
			"dragonwall gates",
			"end of the empire",
			"faceless animist",
			"finishing touches",
			"fleeting thoughts",
			"fleshcage shambler",
			"forgotten homelands",
			"fuhai-no-oni",
			"heralds of shikai",
			"house of forgotten whispers",
			"imako, ninefingers",
			"imperial port",
			"imperial siege",
			"inoshi the wild boar",
			"kami's greed",
			"kamu-tribe outfitter",
			"kemono-no-oni",
			"ketsueki, kiyomi's legacy",
			"kizoku valiant",
			"kurayami butcher",
			"kurayami necromancer",
			"kurayami shrine",
			"lord rokai",
			"memorial of the fallen",
			"midnight keep",
			"mystic arts",
			"only memories remain",
			"perilous passage",
			"prayer of drifting lights",
			"ryukami, the first sovereign",
			"saishuteki castle",
			"sasori nightrunner",
			"scrollmaster",
			"seishin dojo",
			"sever limbs",
			"shadowstrider",
			"shikai revenant",
			"shikai's redoubt",
			"shizura, keeper of traditions",
			"shugenja's journal",
			"sunset monastery",
			"tarraka-no-oni",
			"temple of falling leaves",
			"the last sacred gate",
			"tower of long shadows",
			"tsang jin, master of the jade sea",
			"unearthly grace",
			"unhallow",
			"unzari ruins",
			"way of the dragon",
			"whisper of the winds",
			"abyssal stalker",
			"ancient saber",
			"arcanum owl",
			"assassinate",
			"blood fiend",
			"bloodfire phoenix",
			"bloodstone halls",
			"caustic lurker",
			"crumbling vestige",
			"death strike",
			"due judgement",
			"erase from existence",
			"eternal oak",
			"fell the haughty",
			"festering shambler",
			"forced sprouting",
			"gavis the stalwart",
			"grave revenant",
			"healer's knack",
			"hill of souls",
			"ironsmash wrecker",
			"kotis, promised general",
			"library specter",
			"life's harbinger",
			"life's will",
			"lord of swarms",
			"master spellwright",
			"mindbreaker sphinx",
			"moonlit shore",
			"morbid plunder",
			"murderous rampage",
			"palloren vulture",
			"planar processor",
			"predatory feast",
			"primal evocation",
			"prophetic flame",
			"recall to mind",
			"rise from the grave",
			"rot rebirth",
			"rouse from below",
			"sagi aysan",
			"seismic spike",
			"sphinx mentor",
			"spider broodmother",
			"spirit drain",
			"trail of rebirth",
			"twice-lived dead",
			"valley falls",
			"vengeant souls",
			"verdant sanctum",
			"verendas brawler",
			"wild ravine",
			"acolyte of night",
			"blood ritual",
			"bloodriver",
			"cloudbank",
			"cloudchaser kestrel",
			"corpsebed",
			"corrupted dancer",
			"cradle of corruption",
			"deathmask initiation",
			"divine butcher",
			"doomsower",
			"drowned weaver",
			"dying wishes",
			"elrayin, the manaroot",
			"even death may die",
			"feeding time",
			"gravelocked seeker",
			"grip of the deadwood",
			"heart of the deadwood",
			"infinite dreams",
			"liquefaction",
			"lotusheart gorran",
			"melodae, the favored",
			"monkeyshines",
			"moonlight stalker",
			"mosecf, the sunseeker's path",
			"mother night",
			"mother's disciples",
			"nadei the wavecaller",
			"nightshade shaman",
			"novean sky swallower",
			"oakpoint",
			"pelt's refuge",
			"pond tenders",
			"primordial gorran",
			"ralora, unforgiving depths",
			"read the entrails",
			"return to light",
			"revert to dust",
			"rotting sunseeker",
			"scion of death",
			"sea of skies beyond",
			"seedshrine",
			"seeker's end",
			"seila, the lost one",
			"sever",
			"shoring naiad",
			"sunstage",
			"swampedge sentinel",
			"synapstorm",
			"tangled pathfinder",
			"the sun also rises",
			"this too shall pass",
			"whispers of the dark",
			"yrodu, the lotus ablaze",
			"arctic mine",
			"assassin's warning",
			"bearer of the lantern",
			"boneweary warrior",
			"callow survivors",
			"canal lurker",
			"compelling pariah",
			"coppergild mercenary",
			"crumbling precipice",
			"crystal cavern",
			"crystal puncture",
			"cult of trinity's fall",
			"daunting skyline",
			"days of decay",
			"decrepit crags",
			"drown in nightmares",
			"elixir of immortality",
			"failing port",
			"festering waif",
			"feverish noble",
			"forgotten sins",
			"forgotten steppe",
			"fretport gravetender",
			"fretport's fade",
			"fretport's lament",
			"gabryel's devout",
			"grim courtyard",
			"grim gravetender",
			"hazy lagoon",
			"heedless lovers",
			"hide from horrors",
			"honor's refuge",
			"influential wildborn",
			"iron warden",
			"kalemn weller",
			"keenheart blade",
			"lurking terrors",
			"mass executions",
			"mental fracture",
			"merchant's district",
			"mourn the lost",
			"murmuring falls",
			"nomad's township",
			"phosphorescent ravine",
			"prayers of defiance",
			"prayers of judgement",
			"precarious ledgers",
			"prophet of pacifism",
			"purging watchkeeper",
			"rampant summit",
			"resplendent substratum",
			"rickety guildhall",
			"rising riots",
			"ruined citadel",
			"sedate tundra",
			"serene trail",
			"sewer pack",
			"shared reminiscence",
			"shifting glade",
			"sickening madness",
			"steadfast heart",
			"valeriya's militant",
			"vibrant rainforest",
			"wary watchkeeper",
			"wayward afflicted",
			"weathered veteran",
			"whisper collector",
			"wisdom in reflection",
			"withering beggar",
			"aether recoverer",
			"aetherite dagger",
			"aetherlock effigy",
			"at the gallows",
			"blind soulcaller",
			"bloodleaf butcher",
			"bloodleaf druid",
			"bloodleaf warcry",
			"bloodthirsty ambusher",
			"bounty collector",
			"bounty leveler",
			"chief striking dawn",
			"creeping hidebehind",
			"deputy gibem",
			"derelict town",
			"dreamkeeper",
			"dusk occultist",
			"elven wanderer",
			"forgotten haunt",
			"forlorn farmhand",
			"ghastly character",
			"gifts of ancient ulek",
			"gleaming rider",
			"graygulch drifter",
			"graygulch howler",
			"graygulch lurker",
			"graygulch outcast",
			"graygulch turncoat",
			"haunting bard",
			"heavy moneybag",
			"howler sellout",
			"injustice",
			"lease on life",
			"lingering guide",
			"lonely return",
			"loreweaver",
			"maligned scavenger",
			"march of the gray",
			"mudslinging",
			"murder",
			"mysteries of the ulek",
			"nightrail forger",
			"nightshade cultivator",
			"old-world forgotten",
			"public hanging",
			"qilan seer",
			"ravenous chupacabra",
			"reforge",
			"spectral hunter",
			"spectral slinger",
			"spirit of infamy",
			"sunrise bluffs",
			"sunrise prairie",
			"sunrise river",
			"sunrise ruins",
			"sunrise woods",
			"sunset cliffs lawman",
			"sunset cliffs patron",
			"the aetherite saloon",
			"the wicker lord",
			"tracker of wild places",
			"ulek crusher",
			"ulek elder",
			"ulek wayfinder",
			"ulek windrider",
			"unassuming swineherd",
			"uncovered mine",
			"vengeful agent",
			"vessel of lost souls",
			"wanted",
			"warning shot",
			"weaver of the winds",
			"wild bounties",
			"window shopping",
			"agent of long shadows",
			"arcane strategist",
			"backburner",
			"bitter lies",
			"chamber of splendor",
			"chigau, the red market",
			"chimei scourge",
			"daughter of suisei",
			"deathless disciple",
			"diffuse",
			"double-edged duelist",
			"dragon's eye descendant",
			"dragonfly shrine",
			"dragonsoul disciple",
			"ebb and flow",
			"elemental power",
			"enshrine",
			"fiery embrace",
			"fire and ashes",
			"flash of blades",
			"garrote",
			"ginjiro chimei",
			"grasp of water",
			"hero of shengin province",
			"hiroto jaakuna",
			"hirukari's immortal",
			"honor and glory",
			"illicit tutor",
			"imperial coins",
			"imperial legacies",
			"jade temple",
			"jade vault reclaimer",
			"journey through uwaito",
			"jun",
			"kareki retainer",
			"kareki vanguard",
			"kinjiru blackguard",
			"kinjiru cavalry",
			"kinjiru warlord",
			"lives redeemed",
			"masamori hunter",
			"masamori initiate",
			"master of elements",
			"moranai survivalist",
			"mortal tapestry",
			"mortal will",
			"night ambush",
			"nightfire adept",
			"nightmare riders",
			"nightmarish fears",
			"old soeji",
			"palace of reflections",
			"past, present, future",
			"path of shadows",
			"phantasmal stalker",
			"profaner of souls",
			"proffered heirloom",
			"raikai raider",
			"red flower assassin",
			"sage of reflections",
			"scales of seishin",
			"scout the terrain",
			"sea cache",
			"seek guidance",
			"setting sun",
			"shengin heartland",
			"shengin renegade",
			"shengin scoundrel",
			"smoldering pages",
			"soulkindle lantern",
			"spirit keeper",
			"spirit script",
			"stolen breath",
			"stonework infantry",
			"strike from the shadows",
			"suisei the southern star",
			"sundering sage",
			"sworn cohort",
			"thunderlash mystic",
			"yasei, heart of jidai",
			"aerie's pillar",
			"archive guardian",
			"breaker of secrets",
			"bygone guardian",
			"cadre hawk",
			"ceaseless stalker",
			"ceaseless valiant",
			"channeling stone",
			"compulsion's voice",
			"conjuring of locusts",
			"face the dawn",
			"false vitality",
			"forgotten pit",
			"gruff smith",
			"lumbering hillock",
			"rahit's prodigy",
			"rousing rubble",
			"salva tore",
			"shatter facade",
			"sigil of radiance",
			"thought blossom",
			"vitality maestro",
			"whistling blades",
			"young necromancer",
			"abandoned den",
			"astrid, disgruntled princess",
			"bjarndyr militant",
			"blood hunter's spear",
			"bloodguard's hand",
			"bloodshed devotee",
			"cane dancer",
			"casualty of war",
			"chains of subdual",
			"cryptic ritual",
			"demolish",
			"departed evangel",
			"dragon queen's den",
			"engrave",
			"fiery reckoning",
			"flesh shredder",
			"frosted adder",
			"greenheart den",
			"grizzly matriarch",
			"hibernation den",
			"hungering horde",
			"issbarren phoenix",
			"last dusk",
			"leech-ridden corpse",
			"marked scent",
			"mirin, held by the heavens",
			"mortal resurrection",
			"nature's claim",
			"pinion peaks",
			"raider's den",
			"recover",
			"rend asunder",
			"rimecraft owl",
			"rotfeeder slime",
			"ruthless conscript",
			"saffrisa, heir apparent",
			"saffrisa's touch",
			"sanitarium skeleton",
			"shipway whale",
			"shorecrash octopus",
			"sinner's purge",
			"skhorvall eternal",
			"steelcrusher viking",
			"tear loose",
			"the issbarrens",
			"unending voracity",
			"vitality reclaimer",
			"wake of the beast",
			"war-torn tundra",
			"warfield excavator",
			"wave of ice",
			"whispered wishes",
			"winter widow",
			"xiong mao, the intrepid",
			"aelinn, serpent's voice",
			"amateur pilfering",
			"autumn moon",
			"beguiling witch",
			"bellani mystic",
			"birth of whispers",
			"blundering clocktower",
			"canyon creek",
			"chef's apprentice",
			"cloud rock",
			"clouded mind",
			"concord of ravens",
			"crystal grotto",
			"cumulus horizon",
			"desraen, serpent's will",
			"evolving wilds",
			"exhausted farmhand",
			"fey grove",
			"frigid thicket",
			"glacial buttress",
			"haunted boughs",
			"humored outlaw",
			"incarcerate",
			"intoxicate",
			"latent potential",
			"legendweaving",
			"maghbri oracle",
			"midnight stalking",
			"moon of the encroaching night",
			"moon of the final dawn",
			"moon of the frozen dusk",
			"moon of the lingering day",
			"moon of the promised day",
			"reflect on serenity",
			"rotwood whisper",
			"ruined precipice",
			"scrollsnatcher",
			"small luxuries",
			"soaring canyon",
			"twinfire dragon",
			"verdant bluff",
			"whisper witch",
			"accursed by unborn fates",
			"aethermage's chains",
			"ancient cairns",
			"arbiter of endless summer",
			"arcane duelist",
			"avenging yuroda",
			"awaken the nav",
			"barricade patrol",
			"cackling tormentor",
			"catalog the possibilities",
			"chroma, the faerie circle",
			"coiling mystic",
			"collector of histories",
			"crack open the cache",
			"darken the skies",
			"detritus scourge",
			"dragongate",
			"duelist's forms",
			"enigma of seventy scrolls",
			"exiled necromancer",
			"field of obelisks",
			"finish the job",
			"from ancient tomes",
			"frostfall hunter",
			"gate to the nav",
			"halskrow street scavenger",
			"hunter of the moon-serpent",
			"immortalize in stone",
			"keep at bay",
			"king of bones",
			"masha's lightbound",
			"merchant of false lives",
			"mina and adurnos",
			"nature's defiance",
			"noxious garden",
			"omenreaper",
			"oracle's vision",
			"overgrown ruins",
			"pact of martyrs",
			"paincaller",
			"paranoid archivist",
			"price of wisdom",
			"putrid lurker",
			"pyremage's last rite",
			"return to earth",
			"rune of rejuvenation",
			"rune-scribe's apprentice",
			"sadistic indulgence",
			"sever flesh",
			"spare the meek",
			"spiteful domovoi",
			"stonefall golem",
			"through the ashen gate",
			"touch of the uncanny",
			"tracer sigil",
			"trespasser of the gallows",
			"twist the threads",
			"twisted stampede",
			"under untamed skies",
			"unliving swarm",
			"unwavering sentinel",
			"wanderer's sky",
			"wreath of crows",
			"zadyk resourcefulness",
			"amateur auteur",
			"arisen troops",
			"ascendant's gate",
			"babbling experiment",
			"backalley silencer",
			"backstage rooms",
			"backstage tinkers",
			"bahum, the warden",
			"bit player",
			"blood artist",
			"blood overruling",
			"canopy scout",
			"chi lee of the underworld",
			"clock of seasons",
			"compulsive accuser",
			"corpsing",
			"curtain call",
			"cut short",
			"diasune tracker",
			"eldritch egg",
			"encore",
			"encrypted monument",
			"first blood",
			"forsaken bloodletter",
			"gilded cipher",
			"golden touch",
			"growing pains",
			"heist headquarters",
			"hidden hollow",
			"komurk harvester",
			"legitimate establishment",
			"lively prop",
			"malign growth",
			"mei, the infiltrator",
			"mei's collector",
			"night on flayed mountain",
			"performer of enlightenment",
			"pilfered process",
			"posthumous informant",
			"rei's awakening",
			"reprising bard",
			"restoration",
			"return to form",
			"ruined theater",
			"ruptured citadel",
			"ruptured expanse",
			"ruptured falls",
			"ruptured flats",
			"ruptured grotto",
			"ruptured grove",
			"ruptured meadow",
			"ruptured morass",
			"ruptured square",
			"ruptured trail",
			"ruststep centipede",
			"scuripi collector",
			"seedy bar",
			"servant of armageddon",
			"seven-year step",
			"slave child",
			"soul gate",
			"starforge armor",
			"stormcannon gauntlet",
			"sword of redemption",
			"talent pool",
			"talent scout",
			"tome of loss",
			"tower prowler",
			"truth extractor",
			"underworld informant",
			"unraveling",
			"upstage",
			"urchin defector",
			"walking armory",
			"warlord's mantle",
			"worldslayer",
			"absorb the soul",
			"aetheric disarm",
			"answer midnight's call",
			"brazen blackguard",
			"catalina's turf",
			"clear the way home",
			"consign to oblivion",
			"consult on ages lost",
			"corporate war",
			"crush all in their path",
			"custom armaments",
			"darken the sky",
			"dawn of the final day",
			"demolitionist deviser",
			"determined slayer",
			"devour memories",
			"dominik's shack",
			"douse in flame",
			"drink thoughts like oil",
			"elderbane rifle",
			"evening report",
			"forgotten doorway",
			"fortunate exorcist",
			"fulfill twisted dreams",
			"ganzorig's domain",
			"hiroto's refuge",
			"impeccable aim",
			"imperial titan",
			"lie dreaming not dead",
			"lurk at vision's edge",
			"mari, dawn resurgent",
			"marinton occultist",
			"mei liva, the exfiltrator",
			"mountain-western inventor",
			"neblus' legacy",
			"pained ascension",
			"prophet of reclamation",
			"raven-cursed dominik",
			"recall forgotten eons",
			"reckless research",
			"reclaim the world",
			"ride the storm",
			"riga's workshop",
			"riko's academy",
			"rise from the harbor",
			"riv's safehouse",
			"saboteur's panic",
			"secret-hoarder",
			"severin, broken genius",
			"shadow of izumito",
			"shatter mortal conveyances",
			"shroud the world in doom",
			"singularity's grasp",
			"spark new life",
			"specialist saboteur",
			"stand unassailable",
			"strike down the usurpers",
			"suborn humanity's works",
			"takumi's headquarters",
			"teeth without number",
			"tentacled grip",
			"thuggish detective",
			"tower over the sky",
			"transformative insights",
			"treacherous toss",
			"truth unveiled",
			"truthmarked archivist",
			"tsubasa's redoubt",
			"twelve thousand eyes",
			"unorthodox methods",
			"watch from above",
			"worlds colliding",
			"xiong mao, the protector",
			"xiu's escape",
			"archangel of accord",
			"astral alignment",
			"atrophy",
			"bal's descent",
			"barren boneyard",
			"bazaar informant",
			"beetleback forager",
			"bleak condor",
			"blood jade prophet",
			"brazen sacrilege",
			"calcified dunes",
			"chosen of bal",
			"cruel consultation",
			"deathless siege",
			"dissipate",
			"el-mazar, wayward palace",
			"flourishing dunes",
			"furnace golem",
			"gaunt abnormality",
			"gemplate golem",
			"hafiq the wise",
			"hajir soothsayer",
			"harsh erosion",
			"helm of princes",
			"highland dunes",
			"iekin's portal",
			"igneous pulverizer",
			"immolated grave",
			"judicious djinni",
			"liturgic tutor",
			"loose threads",
			"menna al-mejjat",
			"mischievous romish",
			"morrow probe",
			"mukhif the grim",
			"outflank",
			"painted bluffs",
			"ravaged monument",
			"rubble scavenger",
			"runed servitor",
			"ruthless vagrant",
			"sandswept bazaar",
			"saturated dunes",
			"scabrous automaton",
			"scaleback steed",
			"selfish journeyman",
			"seraph of renewal",
			"seto san, summer blossom",
			"shadowband consul",
			"sink into the floor",
			"skeletal oasis",
			"slum scrounger",
			"strangulate",
			"strike down",
			"stygian dunes",
			"sunrazed ruins",
			"tip the scales",
			"tomb steward",
			"tomb of great drakes",
			"unfettered atrocity",
			"vengeful cohort",
			"volatile stonework",
			"arcanist's spellsurge",
			"battle-blind leonin",
			"beckon the shadows",
			"bittersweet reunion",
			"blinded avenger",
			"brutal champion",
			"conjured shade",
			"dark huntress",
			"diabolic designs",
			"dust barrens",
			"exultation of might",
			"ferocity of the redeemed",
			"fidelity of the pure",
			"gift to the gloam",
			"gloaming smokeweaver",
			"golden glade",
			"hesediel, the reborn",
			"leija's greenblade",
			"ligos, shadow's source",
			"migration range",
			"persistent fiend",
			"reaping mask",
			"remembrance of light",
			"rend",
			"resolution of stone",
			"rite of the dark harvest",
			"ritual of coalescence",
			"rius, temple of the grandfather",
			"scion of fecundity",
			"selene the cruel",
			"shattered valkyrie",
			"singers' grove",
			"smokeweaver initiate",
			"snowline ascetic",
			"soulcarver",
			"strength of the patient",
			"tea of augury",
			"the aurora's heart",
			"the court of angels",
			"toros the warchief",
			"twilight blade",
			"upon the altar",
			"vindictive regent",
			"warband commander",
			"warband lieutenant",
			"wealth of the underbrush",
			"ancestor's calling",
			"art studio",
			"artisan's sorrow",
			"aven acoustimancer",
			"banish",
			"bite down",
			"blessed mausoleum",
			"bog rebirth",
			"bogborn exorcist",
			"bokor's recruitment",
			"brash hunter",
			"cataclysmic preacher",
			"creeping pianist",
			"dangerous territory",
			"eerie bayou",
			"faradia's favored",
			"forlorn ruin",
			"grim festivities",
			"herald of festivities",
			"kantra of old majik",
			"lakeside park",
			"mushroom lagoon",
			"oracle's ploy",
			"prayer hall",
			"proselytize",
			"reclaim the devout",
			"rejoicing aristocrats",
			"returned bokor",
			"ritzy parlor",
			"royal domain",
			"shaman of the first pact",
			"smite the monstrous",
			"solemn offering",
			"sporeflow protector",
			"stinghopper",
			"storehouse collapse",
			"sunlit plaza",
			"tear to shreds",
			"vacated bar",
			"vibrant rapture",
			"vindictive abbot",
			"act of repentance",
			"adiran survivors",
			"aerida's assistant",
			"anarchy storm",
			"appeal to the ancestors",
			"artist's vista",
			"charming marauder",
			"cognitive fumigator",
			"contemplate obscurity",
			"culminating despair",
			"fading dead",
			"fallacy's sanctifier",
			"felice, adira's salvation",
			"felice's study",
			"once abandoned",
			"once betrayed",
			"ophidian oracle",
			"over the horizon",
			"rubble tender",
			"seek refuge",
			"seeker of horizons",
			"stark copse",
			"stark hinterlands",
			"stark horizon",
			"stark stream",
			"stark wildfire",
			"strayseeker ranger",
			"theurgist of the depths",
			"withering husk",
			"abandoned monument",
			"across the threshold",
			"aether corsair",
			"aether gateway",
			"ageless weaver",
			"alethea, syzygy captain",
			"arboreal runes",
			"autumn canopy",
			"basalt ritualist",
			"beneath the zhedina",
			"blackrift dryad",
			"blossoming expanse",
			"brine fleet bay",
			"brinechum",
			"caldera crawlers",
			"cave diving",
			"chronosphere sovereign",
			"cloudshaper pilgrim",
			"cloudsteel summit",
			"cursed wastes",
			"customs lookout",
			"dreadfire tyrant",
			"dreamscape",
			"dustchoked outpost",
			"endless trove",
			"entropic harvest",
			"eternal reactor",
			"excursion contingent",
			"explorer's ascent",
			"fenhauler gang",
			"filch",
			"forgotten remains",
			"fractured reach",
			"fungal swathe",
			"gathering beacon",
			"ghostspore mire",
			"gilded gulch",
			"glacial shelf",
			"gloam gullet",
			"grove of embers",
			"guided by the weave",
			"gyr, awoken world",
			"gyreon smuggling",
			"heart of zhedina",
			"idravir, the last city",
			"iknan, the last gildmane",
			"incense stoker",
			"jadycian empath",
			"kilnfire",
			"krismite vault",
			"lotus lake",
			"marrow raptor",
			"maw of a thousand worlds",
			"molten falls",
			"monument of queens",
			"morphic verge",
			"nereba, sandchoked archives",
			"opulent proprietor",
			"otherworldly forest",
			"otherworldly gifts",
			"otherworldly island",
			"otherworldly mountain",
			"otherworldly plains",
			"otherworldly swamp",
			"paracosm",
			"planar eulogist",
			"polyp pools",
			"portal inhibitor",
			"precursor sanctum",
			"promethean grotto",
			"pyroclastic maw",
			"quandary seer",
			"quickmire",
			"rainsculpted gorge",
			"razione racecourse",
			"razorshell marauder",
			"reborn from the ashes",
			"relentless pathcutter",
			"rhyolithic hellkite",
			"rift splicing",
			"riftbreaker mage",
			"rogg, chaos treader",
			"rubble seer",
			"ruin delver",
			"scion of desolation",
			"seeds of new life",
			"shadowcleft hideout",
			"shambling morass",
			"shifting canyon",
			"shifting cascade",
			"shifting crag",
			"shifting grove",
			"shifting morass",
			"shiftscale drake",
			"shuddering node",
			"silksoul celestial",
			"skylight fortress",
			"smuggler's den",
			"soaring rainforest",
			"soulblade",
			"spoils of the undermarket",
			"starlight beacon",
			"steamlit peaks",
			"stormtide renegade",
			"syzygy navigator",
			"syzygy privateer",
			"tears of tizuma",
			"thermal surger",
			"timeless shrine",
			"tomb of shifting sands",
			"umberlure angler",
			"undermarket favors",
			"untethered spire",
			"vedlinn ross",
			"verdant renewal",
			"volcanic terror",
			"voliv edgelands",
			"wasteland ravagers",
			"whisper in the rift",
			"woven network",
			"xoqal, world eater",
			"zhargetan reclaimer",
			"zhedina confiscator",
			"zhedina exchange",
			"zhedina outskirts",
			"zhelid, planar academy",
			"ambitious necromancer",
			"arcane metalcrafter",
			"artisan's genius",
			"backwoods cultivator",
			"banish through the veil",
			"beckon darkness",
			"brilliant academy",
			"brilliant archives",
			"brilliant capital",
			"brilliant castle",
			"brilliant citadel",
			"brilliant cityscape",
			"brilliant hub",
			"brilliant mansion",
			"brilliant port",
			"brilliant workshop",
			"calamity dragon",
			"careless violence",
			"city gate",
			"claim for civilization",
			"corrupted knowledge",
			"deliver from dilapidation",
			"disqualify",
			"dovon, verdant experimenter",
			"embrace the veil",
			"forgemaster's charm",
			"gilded gearhulk",
			"herald of might",
			"herald of wisdom",
			"imagine",
			"inevitable future",
			"jessica turin, battlemage",
			"matron of machines",
			"monstrous hunter",
			"omegalomania",
			"perpetual motion machine",
			"petal-weaver alexa",
			"polgek restorationist",
			"purging light",
			"reality rewoven",
			"renewal grove",
			"riftway to the other side",
			"runecrested valley",
			"sealed riftway",
			"seeker of untouched beauty",
			"sesilius, chosen speaker",
			"speedreading",
			"sword of tides and time",
			"the feller of greatwoods",
			"timeworn crags",
			"transplanted citadel",
			"unified theory",
			"veil's recovery",
			"veilborn stalker",
			"veilcrossed twins",
			"acid sewage",
			"awaken to the new world",
			"battery bearer",
			"bright-eyed adventurer",
			"cantrip collector",
			"children of the void",
			"deadwood terror",
			"deepmire abomination",
			"drained shore",
			"drought-plagued slum",
			"drove of the lost",
			"excavator of the beyond",
			"fate tracer",
			"favoured firebrand",
			"fertile flesh",
			"fluctuating locale",
			"forsaken getaway",
			"godwatcher",
			"grave of an old lord",
			"grim armory",
			"haunted fairground",
			"hellwaste settlement",
			"hoverbike courier",
			"hunger of old lovi",
			"kaur, end of lies",
			"kaur's gift",
			"kielie, risti strike leader",
			"left on the wayside",
			"life remembers its roots",
			"makias, marked marauder",
			"memorial ground",
			"mennin jar",
			"mennin pack",
			"monstrous amalgam",
			"neo-alchemist",
			"neophyte of the old gods",
			"open the cryo-chambers",
			"procession of the conscripted",
			"pulsating mass",
			"ravenous forsaken",
			"realm tiller",
			"reason rots, rage remains",
			"rebuild history",
			"reclamation project",
			"refuse trawler",
			"resign to madness",
			"risti citadel",
			"risti inquisitor",
			"risti salvager",
			"risti watchkeeper",
			"scavenger holdout",
			"scavenger hunt",
			"scavengermobile",
			"scorched-earth defence",
			"secluded farmstead",
			"seductive seashell",
			"sepulchral seas",
			"sovereign of old lovi",
			"surveyor's rifle",
			"the afterlife takes its due",
			"the ancestors pass judgment",
			"the bliss of ignorance dies",
			"the cannibals of kallio hill",
			"the flesh becomes soil",
			"the hidden truths resurface",
			"the mist thirsts for silence",
			"the songs of gods echo",
			"true shot",
			"vulture corps",
			"warped landscape",
			"watchers of the veil",
			"wilderness forager",
			"windmill project",
			"worn peacekeeper",
			"ascension",
			"aureate panorama",
			"corvid heretic",
			"demon of dark shadows",
			"descend on the helpless",
			"earthform pachyderm",
			"endless discoveries",
			"escape death",
			"frostfire hulk",
			"frozen hinterlands",
			"gaze over the wilds",
			"guardian of the divergent",
			"hazy coppice",
			"heartripper zombie",
			"honor the lost",
			"jenn's stand",
			"lowland vista",
			"ominous hart",
			"phantasmal reflection",
			"poisonheart druid",
			"shatter the mask",
			"skyscreecher dragon",
			"spellflux skeleton",
			"spires of caulte",
			"strix of dark omens",
			"sunlit fissure",
			"surge of darkness",
			"testament to heroism",
			"the awakening",
			"the flames approach",
			"the whisperwoods",
			"towering boughs",
			"vali, planar researcher",
			"what lurks beyond",
			"whisperwoods exploration",
			"whisperwoods phoenix",
			"whisperwoods reclaimer",
			"worldly travels",
			"a grave sentence",
			"aether runes",
			"agrestal decay",
			"all-enduring mafua",
			"an'yama, elder guardian",
			"ancient dominion",
			"barbed cocoon",
			"battle for msuji highlands",
			"berylscale alaj",
			"blackmoat bully",
			"bleak dominion",
			"blisterbug",
			"bloodfell caves",
			"blossoming sands",
			"bogfume pact",
			"bone splinters",
			"brushfire",
			"butcher of shallow graves",
			"coastal dominion",
			"desolate dominion",
			"dismal backwater",
			"end of days",
			"explore forgotten lands",
			"fakadeh, florid queen",
			"felling vines",
			"fester swarm",
			"foul vulture",
			"frontier savior",
			"gleaming river",
			"grotto scarab",
			"headhunter mantis",
			"hembwe, the all-mother's hand",
			"into waridi valley",
			"joyful deviant",
			"jungle hollow",
			"kafyabari enforcer",
			"kafyabari patrol",
			"kambiro, the untrue king",
			"majestic dominion",
			"manic river-fishers",
			"murky peat",
			"murmuring typhoon",
			"mythos scribe",
			"netherform",
			"pakka, the shadowcloak",
			"pestilent vermin",
			"pith wilt",
			"primal dominion",
			"pristine dominion",
			"pungent beetle",
			"rainbow phoenix",
			"reticulate chemist",
			"rip to shreds",
			"ruchi, the effervescent",
			"rugged dominion",
			"rugged highlands",
			"ruinous naga",
			"scoured barrens",
			"shadow stalker",
			"sheltered diviner",
			"silthway scuttler",
			"stalwart dominion",
			"sunwashed spires",
			"swiftwater cliffs",
			"the banishment of seh'a",
			"the harnessing of fire",
			"thornwood falls",
			"threshing sundew",
			"tranquil cove",
			"tropical grove",
			"trouble brewing",
			"twilight ambush",
			"vast savannah",
			"verdant dominion",
			"vibrant flames",
			"wind-scarred crag",
			"abomination emissary",
			"aldorus fin, vice president",
			"atrocity of flesh",
			"barren vista",
			"between life and death",
			"blooming vista",
			"bog apex",
			"bury the past",
			"come out and play",
			"convert to resources",
			"cosmic war",
			"crucible of worlds",
			"dead end adventurer",
			"dead man's party",
			"determined explorer",
			"end of the world",
			"enter mephisto's gate",
			"far too young to die",
			"fiery erasure",
			"find happiness in misery",
			"gateblessed explorer",
			"glacial vista",
			"glitch, galactic muse",
			"glowspore grove",
			"green daywalker",
			"guardian of lost truths",
			"hall of random access memories",
			"hardened explorer",
			"hero's downfall",
			"hold me down",
			"human frailty",
			"i'll be gone",
			"living vista",
			"malignant reaver",
			"marshy vista",
			"nebula of empty gold",
			"new divide",
			"no rest",
			"novaheart guardian",
			"on the shoulders of giants",
			"one bad night",
			"painwield explorer",
			"pernicious primavore",
			"persevere",
			"prismatic cavern",
			"prismatic scyphozoa",
			"prosthetic repairs",
			"recurring abomination",
			"remember for centuries",
			"returned explorer",
			"rot",
			"sadie dal, doctor dreamer",
			"scavenging pack",
			"senator christian winters",
			"slyten crystal motherlode",
			"source decay",
			"spaceship invader",
			"speed of darkness",
			"starborne hellkite",
			"strange discovery",
			"sword of monsters and men",
			"tessellated orb",
			"the flenser of singularities",
			"the tomb of precursors",
			"trick mirror gui",
			"twisted predator",
			"uncover the truth",
			"unending armies",
			"venomclaw skitterer",
			"whimsy",
			"wild dogs of the night",
			"ambush gharial",
			"arcane sanctum",
			"archangel of bliss",
			"bant command",
			"bigroot valley",
			"bleak shoreline",
			"blessed radiance",
			"blessed vanquisher",
			"bloated visceroid",
			"bloodbraid ritualist",
			"carnage gorger",
			"caustic mangrove",
			"cesspool scrapper",
			"charred marsh",
			"citadel battlemage",
			"cling to undeath",
			"cloudcover heights",
			"cloudheath sentinel",
			"cognition crucible",
			"conflux ravager",
			"crumbling necropolis",
			"dagger-thrash marauders",
			"demonic rite",
			"dire predictions",
			"dissident's vortex",
			"disturb the riddle gate",
			"dregscape chant",
			"dregscape wretch",
			"edarna the everforge",
			"edarna's augurling",
			"entrail elemental",
			"erupting territory",
			"esper command",
			"exenterate",
			"fathom the forbidden",
			"fearful flooding",
			"flesheater vine",
			"forbidding isle",
			"gloomtide gulf",
			"grixis command",
			"hazy summits",
			"heart of spores",
			"hellion devastator",
			"hellkite omnivore",
			"hostile barbfly",
			"idyllic oasis",
			"incantation demon",
			"infernal flames",
			"jund command",
			"jungle shrine",
			"kaalia's abomination",
			"kaleidoscape",
			"kess the necromaster",
			"knotvine preserver",
			"lava hellions",
			"lichen's grasp",
			"lush coast",
			"maelstromancy",
			"magma spray",
			"meren, bane of the cairns",
			"mortal finish",
			"nacatl skirmisher",
			"nefarox, strifelord",
			"nel toth shaman",
			"obscene recitation",
			"peaceful passage",
			"perilous sojourn",
			"profound introspection",
			"ravenous tarwurm",
			"recraft in steel",
			"refulgent rupture",
			"regurgitator ooze",
			"rings of new alara",
			"sanctum battlemage",
			"savage battlemage",
			"savage lands",
			"scaleshredder",
			"sculler's oar",
			"sculpted observatory",
			"seaside citadel",
			"sharuum, archmagocrat",
			"shining revival",
			"somber meadow",
			"sphinx's scrutiny",
			"terramorphic expanse",
			"thallid cultivator",
			"thrinax sporemother",
			"tidehollow lich",
			"torchlight tormentor",
			"tumultipede",
			"twisting fissure",
			"unearth",
			"varakna wurm",
			"velir the sunderer",
			"viashino glutton",
			"vigor from the vein",
			"volcano elemental",
			"anatomy",
			"behead",
			"burning sulfur",
			"center of culture",
			"choking dunes",
			"collapse the pillars",
			"crescent of possibilities",
			"crooked merchant",
			"crushclaw pulverizer",
			"death pits hawker",
			"delugic surger",
			"donkey jawbone",
			"epic of anku",
			"epic of inishtu",
			"epic of jobiah",
			"funerary barge",
			"grapple with the past",
			"inishtu, desert healer",
			"legacy warmask",
			"life's worth",
			"many-voiced tower",
			"marrow cruncher",
			"merchant of flesh",
			"mustering grounds",
			"nameless throng",
			"pound by pound",
			"primordial progenitor",
			"rupture spire",
			"sacrificial bull",
			"sandburst",
			"sarrutu flamebinder",
			"selezzar, tyrant of endak",
			"sling of the meek",
			"splinter of creation",
			"stolen innovations",
			"stonecut lammasu",
			"sunnula's firebird",
			"tradition",
			"urn of heroes",
			"wondrous bazaar",
			"barbed beast",
			"brutality",
			"bug catcher",
			"call back",
			"caustic caterpillar",
			"chikyu league arena",
			"citadel bagworm",
			"cruel fledgling",
			"curious fossil",
			"egg bomb",
			"fierce lunge",
			"forage",
			"forgotten temple",
			"from beyond the grave",
			"gene pool",
			"ghastly spirit",
			"ghastly tether",
			"healing center",
			"hex maniac",
			"ice path",
			"lake of rage",
			"lava plume",
			"lucien, the ravenous",
			"maple's journal",
			"maven of fear",
			"moonlight",
			"mournful newborn",
			"muggy mire",
			"ominous wind",
			"paleontologist",
			"perish song",
			"poised koi",
			"power plant",
			"practice range",
			"professor maple",
			"psychic assault",
			"revived pterosaur",
			"rocket poacher",
			"ruined lab",
			"ruined shrine",
			"safe from harm",
			"scuttling gnat",
			"secret stash",
			"sludge drudger",
			"still waters",
			"strategic planning",
			"sucker punch",
			"sunset herald",
			"titanic fossil",
			"treasure beach",
			"truffle snuffer",
			"unburdened",
			"victory road",
			"wandering hamlet",
			"warden of lives",
			"wicked fossil",
			"wondering oaf",
			"abyss surger",
			"all for one",
			"black spot",
			"blood for bones",
			"brig of the damned",
			"crypt strider",
			"down with the ship",
			"dragonlord's shrine",
			"dreadbearer",
			"dwarven war hatchet",
			"exotic discovery",
			"expunge the terrors",
			"fiery temper",
			"flaming point technique",
			"fog at sea",
			"gaze of the grave",
			"ghastly scorpion",
			"ghost sloop",
			"good night's sleep",
			"grasp of hollows",
			"grave wrangler",
			"greedy rapscallions",
			"grisly reaper",
			"holcomb of the peregrine",
			"imperious wurm",
			"infernal fury",
			"keelhaul",
			"kelp garden",
			"knotweald sapling",
			"land ho!",
			"law enforcement",
			"light the fuse",
			"ligneous enormity",
			"long forgotten",
			"malignant rise",
			"marisa of the gravehowl",
			"merciless bandit",
			"oaken sentry",
			"perennial unrest",
			"pick up the pieces",
			"pirate's hideout",
			"plummet",
			"pyre apostle",
			"rattled bones",
			"raving brigand",
			"revivification",
			"rising terrain",
			"roll the dice",
			"ruinous proselyte",
			"run through",
			"slaughterkeg",
			"smoldering husk",
			"strange tides",
			"tamiyo, lunar arcanist",
			"trawl the wreckage",
			"two-faced marauder",
			"ulcerous hellion",
			"vagabones",
			"verdurous herald",
			"visions of oblivion",
			"wakeborne kraken",
			"abalone abomination",
			"anemone cluster",
			"anemothrys, reefcrown",
			"aquatic might",
			"awakening of evil",
			"bigger fish",
			"blood in the water",
			"bloodhollow bruiser",
			"bubblespout sentry",
			"buried at sea",
			"circling predators",
			"collect rotting remains",
			"coralight castle",
			"crack open",
			"crush the hull",
			"crushing grip",
			"curious disturbances",
			"cuxuri beckoner",
			"cuxuri harbinger",
			"cuxuri rift",
			"cuxuri's corruption",
			"danithra caller",
			"danithra champion",
			"danithra inquisitor",
			"danithra muckbruiser",
			"dawson's loot",
			"death sentence",
			"deep-sea terror",
			"depthlight captain",
			"depthlight frontliner",
			"depthlight salvager",
			"doom and gloom",
			"drag beneath",
			"drawn to the light",
			"dredgeline colossus",
			"elmare's grandeur",
			"enchanting palace",
			"eye of the beholder",
			"final struggle",
			"foregone ancestries",
			"frontline descender",
			"gaze deeper",
			"gloomtide whelk",
			"glum oarfish",
			"gobble up",
			"grisly ruins",
			"herald from below",
			"hit the bottom",
			"hopesinker",
			"horrors' reach",
			"ink seer",
			"into the abyss",
			"jumbo shrimp",
			"krill-clan guardian",
			"lionfrill hunter",
			"lost empire's legacy",
			"lurking angler",
			"mandibled mass",
			"master of the abyss",
			"mettalia, light from above",
			"mettalia's forward",
			"molten basin",
			"myrmidon, coralight exile",
			"mysterious lights",
			"mystic mackerel",
			"nightmares unseen",
			"noble birthright",
			"oceanographer",
			"oil driller",
			"oryxyth, doom of elmare",
			"oryxyth's brood",
			"paradise reef",
			"raise the dreadreef",
			"rappel liner",
			"redgill corsair",
			"regal coralhorn",
			"roving dreadnought",
			"ruin dive",
			"salvage titan",
			"seabed delver",
			"seafloor casket",
			"seafloor tomb",
			"seafoam slasher",
			"shambling dreadreef",
			"shanty town",
			"shark slayer",
			"shine a light",
			"silent doom",
			"silt lurker",
			"silt miner",
			"snuff out the light",
			"specimen collector",
			"stinging swordfish",
			"storm the seafloor",
			"sunken-eye angler",
			"tectonic chateau",
			"treasure haulers",
			"trenchbottom mariners",
			"triplicate monstrosity",
			"truth beyond belief",
			"turi of hollow depths",
			"turi's masterstroke",
			"twenty thousand leagues",
			"typhoon caverns",
			"vibrant sandbar",
			"volcanic catastrophe",
			"volcanic hollow",
			"vyzer, the fallen despot",
			"way of the danithra",
			"weight of oceans",
			"wilt",
			"alonzo, departed detective",
			"brutal blow",
			"bvala, queen of the swarm",
			"camahueto calf",
			"ciel, the raider king",
			"clean-up crew",
			"end of all things",
			"endless helpless souls",
			"forbidden burial",
			"forked pillar",
			"ghislain, cryptbreaker",
			"hop of life",
			"inescapable fate",
			"invent the future",
			"kenleigh, liege of redemption",
			"lay low",
			"night of the unliving",
			"plasma enforcer",
			"project head",
			"reveal eternities",
			"ria-demian charm",
			"vulture valleys",
			"warfaring epunamun",
			"xirix, the usurper",
			"zarad, the final adversary",
			"bag of holding",
			"bind the great evil",
			"cavern scourge",
			"coastal metropolis",
			"crowded tavern",
			"determined hero",
			"devious plot",
			"doom cultist",
			"doomed traveler",
			"dragon-forged armor",
			"entitled griefer",
			"fertile steppe",
			"final form",
			"foretold cataclysm",
			"fourth eye dealings",
			"frantic researcher",
			"gather the ingredients",
			"grisly feast",
			"heroic return",
			"hoarding arachnid",
			"homeward amulet",
			"ilhus, knight of zarad",
			"improbable aim",
			"ingredient scroungers",
			"invoke the divine",
			"load-bearing behemoth",
			"magma bolt",
			"map all creation",
			"mending valkyrie",
			"mukal butcher",
			"mukal charger",
			"mukal desecrator",
			"mukal forerunner",
			"mukal pillager",
			"mukal rager",
			"mukal reaper",
			"mukal sire",
			"mukal swarmhorde",
			"mukal swordsman",
			"mukal warleader",
			"necromancer's gambit",
			"nidhir, the one beyond",
			"no way out",
			"omen serpent",
			"palette swap",
			"puzzling stratagem",
			"raid the forgotten tomb",
			"ravenous grue",
			"relic corrosion",
			"resurrection priest",
			"revela, star-touched",
			"rogue's passage",
			"scavenging alchemist",
			"scour forgotten archives",
			"seek the maker's egg",
			"shambling retinue",
			"shedding of the coils",
			"smash and grab",
			"smelting breath",
			"soaring skymage",
			"spawning barrens",
			"taran joy, cruel huntress",
			"thalassic borough",
			"tomb creeper",
			"town elder",
			"twitchy pyromancer",
			"undying lich",
			"unending slime",
			"urak, voice of the horde",
			"waypoint stone",
			"weak-spot colossus",
			"wild peak",
			"admonish",
			"alratha, pearl of the sand sea",
			"ancient tablet",
			"approach the dark tomb",
			"bloodstained altar",
			"bloodstained calamity",
			"calamity apparition",
			"charging brute",
			"collapsing ridges",
			"consult ancient knowledge",
			"conto sika, ruined glory",
			"cosmic calamity",
			"dark apprentice",
			"dark behemoth",
			"darna's atrocity",
			"death rites",
			"decisive arcanist",
			"desert's hearth",
			"dthan, who bloodies the sands",
			"ecological refuge",
			"eternal duneborn",
			"eve, the mastermind",
			"from far and near",
			"giant's remains",
			"heavy sandstorm",
			"illuminated firebird",
			"mage's command",
			"naiala, the informant",
			"observer of aeons",
			"open the tomb",
			"painful rites",
			"path of fire",
			"pilgrim's packbeast",
			"plague calamity",
			"regrow anew",
			"restore",
			"ruinshell crab",
			"sand twister",
			"sandwurm's command",
			"scavenging sandwurm",
			"scholar of necromancy",
			"screeching duneborn",
			"search the archives",
			"seeking horizons",
			"skelephant",
			"spiny lizard",
			"stargazing",
			"summoned skeleton",
			"sunless sky",
			"surging wurm",
			"swaying sands",
			"the duneborn host",
			"thief's command",
			"tormenter of graves",
			"trail of bones",
			"turn up",
			"verdant oasis",
			"vicious stinger",
			"winged stinger",
			"ylda's confluence",
			"a flawless world",
			"a vision too vast",
			"abjuration savant",
			"become nothing",
			"beyond all horizons",
			"black hole musings",
			"blessing of roya",
			"blinded necromancer",
			"blooming martyr",
			"born anew",
			"breach the lilies",
			"cackling seer",
			"death kneels before",
			"drenched in triumph",
			"drown amidst the cosmos",
			"emberheart witch",
			"embrace of mist",
			"everember phoenix",
			"fade",
			"fall of masha",
			"fields of worship",
			"fortune dealer",
			"from unbidden realms",
			"gift to finality",
			"give to sacred halls",
			"hadik, might of mortals",
			"hadik's cohort",
			"heavens claim their due",
			"helar's herald",
			"hollyberry murder",
			"ichorsap dryad",
			"ill-fated seer",
			"inscrutable realms",
			"inviolable realms",
			"keep what was lost",
			"masha ritualist",
			"misery keeps company",
			"mnemonic wall",
			"mortal deeds",
			"mortal realms",
			"moth-heart husk",
			"mourn no more",
			"palesoul mender",
			"pieces of creation",
			"reclusive augur",
			"remnant of the hunt",
			"sacrifice to setar",
			"settlement scout",
			"shepherd of lonely souls",
			"shuck mortal coils",
			"silver-dawn elder",
			"solar hatching",
			"still-smoke hunter",
			"still-smoke skirmisher",
			"still-smoke stitcher",
			"stubborn blademate",
			"subdue false idols",
			"swarm of sporemites",
			"tempting realms",
			"the mind falters",
			"these final moments",
			"through shattered senses",
			"time flows to its end",
			"understand desolation",
			"unravel shattered worlds",
			"upon fourfold wings",
			"vashi, twin-star paragon",
			"walker of the final path",
			"walking remorse",
			"welcome what comes",
			"while blood still flows",
			"wild realms",
			"witness the divine",
			"world torn asunder",
			"worn to nothing",
			"agent of andazir",
			"aminatou, justicar",
			"ancestral guidance",
			"assassin of fahrib",
			"avaz citadel",
			"avaz sanctuary",
			"avaz temple",
			"blessing of golna",
			"border seeker",
			"bustling bazaar",
			"call of piruz",
			"call of the huma",
			"contemplate the cosmos",
			"danaj citadel",
			"danaj decider",
			"danaj sanctuary",
			"danaj temple",
			"delve for treasures",
			"devastating charge",
			"doomed alchemist",
			"efreetspeaker",
			"endless infantry",
			"falconry",
			"fall from the heavens",
			"fiery truthseeker",
			"fight for succession",
			"furnished ghul",
			"fury of hadak",
			"gathering of minds",
			"ghul of forgotten pasts",
			"ghulish unearthing",
			"gilded guardian",
			"golna, the first shah",
			"grandstanding huma",
			"greater masticore",
			"hidden cache",
			"hidden garden entrance",
			"ironhide hadhayosh",
			"jahan, the third shah",
			"judgment of the soul",
			"kahroba, forefather of all",
			"kahroba's command",
			"kaneh citadel",
			"kaneh sanctuary",
			"kaneh temple",
			"lasting legacy",
			"mahara's command",
			"marketplace crossroads",
			"mercantile satrapy",
			"neutral citystate",
			"nightly raid",
			"nizev citadel",
			"nizev sanctuary",
			"nizev temple",
			"paladin of order",
			"paygan archer",
			"peek into the future",
			"peer into the cosmos",
			"piruz, the fourth shah",
			"piruz's knight",
			"rapid transformation",
			"recreator of myths",
			"relentless army",
			"return to the beginning",
			"rite of ends",
			"sacred heirloom",
			"satrapy overseer",
			"serene thoughts",
			"shala na, planar outcast",
			"shapur, the fifth shah",
			"shift the sands",
			"shifting city",
			"shomi's journey",
			"shrine to those gone",
			"soli citadel",
			"soli sanctuary",
			"soli temple",
			"surreal bakhtak",
			"tamaak's devourer",
			"the blacksmith's banner",
			"the grand simurgh",
			"vizier of lies",
			"war of resources",
			"worth of ruin",
			"zareen, the second shah",
			"zareen's pariah",
			"astral gateway",
			"avengeance angel",
			"bile of the world",
			"civilization's cost",
			"crystal wave",
			"dreamsteel paladin",
			"entelan deep storage",
			"magus of the grave",
			"okrophore",
			"rain zai, spiritscale",
			"restore life",
			"spike wall trap",
			"starbane elemental",
			"bow or burn",
			"coveted heirloom",
			"geetha, glass-shaper",
			"liliana at the brink",
			"shinrei of the ghosting way",
			"starjump",
			"synchronous hellkite",
			"twisting memories",
			"wunderkind devising",
			"bitter duckling",
			"call of the clocktower",
			"eldritch emergence",
			"eternal blessings",
			"forbidden treasure",
			"from shengin's heart",
			"grim botanist",
			"ishim's meddling",
			"marshy marauder",
			"mortal whims falter",
			"ser wayver, the broken hour",
			"suburban runebrawler",
			"weaver of mists",
			"wish to see",
			"bustling harbor",
			"dreary township",
			"glittering grove",
			"monsoon lagoon",
			"urban wastelands",
			"librarian of whispers",
			"rini, sundial archcleric",
			"imitator of success",
			"thin the veil",
			"roggar the furious",
			"beckon the damned",
			"sundew tender",
			"starved oasis",
			"major benjamin stout",
			"tenuous existence",
			"hallowed duet",
			"mausoleum resident",
			"parasitic rebirth",
			"horizon sovereign",
			"obscoriate",
			"deus ex machina",
			"the heart-hardened",
			"if memory serves",
			"jack, horrific harvester",
			"kunal, dragonclaw's legacy",
			"cortex coil",
			"dustridden sepulcher",
			"risti workshop",
			"avatar of innovations",
			"dragonglass harp",
			"flourishing lowlands",
			"forgotten monument",
			"pathway of lost sultans",
			"raintouched basin",
			"scoured mesa",
			"silent ridge",
			"windworn spires",
			"mechanomind researcher",
			"arcane oasis",
			"arid causeway",
			"bloodsand gulch",
			"blooming needles",
			"crumbling aqueduct",
			"desiccated trail",
			"dunesea expanse",
			"humble hamlet",
			"resurgent oasis",
			"rot-sand ruins",
			"sundappled scrub",
			"chigau market outskirts",
			"dha-bukan, jewel of the dunes",
			"eroded sanctuary",
			"telarine zenitheer",
			"worldwise ascetic",
			"kalro gritbrawler",
			"dunehaze revolutionary",
			"fakadeh's anointed",
			"hisashi's repose",
			"ayala's blessing",
			"ivenge's evangel",
			"mystery of the dying herds",
			"patent thief",
			"ward-lost hermit",
			"tutorial boss",
			"brume trench-thrasher",
			"clutch of the void",
			"glimpse the stars",
			"one person's trash",
			"rune-scribe's revealing",
			"recruiter of irregulars",
			"ideals eternally endure",
			"ethersketch blueprints",
			"encore of the drowned",
			"nestled delta",
			"kai'shi's spellgorgers",
			"pilgrim of bal",
			"achet-aton's vizier",
			"harpooned bubbledomer",
			"unshackled revolutionary",
			"kabuto-no-oni",
			"a villain revealed",
			"enduring plague",
			"gifts of the abyss",
			"on eli's orders",
			"the show must go on",
			"curse of life's cycles",
			"jolt awake",
			"arrogant entrant",
			"tempting prey",
			"speaker of ancient gods",
			"saffrisa's darkcaster",
			"seep forth from the beyond",
			"maaru's hoard",
			"soulshifter",
			"deathbed confessor",
			"a slave's vengeance",
			"eradicated education",
			"orodu's consumption",
			"stormvolt apprentice",
			"aspect of an'yama",
			"coral plunderers",
			"ire of ancient tomes",
			"roggar's mastery",
			"harvesters gone haywire",
			"hatsuo's maneuver",
			"hookhand freebooter",
			"flameform amalgam",
			"vitin slagshaper",
			"creed's desperado",
			"children of aelani",
			"da'lang's preyscenter",
			"out of fashion",
			"bellow of the highlands",
			"descent from the highlands",
			"chaos of the conflux",
			"dovon's masterwork",
			"pineblight caribou",
			"aethermancer's companion",
			"disciple of destruction",
			"script spirit",
			"shaman of burning ashes",
			"terrors of cuxuri trench",
			"coiling spiritscale",
			"spellbone screecher",
			"ormh, discordant envoy",
			"hell or high water",
			"ms. moxie, aetherite proprietor",
			"vir of the starskipper",
			"blistering boneyard",
			"shrine of the world-shepherd",
			"bahum's absolution",
			"seeker of conto sika",
			"scorn the ordinary",
			"eighth-life companion",
			"secrets of coralight court",
			"phantom walker",
			"tarmovore",
			"streets of mustasheen",
			"soul of muetar",
			"farmyard",
			"pompous explorer",
			"deadly harpoon",
			"pupil of lightning",
			"nobility",
			"voidtouched nightblade",
			"brightflame phoenix",
			"the masque, archvillain",
			"purging watchwarden",
			"rokai's gambit",
			"hegemony monarch",
			"bigger they are",
			"loot the cemetery",
			"highway robbery",
			"consult the ancestors",
			"hextwister hare",
			"memory theft",
			"final chapter",
			"metal munch",
			"gloomhollow woodlurker",
			"changing seasons",
			"kula's disciple",
			"tinyvale treetops",
			"bleakrealm moor",
			"dawn hill outskirts",
			"fabled passage",
			"flamingo rock",
			"frondpond grotto",
			"gloomhollow woodlock",
			"highpoint shrine",
			"humble abode",
			"fang den jaws",
			"slipsand oasis",
			"exotic isle",
			"performance of a lifetime",
			"the gloomhollow draught",
			"flourish in the slipsands",
			"defraud",
			"valorous stance",
			"hoof cliff horngrove",
			"alaina, the second chance",
			"quillback of gloomhollow",
			"hoof cliff caretaker",
			"crossroads town",
			"northrime aurora",
			"kaone of the golden sonata",
			"canopyctopus",
			"take all you can carry",
			"ingenious solution",
			"siltbottom expedition",
			"gloomhollow expedition",
			"unhappy ending",
			"paleolizard",
			"trapper's hideout",
			"enigma mystic",
			"rugged expanse",
			"eon campfire",
			"kula, sage of gloomhollow",
			"belligerence",
			"unite against evil",
			"ritual of soot",
			"blazing outro",
			"venomfrill familiar",
			"leyline invoker",
			"plots that span realms",
			"astralhorn familiar",
			"battle at the boneyard",
			"intersection of fates",
			"mikkino's climactic clash",
			"whisper of the wild",
			"paw valley alpha",
			"ripper of the fang den",
			"breathtaking valley",
			"karoa's downfall",
			"endless repentance",
			"angel of redemption",
			"call forth greatness",
			"combat expertise",
			"fulguration",
			"greater restoration",
			"flurry of bolts",
			"vital strike",
			"weight of nobility",
			"clockwork artifice",
			"grand arcana",
			"lurzog, kytherax's disciple",
			"oriveen, scroll savant",
			"practiced sorcerer",
			"seeds of prophecy",
			"stormcloud drake",
			"turn back time",
			"wind stance",
			"ashen procession",
			"assassination contract",
			"belligerent mob",
			"bloodbond ritualist",
			"carrion sculptor",
			"catacomb dredger",
			"charnel legion",
			"corpseshift",
			"critical focus",
			"daggersworn elite",
			"death knell",
			"endmire raven",
			"grim necromancer",
			"hint of wolfsbane",
			"marrowcaster",
			"nherix, the soulcage",
			"pestilent scavenger",
			"poisoned shiv",
			"vokha, bloodstone exarch",
			"rezzal, the loamfeaster",
			"sarrithaz, the fiendblade",
			"sovereign's ambitions",
			"soul drain",
			"velinor, storm of shadows",
			"whispered breath",
			"dragonheart seer",
			"emberheart arcanist",
			"fiery explosion",
			"hellfire titan",
			"hoarding dragon",
			"improved initiative",
			"osgaerith archivist",
			"slaug's warhowler",
			"towering inferno",
			"trove keeper",
			"daughter of calenfyr",
			"frontier trackers",
			"gloamrazer hydra",
			"gorganith, ruin maw",
			"great fortitude",
			"mourngash, the harvester",
			"nightshade ambusher",
			"oakcudgel giant",
			"reclaimed by nature",
			"student of the wilds",
			"wharling willow",
			"commanding princess",
			"eternal purpose",
			"vitality exchange",
			"eilwyn, speaker of seasons",
			"eryth, mire dredger",
			"fhinon, the dirgechanter",
			"xilreth, dread servant",
			"dreadstone watcher",
			"endmire scourer",
			"haunted heirloom",
			"sphere of sorcery",
			"ancestral glade",
			"archmage's tower",
			"bustling marketplace",
			"chamber of ceremonies",
			"cloudpeak spires",
			"commander's stronghold",
			"conjured acropolis",
			"magnificent palace",
			"midnight gate",
			"mystical tomb",
			"sacred summits",
			"seaside grotto",
			"sunlit meadow",
			"tranquil shrine",
			"vale ruins",
			"vraniveer's edge",
			"wildkin grove",
			"pallid herald",
			"vaeldan's liberator",
			"restore the rose order",
			"zirrat, the soulsearcher",
			"begin the purge",
			"the roseblade",
			"tomb of the roseblade",
			"heavenly radiance",
			"carrion scythe",
			"together in death",
			"bloodbriar archdruid",
			"field tender",
			"byron, unlikely hero",
			"imisti, elven insurgent",
			"henrick's memorial",
			"cresting bay",
			"firehearth halls",
			"serene chapel",
			"wise old oak",
			"swarming midden",
			"scion of the rose order",
			"rat king",
			"corsair sellsword",
			"sofia's swashbucklers",
			"distracting flourish",
			"midden heap",
			"slipping sanity",
			"usurper's end",
			"deepstone operative",
			"tyrant of prophecies",
			"feasting ettin",
			"hamlet bounder",
			"cursebreaker hammer",
			"secluded courtyard",
			"sparring ground",
			"bloodbriar acolyte",
			"the bloodline endures",
			"leave to the rats",
			"sewer dweller",
			"burn the witch",
			"flameboon alchemist",
			"barkcrush",
			"indomitable armory",
			"crescent of the harvest moon",
			"descended glacier",
			"descended hollow",
			"descended fissure",
			"descended gorge",
			"descended countryside",
			"cleansweep",
			"cold embrace",
			"endless gossip",
			"maddening theory",
			"shattered image",
			"spectral seize",
			"act of jealousy",
			"bleeding aces",
			"burning hatred",
			"iron backbite",
			"reckless arson",
			"warm one's bones",
			"fleeting resonance",
			"virtuous cadenza",
			"broken spirit",
			"gallows griffin",
			"herald of purity",
			"lamplight watchman",
			"militia surgeon",
			"seraph of sunset",
			"canal kelpie",
			"carapace spider",
			"ironsnap hunter",
			"osheen courtier",
			"returned stag",
			"soulraving hunt",
			"thatcher militia",
			"noonfiend",
			"bezoarbeast",
			"lifespark alchemist",
			"unstill unlife",
			"tasseography",
			"alchemist's abode",
			"estate scarecrow",
			"ethereal pact",
			"shock or disbelief",
			"charred phoenix",
			"opera house",
			"troubled homesteader",
			"somber seer",
			"autumn ward",
			"innocence lost",
			"equinox sprite",
			"bitter starfall",
			"historiamancer",
			"sublime truth",
			"rotten grin",
			"pyrophoric blast",
			"tragic end",
			"starcrossed widow",
			"edgar, divine regent",
			"fencing grace",
			"divine theurge",
			"imperfect stone",
			"solar pact",
			"beatrice's dodger",
			"celestial concordance",
			"wharf lumper",
			"sleepless scholar",
			"bitter pact",
			"into the maw of hell",
			"undying bond",
			"shining censure",
			"voracious interest",
			"fated fall",
			"virtue of resilience",
			"life from death",
			"imperial capital",
			"doomed woodsman",
			"romantic recollections",
			"arcanotripsy",
			"disarray",
			"veiled merfolk",
			"fall to ruin",
			"abyssal familiar",
			"leticia petrine",
			"thriving bluff",
			"thriving moor",
			"thriving isle",
			"thriving grove",
			"thriving heath",
			"cruel vintage",
			"authenticity",
			"reckless experiment",
			"break down",
			"crested cloudfisher",
			"entelan idealist",
			"first snow",
			"gatekeeper geist",
			"guiltless matron",
			"hunted haunt",
			"oscuran wingmate",
			"runic enforcer",
			"siphon student",
			"small comfort",
			"solari's faithful",
			"twilight vigil",
			"valera, constructed angel",
			"vengeful sorrow",
			"volarian sightseer",
			"aetheric researcher",
			"been there, done that",
			"devotee of winds",
			"imagination augmentation",
			"leave behind",
			"overcharge",
			"path lighter",
			"rappel",
			"shiverpass taskmage",
			"snowed in",
			"street stray",
			"thirst for nostalgia",
			"tranquil path",
			"wizened tortle",
			"acolyte of the tempest",
			"change of plans",
			"crushing guilt",
			"doomed widow",
			"the endless tempest",
			"guiltless wraith",
			"inconspicuous otter",
			"makeup call",
			"second death",
			"senn, the haunting gaze",
			"senn's essence",
			"shadowlurk",
			"skullhoarder dragon",
			"sluiceway collector",
			"spiked burrower",
			"swipe secrets",
			"token of tribulation",
			"unrelenting",
			"abrasive citizen",
			"callous conduit",
			"competing design",
			"curio hellkite",
			"hotshot renegade",
			"scoff",
			"state collapse",
			"test of mettle",
			"tortle tinkerer",
			"tortle waymaker",
			"trail blazer",
			"wandering conqueror",
			"calavanting",
			"carrion monitor",
			"catacomb recovery",
			"churner of souls",
			"crushing victor",
			"curious charter",
			"font of sorrows",
			"gemcrusher turtle",
			"indomitable spirit",
			"the lonely hunter",
			"remnant spotter",
			"scenic route",
			"search ancient troves",
			"something in the woods",
			"tempest dodger",
			"tortle guard",
			"tortle trader",
			"tortle traveler",
			"unexpected brawl",
			"worldweary pangolin",
			"bright future",
			"colossal hermit",
			"curious amalgam",
			"dreams come true",
			"drop bear",
			"entelan contact",
			"grieving process",
			"halcyon daze",
			"hannah, aethertechnician",
			"herald of rot",
			"irbek's bestiary",
			"join the chorus",
			"karina, planar tourist",
			"leafcrowned fox",
			"the locus of sorrows",
			"lovebird lounge",
			"the moribund manuscript",
			"panda pioneer",
			"prove your worth",
			"reader of bones",
			"take flight",
			"thundering towershell",
			"torch of those underfoot",
			"tortle veteran",
			"usona lurker",
			"aukashi, electric legacy",
			"distraction doll",
			"petrified guard",
			"barbed reef",
			"calciform wastes",
			"crumbling shrine",
			"implant greenhouse",
			"snow drift",
			"spiny ridge",
			"student of the elixir",
			"huolin sanctifier",
			"enlightened orator",
			"funerary daoshi",
			"accept mortality",
			"festive firecrackers",
			"expel darkness",
			"celestial intervention",
			"forsaken soulherd",
			"bai long ma, fabled innocence",
			"daoshi spiritdancer",
			"glorious rebirth",
			"sha long, harmonious wind",
			"haze qilin",
			"wildershrine pilgrimage",
			"worldly detachment",
			"claimed by the mists",
			"wanderer of many",
			"lunar deus blackguard",
			"sha wujing, depth of desire",
			"carrion courier",
			"bleeding-edge garroter",
			"fiendish yaoguai",
			"weeping yaoguai",
			"jade empire outlaw",
			"augur of bleak horizons",
			"mortal frailty",
			"free from the coil",
			"kinsang duskblade",
			"gau ding soulhoard",
			"lotus-scarred luocha",
			"divide and slaughter",
			"dawning of the celestials",
			"zhizhu jing, duality of fates",
			"devourer of legacy",
			"water sutra daoshi",
			"syndicate sycophant",
			"feast upon maligned souls",
			"niu mo wang, ashen absolution",
			"pan long, remorseless wind",
			"laiyru huntsman",
			"royal retriever",
			"roseblood hart",
			"refulgent flare",
			"hook-style trainee",
			"battle of principles",
			"xijiang, the fiend judge",
			"pi and jiu, botanic elixirists",
			"kui mu lang, warden below",
			"keeper of pearls",
			"huolin ranger",
			"jade empire cartographer",
			"hibiscus snapdragon",
			"filial piety",
			"pilgrim's respite",
			"kinsang spiritualist",
			"leafguard larva",
			"awaken ancestry",
			"illustrious qilin",
			"jade harvester",
			"lian taizi, bountiful earth",
			"agent of equilibrium",
			"laiyru lumberjacks",
			"monastery scribe",
			"stolen stratagem",
			"through the divine gate",
			"skittering yaoguai",
			"reminiscence",
			"zhu bajie's command",
			"shan jun's command",
			"ye feng, lotus apothecary",
			"undying remorse",
			"forbidden wisdom",
			"spirit snare",
			"inciter of spirits scorned",
			"quan li, dusk operative",
			"mianju, taker of names",
			"aspect of divinity",
			"mortal benediction",
			"heaven's end chronicler",
			"lotus wastes merchant",
			"roots from ruin",
			"oozing yaoguai",
			"monk of mid-autumn",
			"wei ji, dawn and dusk",
			"xiong mao, the enduring",
			"shan jun, mortal eclipse",
			"pinnacle of purity",
			"harvest reaper",
			"taifeng shrine",
			"hozen shrine",
			"shoupan shrine",
			"paomar shrine",
			"guang shrine",
			"lieshi shrine",
			"kinsang shrine",
			"laiyru shrine",
			"qi-long shrine",
			"huolin shrine",
			"lotus barrens",
			"eminent palace",
			"ominous palace",
			"forbidden palace",
			"montane palace",
			"concordant palace",
			"eidolic palace",
			"forsaken palace",
			"serene palace",
			"opalescent palace",
			"radiant palace",
			"lonely aerie",
			"treacherous oasis",
			"ravenous hollow",
			"grizzled den",
			"pride ridge",
			"scrounging dunes",
			"reclusive copse",
			"overgrown enclave",
			"spined spire",
			"vulpine bluffs",
			"spirit blossom shrine",
			"forbidden shiangshi arts",
			"gui, the brinebearer",
			"wei ji, life's rhythm",
			"the great war ends",
			"shuilong technique",
			"dance of dragons",
			"birth of the yaozu",
			"the blood sun sets",
			"ruchong awakening",
			"kai'oro, grave betrayer",
			"heyu, depthlurker",
			"xiejuan and hao lu",
			"emperor dan te mogui",
			"the orange orchard",
			"xueyang san",
			"shrine of elder lords",
			"outcast of the folded fan",
			"heping's acolyte",
			"cerulean sovereign",
			"hydrolyze",
			"eaveshoppers",
			"shifu of xiangyin temple",
			"demon of hubris",
			"consign to old diyu",
			"whispers of the dead",
			"fervid dragonheart",
			"keen redtail",
			"chaparral hunter",
			"spawn of qiyan",
			"lu'she temple customs",
			"altar of twisted piety",
			"the royal vignettes",
			"mire sculptor",
			"fables of the ill-fated",
			"festival centrum",
			"fox of an amber dawn",
			"russet denmother",
			"abandon the past",
			"lizhao's soulblade",
			"grim bounty",
			"traveler's trial",
			"nightblade umbra",
			"char brewer",
			"flame juggler",
			"scorching dragonfire",
			"violent devotion",
			"crooning eulogist",
			"called shot",
			"roadside reaper",
			"brutalize",
			"unstoppable slaughter",
			"the collection",
			"bedfellow",
			"living broadcast",
			"final findings",
			"derange",
			"communion",
			"catastrophic crash",
			"misshapen monstrosity",
			"frozen over",
			"swarm of the damned",
			"exorcise",
			"otherworldly passage",
			"ominous discovery",
			"something in the shadows",
			"whispering paranoia",
			"shady souvenirs",
			"misty churchyard",
			"lost station",
			"hellfire caverns",
			"enshrouded village",
			"keeper of the collection",
			"the shepherd of nowhere",
			"john furo, the unfortunate",
			"ravenous attraction",
			"aspiring hero",
			"corpsebark",
			"demented brainiac",
			"sunken homestead",
			"grasping souls",
			"violent feeding",
			"horrific invocation",
			"sea of corpses",
			"starving stalker",
			"morbid mimic",
			"jumpscare",
			"apocalypse awakens",
			"cutthroat carnie",
			"the hewitt brothers",
			"whirling repository",
			"alchemical reserve",
			"soaring observatory",
			"oil the mind",
			"stir the pot",
			"bureaucratic dues",
			"endure ennui",
			"recollection revelation",
			"shadowed apostle",
			"review curriculum",
			"arpechian architect",
			"sending stones",
			"endless inspiration",
			"counting clouds",
			"chronotome",
			"humble archivist",
			"twilight dancer",
			"bestower of blooms",
			"freedom of life",
			"dream keeper",
			"revisionary studies",
			"compose from dreams",
			"esoteric herbology",
			"focused apprentice",
			"studies past",
			"flourishing forest",
			"flourishing island",
			"flourishing plains",
			"flourishing swamp",
			"flourishing mountain",
			"ardy, indecisive pupil",
			"journey beyond",
			"manipulator of waves",
			"hoarding crab",
			"oriq soulweaver",
			"treacherous warden",
			"hail to the queen",
			"sear, forged of lava",
			"hold life in taloned grasp",
			"syncretic master",
			"warden of distortion",
			"irticull's vanguard",
]

		names
			.map{|n| db.cards[n]}
			.flat_map{|card| card ? card.printings : []}
			.to_set
	end

	def to_s
		'is:marisa'
	end
end