class ConditionIsStaple < Condition
	def search(db)
		names = [
			"wayfarer's shrine",
			"nebula of empty gold",
			"monument of queens",
			"sedate tundra",
			"pith wilt",
			"pool of light",
			"sealed riftway",
			"shifting glade",
			"duress",
			"resplendent substratum",
			"seal the tomb",
			"ocean monastery",
			"mysterious cataract",
			"crystal cavern",
			"mana confluence",
			"scorch",
			"stand unassailable",
			"cosmic sinkhole",
			"forbidden treasure",
			"prying inquiry",
			"spell pierce",
			"sacrificial bull",
			"crumbling precipice",
			"lumbering hillock",
			"solar flare",
			"cursory glance",
			"amber hills",
			"ostracizer orb",
			"pay up",
			"the high prairies",
			"tiny heroine totti",
			"bounty of the gardens",
			"murmuring falls",
			"arctic mine",
			"timber range",
			"lush oasis",
			"barren desolation",
			"embodied soul",
			"portal fracture",
			"xanigan, the darkened cloud",
			"voidflare",
			"forgotten steppe",
			"shardstone rift",
			"shal'draen's rage",
			"out-of-body experience",
			"heart of the glade",
			"inishtu, desert healer",
			"flooded depths",
			"admonish",
			"recall forgotten eons",
			"sigil of radiance",
			"monkeyshines",
			"magmatic torrent",
			"thought blossom",
			"frostfire geysers",
			"sunlit highland",
			"bessie's brood",
			"ruin delver",
			"grim bastion",
			"tal, locus sentry",
			"still the pandemonium",
			"mirrorgate",
			"end of all things",
			"shifting cascade",
			"prodigious panya",
			"stolen secrets",
			"shugenja sanctuary",
			"nereba, sandchoked archives",
			"idyllic odyssey",
			"nomad's township",
			"forked pillar",
			"shifting grove",
			"rampant summit",
			"roggar's frenzy",
			"cane dancer",
			"powder scatterer",
			"masahita, bloodtongue",
			"shifting crag",
			"seek prophecy",
			"fiery burst",
			"gloomcover steppe",
			"setting sun",
			"dovon, verdant experimenter",
			"brutal blow",
			"seto san, the dragonblade",
			"garth of the chimera",
			"ria-demian charm",
			"relic corrosion",
			"kaalia's abomination",
			"fox of the orange orchard",
			"mana ascetic",
			"silent hypnotist",
			"fungal mire",
			"spiraling canyon",
			"rakkiri dissident",
			"fractured reach",
			"new divide",
			"shikai's redoubt",
			"endless helpless souls",
			"lavatorn fields",
			"shifting canyon",
			"lucien, the grifter",
			"conjure realities",
			"the flames approach",
			"bant command",
			"nature's claim",
			"wheat from chaff",
			"oracle's vision",
			"confirm hypothesis",
			"descend on the helpless",
			"gift of the phoenix",
			"publicly disgraced",
			"one with the world",
			"tether of simplicity",
			"tsang jin, master of the jade sea",
			"negate",
			"verdant dominion",
			"kaur, end of lies",
			"rapacious rattler",
			"gleaming river",
]

		names
			.map{|n| db.cards[n]}
			.flat_map{|card| card ? card.printings : []}
			.to_set
	end

	def to_s
		"is:staple"
	end
end