# frozen_string_literal: true

source 'https://rubygems.org'
gem 'damerau-levenshtein'
gem 'memory_profiler', require: false, group: :test
gem 'nokogiri'
gem 'pathname-glob'
gem 'pry'
gem 'rake'
gem 'rspec', require: false, group: :test
gem 'simplecov', require: false, group: :test
gem 'unicode_utils'
gem 'byebug', '~> 11.1', groups: %i[development test]
